### DISCUSSION TITLE
amtool check-config validate templates

### DISCUSSION THREAD

**Discussion by marchenko1985** [prometheus/alertmanager#2903] [Ideas]
will be so nice if `amtool` will not only check the correctness of the configuration file but also given templates

repro:

**alertmanager.yml**

```yml
global:
  slack_api_url: https://hooks.slack.com/services/xxxx
route:
  receiver: demo

receivers:
  - name: demo
    slack_configs:
    - title: '{{ if .CommonLabels.alertname }}{{ .CommonLabels.alertname }}{{ if .GroupLabels.alertname }}{{ .GroupLabels.alertname }}{{ else }}alertmanager{{ end }}'
```

```bash
docker run --rm -v $PWD:/code -w /code --entrypoint=amtool prom/alertmanager check-config alertmanager.yml
```

will say that everything fine

but sooner or later you will realize that you are not receiving alerts not because everything is fine but because a silly typo in the template 🤷‍♂️

from golang perspective such template will raise an error `template: :1: unexpected EOF`:

```go
package main

import (
	"html/template"
)

func main() {
	_, err := template.New("").Parse(`{{ if .CommonLabels.alertname }}{{ .CommonLabels.alertname }}{{ if .GroupLabels.alertname }}{{ .GroupLabels.alertname }}{{ else }}alertmanager{{ end }}`)
	if err != nil {
		panic(err)
	}

}
```

so theoretically `amtool` can perform such check on each field that can use templates and warn us, so we know about the problem before applying changes to alertmanager
