### DISCUSSION TITLE
Send an alert to more that one slack channel with the same receiver

### DISCUSSION THREAD

**Discussion by rondomondo** [prometheus/alertmanager#3342] [Ideas]
We have a setup that sends alerts to tons of receivers. Two of the biggest contributors to this receiver list bloat are to pagerduty and slack. This question just concerns the slack notifier for now.

Currently the only way we can send the same notification to multiple slack channels is to define a new receiver and match on a different label for the alternative channel. 

I wonder if anybody has thoughts (previous or new) on modifying the slack receive/notifier so that if more than one "#channel name" appears then it will send distinct notifications out for each? I was thinking something like this for example...

```
receivers:
  - name: slack-receiver-multi
    slack_configs:
      - channel: '{{ .CommonLabels.slack_recipients }}'
      - ...

# where the template '{{ .CommonLabels.slack_recipients }}' could be a comma 
# delimited string that evaluates to '#channel_1, #channel_2[,...]'

# example 

receivers:
  - name: slack-receiver-multi
    slack_configs:
      - channel: '#channel_1'
      - ....
      
# or 

receivers:
  - name: slack-receiver-multi
    slack_configs:
      - channel: '#channel_1, #channel_2, #channel_3'
      - ...
```

The main immediate reason for me is because of the extra duplication of receivers we define that differ very slightly and that all these receivers are also referenced individually elsewhere in other code. Helm Charts, ConfigMaps etc... 

I would be interested to hear any thoughts or suggestions. Is there a process that you lot can point me to if I can look into it, and make local patch efforts myself to see?

Thanks all.
Dave.
