### DISCUSSION TITLE
Configure custom templates in docker-compose

### DISCUSSION THREAD

**Discussion by CockstarGames** [prometheus/alertmanager#3684] [Q&A]
How to properly integrate my own custom Telegram template into docker-compose? Unfortunately I couldn't found any example. :(

My docker-compose:
```
 alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/templates:/etc/alertmanager/templates
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
```

alertmanager.yml
```
global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'telegram_bot'

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: '12345678:AAAAAAAAAAAAAAAAAAAAAAAAAAA'
    api_url: 'https://api.telegram.org'
    chat_id: -1000000000000
    parse_mode: 'HTML'
templates:
- /etc/alertmanager/templates/telegram.tmpl
```
It won't work. I do something wrong?
I need a help to properly integrate my own custom Alertmanager template into docker-compose.
