### ISSUE TITLE
[victorops] make message_type template-able

### ISSUE THREAD

**Issue by caarlos0** [prometheus/alertmanager#1018]
Sorry, I don't know how to express exactly what I meant in words, so, here is code.

We have several teams here, and alerts are routed to the responsible team. For example:

```yaml
    - match_re:
        service: ^(foo|bar).*
      receiver: team1-info
      routes:
        - match:
             severity: page
           receiver: team1-page
```

Later, we define the receivers as:

```yaml
- name: 'team1-page'
  victorops_configs:
  - routing_key: team1
    message_type: CRITICAL

- name: 'team1-info'
  victorops_configs:
  - routing_key: team1
    message_type: WARNING
```

The problem with this is that we need to replicate a lot of code (for example, matching services, instances, etc), which is not a breaker but it makes the config more difficult to read because of the repetition.

I wonder if there is a way of doing something like:

```yaml
- name: team1
  victorops_configs:
  - routing_key: team1
    message_type: {{ $labels.severity }}
```

If that was possible, it would be easier to maintain this configs. 

Any tips?

**Comment by stuartnelson3** [comment]
This is a usage question, which in the future should be directed to prometheus-users@googlegroups.com

The config file is read as a complete file, with no interpolation happening when parsing. We recommend using templating as provided by your config management software of choice (chef, ansible, etc.) to turn an alertmanager config template into an alertmanager config on your node.

**Comment by stuartnelson3** [comment]
If you look at the documentation, you can see how to accomplish this: https://prometheus.io/docs/alerting/notification_examples/

```yaml
- name: team1
  victorops_configs:
  - routing_key: team1
    message_type: {{ .Labels.severity }}
```

This might do what you want.

**Comment by jperville** [comment]
Hello, having the same issue here with the following config:

```yaml
    - name: 'victorops'
      victorops_configs:
        - api_key: 'XXXXXXXXXXXXXXXXXXXX'
          routing_key: 'myenvironment'
          message_type: '{{ .Labels.severity | toUpper }}'  # <-------
          state_message: 'Alert: {{ .CommonLabels.alertname }}. Summary:{{ .CommonAnnotations.summary }}. RawData: {{ .CommonLabels }}'
```

On VictorOps, all alerts have "message_type = CRITICAL", as if the value of the expanded message_type was not one of `INFO`, `WARNING` or `CRITICAL` and the default value (`CRITICAL`) was used.
