### ISSUE TITLE
Alertmanager webhook root status misleading

### ISSUE THREAD

**Issue by josedonizetti** [prometheus/alertmanager#1051]
Alertmanager won't consider the status of the alert when grouping but then sending a webhook notification the root status of the payload is misleading because the group may have both firing and resolved alerts, and the root status only says either one or the other.

Webhook payload
```
{
  "receiver": "webhook",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "ServerStop",
        "env": "prod",
        "status": "firing"
      },
      "annotations": {},
      "startsAt": "2017-10-21T15:50:17.16095407-02:00",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": ""
    },
    {
      "status": "resolved",
      "labels": {
        "alertname": "ServerStop",
        "env": "prod",
        "instance": "a1",
        "status": "resolved"
      },
      "annotations": {},
      "startsAt": "2017-10-21T15:50:28.806970773-02:00",
      "endsAt": "2017-10-21T15:50:28.806970877-02:00",
      "generatorURL": ""
    }
  ],
  "groupLabels": {
    "alertname": "ServerStop",
    "env": "prod"
  },
  "commonLabels": {
    "alertname": "ServerStop",
    "env": "prod"
  },
  "commonAnnotations": {},
  "externalURL": "http://Joses-MacBook-Pro-2.local:9093",
  "version": "4",
  "groupKey": "{}:{alertname=\"ServerStop\", env=\"prod\"}"
}
```

Alertmanager config:
```
global:
  resolve_timeout: 1h

route:
  group_by: ['alertname', 'env']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 3h
  receiver: webhook
    
receivers:
- name: webhook
  webhook_configs:
    - url: <url>
```

I'm able two simulate this in master.
