### ISSUE TITLE
executing "" at <.Alerts>: can't evaluate field Alerts in type template.Alert

### ISSUE THREAD

**Issue by jangrewe** [prometheus/alertmanager#1053]
**What did you do?**
Create custom notification templates

**What did you expect to see?**
Notifications being sent to Slack in the expected format.

**What did you see instead? Under which circumstances?**
No notifications is being sent when an alert fires.

**Environment**

* System information:
Running the official Docker image:
```
Linux 4.9.0-4-amd64 x86_64
```
* Alertmanager version:
```
alertmanager, version 0.9.1 (branch: HEAD, revision: 9f5f4b2a516d35cfaf196530b277f1d109254569)
  build user:       root@3b87d661c3dd
  build date:       20170929-12:59:03
  go version:       go1.9
```

* Prometheus version:
```
/prometheus $ prometheus -version
Error parsing commandline arguments: unknown short flag '-v'
prometheus: error: unknown short flag '-v'
```
```
/prometheus $ prometheus --version
prometheus, version 2.0.0-rc.1 (branch: HEAD, revision: 5ab8834befbd92241a88976c790ace7543edcd59)
  build user:       root@1f56dd8b6f7b
  build date:       20171017-12:34:15
  go version:       go1.9.1
```

* Alertmanager configuration file:
```
global:
[...]
route:
  receiver: k8s-admin-slack
  group_by:
  - alertname
  - k8s_cluster
receivers:
- name: k8s-admin-slack
  slack_configs:
  - send_resolved: true
    api_url: <secret>
    channel: k8s-alerts
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '[{{ .Status | toUpper }}] <{{ template "__alertmanagerURL" . }}|{{ .CommonAnnotations.summary
      }}>'
    title_link: '{{ template "slack.default.titlelink" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: |-
      *Cluster:* {{ .CommonLabels.k8s_cluster }}
      {{ range .Alerts }}{{ if gt (len .Alerts) 1 }}--
      {{ end }}
      {{ .Annotations.description }}
      {{ end }}
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
templates:
- /etc/alertmanager/slack.tmpl
```

* Prometheus configuration file:
```
[...]
      - alert: ScrapeTargetDown
        expr: up != 1
        for: 5m
        labels:
          severity: warn
        annotations:
          summary: "Scrape target down"
          description: "*Details:* The scrape target *{{ .Labels.job }}* on host *{{ .Labels.instance }}* is down."
```

* Logs:
```
 time="2017-10-23T09:20:50Z" level=error msg="Notify for 1 alerts failed: Cancelling notify retry for "slack" due to unrecoverable error: template: :2:33: executing "" at &lt;.Alerts&gt;: can't evaluate field Alerts in type template.Alert" source="dispatch.go:264" 
time="2017-10-23T09:21:50Z" level=error msg="Error on notify: Cancelling notify retry for "slack" due to unrecoverable error: template: :2:33: executing "" at &lt;.Alerts&gt;: can't evaluate field Alerts in type template.Alert" source="notify.go:283" 
```
