### ISSUE TITLE
For flapping alerts, FIRING notifications are only sent once when `send_resolved: false` is set

### ISSUE THREAD

**Issue by juliusv** [prometheus/alertmanager#1063]
Given:

- Prometheus 2.0 at current master *or* Prometheus 1.8.1 (doesn't matter)
- Alertmanager at current master

...and the intentionally flapping alerting rule:

```
groups:
- name: demo-service-alerts
  interval: 15s
  rules:
  - alert: TimeBasedTestAlert
    expr: vector(time()) % 600 < 300
    for: 1m
    labels:
      severity: test
```

...and the AM config:

```
route:
  receiver: foo
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'foo'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/XXX/XXX'
    channel: '#test-alerts'
    send_resolved: false
```

...the initial FIRING notification always makes it to Slack, but for further on/off cycles of the alert, no further FIRING notifications get sent to Slack even after the `group_interval` has passed multiple times.

When setting `send_resolved: true`, both RESOLVED and FIRING notifications appear at regular intervals as expected (every 10 minutes).

It doesn't seem like this always has been the case. At least in Cortex, which still vendors old AM packages, this is handled correctly. I noticed this when upgrading Cortex to current AM packages. But I haven't pinpointed the exact commit that caused this yet in AM.
