### ISSUE TITLE
Alertmanager eventually consumes all available storage

### ISSUE THREAD

**Issue by ilackarms** [prometheus/alertmanager#1074]
**What did you do?**
Run Prometheus Alertmanager inside a docker container (specifically as an openshift pod). 

**What did you expect to see?**
Storage should be refreshed after some retention period.

**What did you see instead? Under which circumstances?**
All storage on the host was eventually consumed by alertmanager's data directory.

**Environment**
oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocp-master01.10.35.48.138.nip.io:8443
openshift v3.6.173.0.5
kubernetes v1.6.1+5115d708d7

* System information:

Linux 3.10.0-514.16.1.el7.x86_64 x86_64

* Alertmanager version:

alertmanager, version 0.7.1 (branch: , revision: )
  build user:       root@dfa0e46aa7ac
  build date:       20170725-15:23:21
  go version:       go1.8.1

* Prometheus version:

prometheus, version 2.0.0-alpha.3 (branch: , revision: )
  build user:       root@dfa0e46aa7ac
  build date:       20170630-18:26:12
  go version:       go1.8.1

* Alertmanager configuration file:
```
global:

# The root route on which each incoming alert enters.
route:
  # default route if none match
  receiver: alert-buffer-wh

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  # TODO:
  group_by: []

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

receivers:
- name: alert-buffer-wh
  webhook_configs:
  - url: http://localhost:9099/topics/alerts
```

Relevant BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1508059
