### ISSUE TITLE
Why does alertmanager send multiple [resolved] alerts ?

### ISSUE THREAD

**Issue by shogosanz** [prometheus/alertmanager#1125]
**What did you do?**

I have executed `mysql.server stop` to become db_status's value 0
```
db_status 1.0
↓
db_status 0.0
```
![2017-11-29 12 01 06](https://user-images.githubusercontent.com/25962808/33355954-23a01e80-d4fd-11e7-9fd5-f0ec140b75c4.png)

**What did you expect to see?**
I expect alertmanager send only once resolved alert.

**What did you see instead? Under which circumstances?**
Alertmanager sent multiple alerts. every interval (1m).
<img width="562" alt="2017-11-29 12 06 31" src="https://user-images.githubusercontent.com/25962808/33356069-d230a2d0-d4fd-11e7-8fc9-52861e9d5930.png">
alertmanager1 mesh status
![2017-11-29 12 16 25](https://user-images.githubusercontent.com/25962808/33356344-527cbfea-d4ff-11e7-92a5-cef0ffe28ca8.png)
alertmanager2 mesh status
![2017-11-29 12 17 47](https://user-images.githubusercontent.com/25962808/33356352-5edfbd50-d4ff-11e7-8015-47c1738d6609.png)

**Environment**

* System information:
docker-compose.yml
```
version: '2'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle

  alertmanager1:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: -config.file=/etc/alertmanager/alertmanager.yml -mesh.peer=alertmanager2:6783

  alertmanager2:
    image: prom/alertmanager
    ports:
      - "9094:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: -config.file=/etc/alertmanager/alertmanager.yml -mesh.peer=alertmanager1:6783
```

* Alertmanager version:
```
alertmanager, version 0.11.0 (branch: HEAD, revision: 30dd0426c08b6479d9a26259ea5efd63bc1ee273)
  build user:       root@3e103e3fc918
  build date:       20171116-17:43:56
  go version:       go1.9.2
```

* Prometheus version:

![2017-11-29 12 26 44](https://user-images.githubusercontent.com/25962808/33356595-a6629b2e-d500-11e7-9f02-3af7f57d6148.png)

* Alertmanager configuration file:
```
global:
  slack_api_url: 'https://hooks.slack.com/services/SECRET'

route:
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1m  
  receiver: slack
  group_by: [instance,alertname]

receivers:
- name: slack
  slack_configs:
  - channel: '#test'
    text: "{{ .CommonAnnotations.text }}"
    icon_emoji: '{{ if eq .Status "firing" }}:exclamation:{{ else }}:+1:{{ end }}'
    send_resolved: true
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'codelab-monitor'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager1:9093'
      - 'alertmanager2:9093'

rule_files:
  - ./alert.rules.yml
```
* rules
```
groups:
- name: slackal
  rules:
  - alert: SlackAlert
    expr: db_status == 0
#    for: 1s
    annotations:
      text: "DB server is down"
```

Please give me some advice on what I should do.
thank you and regards.

**Comment by fatalsaint** [comment]
See issue #964 - for now if you raise your repeat_interval you can avoid it.  I set my critical alerts to 1h and warnings to 24h and have managed to avoid the duplicates.

**Comment by shogosanz** [comment]
Thank you for your advice.
I'll check #964 .
I cannot understand why Prometheus send duplicate [Resolved] POST to Alertmanager API. Despite that Alertmanager should send only once RESOLVED notification in principle.

**Comment by c-datculescu** [comment]
Just to chip in: In the prometheus code there is a constant that keeps an alert for exactly 15 min if it has been resolved. Increasing the repeat_interval to 15 min fixes it for most of my cases (it is not yet clear for me why the 15 min is needed).

**Comment by nsaud01** [comment]
I have repeat_interval set to 3 hours and I'm still getting "resolved" only alerts every three hours.

```
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack
```
