### ISSUE TITLE
Alertmanager not printing labels when sending notifications

### ISSUE THREAD

**Issue by ashth231** [prometheus/alertmanager#1144]
**What did you do?**
I have configured **TargetInstanceDown** alert to send notifications to hipchat.I use the default hipchat message template. 

**What did you expect to see?**
Notifications with labels saying which target is down
**What did you see instead? Under which circumstances?**
I did see the Notification with the labels for the first FIRING alert. But for the next alert for a different node, labels were not printed. 

![screen shot 2017-12-14 at 12 34 09](https://user-images.githubusercontent.com/33930961/33992672-7552762c-e0cb-11e7-84ba-5e010599fce4.png)

**Environment**
* Alertmanager version:

	v0.9.1

* Prometheus version:

	v1.8.2

* Alertmanager configuration file:
```
 global:
      resolve_timeout: 5m
      hipchat_auth_token: 'xxx'
      hipchat_url: 'hipchat.com'
    route:
      group_by: [service]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: hipchat
    receivers:
    - name: hipchat
      hipchat_configs:
      - auth_token: 'xxx'
        room_id: <roomid>
        message_format: text
        notify: true
```

* Alert:
```
## Target is down
ALERT target_is_down
  IF up == 0
  FOR 2m
  LABELS {severity="critical"}
  ANNOTATIONS {
    title = "{{ $labels.job }}/{{ if $labels.fqdn }}{{ $labels.fqdn }}{{ else }}{{ $labels.instance }}{{ end }} failed to be scraped for the last few minutes.",
    summary = "Instance {{ $labels.instance }} down",
    description = "Check prometheus alerts and targets to undestand which hosts or exporters could not be scraped",
  }
```
