### ISSUE TITLE
Alertmanager not disinhibiting alert

### ISSUE THREAD

**Issue by oscarruizmrf** [prometheus/alertmanager#1153]
**What did you do?**
We configured a couple of alarms and expect one of them (tooManyAlarms) to inhibit the other one (lowRevenueComparedToPredction).

**What did you expect to see?**
In the first 10 minutes range, alert tooManyAlarms inhibits lowRevenueComparedToPrediction that fires every 2 minutes. Alertmanager shows lowRevenueComparedToPrediction inhibited, as expected. Also, there is no notification via Slack about lowRevenueComparedToPrediction alarms, as expected.

But, in the next 10 minutes range, tooManyAlarms is not firing, hence I expect lowRevenueComparedToPrediction to fire every 2 minutes and notify via Slack.
I expect to see the alarm (lowRevenueComparedToPrediction) in alarmmanager not inhibited. 

**What did you see instead? Under which circumstances?**
 Alertmanager shows lowRevenueComparedToPrediction firing but inhibited although tooManyAlarms is not firing. So, once lowRevenueComparedToPrediction is inhibited, it never disinhibits, unless we restart alertmanager. In that case, lowRevenueComparedToPrediction fires, notifies via Slack and appears not inhibited in alertmanager, until next inhibition.

**Environment**

* System information:

	Darwin 17.2.0 x86_64

* Alertmanager version:

Alertmanager is not showing version, got it from github "github.com/prometheus/alertmanager/cmd/..."
alertmanager, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.9.2

* Prometheus version:

Not showing version on --version.
prometheus, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.9.2

* Alertmanager configuration file:
```
route:
  # Whether an alert should continue matching subsequent sibling nodes.
  receiver: 'slack_team'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 15s
  repeat_interval: 30m
  routes:
  - match_re:
      jiraProject: ^([a-bA-Z]+)$
    receiver: 'slack_team'
  - match:
      owner: test
    receiver: 'slack_test'
    continue: true  

inhibit_rules:
- target_match_re:
    severity: warning
    group: .+  
  source_match_re:
    severity: critical
    group: .+
  # Apply inhibition if the group is the same.
  equal: ['group']
```

* Prometheus configuration file:
```
Alerts for replicating the issue.
groups:
- name: Revenue
  interval: 10s
  rules:
  - alert: tooManyAlarms
    expr: minute() % 20 < 10
    labels:
      group: revenue
      severity: critical
      owner: test
    annotations:
      summary: "Fires every 10 minutes"
      description: "Fires every 10 minutes"
  - alert: lowRevenueComparedToPrediction
    expr: minute()%2 == 0
    labels:
      group: revenue
      severity: warning
      jiraProject: RV
    annotations:
      summary: "Low revenue compared to estimation"
      description: "Low revenue compared to estimation"   
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
