### ISSUE TITLE
Alerting issue in Prometheus is resolved and amtool shows empty alert but alert manager still sending alerts to configured email

### ISSUE THREAD

**Issue by Deepak-Routray** [prometheus/alertmanager#1161]
**What did you do?**
I setup alert manager with old email and afterwards chnaged the config email to a new email but old email still getting emails even when alert is resolved. Prometheus alert page and amtool not showing any firing alert.
**What did you expect to see?**
Alerts to both my old and new email should be stopped.
**What did you see instead? Under which circumstances?**
I am getting regular email with the issue which is already resolved. Even old email getting the alerts while it is no more configured.
**Environment**
Linux Centos
* System information:
Linux 3.10.0-514.16.1.el7.x86_64 x86_64
* Alertmanager version:
Latest(0.12.0)
	insert output of `alertmanager -version` here
alertmanager, version 0.12.0 (branch: HEAD, revision: fc33cc78036f82ef8d4734c197a96f7cb6c952a3)
  build user:       root@c9169eb10d06
  build date:       20171215-14:13:20
  go version:       go1.9.2

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)
prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2
* Alertmanager configuration file:
```
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'no-reply@example.com'
  smtp_require_tls: false
# The directory from which notification templates are read.
templates:
- '/home/centos/Prometheus/alert_manager/template/*.tmpl'
# The root route on which each incoming alert enters.
route:
  group_by: ['alertname', 'cluster', 'service']   # The labels by which incoming alerts are grouped together.
  group_wait: 30s                                 # When a new group of alerts is created by an incoming alert, it waits at least this much to send the initial notification.
  group_interval: 0s                              # When the first notification was sent, wait until 'group_interval' to send a batch of new alerts that started firing for that group.
  repeat_interval: 0s                             # If an alert has successfully been sent, wait until 'repeat_interval' to resend them.
  receiver: 'email_managers'                      # A default receiver
  routes:                                         # This route performs a regular expression match on alert labels to catch alerts that are related to a list of services.
  - match:
      severity: 'page'
    receiver: 'email_managers'
receivers:
- name: 'email_managers'
  email_configs:
  - to: 'ranjan.deepak@gmail.com'

```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

rule_files:
   - "alert.rules"
   - "node.rules"

scrape_configs:
  - job_name: 'all'
    file_sd_configs:
      - files:
        - '*.json'

```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here

Nothing useful is coming up in logs..
```
