### ISSUE TITLE
Default global api key for OpsGenie config

### ISSUE THREAD

**Issue by zemek** [prometheus/alertmanager#1173]
Can we default the OpsGenie `api_key` to be like `global.opsgenie_api_key` ? It looks like it's not configured like that looking at the docs on https://prometheus.io/docs/alerting/configuration/#opsgenie_config
```
# The API key to use when talking to the OpsGenie API.
api_key: <secret>
```

For example, the VictorOps config has 
```
# The API key to use when talking to the VictorOps API.
[ api_key: <secret> | default = global.victorops_api_key ]
```

**Comment by stuartnelson3** [comment]
From reading the docs, the `api_key` can be either a specific team integration (in which case it replaces the `teams` field for the api_key's owning team), or a general key that then must be routed by using teams.

I think this proposal sounds fine. Users should be aware that setting the global `api_key` to a team integration `api_key` squashes all attempts to route via `teams`, since this happens currently if they set it on an individual receiver..

**Comment by stuartnelson3** [comment]
@zemek may I ask a bit about your setup? I'm wondering how you're writing out your config file, and how many ops genie receivers you have, if you're using team integration api keys or a single global one, etc?

**Comment by zemek** [comment]
we have about 10 opsgenie receivers, one for each oncall rotation that's set up like this, using the same api key for each one.
```
receivers:
  - name: 'team1-pager'
    opsgenie_configs:
      - api_key: "xxx"
        teams: "Team1"
  - name: 'team2-pager'
    opsgenie_configs:
      - api_key: "xxx"
        teams: "Team2"
  - name: 'team3-pager'
    opsgenie_configs:
      - api_key: "xxx"
        teams: "Team3
```

@stuartnelson3 is there a better way of doing this?
