### ISSUE TITLE
*smtp.plainAuth failed: wrong host name

### ISSUE THREAD

**Issue by lklkxcxc** [prometheus/alertmanager#1174]
**What did you do?**
The alertmanager send email failed 
**What did you expect to see?**
My email accout received alert mail
**Environment**

* System information:

Linux 4.13.0 x86_64

* Alertmanager version:

alertmanager, version 0.12.0 (branch: HEAD, revision: fc33cc78036f82ef8d4734c197a96f7cb6c952a3)
  build user:       root@c9169eb10d06
  build date:       20171215-14:13:20
  go version:       go1.9.2

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
global:
      # ResolveTimeout is the time after which an alert is declared resolved
      # if it has not been updated.
      resolve_timeout: 5m

      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: smtp.mxhichina.com:465
      smtp_from: 123@mxhichina.com
      smtp_auth_username: 123@mxhichina.com
      smtp_auth_password: xxxx
      smtp_require_tls: false

```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=error ts=2018-01-02T06:48:12.366058027Z caller=notify.go:303 component=dispatcher msg="Error on notify" err="*smtp.plainAuth failed: wrong host name"
level=error ts=2018-01-02T06:48:12.366145229Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="*smtp.plainAuth failed: wrong host name"
level=error ts=2018-01-02T06:53:12.366540064Z caller=notify.go:303 component=dispatcher msg="Error on notify" err="*smtp.plainAuth failed: wrong host name"
level=error ts=2018-01-02T06:53:12.366641457Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="*smtp.plainAuth failed: wrong host name"
```
