### ISSUE TITLE
Default template for multiple receivers

### ISSUE THREAD

**Issue by rophy** [prometheus/alertmanager#1181]
Hi,  is it possible to do the following?

```
route:
  pagerduty_config:
    - description: 'my template here'
  routes:
  - match:
      service: 'a'
    receiver: 'a'
  - match:
      service: 'b'
    receiver: 'b'
  - match:
      service: 'c'
    receiver: 'c'

receivers:
  - name: "a"
    pagerduty_configs:
    - service_key: 'key_a'
  - name: 'b'
    pagerduty_configs:
    - service_key: 'key_b'
  - name: 'c'
    pagerduty_configs:
    - service_key: 'key_c'
```

essentially, have some common receiver config which is shared between receivers, `pagerduty_configs.description` in the example above.
