### ISSUE TITLE
Alertmanager only send one alert firing/resolved

### ISSUE THREAD

**Issue by heng-Yuan** [prometheus/alertmanager#1184]
**I have deployed prometheus, node_exporter, alertmanaer, and my own webhook. When node_exporter was down, I could receive an alert from alertmanager to my webhook and email. But when I started node_exporter I couldn't receive nothing from alertmanager, Unless I restarted alertmanager.**

**There are my alertmanager debug infomation:**
```
level=info ts=2018-01-09T03:23:59.177148788Z caller=main.go:155 msg="Starting Alertmanager" version="(version=0.11.0, branch=HEAD, revision=30dd0426c08b6479d9a26259ea5efd63bc1ee273)"
level=info ts=2018-01-09T03:23:59.177255874Z caller=main.go:156 build_context="(go=go1.9.2, user=root@3e103e3fc918, date=20171116-17:43:56)"
level=info ts=2018-01-09T03:23:59.178548274Z caller=main.go:293 msg="Loading configuration file" file=alertmanager.yml
level=info ts=2018-01-09T03:23:59.187655466Z caller=main.go:368 msg=Listening address=:9093
level=debug ts=2018-01-09T03:25:44.498966195Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:25:59.498876083Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:26:14.498678705Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:26:29.498620867Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:26:44.498608212Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:26:59.498237234Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:27:14.498302178Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:27:29.498486444Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:27:44.498640619Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:27:59.498454116Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:28:14.499288295Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:28:29.49845806Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:28:29.498711656Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}:{alertname=\"NodeDown\"}" msg=Flushing alerts=[NodeDown[03db258][active]]
level=debug ts=2018-01-09T03:28:44.498676727Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:28:59.498456339Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:29:14.498436002Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:29:29.498506056Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:29:44.498578373Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:29:59.498494489Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:30:14.498684043Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:30:29.498619704Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:30:44.49943832Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:30:59.49844713Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:31:14.498489998Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][active]
level=debug ts=2018-01-09T03:31:29.498411096Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:31:44.498197273Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:31:59.498400304Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:32:14.49831899Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:32:29.498308943Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:32:44.498386574Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:32:59.498213041Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:33:14.498079146Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:33:29.498277496Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:33:44.498338878Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:33:59.498180345Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:34:14.498466798Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:34:29.498244372Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:34:44.498176934Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:34:59.49818067Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:35:14.498129068Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
level=debug ts=2018-01-09T03:35:29.498206503Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeDown[03db258][resolved]
```

**And this is my webhook code:**
```
def deal_recv(dict_):
    ...

class RequestHandler(BaseHTTPRequestHandler):
	def do_POST(self):
		ctype, pdict = cgi.parse_header(self.headers['content-type'])
		if ctype == 'application/json':
			length = int(self.headers['content-length'])
			post_values = json.loads(self.rfile.read(length))
			deal_recv(post_values)
		else:
			print("Only json data is supported.")
			self.send_error(415, "Only json data is supported.")
			self.send_header('Content-type', 'text/html')
			self.end_headers()
			return
		self.send_response(200)
		self.send_header('Content-type', 'text/html')
		self.end_headers()
		return

def start_server(port):
	http_server = HTTPServer(('', int(port)), RequestHandler)
	http_server.serve_forever()

if __name__ == "__main__":
	start_server(29100)
```

**Environment**

* System information:

	Linux 3.10.0-229.el7.x86_64 x86_64

* Alertmanager version:

	alertmanager, version 0.11.0 (branch: HEAD, revision: 30dd0426c08b6479d9a26259ea5efd63bc1ee273)
  build user:       root@3e103e3fc918
  build date:       20171116-17:43:56
  go version:       go1.9.2

* Prometheus version:

	prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2

* Alertmanager configuration file:
```
global:
    smtp_smarthost: 'smtp.XXX.com:25'
    smtp_from: 'mail-helper@XXX.com'
    smtp_auth_username: 'mail-helper@XXX.com'
    smtp_auth_password: 'XXX'
route: 
    receiver: 'default-receiver'
    group_by: ['alertname', 'group']
    group_wait: 3m
    group_interval: 1h
    repeat_interval: 24h
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service'] 
receivers: 
- name: 'default-receiver'
  email_configs: 
  - to: 'leon@XXX.com' 
    send_resolved: true
  webhook_configs:
  - url: 'http://172.16.199.31:29100/' 
    send_resolved: true
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['127.0.0.1:9093']
rule_files:
  - "rules/up.rules.yml"
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['172.16.199.31:9100']
```
