### ISSUE TITLE
Alertmanager scanning entire network for peers

### ISSUE THREAD

**Issue by adityanmishra** [prometheus/alertmanager#1243]
**What did you do?**
Upgrade Alertmanager from 0.9 to 0.14 with mesh for HA
**What did you expect to see?**
Only assigned hosts
**What did you see instead? Under which circumstances?**
Almost all hosts in mesh
**Environment**
QA
* System information:
Linux 3.10.0-693.17.1.el7.x86_64 x86_64
	insert output of `uname -srm` here

* Alertmanager version:
0.14.0
	insert output of `alertmanager -version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
version: '2'
services:
  alertmanager:
    image: XXXX/prom/alertmanager:v0.14.0
    container_name: alertmanager
    command:
      - '--web.listen-address=:8081'
      - '--log.level=debug'
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--mesh.peer=x.x.x.x'
    restart: unless-stopped
    network_mode: "host"

insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
