### ISSUE TITLE
memberlist DNS resolution error

### ISSUE THREAD

**Issue by jamtur01** [prometheus/alertmanager#1261]
I am running `master` to play with the new memberlist clustering in Kubernetes. I have an odd DNS resolution error... It doesn't appear to interfere with functionality but wanted to log it in case anyone else sees it and is confused too.

So this is my service and statefulset:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webui
  namespace: monitoring
  labels:
    app: alertmanager
    component: core
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: web
      name: web
  selector:
    app: alertmanager
    component: core
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    component: core
spec:
  ports:
  - port: 8001
    name: cluster
  type: ClusterIP
  clusterIP: None
  selector:
    app: alertmanager
    component: core
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    component: core
spec:
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: alertmanager
  serviceName: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
        component: core
    spec:
      containers:
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:master
        imagePullPolicy: IfNotPresent
        command:
        - "sh"
        - "-c"
        args:
        - /bin/alertmanager
            --config.file=/etc/alertmanager/config.yml
            --web.listen-address=0.0.0.0:9093
            --cluster.listen-address=0.0.0.0:8001
            --storage.path=/alertmanager
            --cluster.peer="alertmanager-0.alertmanager.monitoring.svc:8001"
            --cluster.peer="alertmanager-1.alertmanager.monitoring.svc:8001"
            --cluster.peer="alertmanager-2.alertmanager.monitoring.svc:8001"
            --log.level=debug
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 8001
          name: cluster
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: web
            scheme: HTTP
          failureThreshold: 10
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/status
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
        - name: alertmanager-config-volume
          mountPath: /etc/alertmanager/
        - name: alertmanager-data-volume
          mountPath: /alertmanager/
      volumes:
      - name: alertmanager-config-volume
        configMap:
          name: alertmanager-server-conf
      - name: alertmanager-data-volume
        emptyDir: {}
```

This is the debug output from one of the alertmanagers:

```
addrs 0.0.0.0:8001
level=info ts=2018-02-27T03:33:46.165947329Z caller=main.go:151 msg="Starting Alertmanager" version="(version=0.14.0, branch=master, revision=29e441f88f3e758ff6a1c8a536fdb752c5b32af9)"
level=info ts=2018-02-27T03:33:46.166043263Z caller=main.go:152 build_context="(go=go1.9.2, user=root@19dec1fcf7af, date=20180222-15:01:16)"
level=debug ts=2018-02-27T03:33:46.24821988Z caller=cluster.go:75 component=cluster msg="resolved peers to following addresses" peers=alertmanager-0.alertmanager.monitoring.svc:8001,alertmanager-1.alertmanager.monitoring.svc:8001,alertmanager-2.alertmanager.monitoring.svc:8001
level=debug ts=2018-02-27T03:33:46.262930727Z caller=cluster.go:347 component=cluster received=NotifyJoin node=01C7AN5GMFPHBMYV1YQK4D247D addr=100.96.7.8:8001
level=warn ts=2018-02-27T03:33:46.326634461Z caller=cluster.go:122 component=cluster msg="failed to join cluster" err="3 errors occurred:\n\n* Failed to resolve alertmanager-0.alertmanager.monitoring.svc:8001: lookup alertmanager-0.alertmanager.monitoring.svc on 100.64.0.10:53: no such host\n* Failed to resolve alertmanager-1.alertmanager.monitoring.svc:8001: lookup alertmanager-1.alertmanager.monitoring.svc on 100.64.0.10:53: no such host\n* Failed to resolve alertmanager-2.alertmanager.monitoring.svc:8001: lookup alertmanager-2.alertmanager.monitoring.svc on 100.64.0.10:53: no such host"
```

HOWEVER - the cluster is working:

<img width="627" alt="screenshot 2018-02-26 22 57 26" src="https://user-images.githubusercontent.com/4365/36709894-72175100-1b48-11e8-98f4-c82e5c85bf7a.png">

So I am not sure why it's telling me it can't resolve the endpoints... *shrugs*

**Comment by simonpasquier** [comment]
It seems that this AlertManager instance tries to resolve the names while they are not yet registered in the k8s DNS server. I suspect that the cluster state is ok because another instance of the cluster has managed to connect to this instance and has broadcast the peer information.

@fabxc would it make sense to add more retries for the DNS resolution?

**Comment by simonpasquier** [comment]
In another context but still using StatefulSet, I've investigated a similar configuration (eg deploying AlertManager using statefulet). Here is what happens using the OP example:

* k8s launches the first pod (`alertmanager-0`). When the alertmanager process starts, it can't resolved any of the peer addresses hence the errors in the log.
* once `alertmanager-0` is running and ready, k8s launches `alertmanager-1`. This time when the alertmanager process starts, it resolves `alertmanager-0.alertmanager.monitoring.svc` and connects to it. `alertmanager-2.alertmanager.monitoring.svc` can't be resolved though so it will logged.
* once `alertmanager-1` is running and ready, k8s launches `alertmanager-2`. When the alertmanager process starts, it resolves both `alertmanager-0.alertmanager.monitoring.svc` and `alertmanager-1.alertmanager.monitoring.svc`, and it connects to them.
* The cluster is now complete.

In the end, it works because the default pod management for statefulsets is to start pods sequentially. If you were to set `podManagementPolicy: Parallel` (more [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies)), it would fall apart.

**Comment by csghuser** [comment]
@jamtur01 @simonpasquier Thanks for this, works fine for me it seems. 

Only issue is that prometheus seems to want to scrape on port 8001 as well as 9093 when looking at targets in Prometheus. Is there a way to avoid this?

**Comment by simonpasquier** [comment]
@csghuser can you ask the question on the prometheus mailing list so that the discussion can benefit to everyone else? Also please provide the details on your Prometheus configuration.

**Comment by csghuser** [comment]
I managed to fix it by adding the port:

```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
```
