### ISSUE TITLE
Alertmanager Configuration global http_config

### ISSUE THREAD

**Issue by mrl045** [prometheus/alertmanager#1274]
**What did you do?**
Tried to implement a global http_config. 

**What did you expect to see?**
Nothing

**What did you see instead? Under which circumstances?**
time="2018-03-05T13:46:07Z" level=error msg="Loading configuration file failed: unknown fields in global: tls_config" file="/etc/config/alertmanager.yml" source="main.go:238"

Also tried the following configuration (i am using configMaps for Kubernetes):
```
apiVersion: v1
data:
  alertmanager.yml: |-
    global:
      # ResolveTimeout is the time after which an alert is declared resolved
      # if it has not been updated.
      resolve_timeout: 5m

      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'foo@bar.com'
      smtp_auth_username: 'foo@bar.com'
      smtp_auth_password: 'barfoo'

      # The API URL to use for Slack notifications.
      slack_api_url: 'https://mattermost.xxxx/hooks/xxxx'
      http_config:
        - tls_config:
             ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
```
Read the following documentation:
https://prometheus.io/docs/alerting/configuration/#%3Chttp_config%3E

       

**Environment**
Kubernetes 1.8.5

* System information:

	Linux 4.14.11-coreos x86_64

* Alertmanager version:

	prom/alertmanager:v0.9.1

* Prometheus version:

	prom/prometheus:v1.8.1

* Alertmanager configuration file:
```
apiVersion: v1
data:
  alertmanager.yml: |-
    global:
      # ResolveTimeout is the time after which an alert is declared resolved
      # if it has not been updated.
      resolve_timeout: 5m

      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'foo@bar.com'
      smtp_auth_username: 'foo@bar.com'
      smtp_auth_password: 'barfoo'

      # The API URL to use for Slack notifications.
      slack_api_url: 'https://mattermost.xxxx/hooks/xxxx'
      http_config:
        - tls_config:
             ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
time="2018-03-05T13:56:46Z" level=info msg="Starting alertmanager (version=0.9.1, branch=HEAD, revision=9f5f4b2a516d35cfaf196530b277f1d109254569)" source="main.go:109" 
time="2018-03-05T13:56:46Z" level=info msg="Build context (go=go1.9, user=root@3b87d661c3dd, date=20170929-12:59:03)" source="main.go:110" 
time="2018-03-05T13:56:46Z" level=info msg="Loading configuration file" file="/etc/config/alertmanager.yml" source="main.go:235" 
time="2018-03-05T13:56:46Z" level=error msg="Loading configuration file failed: unknown fields in global: tls_config" file="/etc/config/alertmanager.yml" source="main.go:238"
```

**Comment by simonpasquier** [comment]
This will be supported in the future version (v0.15.0) of AlertManager.

**Comment by mrl045** [comment]
Okay great news. I will wait for the next update. 

Thank you for your answer and keep up the good work 👍

**Comment by princerachit** [comment]
Has this feature added in v0.15.0-rc.1? @simonpasquier 
I am getting the error ```Invalid Alertmanager config: unknown fields in webhook config: http_config```

**Comment by simonpasquier** [comment]
@princerachit yes the feature is present, I've just verified from the release tarball.

**Comment by princerachit** [comment]
Any idea why this is happening?

```
global:
  resolve_timeout: 5m
route:
  receiver: "r1"
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m
receivers:
- name: "alertstore"
  webhook_configs:
  - url: '${ALERT_STORE_URL}'
    send_resolved: true
    http_config:
      basic_auth:
        username: '${USERNAME}'
        password: '${PASSWORD}'
```

Error `Invalid Alertmanager config: unknown fields in webhook config: http_config`
