### ISSUE TITLE
Alertmanager value is not updated for subsequent reports

### ISSUE THREAD

**Issue by matejzero** [prometheus/alertmanager#1283]
**What did you do?**

Setup some exporter, alerts and hoped to see updated values for alarms in Alertmanager.

**What did you expect to see?**

I expected `value` field to be updated on reevaluation.

**What did you see instead? Under which circumstances?**

I'm seeing the same (first) value all the time. It doesn't get updated, although I can see updated values in Prometheus UI.

Similar issue(#550) was suppose to be fixed some time ago.

View from Prometheus UI, where we can see value being updated:
![prometheus](https://user-images.githubusercontent.com/4689252/37403889-8b8ec97a-2790-11e8-9e1d-e69c82483efb.png)
![screen shot 2018-03-14 at 13 55 52](https://user-images.githubusercontent.com/4689252/37403891-8bcc1fe6-2790-11e8-9494-cca2bacb57f5.png)

View in Alertmanager after some time:
![alertmanager](https://user-images.githubusercontent.com/4689252/37403890-8bae092a-2790-11e8-8f7b-95229ca5917b.png)

**Environment**

* System information:

```
# uname -srm
Linux 3.10.0-693.11.6.el7.x86_64 x86_64
```

* Alertmanager version:

```
# ./alertmanager --version
alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
  build user:       root@37b6a49ebba9
  build date:       20180213-08:16:42
  go version:       go1.9.2
```

* Prometheus version:

```
# ./prometheus --version
prometheus, version 2.2.0 (branch: HEAD, revision: f63e7db4cbdb616337ca877b306b9b96f7f4e381)
  build user:       root@52af9f66ce71
  build date:       20180308-16:40:42
  go version:       go1.10
```

* Alertmanager configuration file:

This is a testing instance, so basically default config.

* Prometheus configuration file:

Relevant part of config:
```
---
# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert-rules/*.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager_host:9093"
```

* Logs:

Nothing special in logs. Maybe I should run in debug mode.

**Comment by brian-brazil** [comment]
There's insufficient information in this report to indicate a problem. Where exactly are you seeing the old value, what are your alerting rules, and what is the receiver config?

**Comment by matejzero** [comment]
I'm seeing the old value in front page in AlertManager UI under Alerts and also in `unsee` dashboard.

Unfortunately, I don't have any reports sent by alertmanager to my email (will have them tomorrow), so I can't tell if values there are being updated.

My alerting rule:
```
    - alert: MySQLReplicationLag
      # expr: (mysql_slave_lag_seconds > 30) AND on (instance) (predict_linear(mysql_slave_lag_seconds[5m], 60*2) > 0)
      expr: (mysql_slave_status_seconds_behind_master > 30) AND on (instance) (predict_linear(mysql_slave_status_seconds_behind_master[5m], 60*2) > 0)
      for: 1m
      labels:
        severity: critical
        value: "{{ humanize $value }}"
      annotations:
        summary: "MySQL slave replication is lagging"
        description: "The mysql slave replication has fallen behind and is not recovering"
```

Alertmanager config:
```
global:
  smtp_smarthost: 'mail.company.com:25'
  smtp_from: 'alertmanager@company.com'
            
templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 1h
  receiver: team-mail

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
- name: 'team-mail'
  email_configs:
  - send_resolved: true
    to: 'matejz@company.com'
```
