### ISSUE TITLE
alertmanager can't silenced all matched alerts

### ISSUE THREAD

**Issue by Sisphyus** [prometheus/alertmanager#1295]
**What did you do?**
prometheus run very well unless when I configure the alertmanager silence rules to test if I really can silenced alert, 9 alerts matched, but only 7 can be silenced(without "cache_traffic" and "nodestat_cnc_http_1") , I can't find what's wrong with my configuration

**What did you expect to see?**
all of the matched alerts can be silenced
**What did you see instead? Under which circumstances?**
![x n 3 mx4toinmsus 2d60](https://user-images.githubusercontent.com/22763940/37764011-928df586-2dfb-11e8-98d1-6ebd5f0e1f60.png)
![g ybabme7syrsp3 mtotzo](https://user-images.githubusercontent.com/22763940/37764084-c44b4bdc-2dfb-11e8-9e90-2c146336de25.png)
![k5 qqyk8 r4 mu geu](https://user-images.githubusercontent.com/22763940/37764158-dc2fb6c0-2dfb-11e8-87cb-ec9b2168dac1.png)

**Environment**

* System information:

	Linux 3.10.0-229.el7.x86_64 x86_64

* Alertmanager version:

  alertmanager, version 0.14.0 
  build user:       root@37b6a49ebba9
  build date:       20180213-08:16:42
  go version:       go1.9.2

* Prometheus version:

  prometheus, version 2.1.0 
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2

* Alertmanager configuration file:
```
global:
  smtp_smarthost: '***'  
  smtp_from: '***'  
  smtp_auth_username: '***'  
  smtp_auth_password: '***'    
  smtp_require_tls: false      
route:
  group_by: ['group','alertname','severity']    
  group_wait: 30s   
  group_interval: 10m    
  repeat_interval: 1h     
  receiver: 'test-mails'   
receivers:
- name: 'test-mails'
  email_configs:
  - to: "tangyj@fxdata.cn"
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s 
  evaluation_interval: 1m 
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093
rule_files:
   - "/etc/prometheus/rules/*.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: "60s"
    static_configs:
      - targets: ['localhost:9091']
```
