### ISSUE TITLE
Change hipchat_configs.notify from boolean to string type

### ISSUE THREAD

**Issue by timbunce** [prometheus/alertmanager#1320]
**What did you do?**
```
- name: redacted
  hipchat_configs:
    - auth_token: redacted
      api_url: 'redacted'
      room_id: 6689
      notify: '{{ if eq .GroupLabels.env "prod" }}true{{ else }}false{{ end }}'
```
**What did you expect to see?**

Alertmanager working and template control over hipchat notify setting

**What did you see instead? Under which circumstances?**
```
level=error ts=2018-04-11T10:38:17.284690585Z caller=main.go:278 msg="Loading configuration file failed" file=/etc/alertmanager.yml err="yaml: unmarshal errors:\n  line 193: cannot unmarshal !!str `{{ if e...` into bool"
```

The [hipchat api](https://developer.atlassian.com/server/hipchat/messages/) defines the notify field as either a string _or_ boolean ("`str | bool`").

Changing hipchat_configs.notify from boolean to string type would enable template control and be forward compatible with existing configurations.

**Comment by brian-brazil** [comment]
May I ask why you want to control this? This sort of thing is typically handled by routing, not templating.

**Comment by timbunce** [comment]
To avoid having near-duplicate receiver definitions and adding complexity to the routing.
(Where env=prod the routing also fires a pagerduty notification but that might take a while to get routed to the relevant team.)

**Comment by brian-brazil** [comment]
It sounds like you already have that complexity, as it's fundamental.

**Comment by timbunce** [comment]
I'm not following the reasoning that, because we have some amount of complexity already, adding more is okay.

We have many teams so many hipchat channels so many hipchat_configs.

To "handle it by routing" would mean _doubling_ the number of hipchat_configs, duplicating the config of each, just to have one with `notify: false` and a duplicate with `notify: true`, and then effectively duplicating the relevant routing rules to route to the `notify: true` receivers when appropriate.

That seems like a significant and unreasonable increase in complexity for something that could be trivially and naturally addressed by enabling templating of the notify attribute like the color attribute.

If the color attribute didn't support templating I doubt there would be suggestions to duplicate the hipchat_config for each desired color and handle it by routing.

**Comment by brian-brazil** [comment]
> then effectively duplicating the relevant routing rules to route to the notify: true receivers when appropriate.

You already have to have these routes and receivers in order to send these subset alerts to Pagerduty.

Receiver templating is intended for changing what the message looks like, not how it is delivered.

**Comment by timbunce** [comment]
Teams want an alert to their hipchat channel to trigger a notify for different conditions (typically wider/looser) than those that would cause an alert to go to Pagerduty.

**Comment by brian-brazil** [comment]
You really want a route for that, I don't think there's enough justification for a breaking change here.

I'd also note that distracting an entire team with a notification is not a great idea, if it's important that the team looks at it it should go to the designated oncall/onduty person.

**Comment by timbunce** [comment]
In what way would this be a breaking change?

**Comment by brian-brazil** [comment]
You're changing the type of a field.

**Comment by timbunce** [comment]
Current possible values of this boolean field are
```
notify: true
notify: false
```
Changing the field type to string, and passing either of those values to hipchat, will not change any behaviour.

**Comment by brian-brazil** [comment]
There are far more valid values than that for a bool in YAML.

**Comment by timbunce** [comment]
That's true, but my point still stands. All the valid values for true and false for a boolean field in YAML are also valid as unquoted strings. Changing the type from boolean to string to enable templating will not change the behaviour of existing configurations. I'm sure this is not a breaking change otherwise I wouldn't have proposed it.

**Comment by brian-brazil** [comment]
You've making an assumption there which the docs do not support. Just because it would be a valid configuration doesn't meant that hipchat would understand it.

**Comment by timbunce** [comment]
I've just tested the hipchat API and can confirm that it accepts both string and boolean types for the notify field [per the docs](https://developer.atlassian.com/server/hipchat/messages/) and that the strings `true` and `yes` (with any capitalization) enable notifications.

It doesn't accept `y` or the word `on` which are other [common values for a boolean](http://yaml.org/type/bool.html) accepted by most parsers ([e.g.](https://github.com/go-yaml/yaml/blob/86f5ed62f8a0ee96bd888d2efdfd6d4fb100a4eb/resolve.go#L37-L39)). It would be trivial to detect these values and map them to `true`.

**Comment by brian-brazil** [comment]
I don't think it'd be worth the complication for a use case which I'm still not clear on.

**Comment by timbunce** [comment]
Here's an example of a config with team based routing without being able to template the notify setting:
```
route:
  ...
  routes:
  - match:
      team: aaa
    receiver: hipchat-aaa
    - match:
        env: prod
      receiver: hipchat-aaa-notify
  - match:
      team: bbb
    receiver: hipchat-bbb
    - match:
        env: prod
      receiver: hipchat-bbb-notify
  - match:
      team: ccc
    receiver: hipchat-ccc
    - match:
        env: prod
      receiver: hipchat-ccc-notify
  - match:
      team: ddd
    receiver: hipchat-ddd
    - match:
        env: prod
      receiver: hipchat-ddd-notify
receivers:
- name: hipchat-aaa
  hipchat_configs:
    - send_resolved: True
      room_id: aaa
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
- name: hipchat-aaa-notify
  hipchat_configs:
    - send_resolved: True
      room_id: aaa
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: true
- name: hipchat-bbb
  hipchat_configs:
    - send_resolved: True
      room_id: bbb
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
- name: hipchat-bbb-notify
  hipchat_configs:
    - send_resolved: True
      room_id: bbb
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: true
- name: hipchat-ccc
  hipchat_configs:
    - send_resolved: True
      room_id: ccc
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
- name: hipchat-ccc-notify
  hipchat_configs:
    - send_resolved: True
      room_id: ccc
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: true
- name: hipchat-ddd
  hipchat_configs:
    - send_resolved: True
      room_id: ddd
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
- name: hipchat-ddd-notify
  hipchat_configs:
    - send_resolved: True
      room_id: ddd
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: true
```
In practice each team would have a more complex routing tree.

Here's the same config using the ability to template the notify setting:
```
route:
  ...
  routes:
  - match:
      team: aaa
    receiver: hipchat-aaa
  - match:
      team: bbb
    receiver: hipchat-bbb
  - match:
      team: ccc
    receiver: hipchat-ccc
  - match:
      team: ddd
    receiver: hipchat-ddd
receivers:
- name: hipchat-aaa
  hipchat_configs:
    - send_resolved: True
      room_id: aaa
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: '{{ if eq .GroupLabels.env "prod" }}true{{ else }}false{{ end }}'
- name: hipchat-bbb
  hipchat_configs:
    - send_resolved: True
      room_id: bbb
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: '{{ if eq .GroupLabels.env "prod" }}true{{ else }}false{{ end }}'
- name: hipchat-ccc
  hipchat_configs:
    - send_resolved: True
      room_id: ccc
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: '{{ if eq .GroupLabels.env "prod" }}true{{ else }}false{{ end }}'
- name: hipchat-ddd
  hipchat_configs:
    - send_resolved: True
      room_id: ddd
      from: 'prometheus'
      color: '{{ if eq .Status "firing" }}{{ if eq .GroupLabels.env "prod" }}red{{ else }}yellow{{ end }}{{ else }}green{{ end }}'
      notify: '{{ if eq .GroupLabels.env "prod" }}true{{ else }}false{{ end }}'
```

**Comment by brian-brazil** [comment]
That config does not match the scenario you described, there are no pagerduty configs.

**Comment by timbunce** [comment]
I was focusing on the routing required for hipchat with and without this feature.
With pagerduty included the routing for each team would look something like this: 
```
    - match:
        team: aaa
      receiver: hipchat-aaa
      routes:
      - match:
          env: prod
        routes:
        - match:
            severity: critical
          receiver: pagerduty-aaa
          continue: true
        - receiver: receiver: hipchat-aaa-notify
```
