### ISSUE TITLE
all peers sending notifications

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1341]
**What did you do?**
Deployed alertmanager built off `dc5fc02d221665df3136b4ee6ef5ba64f5b83f02` to baremetal and ran as normal. I checked the various alertmanager metrics to see how it was performing, and `alertmanager_notifications_total` caught my eye.

**What did you expect to see?**
I expected to see a single instance sending all notifications when viewing the metrics `alertmanager_notifications_total`. My understanding of the wait stage and peer position was that it should be only in failure cases that a peer with a higher mesh position should send notifications.

**What did you see instead? Under which circumstances?**
Under normal operation, all 4 instances are regularly sending out notifications to all integrations being used (email, pagerduty, slack).

![image](https://user-images.githubusercontent.com/1398104/39236349-eb83a144-4878-11e8-8841-8c8a90ce8a23.png)

**Environment**

* System information:
`Linux 4.4.10+soundcloud x86_64`

* Alertmanager version:

```
alertmanager, version 0.15.0-rc.1 (branch: master, revision: dc5fc02d221665df3136b4ee6ef5ba64f5b83f02)
  build user:       stuart@starch
  build date:       20180424-08:54:18
  go version:       go1.10.1
```
the version is incorrect, it's built off a more recent revision. the major change I see in the changelog between the released `rc1` and the revision above is https://github.com/prometheus/alertmanager/pull/1301.

* Alertmanager configuration file:
```yaml
route:
  group_wait: 2m
  group_interval: 1h
  repeat_interval: 24h
  receiver: prodeng-warn
  group_by: [alertname, zone, system]
  routes:
    # bunch of routes. Some have custom intervals, usually:
    group_wait: 20s
    group_interval: 5m
    repeat_interval: 3h
```

* Startup command:
```
/srv/prometheus/alertmanager/alertmanager \
  --web.listen-address=":9093" \
  --web.external-url="http://alertmanager/" \
  --log.level="debug" \
  --config.file="/srv/prometheus/alertmanager/alertmanager.yml" \
  --cluster.listen-address=xx.xx.xx.xx:9094 \
  --cluster.settle-timeout=2m \
  --cluster.peer=xx.xx.xx.xx:9094 \
  --cluster.peer=xx.xx.xx.xx:9094 \
  --cluster.peer=xx.xx.xx.xx:9094 \
  --cluster.peer=xx.xx.xx.xx:9094 \
  --storage.path="/srv/prometheus/alertmanager/data"
```
Note: Each node is also included as a `--cluster.peer`

* Logs:
I haven't noticed anything out of the ordinary. It might be good to add some logging here:

https://github.com/prometheus/alertmanager/blob/master/notify/notify.go#L441-L448

and note how long a peer waited before sending.

EDIT:

Status page:
![image](https://user-images.githubusercontent.com/1398104/39239704-fc0ff5b8-4881-11e8-8d8f-bcbd499c9e58.png)

**Comment by stuartnelson3** [comment]
@mxinden @fabxc @brancz

**Comment by brancz** [comment]
This definitely looks strange, unfortunately I'm extremely busy and won't be able to have a look at this any time soon. cc @simonpasquier

**Comment by simonpasquier** [comment]
> My understanding of the wait stage and peer position was that it should be only in failure cases that a peer with a higher mesh position should send notifications.

This is generally correct though low `group_wait` intervals can cause some variation. In your case with a default peer timeout of 15s, AlertManagers `#2` and `#3` will stop on WaitStage for 30s and 45s which is longer than the 20s `group_wait`. In the end, it may be that the alert groups don't tick at the same time on the different AlertManagers after the initial notification (see https://github.com/prometheus/alertmanager/issues/1005#issuecomment-375702952). But right now it is just my guess.

Just to be sure, is `alertmanager_peer_position` stable across all instances?

**Comment by simonpasquier** [comment]
I see a similar pattern on my local env with low `group_wait` values and 3 AlertManagers.

![image](https://user-images.githubusercontent.com/2587585/39248647-f45f5316-489c-11e8-8a3a-2afb4eabda1c.png)

I'm also seeing another issue with alert groups flapping from resolved to firing and then resolved in a few seconds.

```
15:27:23 receiver.go:57: msg="received notification" gkey="{}/{severity=~\"^(?:critical)$\"}:{job=\"service2\", severity=\"critical\"}" status="resolved" am=http://simon-laptop:9094
15:27:33 client.go:67: msg="sending 4 alert(s)"
15:27:33 receiver.go:57: msg="received notification" gkey="{}/{severity=~\"^(?:critical)$\"}:{job=\"service2\", severity=\"critical\"}" status="firing" am=http://simon-laptop:9095
15:27:43 client.go:67: msg="sending 4 alert(s)"
15:27:43 receiver.go:57: msg="received notification" gkey="{}/{severity=~\"^(?:critical)$\"}:{job=\"service2\", severity=\"critical\"}" status="resolved" am=http://simon-laptop:9094
```

 What happens probably:
* The alert group is firing. AlertManager at position 2 kicks in at `group_interval` but it has to wait for 30s before actually doing anything.
* Within those 30 seconds, the alert group resolves. The AlertManager at position 0 kicks in and sends the resolved notification.
* When AlertManager at position 2 exits from its WaitStage, it sends a firing notification because it compares its own set of alerts with the last entry from the log which was resolved ([source](https://github.com/prometheus/alertmanager/blob/cfde256913c914b32b25e56073d01121e4a96e9e/notify/notify.go#L521)).

Increasing the base timeout interval from 5s to 15s has probably exacerbated this issue. Not sure what was the rationale for changing the value?

**Comment by stuartnelson3** [comment]
>Increasing the base timeout interval from 5s to 15s has probably exacerbated this issue. Not sure what was the rationale for changing the value?

Are you referring to `--cluster.peer-timeout`? Or `resolve_timeout` in the config? How are the alerts being resolved?

**Comment by simonpasquier** [comment]
I meant `--cluster.peer-timeout`. FWIW I'm still running tests with different parameters.

**Comment by simonpasquier** [comment]
The Alertmanager configuration I'm using for the 3 nodes:
```
global:                                        
  resolve_timeout: 5m                          

route:                                         
  group_by: [alertname, job]                   
  group_wait: 20s                              
  group_interval: 60s                          
  repeat_interval: 110s                        
  receiver: 'web.hook'                         
  routes:                                      
  - group_by: [job, severity]                  
    group_wait: 10s                            
    group_interval: 20s                        
    repeat_interval: 70s                       
    receiver: 'web.hook'                       
    match_re:                                  
      severity: critical                       

receivers:                                     
- name: 'web.hook'                             
  webhook_configs:                             
  - url: 'http://127.0.0.1:8081/'              
    send_resolved: true                        
```

I simulate alerts with critical and warning severity for 2 services. In the end, it means 4 different alert groups that fire then resolve alternatively.

When `cluster.peer-timeout` is set to 15s, the notifications are spread across the 3 instances:
![image](https://user-images.githubusercontent.com/2587585/39256056-3cca2714-48ae-11e8-9aa5-d7c7df631f9d.png)

When `cluster.peer-timeout` is 5s, this is less visible:
![image](https://user-images.githubusercontent.com/2587585/39256125-6a6535ec-48ae-11e8-938d-fe24ea340b0a.png)

**Comment by simonpasquier** [comment]
> We're also seeing a situation in which peer at position=0 and peer at position=3 are sending notifications at the same time

For this alert group, what is the route configuration exactly?

**Comment by stuartnelson3** [comment]
```yaml
  - match:
      system: raid
    group_wait: 30m
    repeat_interval: 100000h
    routes:
    - match:
        severity: info
      receiver: devsupport-info
    # Create one ticket per instance, as many alerts tend to fire if something is broken with
    # the RAID controller.
    group_by: [instance, job, system]
    receiver: devsupport
```
