### ISSUE TITLE
smtp.plainAuth failed: unencrypted connection

### ISSUE THREAD

**Issue by justlooks** [prometheus/alertmanager#1358]
i config alertmanager smtp info ,like following
```
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtpdm.aa.com:25'
  smtp_from: 'user@aa.com'
  smtp_auth_username: 'user@aa.com'
  smtp_auth_password: 'password'
  smtp_require_tls: false

```

but i get error in log 
```
level=error ts=2018-05-03T03:18:35.632974975Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="*smtp.plainAuth failed: unencrypted connection"
level=error ts=2018-05-03T03:18:35.632960462Z caller=notify.go:311 component=dispatcher msg="Error on notify" err="*smtp.plainAuth failed: unencrypted connection"

```

```
# ./bin/alertmanager --version
alertmanager, version 0.15.0-rc.1 (branch: HEAD, revision: acb111e812530bec1ac6d908bc14725793e07cf3)
  build user:       root@f278953f13ef
  build date:       20180323-13:05:10
  go version:       go1.10
```
