### ISSUE TITLE
amtool: off my one error in yaml UnamarshalStrict

### ISSUE THREAD

**Issue by adamdecaf** [prometheus/alertmanager#1375]
**What did you do?**

Given the following alertmanager config:

```yaml
route:
  routes:
    - receiver: test

receivers:
  - name: test
    slack_configs:
      - channel: "{{ if eq .Annotations.description "" }}{{ .Annotations.message }}{{ else }}{{ .Annotations.description }}{{ end }}"
```

**What did you expect to see?**

The error is on line 8. It should be `- channel: '...'`

**What did you see instead? Under which circumstances?**

```
$ amtool check-config bad.yaml 
Checking 'bad.yaml'  FAILED: yaml: line 7: did not find expected key

amtool: error: failed to validate 1 file(s)
```

**Environment**

* Alertmanager version:

```
$ git log -n1 
commit 942be9d99333e54cd9cce5debb7d24568b39931e (HEAD -> master, origin/master, origin/HEAD)
Author: stuart nelson <stuartnelson3@gmail.com>
Date:   Wed May 9 10:57:01 2018 +0200

    cli alert query: Expose --active and --unprocessed (#1370)
```
