### ISSUE TITLE
cat't get email with err=EOF

### ISSUE THREAD

**Issue by xuejipeng** [prometheus/alertmanager#1378]
**What did you do?**
  config the email alert

**What did you expect to see?**

  get email
**What did you see instead? Under which circumstances?**

  don't get anything
**Environment**

* System information:

Linux 3.10.0-693.11.6.el7.x86_64 x86_64
* Alertmanager version:
  alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
  build user:       root@37b6a49ebba9
  build date:       20180213-08:16:42
  go version:       go1.9.2
* Prometheus version:

	prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10

* Alertmanager configuration file:
```
 global:
      resolve_timeout: 2m
      smtp_smarthost: 'smtp.qiye.163.com:994'
      smtp_from: 'test@163.com'
      smtp_auth_username: 'test@163.com'
      smtp_auth_password: '*********'
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1m
      receiver: 'email_alert'
     
    receivers:
    - name: 'email_alert'
      email_configs:
      - to: 'test1@163.com'
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
evel=debug ts=2018-05-12T13:45:34.824101555Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeMemoryUsage[990e5a1][active]
level=debug ts=2018-05-12T13:45:34.824159879Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=NodeMemoryUsage[94b61d3][active]
level=debug ts=2018-05-12T13:45:34.900753567Z caller=notify.go:605 component=dispatcher msg="Notify attempt failed" attempt=1 integration=email receiver=email_alert err=EOF
level=debug ts=2018-05-12T13:45:34.90089863Z caller=notify.go:605 component=dispatcher msg="Notify attempt failed" attempt=1 integration=email receiver=email_alert err=EOF
```
