### ISSUE TITLE
--web.exernal-url breaks healthcheck to localhost

### ISSUE THREAD

**Issue by anthraxn8b** [prometheus/alertmanager#1382]
**What did you do?**
- added `--web.exernal-url=http://myexternalurl.nowhere` parameter
- created a healthcheck to http://localhost:9093
- deploy container on docker swarm

**What did you expect to see?**
- healthy container - healthcheck OK

**What did you see instead? Under which circumstances?**
- restarted container - healthcheck NOT OK (checked this by starting a bash inside the container and doing a `wget --spider https://localhost:9093` which results in a 404 - !not connection refused!)

**PROMETHEUS BEHAVES AS EXPECTED!**

**Environment**

* System information: Linux 3.10.0-693.11.6.el7.x86_64 x86_64
* Alertmanager version: 0.14.0
  alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
    build user:       root@37b6a49ebba9
    build date:       20180213-08:16:42
    go version:       go1.9.2

* Prometheus version:
  prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
    build user:       root@149e5b3f0829
    build date:       20180314-14:15:45
    go version:       go1.10

* Alertmanager configuration file:
```
#
# https://prometheus.io/docs/alerting/configuration
#
global:
  smtp_from: alertmanager.somewhere@noreply.com
  smtp_smarthost: 10.24.50.12:25
  smtp_require_tls: false

  pagerduty_url:
  hipchat_api_url:
  opsgenie_api_url:
  victorops_api_url:

route:
  group_by:   ['alertname', 'cluster', 'service']
  group_wait: 30s
  receiver:   'email_config'

receivers:
- name: email_config
  email_configs:
  - to: 'me@home'
    headers: { stage : 'TEST' }
```

* Prometheus configuration file: not required

* Logs: There is nothing written to the alertmanager log when getting the 404.
