### ISSUE TITLE
When a group has multiple alarms,cannot receive resolved  notice

### ISSUE THREAD

**Issue by fubotao** [prometheus/alertmanager#1399]
**What did you do?**
There are ten alarms in a notice group. after a time,one of them has resolved,But I didn't receive any notice. repeat_interval later, I got a notice， it has nine alarms.
if the group only have one alarm, When the alarm is resolved, I can receive the notice immediately.

**What did you expect to see?**
When a group has multiple alarms , One of them resolved, I should be notified immediately.

**What did you see instead? Under which circumstances?**
 nothing

**Environment**

* System information:

          Linux 2.6.32-573.22.1.el6.centos.plus.x86_64 x86_64
* Alertmanager version:
           version 0.15.0-rc.1 
* Prometheus version:

	prometheus  2.1.0

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m 
  smtp_smarthost: '192.168.3.101:25'
  smtp_from: 'prometheus@alter.com'
  smtp_require_tls: false
  
templates:
   - /prometheus/test/alertmanager-0.15.0-rc.1.linux-amd64/test.tmpl
route:
  group_by: ['alertname', 'job_name','severity']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 10m
  receiver:  team-X-mails
receivers:
- name: 'team-X-mails'
  email_configs:
  - to: 'xxxxxx@139.com'
    send_resolved: true
    #html: '{{ template "email.test.html" . }}'
    #headers: {Subject: '{{ template  "subject_email" . }}'}
```

**Comment by simonpasquier** [comment]
> When a group has multiple alarms , One of them resolved, I should be notified immediately.

This isn't the current expectation. `group_interval` only applies when new alerts are added to the group, not when existing alerts resolve.

From the [docs](https://prometheus.io/docs/alerting/configuration/#route):

```
# How long to wait before sending a notification about new alerts that
# are added to a group of alerts for which an initial notification has
# already been sent. (Usually ~5m or more.)
[ group_interval: <duration> | default = 5m ]
```

**Comment by simonpasquier** [comment]
A group of alerts is what matters for AlertManager so if the group itself isn't resolved, there's no point to send a notificaiton. If you want more fine-grained notifications, you can either lower `repeat_interval` or group on more labels.

**Comment by fubotao** [comment]
OK.  But   the number of alarms in a group has changend .   More will  send a notificaiton, less is not.
Thanks

**Comment by fubotao** [comment]
Which version has this feature

**Comment by pintify** [comment]
I guess anyone closed before this [commit](https://github.com/prometheus/alertmanager/commit/62b957cc14031947337f3ad5cfb62d6fe3e38bab), but particularly we are working with 0.5.1 (a bit old, I know, we were very keen on the upgrade).

**Comment by simonpasquier** [comment]
Can you describe in more details why you need this feature?
I think that the rationale for not sending updates on partial resolution is to avoid the extra noise and load on the AlertManager and receivers. Basically something is wrong with my system and I don't care that a fraction of alerts has been resolved in between.

**Comment by brian-brazil** [comment]
Yes, the purpose of group_interval is the throttle the number of notifications from a group. This is largely for human sanity.
Sending partial notifications would defeat the entire purpose of group_interval.

**Comment by pintify** [comment]
The main purpose is integration: besides the mailing, we push the notifications through a web service that collects the alerts and resolutions and register them within a centralized alerts system (Prometheus is only part of the alert architecture), so the termination of an alert is as needed as the beginning of it. We considered reducing repeat_interval but the increase of the traffic was worse solution than simply falling back to previous version.

**Comment by brian-brazil** [comment]
I presume that's via a webhook, the next webhook notification will include all the resolved alerts since the last notification.

**Comment by pintify** [comment]
Indeed, but real time is lost. This is particularly annoying when, for example, some of the alerts remain for long time.

We faced this situation recently (the way we discovered the issue, indeed), when part of the system went down. The alerts raised for all of the equipments affected but lasted much time in going down because after booting them one of them needed to be replaced and we had to wait a couple of days.

**Comment by brian-brazil** [comment]
It's not the goal of the alertmanager to be realtime, the goal is to provide high signal to noise notifications to humans. With the above configuration the delay is going to be at most one minute.

If even that 1m delay is too much, I'd suggest ingesting the alerts from Prometheus directly rather than via the Alertmanager.

**Comment by pintify** [comment]
Actually, our configuration is:
```
  group_wait: 1m
  group_interval: 2m
  repeat_interval: 6h
```
However, when alert is solved, there are no notifications after the 2 minutes, at most the repetition after 12h which only lists the firing alerts but not the resolved. The service does not notice the resolution until all of them are solved.

The 2 minutes delay would be perfect, respect group_interval in both firing and resolving notifications seems fair to me.

**Comment by brian-brazil** [comment]
@pintify Can you file a separate bug for this then please, including the exact version you're running?

**Comment by pintify** [comment]
#https://github.com/prometheus/alertmanager/issues/1403

**Comment by jidckii** [comment]
Faced the same problem.
I do not receive a notification resolved if all problems are in the 1st group.

For example, I monitor 40 URLs in a blackbox.

I have these configurations:

prom/prometheus:v2.2.1 :

```
- job_name: blackbox
  scrape_interval: 10s
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
  - targets:
    - https:/site1.example.com
    - http:/site2.example.com
    - https:/site3.example.com
    - http:/site4.example.com
    - https:/site5.example.com
    - https:/site6.example.com
    - https:/site7.example.com
    - https:/site8.example.com
    - http:/site9.example.com

  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox_exporter:9115 
```

rule_alerts:    

```
---
groups:
- name: web
  rules:

  - alert: Site_Down
    expr: probe_success != 1
    for: 1m
    labels:
      severity: critical
    annotations:
      description: "Site {{ $labels.instance }} is down for 1 min."
```

prom/alertmanager:v0.14.0 :    

```
---
global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'email@example.org'
  smtp_auth_username: 'email@example.org'
  smtp_auth_password: "{{ SMTP_AUTH_PASSWORD }}"

route:
  group_by: ['web']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 1h
  receiver: ops

receivers:
- name: 'ops'
  email_configs:
  - send_resolved: true
    to: 'email@example.org'

```

for example (behavior with the parameter `repeat_interval: 1h`):

12:00 site1 down (I get email Firing 1)
12:10 site2 down (I receive email Firing 2)
12:30 site2 up (do not receive anything)
13:10 (I receive email Firing 1 (site1))


That is, I do not receive a notification at all that the site2 is resolved.
I link this with the `resolve_timeout: 5m`
Since if `repeat_interval: 10m` this scenario is already like this:

12:00 site1 down (I get email Firing 1)
12:10 site2 down (I receive email Firing 2)
12:30 site2 up (do not receive anything)
13:10 (I receive email Firing 1 (site1), Resolved 1 (site 2)))


I understand that the goal is to avoid unnecessary noise. But I have the feeling that the site2 did not work.

And by default in the body of the message Resolved, there is no information about when it worked, and how long it lasted Firing ...

In general, it is very much misleading, especially if you look at the service from the outside and you just need to know what and when DOWN and what and when UP
