### ISSUE TITLE
Not receiving resolved alert

### ISSUE THREAD

**Issue by prasenforu** [prometheus/alertmanager#1401]
I am using Prometheus and Alertmanager in Openshift 3.9 (Origin).

my Alertmanager config file as follows ..

```
global:
 smtp_smarthost: 'in-v3.mailjet.com:25'
 smtp_from: 'xxx@gmail.com'
 smtp_auth_username: 'user-token'
 smtp_auth_password: 'pass-token'
route:
 # default route if none match
 receiver: all
 group_by: []
receivers:
- name: mail
  email_configs:
  - to: "kkkkk@xxx.com"
    send_resolved: true
- name: all
  email_configs:
  - to: "yyyyyy@gmail.com"
    send_resolved: true
  webhook_configs:
  - url: http://localhost:9099/topics/alerts 
```
I know in webhook_configs resolved is true but both config (webhook_configs & email_configs) not sending resolved alert.

Image : `openshift/prometheus-alertmanager:v0.14.0`
