### ISSUE TITLE
Resolved notification sent only when all alerts are solved

### ISSUE THREAD

**Issue by pintify** [prometheus/alertmanager#1403]
**What did you do?**

Launch several alerts, and solve part of them

**What did you expect to see?**

A resolved notification after part of the alerts were solved.

**What did you see instead? Under which circumstances?**

No solved notification at all. Neither after group_interval time, nor when the repeat_interval reached. Resolution was notified when all the alerts were solved.

**Environment**

Running with the official docker images

* System information:

	Linux 3.10.0-693.5.2.el7.x86_64 x86_64

* Alertmanager version:

	alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
  build user:       root@37b6a49ebba9
  build date:       20180213-08:16:42
  go version:       go1.9.2

* Prometheus version:

	prometheus, version 1.6.1 (branch: master, revision: 4666df502c0e239ed4aa1d80abbbfb54f61b23c3)
  build user:       root@7e45fa0366a7
  build date:       20170419-14:32:22
  go version:       go1.8.1

* Alertmanager configuration file:
```
...
  routes:
  - match:
      ...
    receiver: 'X-team'
    group_by: ['alertname']
    group_wait: 1m
    group_interval: 2m
    repeat_interval: 6h

receivers:
- name: 'X-team'
  webhook_configs:
  - url: 'my-url'
    send_resolved: true
```
