### ISSUE TITLE
alertmanager.url can not be an alias setup in /etc/hosts

### ISSUE THREAD

**Issue by casertap** [prometheus/alertmanager#141]
Here is part of my docker-compose.yml
````
promalertmgr:
  build: promalertmgr/
  container_name: promalertmgr
  ports:
    - "9093:9093"
  expose:
    - "9093"
  command: "-config.file=/alertmanager.conf"
  env_file:
    - './.env'

prometheus:
  build: prometheus/
  container_name: prometheus
  links:
    - cadvisor
    - promalertmgr
    - streamapp
    - dashboardapp
    - analyzeapp
    - mongo
  ports:
    - "9090:9090"
  command: "-config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://192.168.99.100:9093"
  env_file:
    - './.env'

`````
If I change this: 
````
-alertmanager.url=http://192.168.99.100:9093
````
into this:
````
-alertmanager.url=promalertmgr:9093
````
It does not work anymore.

**Comment by casertap** [comment]
the alertmanager.url needs to be a public url. Meaning the url must be outside of the docker private network (it can not stay inside the private network of docker, using an alias will not work). 
This can be a problem because the port 9093 is then open to anybody to see...

Someone interested in this issue?

**Comment by fabxc** [comment]
As in #164, there's nothing to be done on the Alertmanager side here.

**Comment by fuzzyami** [comment]
@casertap: you state that "the alertmanager.url needs to be a public url" - i'm wondering how you've reached that conclusion. I'm trying to link a dockerized Prometheus to my dockerized AlertManager and getting the following error - which may be related to your claim:
``` "time="2016-10-13T08:46:37Z" level=error msg="Error sending alerts: Post alertmanager:9093/api/v1/alerts: unsupported protocol scheme \"alertmanager\"" alertmanager="alertmanager:9093" count=1 source="notifier.go:308""```

**Comment by brancz** [comment]
@fuzzyami you need to include the protocol scheme in your url. `alertmanager:9093` does not, you are likely looking for `http://alertmanager:9093`.

**Comment by fuzzyami** [comment]
@brancz - just figured it out. thanks though!

**Comment by AxelMonroyX** [comment]
I get the IP from docker inspect, replace it in a file and then run the prometheus container
```
docker run --name alert -p 9093 prom/alertmanager

ALERT_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' alertmanagercontainer)
sed -i "s@ALERT_IP@${ALERT_IP}@g" prometheus.yml

docker run -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml -p 9090  --link alert:alert prom/prometheus
```

and my prometheus.yml looks like

```
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - ALERT_IP:9093
```
