### ISSUE TITLE
missing agentid 0.15.0-rc.3

### ISSUE THREAD

**Issue by zhailibao2013** [prometheus/alertmanager#1425]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here
        Linux 4.9.34-29.el7.x86_64 x86_64

* Alertmanager version:

	insert output of `alertmanager --version` here
alertmanager, version 0.15.0-rc.3 (branch: HEAD, revision: 5e86f61bd73c6325d6049ab3dbcb468ede26dfe0)
  build user:       root@0d28fc42e4ec
  build date:       20180618-10:26:10
  go version:       go1.10.3

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  smtp_smarthost: '10.124.0.54:25'
  smtp_from: 'alertmanager@xxxx.corp'
  smtp_auth_username: 'user'
  smtp_auth_password: 'xxxxx'
  smtp_require_tls: false
  wechat_api_url: "http://qyapi-weixin.zcbigdata.corp/cgi-bin/"
  wechat_api_secret: "xxxxxxx"
  wechat_api_corp_id: "xxx"  
  http_config:
    proxy_url: "http://proxy.xxxxxx.corp:3128"
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'libaozhai-emails'
  routes:
  - match:
      alertname: DeadMansSwitch
    receiver: 'null'
receivers:
- name: 'null'
- name: 'libaozhai-emails'
  email_configs:
  - to: 'libaozhai@xxxx.cn'
    send_resolved: true
    require_tls: false
  wechat_configs:
    - send_resolved: true
      to_user: "zhailibao"
      agent_id: "1000002"
      corp_id: "xxxx" 
      api_secret: "xxxx-xx"
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here

```
* wireshark pcap:
```
POST http://qyapi-weixin.zcbigdata.corp/cgi-bin/message/send?access_token=7xypGG5TbcYSogr9e1CdApd_F1cZ-qpAU4aw6MLQGoB68BbUmoHRJuvqhiwdM1Uzs66p4hXG1Jfaa9jl6ZlcJHmf4T3-D907iLBuMm_L3Jn4Ra5E2924chc0RdDJGY2i5-EUBOfjINKB5Nb4Nue5qcclS5eOzAVjy72ap7sf6fcg0O-FdQmaHJIW0AooL3lCWHOiBouzE_tWUeln3x_rJyrbGzLCRDNLHRmMpaAcGvw HTTP/1.1
Host: qyapi-weixin.zcbigdata.corp
User-Agent: Go-http-client/1.1
Content-Length: 630

{"text":{"content":"[RESOLVED] kubelet (TargetDown warning)\n14.285714285714285% of kubelet targets are down. Targets are down\n\nAlerts Resolved:\nLabels:\n - alertname = TargetDown\n - job = kubelet\n - severity = warning\nAnnotations:\n - description = 14.285714285714285% of kubelet targets are down.\n - summary = Targets are down\nSource: http://prometheus-k8s-0:9090/graph?g0.expr=100+%2A+%28count+by%28job%29+%28up+%3D%3D+0%29+%2F+count+by%28job%29+%28up%29%29+%3E+10\u0026g0.tab=1\n\nAlertmanagerUrl:\nhttp://alertmanager-main-2:9093/#/alerts?receiver=libaozhai-emails"},"touser":"zhailibao","safe":"0","msgtype":"text"}
HTTP/1.1 200 OK
Server: Apache/2.2.1
Date: Thu, 21 Jun 2018 09:38:12 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 167
Error-Code: 41011
Error-Msg: missing agentid, hint: [1529573892_3_4d6207fcf053f2457a601f77d6f6e9ea], more info at https://open.work.weixin.qq.com/devtool/query?e=41011
X-Cache: MISS from zx-dmz-0-22
X-Cache-Lookup: MISS from zx-dmz-0-22:3128
Connection: keep-alive

{"errcode":41011,"errmsg":"missing agentid, hint: [1529573892_3_4d6207fcf053f2457a601f77d6f6e9ea], more info at https://open.work.weixin.qq.com/devtool/query?e=41011"}

```
* docker images:
```
docker pull quay.io/prometheus/alertmanager:v0.15.0-rc.3

```
