### ISSUE TITLE
When the alarm is restored, the alertmanager send the wrong recovery value message

### ISSUE THREAD

**Issue by tangxuye** [prometheus/alertmanager#1444]
**What did you do?**
I tried to use sql_exporter to collect some business data and cofigured the rule file of prometheus

**What did you expect to see?**
In order to notify me when the alarm is triggered or resolved from altermanager by wechat. 

**What did you see instead? Under which circumstances?**
When the alarm is triggered, the current value of sql  which I have received was  higher than the threshold. That's correct. However, when the current value is less than the threshold, the alarm was restored and the value that I receive is still higher than the threshold.

**Environment**

* System information:

	Linux 3.10.0-327.el7.x86_64 x86_64

* Alertmanager version:

	0.15.0-rc.1

* Prometheus version:

	2.2.1

* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'wechat'
  routes:
  - receiver: 'wechat'
    group_wait: 5s
    group_interval: 1m
    repeat_interval: 3h
    continue: false
    match:
      team: handdeduct

receivers:
- name: 'wechat'
  wechat_configs:
  - corp_id: 'xxxxxxxxxxxx'
    to_user: '@all'
    agent_id: 'xxxxxx'
    api_secret: 'xxxxxxxxxxx'
    send_resolved: true

```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Altermanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.138.30.235:9093

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'nginx_vts_export'
    static_configs:
      - targets: ['localhost:9913']
  - job_name: 'nginx_vts_exporter'
    static_configs:
      - targets: ['10.138.30.154:9913']
  - job_name: 'sql_exporter'
    static_configs:
      - targets: ['10.138.30.235:9399']
  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['10.138.60.219:9419']
```

* Logs:
```
There is no error log about trigger alarm and alarm restore

```
