### ISSUE TITLE
Slack certificate signed by unknown authority

### ISSUE THREAD

**Issue by VinceMD** [prometheus/alertmanager#1453]
**What did you do?**
I setup a Slack receiver

**What did you expect to see?**
I expected to receive notifications in Slack

**What did you see instead? Under which circumstances?**
level=error ts=2018-07-04T01:12:25.705362686Z caller=notify.go:303 component=dispatcher msg="Error on notify" err="Post https://hooks.slack.com/services/XXXXXXX: x509: certificate signed by unknown authority"

where XXXXXX is the actual API webhook

**Environment**

* System information:

Linux 4.14.19-coreos x86_64

* Alertmanager version:

```alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
  build user:       root@37b6a49ebba9
  build date:       20180213-08:16:42
  go version:       go1.9.2
```

* Alertmanager configuration file:
```
# external alertmanager yaml
global:
  resolve_timeout: 10m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'slack-channel'
  routes:
  - match:
      alertname: DeadMansSwitch
    receiver: 'slack-channel'
receivers:
- name: 'slack-channel'
  slack_configs:
  - channel: #vince
    send_resolved: true
    username: 'vince'
    api_url: https://hooks.slack.com/services/XXXXX
```

* Logs:
see above

We use Prometheus Operator to manage Prometheus and Alert manager. I hoped into the container of alert manager and was able to fire the Slack notification with wget (curl not available)

`wget --post-data '{"text":"Hello, World!"}' https://hooks.slack.com/services/XXXXX`

It could be an issue with our company proxy. For many cases we need to supply and install a CA certificate when accessing HTTPS service.

How do I install a custom CA certificate inside the Docker image of Prometheus Alert Manager?
