### ISSUE TITLE
Basic authentication not working in Alertmanager v.0.15.0

### ISSUE THREAD

**Issue by 7mode** [prometheus/alertmanager#1454]
**What did you do?**

I'm trying to use basic authentication in Alertmanager v.0.15.0 by configuring a receiver with `basic_auth` inside `http_config section`.

In the receiver side I print the request headers and I see that `Authorization` header is missing.

**What did you expect to see?**

A request with Authorization header in the receiver side.

**What did you see instead? Under which circumstances?**

A header of the request with the following fields without Authorization header:
```
Content-Length : 2213
User-Agent : Alertmanager/0.15.0
Host : 127.0.0.1:8999
Content-Type : application/json
```

**Environment**

* System information:

	Linux 4.4.0-121-generic x86_64

* Alertmanager version:

	alertmanager, version 0.15.0 (branch: HEAD, revision: 462c969d85cf1a473587754d55e4a3c4a2abc63c)
  build user:       root@bec9939eb862
  build date:       20180622-11:58:41
  go version:       go1.10.3

* Prometheus version:

	prometheus, version 2.3.1 (branch: HEAD, revision: 188ca45bd85ce843071e768d855722a9d9dabe03)
  build user:       root@82ef94f1b8f7
  build date:       20180619-15:56:22
  go version:       go1.10.3

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1m
  receiver: user
receivers:
- name: 'user'
  webhook_configs:
  - url: 'http://127.0.0.1:8999/v1/event'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'admin'
        password: 'password'


inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "/home/ubuntu/prometheus-2.3.1.linux-amd64/node_alerts.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['devstack-rocky-4:9100']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
```
