### ISSUE TITLE
Double notifications in the slack

### ISSUE THREAD

**Issue by Gatses** [prometheus/alertmanager#1472]
**What did you do?**
Configuring notifications in the slack.

**What did you expect to see?**
Notifications to the channel defined by the setting: "channel"

**What did you see instead? Under which circumstances?**
Notifications to the channel defined by the setting (channel), as well as to the default channel specified when creating the Webhook.
If disable the "send_resolved" setting, notifications are only sent to the channel that is defined by the channel setting.

**Environment**

* System information:
Linux 4.4.0-83-generic x86_64

* Alertmanager version:
0.14.0, 0.15.0, 0.15.1

* Prometheus version:
2.3.1

* Alertmanager configuration file:
```
global:
  slack_api_url: 'url'
  resolve_timeout: 1m

route:
  receiver: 'test'
  repeat_interval: 60m

receivers:
- name: 'test'
  slack_configs:
  - send_resolved: true
  - channel: '#channel'
```

**Comment by Gatses** [comment]
```
global:
  **slack_api_url: 'url'**
  resolve_timeout: 1m

route:
  receiver: 'test'
  repeat_interval: 60m

receivers:
- name: 'test'
  slack_configs:
  - send_resolved: true
  - channel: '#channel'
```

At slack it is called "Incoming WebHooks". :)

**Comment by simonpasquier** [comment]
Your configuration is a bit off, it should be:

```yaml
receivers:
- name: 'test'
  slack_configs:
  - send_resolved: true
    # no extra dash before channel
    channel: '#channel'
```

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
