### ISSUE TITLE
/status page "leaking" query string sensitive data

### ISSUE THREAD

**Issue by isavcic** [prometheus/alertmanager#1479]
**What did you do?**

Opened the /status page

**What did you expect to see?**

I expected *not* to see sensitive data, ie. API key in a query string of the URL to a webhook clearly visible.

For example, quite a few modern web servers trim the query string in the logs after the question mark for this very same reason.

**What did you see instead? Under which circumstances?**

API key in plain sight:
```
- name: alerta
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://1.2.3.4:8080/api/webhooks/prometheus?api-key=MYSECRETKEY
```

**Environment**

* System information:

```
4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

* Alertmanager version:

```
alertmanager, version 0.15.1 (branch: HEAD, revision: 8397de1830f154535a31150f9262da0072d8725d)
  build user:       root@efde7f9485ae
  build date:       20180712-18:25:27
  go version:       go1.10.3
```

* Alertmanager configuration file:

Pasted the relevant section above.
