### ISSUE TITLE
alertmanager can't send email

### ISSUE THREAD

**Issue by navyabairi** [prometheus/alertmanager#1480]
hello,

I'm working on setting up alertmanager on google cloud. 
I'm having the some issue with the alertmanager sending emails, but when I use mailx server, I'm getting email without any issue. please helm me with this

I'm using this command with mailx: 
echo -e 'hello' | mailx  -S ssl-verify=ignore -S smtp=smtps://smtpserver.com:2525 -S from="noreply@domain.com" -S ssl-verify=ignore -S nss-config-dir=/etc/pki/nssdb/ -s criticalalert -vv toaddress@domain.com

Below are the logs I'm getting on alertmanager:

`level=error ts=2018-07-25T16:16:28.992881815Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF level=error ts=2018-07-25T16:16:28.992495571Z caller=notify.go:332 component=dispatcher msg="Error on notify" err=EOF level=error ts=2018-07-25T16:16:28.992960753Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF level=error ts=2018-07-25T16:16:38.992955299Z caller=notify.go:332 component=dispatcher msg="Error on notify" err=EOF level=error ts=2018-07-25T16:16:38.993024946Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF level=error ts=2018-07-25T16:16:38.992954963Z caller=notify.go:332 component=dispatcher msg="Error on notify" err=EOF level=error ts=2018-07-25T16:16:38.993125709Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF`

Alertmanager config:

```
- name: 'email'
      email_configs:
      - to: 'toaddress@domain.com'
        send_resolved: true
        smarthost: 'smtp.server.com:2525'
        from: 'noreply@domain.com'
        require_tls: true
        text: 'mail-from-prometheus'
```
