### ISSUE TITLE
Webhook connection timeout in version 0.15.*

### ISSUE THREAD

**Issue by Kirchen99** [prometheus/alertmanager#1493]
**What did you do?**

Let Alertmanager send notifications to webhook.

**What did you expect to see?**

Alerting notification is shown in RocketChat channel.

**What did you see instead? Under which circumstances?**

nothing happens. Error message in logs. It works with same configuration file in v0.13.0 and v0.14.0, but fails in v0.15.0 and v0.15.1

* Alertmanager version:

alertmanager, version 0.15.1 (branch: HEAD, revision: 8397de1830f154535a31150f9262da0072d8725d)
  build user:       root@efde7f9485ae
  build date:       20180712-18:25:27
  go version:       go1.10.3

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: default
  group_by:
  - alertname
  - instance
  routes:
  - receiver: default
    match_re:
      service: ^(?:^(foo1|foo2|baz)$)$
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 90h
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - host
receivers:
- name: default
  webhook_configs:
  - send_resolved: false
    http_config: {}
    url: https://rocket.chat/hooks/$token
- name: alpha
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://webhook
templates:
- /etc/alertmanager/email.test.tmpl
```

* Logs:
```
alertmanager_1  | level=info ts=2018-08-01T14:45:05.864425287Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.1, branch=HEAD, revision=8397de1830f154535a31150f9262da0072d8725d)"
alertmanager_1  | level=info ts=2018-08-01T14:45:05.864884117Z caller=main.go:175 build_context="(go=go1.10.3, user=root@efde7f9485ae, date=20180712-18:25:27)"
alertmanager_1  | level=debug ts=2018-08-01T14:45:05.864931618Z caller=cluster.go:143 component=cluster msg="resolved peers to following addresses" peers=
alertmanager_1  | level=info ts=2018-08-01T14:45:05.880486639Z caller=cluster.go:155 component=cluster msg="setting advertise address explicitly" addr=172.18.0.3 port=9094
alertmanager_1  | level=debug ts=2018-08-01T14:45:05.883130094Z caller=delegate.go:209 component=cluster received=NotifyJoin node=01CKTZ656RVXQVPBFRZMZ5N7PV addr=172.18.0.3:9094
alertmanager_1  | level=debug ts=2018-08-01T14:45:05.884168734Z caller=cluster.go:224 component=cluster msg="joined cluster" peers=0
alertmanager_1  | level=info ts=2018-08-01T14:45:05.885174231Z caller=main.go:320 msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
alertmanager_1  | level=info ts=2018-08-01T14:45:05.892895973Z caller=main.go:396 msg=Listening address=:9093
alertmanager_1  | level=info ts=2018-08-01T14:45:05.893581042Z caller=cluster.go:570 component=cluster msg="Waiting for gossip to settle..." interval=10m0s
alertmanager_1  | level=info ts=2018-08-01T14:46:05.885331424Z caller=cluster.go:579 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=59.991679185s
alertmanager_1  | level=debug ts=2018-08-01T14:46:14.553811524Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=test[7167cee][active]
alertmanager_1  | level=debug ts=2018-08-01T14:46:44.554245008Z caller=dispatch.go:445 component=dispatcher aggrGroup="{}:{alertname=\"test\"}" msg=Flushing alerts=[test[7167cee][active]]
alertmanager_1  | level=debug ts=2018-08-01T14:47:14.553677441Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=test[7167cee][active]
alertmanager_1  | level=debug ts=2018-08-01T14:48:14.553707682Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=test[7167cee][active]
alertmanager_1  | level=debug ts=2018-08-01T14:49:14.553700664Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=test[7167cee][active]
alertmanager_1  | level=debug ts=2018-08-01T14:50:14.553693256Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=test[7167cee][active]
alertmanager_1  | level=debug ts=2018-08-01T14:51:04.943847838Z caller=notify.go:668 component=dispatcher msg="Notify attempt failed" attempt=1 integration=webhook receiver=default err="Post https://rocket.chat/hooks/$token: dial tcp *.59.105.*:443: connect: connection timed out"
alertmanager_1  | level=debug ts=2018-08-01T14:51:14.553608343Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=test[7167cee][active]
alertmanager_1  | level=debug ts=2018-08-01T14:51:44.554404796Z caller=notify.go:668 component=dispatcher msg="Notify attempt failed" attempt=2 integration=webhook receiver=default err="context deadline exceeded"
alertmanager_1  | level=error ts=2018-08-01T14:51:44.554562446Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="context deadline exceeded"
alertmanager_1  | level=error ts=2018-08-01T14:51:44.55459591Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="context deadline exceeded"
alertmanager_1  | level=debug ts=2018-08-01T14:51:44.554689938Z caller=dispatch.go:445 component=dispatcher aggrGroup="{}:{alertname=\"test\"}" msg=Flushing alerts=[test[7167cee][active]]
```

**Comment by simonpasquier** [comment]
This is weird. I suspect that it has to do with v0.15.0/v0.15.1 being built with go1.10 while previous versions were built with go1.9. The test would be to build v0.14.0 with go1.10 and see if the issue reproduces. Are you able to do that? Otheriwse I can provide it.

**Comment by Kirchen99** [comment]
Thank you @simonpasquier . it works with proxy setting:
```
- name: default
  webhook_configs:
  - send_resolved: false
    http_config:
      proxy_url: http://my.proxy.internal:80
    url: https://rocket.chat/hooks/$token
```
This is still weird for me, why in previous versions it works without proxy setting. 
This issue can be closed.
