### ISSUE TITLE
Alertmanager notification failure is on one receiver but retry is on all the receivers in the list

### ISSUE THREAD

**Issue by kavyakul** [prometheus/alertmanager#1494]
**What did you do?**
I have an alert which needs to be sent to two receivers:
```
- name: 'Send_mail'
  email_configs:
  - to: 'X...@domain.com'

    send_resolved: true
  webhook_configs:
  - url: 'http//<IP>:port/api/webhooks/prometheus'
    send_resolved: true
```

**What did you expect to see?**
If the alert is being rejected by one of the receiver, the retries should not send the notification to receiver where there was no rejection.

**What did you see instead? Under which circumstances?**
The alert is being rejected at the web api receiver, while its being successfully sent via email.

Meanwhile the alert is resolved and notification about resolved alert is being sent to both the receivers.
The problem is alertmanager keeps on retrying sending notification about resolved alert to the web api (as its failing there), which is fine, but this retry is also sending resolved notification to email receiver as well.

* System information:

	Linux 3.10.0-693.21.1.el7.x86_64 x86_64

* Alertmanager version: 

	0.6.2

* Alertmanager configuration file:
```
    - receiver: 'Send_mail'
      group_by: ['severity', 'alertname', 'host', 'application','environment']
      group_wait: 2m
      group_interval: 3m
      repeat_interval: 1h
      match_re:
        application: ABC
      continue: true

receivers:
- name: 'Send_mail'
  email_configs:
  - to: 'X...@domain.com'

    send_resolved: true
  webhook_configs:
  - url: 'http//<IP>:port/api/webhooks/prometheus'
    send_resolved: true
     
```

* Logs:
```
time="2018-07-31T22:07:19Z" level=error msg="Notify for 1 alerts failed: Cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 403 from http://IP:port/api/webhooks/prometheus" source="dispatch.go:261"
time="2018-07-31T22:08:09Z" level=error msg="Error on notify: Cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 403 from http://IP:port/api/webhooks/prometheus" source="notify.go:283"
```

Can there be separate configuration(e.g. number_of_retries, resend_on_failure) for both the receivers?

**Comment by simonpasquier** [comment]
_I've edited the description to fix the formatting_

**Comment by simonpasquier** [comment]
Are you really running 0.6.2? If so, please upgrade to the latest stable version and try to reproduce.

**Comment by sosoriov** [comment]
@kavyakul  @simonpasquier I'm having same issue here!

alertmanager version: **0.16.1** 


```yaml
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'ms-test-channel'  # default/fallback request handler
  routes:
    - receiver: ms-test-channel
      match_re:
        cluster: .*cl-dvlp.*


receivers:
- name: ms-test-channel
  webhook_configs:
    - url: "https://outlook.office.com/webhook/xxxxxx/IncomingWebhook/yyyyyy/xxxxx-xxx-xxx-xxx-xxxxxx"
      send_resolved: true

``` 

Error: 

```
alertmanager[173076]: level=error ts=2019-03-27T09:55:18.126281874Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 400 from https:xxxxx
```

any solution?

thanks for your help.
