### ISSUE TITLE
AlertManager throwing 400 status code for hipchat room

### ISSUE THREAD

**Issue by azizzoaib786** [prometheus/alertmanager#1495]
Facing issue on AlertManager when sending alerts to hipchat, sometimes it get success and sometimes it sends error 400.
Please note that AlertManager is running as container inside Linux host.

**Environment**

* System information:

	`Linux 3.10.0-693.17.1.el7.x86_64 x86_64` --> Linux Host

* Alertmanager image:

	`prom/alertmanager:latest`

* Prometheus image:

	`prom/prometheus:latest`

* Alertmanager configuration file:
```
global:
  hipchat_api_url: 'URL'
  http_config:
   proxy_url: 'IP:PORT' 

route:
  group_by: [service]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: hipchat

receivers:
    - name: 'hipchat'
      hipchat_configs:
        - auth_token: <token>
          room_id: <id>
          notify: true
          message: '{{.CommonAnnotations.description}}'
          send_resolved: true
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'VL-FOS-Monitoring'

rule_files:
  - "alert_rules.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['<URL>']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
  
  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
```

* Logs Alert Manager:
```
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=error ts=2018-08-02T08:14:05.9152299Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="cancelling notify retry for \"hipchat\" due to unrecoverable error: unexpected status code 400"
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=debug ts=2018-08-02T08:14:10.868296194Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=vl_backoffice_web_usage_ram[08f5cfe][active]
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=debug ts=2018-08-02T08:14:10.883257989Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=vl_banking_web_usage_ram[e3aff23][resolved]
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=debug ts=2018-08-02T08:14:10.883300432Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=vl_backoffice_vl_web_usage_ram[b900636][resolved]
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=debug ts=2018-08-02T08:14:15.879103775Z caller=dispatch.go:445 component=dispatcher aggrGroup={}:{} msg=Flushing alerts="[vl_backoffice_vl_web_usage_ram[b900636][resolved] vl_backoffice_web_usage_ram[08f5cfe][active] vl_banking_web_usage_ram[e3aff23][resolved]]"
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=debug ts=2018-08-02T08:14:15.91407999Z caller=notify.go:668 component=dispatcher msg="Notify attempt failed" attempt=1 integration=hipchat receiver=hipchat err="unexpected status code 400"
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=error ts=2018-08-02T08:14:15.914140576Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"hipchat\" due to unrecoverable error: unexpected status code 400"
vl-monitor_alertmanager.1.bj0kl7y4ngrr@s-vl-swr-docker01.fidor.intern    | level=error ts=2018-08-02T08:14:15.914158716Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="cancelling notify retry for \"hipchat\" due to unrecoverable error: unexpected status code 400"
```
