### ISSUE TITLE
alertmanager failed to start after setting http_proxy env or add proxy_url in config file

### ISSUE THREAD

**Issue by lazywhite** [prometheus/alertmanager#1537]
I'm trying to set global http proxy
but after I modify config.yml or set environment variables, pod failed to start

**Environment**

* System information:

Linux 3.10.0-862.el7.x86_64 x86_64

* Alertmanager version:
0.15.2

* Prometheus version: 
2.2.1

* Alertmanager configuration file:
```
    global:
      http_config:
        proxy_url: 'http://192.168.33.125:8888' 
    route:
      group_by: ['alertname', 'pod_name']
      group_wait: 10s
      group_interval: 5m
      receiver: Wechat
      repeat_interval: 3h

    receivers:
      - name: 'Wechat'
        wechat_configs:
          - corp_id: 'wd9478bbf2f6'
            to_party: 'AlertCmri'
            agent_id: '1000002'
            api_secret: '1fLWJp4fP28iWAbKmYTtm0yQ'

```

* Logs:
```
[root@master1 prometheus]# kubectl -n monitoring logs monitor-prometheus-alertmanager-5687f4d79b-zzff6 -c prometheus-alertmanager
level=info ts=2018-09-02T07:55:43.437251626Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.0, branch=HEAD, revision=462c969d85cf1a473587754d55e4a3c4a2abc63c)"
level=info ts=2018-09-02T07:55:43.43740602Z caller=main.go:175 build_context="(go=go1.10.3, user=root@bec9939eb862, date=20180622-11:58:41)"
level=info ts=2018-09-02T07:55:43.444940554Z caller=cluster.go:155 component=cluster msg="setting advertise address explicitly" addr=<nil> port=9094
level=error ts=2018-09-02T07:55:43.445778397Z caller=main.go:201 msg="Unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: Failed to parse advertise address \"<nil>\""

```
