### ISSUE TITLE
when failure recovery,i can not receive message

### ISSUE THREAD

**Issue by eason0420** [prometheus/alertmanager#1581]
the config file:

```yaml
receivers:
  - name: 'yunwei'
    wechat_configs:
    - send_resolved: true
      to_party: '@all'
      to_user: "@all"
      agent_id: '1000002'
      corp_id: 'wxxxxxxxxxb'
      api_secret: '9xxxxxxxxxxxxxxxxx0'
      message: "{{ .CommonLabels.alertname }} \n{{ .CommonLabels.instance }} \n{{ .CommonLabels.severity }} \n{{ .CommonAnnotations.description }}\n{{ .CommonAnnotations.value }}"
```

i can receive the alert, but when failure recovery,i can not receive message
