### ISSUE TITLE
Bugs in receiver info from the mail

### ISSUE THREAD

**Issue by xiyanxiyan10** [prometheus/alertmanager#1603]
I configure receiver as this 

```
- send_resolved: false
    to: 3318550879@qq.com
    from: meimei<3318550879@qq.com>
    hello: localhost
    smarthost: smtp.qq.com:25
    auth_username: 3318550879@qq.com
    auth_password: <secret>
    headers:
      From: meimei<3318550879@qq.com>
      Subject: '[梅红伟-test]'
      To: 3318550879@qq.com
    html: '{{ template "alert.html" . }}'
    require_tls: false
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://mce.api.matrixcloud.io:80/clusters/alerts/infos
```
So, alert info will send to the woobhook when send mail to the mails.

But I found the **$alert.EndsAt** in mails not the same with the time in webhook, why alert info **$alert.EndsAt** is  different which from the same policy and receiver group
