### ISSUE TITLE
Prometheus alertmanager **not** sending resolved alerts for restarted pods

### ISSUE THREAD

**Issue by raja-gola** [prometheus/alertmanager#1607]
Prometheus alertmanager **not** sending resolved alerts for restarted pods

Issue: Consider a pod p1 running in namespace n1. An alert is configured to send alert when pod memory reaches 95%. An alert is sent when the pod reaches 95%. But when the pod reaches 100% memory limit and restarts, a **resolved alert** is not sent.

====Prometheus======
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: cluster-services
  labels:
    prometheus: k8s
spec:
  retention: 24h
  replicas: 1
  version: v2.2.1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  resources:
    limits:
      cpu: 6
      memory: 16Gi
    requests:
      cpu: 4
      memory: 14Gi
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            volume: k8s-nfs
        resources:
          requests:
            storage: 1Ti
  alerting:
    alertmanagers:
    - namespace: cluster-services
      name: alertmanager-k8s
      port: web
  ruleSelector:
    matchLabels:
      role: prometheus-k8s-rulefiles
      prometheus: k8s
```

======Prometheus Rules=====
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-k8s-rules
  namespace: cluster-services
  labels:
    role: prometheus-k8s-rulefiles
    prometheus: k8s
data:
  k8s.rules.yaml: |+
    groups:
    - name: k8s-alert.rules
      rules:
      - alert: ClusterServicesPodHighMemUsage
        annotations:
          description: Cluster Services Pod {{$labels.namespace}}/{{$labels.pod_name}}
            has consumed {{$value}}% of memory in staging cluster
          summary: Cluster Services Pod memory usage is high
        expr: floor((sum(container_memory_usage_bytes{namespace="cluster-services"}) by
          (namespace, pod_name) / sum(container_spec_memory_limit_bytes) by (namespace,
          pod_name) ) * 100) < 100 > 95
        for: 30m
        labels:
          alerttype: cluster
          clustername: staging
          severity: high
```

=======Alertmanager======
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: k8s
  namespace: cluster-services
  labels:
    alertmanager: k8s
spec:
  replicas: 2
  version: v0.15.0
  logLevel: debug
  resources:
    limits:
      memory: 1Gi
      cpu: 1000m
    requests:
      memory: 500Mi
      cpu: 500m
```

=======AlertManager config yaml=====
```
alertmanager_config: !unsafe |+
  global:
    resolve_timeout: 5m
  route:
    group_by: [clustername, alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: 'default-ns-alerts'
    routes:
    - match_re:
        alerttype: cluster
      receiver: 'vc3-alerts'
  receivers:
  - name: 'default-ns-alerts'
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/<url>'
      channel: '#default-ns-alerts'
      username: 'DECC-alertmanager'
      title: '{{ template "slack.vmware.title" . }}'
      title_link: 'http://alertmanager-k8s.com/#/alerts'
      text: '{{ template "slack.vmware.text" . }}'
  - name: 'vc3-alerts'
    webhook_configs:
    - url: 'http://webhook.com:21323'
      send_resolved: true
  templates:
  - '*.tmpl'

slack_template: !unsafe |+
  {{ define "slack.vmware.title" }}
  {{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}
  {{ end }}

  {{ define "slack.vmware.text" }}
  {{ range .Alerts }}
  {{ .Annotations.description }}
  {{ end }}
  {{ end }}
```
