### ISSUE TITLE
Cycle: "Firing, Resolved"

### ISSUE THREAD

**Issue by Orsek123** [prometheus/alertmanager#1618]
**What did you do?**
Hello, I have problem with alertmanager cluster. I build cluster with 4 prometheus + (4 sidecar, 4 query), 4 alertmanager. I have two region (region1, region2). In every region there are two prometheus node - replica(A, B). All prometheus have as alerting targets all alertmanager nodes. All alertmanager nodes have have as parameters cluster.peer all alertmanager nodes. Alertmanager send alerts to pagerduty. In alertmanager and pagerduty is grouping disabled.

**What did you see instead? Under which circumstances?**
If I have up all alertmanager nodes so the alerting send every 3minutes resolve. After 1minute it send firing. Cycling again. If I have up only one alertmanager node per region so OK.

**What did you expect to see?**
I need running all nodes. If some prometheus send alert to alertmanager cluster so firing status, if prometheus not send alert so resolve status.

**Environment**

* System information:

	Linux 4.9.0-7-amd64 x86_64
        All running in docker container

* Alertmanager version:

	alertmanager, version 0.15.3

* Prometheus version:

	prometheus, version 2.4.2

* Alertmanager configuration file:
```
global:

templates: 
- '/etc/alertmanager/templates/*.tmpl'

route:
  receiver: 'pagerduty'
  group_by: ['alertname', 'instance', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance', 'job']

- name: 'pagerduty'
  pagerduty_configs:
  - send_resolved: true
    service_key: ....
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    severity: '{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower
      }}{{ else }}critical{{ end }}'
    class: '{{ .CommonLabels.class }}'
    component: '{{ .CommonLabels.component }}'
    group: '{{ if .CommonLabels.environment }}.{{ .CommonLabels.environment }}{{
      end }}{{ if .CommonLabels.region }}.{{ .CommonLabels.region }}{{ end }}{{ if
      .CommonLabels.service }}.{{ .CommonLabels.service }}{{ end }}'
```

* Prometheus configuration file:
Region: region1
Replica: A
```
# my global config
global:
  scrape_interval:     40s
  evaluation_interval: 1m
  external_labels:
    region: region1
    replica: A

# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - source_labels: [region]
      replacement: '' 
      target_label: region
    - source_labels: [replica]
      replacement: ''
      target_label: replica
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - bafana1.region1:9093
      - bafana2.region1:9093
      - bafana1.region2:9093
      - bafana2.region2:9093
```
Region: region1
Replica: B
```
# my global config
global:
  scrape_interval:     40s
  evaluation_interval: 1m
  external_labels:
    region: region1
    replica: B

# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - source_labels: [region]
      replacement: '' 
      target_label: region
    - source_labels: [replica]
      replacement: ''
      target_label: replica
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - bafana1.region1:9093
      - bafana2.region1:9093
      - bafana1.region2:9093
      - bafana2.region2:9093
```
Region: region2
Replica: A
```
# my global config
global:
  scrape_interval:     40s
  evaluation_interval: 1m
  external_labels:
    region: region2
    replica: A

# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - source_labels: [region]
      replacement: '' 
      target_label: region
    - source_labels: [replica]
      replacement: ''
      target_label: replica
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - bafana1.region1:9093
      - bafana2.region1:9093
      - bafana1.region2:9093
      - bafana2.region2:9093
```
Region: region2
Replica: B
```
# my global config
global:
  scrape_interval:     40s
  evaluation_interval: 1m
  external_labels:
    region: region2
    replica: B

# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - source_labels: [region]
      replacement: '' 
      target_label: region
    - source_labels: [replica]
      replacement: ''
      target_label: replica
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - bafana1.region1:9093
      - bafana2.region1:9093
      - bafana1.region2:9093
      - bafana2.region2:9093
```

* Logs:
```
@400000005be95c82236f098c level=debug ts=2018-11-12T10:56:56.594019841Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[456303a][active]
@400000005be95c8316b98b04 level=debug ts=2018-11-12T10:56:57.38076309Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:56:57 [DEBUG] memberlist: Initiating push/pull sync with: 10.52.0.175:9094\n"
@400000005be95ca01b020a24 level=debug ts=2018-11-12T10:57:26.452585627Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[456303a][active]
@400000005be95cba12c2ba0c level=debug ts=2018-11-12T10:57:52.31414958Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:57:52 [DEBUG] memberlist: Stream connection from=10.52.0.176:54258\n"
@400000005be95cbe2139a35c level=debug ts=2018-11-12T10:57:56.556144368Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[9e4ef6e][active]
@400000005be95cbf17266a1c level=debug ts=2018-11-12T10:57:57.387736935Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:57:57 [DEBUG] memberlist: Initiating push/pull sync with: 10.22.0.175:9094\n"
@400000005be95cdc1cf44cd4 level=debug ts=2018-11-12T10:58:26.485316502Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[9e4ef6e][active]
@400000005be95cdc1e06552c level=debug ts=2018-11-12T10:58:26.503348891Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[456303a][active]
@400000005be95cf12e704864 level=debug ts=2018-11-12T10:58:47.778565149Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:58:47 [DEBUG] memberlist: Stream connection from=10.22.0.175:52528\n"
@400000005be95cf612f7fadc level=debug ts=2018-11-12T10:58:52.317722525Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:58:52 [DEBUG] memberlist: Stream connection from=10.52.0.176:54626\n"
@400000005be95cfa1e55a9c4 level=debug ts=2018-11-12T10:58:56.508498654Z caller=impl.go:578 msg="Notifying PagerDuty" incident="{}:{alertname=\"LowDiskSpace\", instance=\"dock011.region1:9100\", job=\"node\"}" eventType=resolve
@400000005be95cfa1fb800b4 level=debug ts=2018-11-12T10:58:56.531041711Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[456303a][active]
@400000005be95cfa20be4554 level=debug ts=2018-11-12T10:58:56.548965886Z caller=impl.go:578 msg="Notifying PagerDuty" incident="{}:{alertname=\"LowDiskSpace\", instance=\"dock008.region1:9100\", job=\"node\"}" eventType=resolve
@400000005be95cfb175e1804 level=debug ts=2018-11-12T10:58:57.391571385Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:58:57 [DEBUG] memberlist: Initiating push/pull sync with: 10.52.0.175:9094\n"
@400000005be95d1822601a2c level=debug ts=2018-11-12T10:59:26.576195564Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[9e4ef6e][active]
@400000005be95d2d2ea88ea4 level=debug ts=2018-11-12T10:59:47.782276972Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:59:47 [DEBUG] memberlist: Stream connection from=10.22.0.175:52882\n"
@400000005be95d3616f1776c level=debug ts=2018-11-12T10:59:56.384307782Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[456303a][active]
@400000005be95d362212dcbc level=debug ts=2018-11-12T10:59:56.571066523Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[9e4ef6e][active]
@400000005be95d3717a90f6c level=debug ts=2018-11-12T10:59:57.396393706Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 10:59:57 [DEBUG] memberlist: Initiating push/pull sync with: 10.52.0.176:9094\n"
@400000005be95d5420bb72ac level=debug ts=2018-11-12T11:00:26.547945959Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[456303a][active]
@400000005be95d692ee7d5dc level=debug ts=2018-11-12T11:00:47.786296172Z caller=cluster.go:287 component=cluster memberlist="2018/11/12 11:00:47 [DEBUG] memberlist: Stream connection from=10.22.0.175:53236\n"
@400000005be95d721b247e74 level=debug ts=2018-11-12T11:00:56.454735658Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=LowDiskSpace[9e4ef6e][active]
@400000005be95d721ed925ec level=debug ts=2018-11-12T11:00:56.50966566Z caller=dispatch.go:445 component=dispatcher aggrGroup="{}:{alertname=\"LowDiskSpace\", instance=\"dock011.region1:9100\", job=\"node\"}" msg=Flushing alerts=[LowDiskSpace[9e4ef6e][active]]
@400000005be95d7220d08d04 level=debug ts=2018-11-12T11:00:56.550082378Z caller=dispatch.go:445 component=dispatcher aggrGroup="{}:{alertname=\"LowDiskSpace\", instance=\"dock008.region1:9100\", job=\"node\"}" msg=Flushing alerts=[LowDiskSpace[456303a][active]]
@400000005be95d7316db304c level=debug ts=2018-11-12T11:00:57.382766837Z caller=nflog.go:534 component=nflog msg="gossiping new entry" entry="entry:<group_key:\"{}:{alertname=\\\"LowDiskSpace\\\", instance=\\\"dock008.region1:9100\\\", job=\\\"node\\\"}\" receiver:<group_name:\"pagerduty\" integration:\"pagerduty\" > timestamp:<seconds:1542020457 nanos:375915602 > firing_alerts:14498338330822246194 > expires_at:<seconds:1542452457 nanos:375915602 > "
```
* Alert configuration:
```
  - alert: LowDiskSpace
    expr: instance:filesystem_free:percent <= 20
    for: 5m
    labels:
      severity: warning
    annotations:
      title: LowDiskSpace
      description: '{{ $labels.instance }} filesystem {{ $labels.device }} has less than 20% disk space remaining.'
      summary: Instance {{ $labels.instance }} filesystem usage warning
```
