### ISSUE TITLE
Always send to slack?

### ISSUE THREAD

**Issue by chngtrn** [prometheus/alertmanager#1619]
I have a requirement that all alerts post to a slack channel first, then if it matches child routes it'll send alerts again, whether it's email or pagerduty. If I use the ```continue``` parameter then slack wouldn't get alerted. If I don't use ```continue``` then I don't get child alerts, email or pagerduty. Below is my route. How can I solve this issue? I'm trying not to add slack config to all of my receivers. Too repetitive. Thanks.

```
route:
  receiver: entry
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

  routes:
  # Sending everything else to Slack first.
  - receiver: slack
    continue: true
    routes:
      # SRE system alerts.
      - match_re:
          alertname: Node.*
        receiver: sre-email
        continue: true
        routes:
        - match:
            severity: critical
          receiver: sre-pagerduty

receivers:
- name: entry

- name: slack
  slack_configs:
  - send_resolved: true

- name: sre-email
  email_configs:
  - send_resolved: true
    to: jdoe@example.com

- name: sre-pagerduty
  pagerduty_configs:
    send_resolved: true
    service_key: 123456789
```
