### ISSUE TITLE
How do you hide your alertmanager dashboard?

### ISSUE THREAD

**Issue by casertap** [prometheus/alertmanager#164]
So my docker-compose look like this:
````
promalertmgr:
    image: prom/alertmanager
    ports:
        - "9093:9093"
    expose:
        - "9093"
    command: "-config.file=/alertmanager.conf"
    volumes:
        - ./alertmanager.conf:/alertmanager.conf:ro
    env_file:
        - './.env'

prometheus:
    image: prom/prometheus
    links:
        - cadvisor
        - promalertmgr
        - wpprog
        - wptrad
        - mysql
    ports:
        - "127.0.0.1:9090:9090"
    expose:
        - "9090"
    command: -config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://${VIRTUAL_HOST_ALERT}:9093
    env_file:
        - './.env'
    volumes:
        - ./alert.rules:/etc/prometheus/alert.rules:ro
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
````
The main problem with this config is
````
promalertmgr:
    ports:
        - "9093:9093"
```
This mean I give access to the 9093 to the outside world.
But really what I want to do is just having my prometheus container communicate with my promalertmgr container via their private network.
The 
````
-alertmanager.url=http://${VIRTUAL_HOST_ALERT}:9093
````
because I have linked prometheus to promalertmgr could simply be: 
````
-alertmanager.url=promalertmgr:9093
```
This way I can remove the 9093:9093 port mapping. If I want to see my dashboard I first need to open an ssh bridge. This will be ideal.
