### ISSUE TITLE
alertmanager send duplicate alerts

### ISSUE THREAD

**Issue by arugaki** [prometheus/alertmanager#1642]
**What did you do?**

I use a webhook like examples/webhook/echo.go to receive alarm messages from Alertmanager,
I found that whenever a new alarm rule is triggered in Prometheus, prometheus sends a new alert message to the Alertmanager, the Alertmanager will send this alert message to the webhook with all previous unresolved alerts and resolved but not too late to delete alerts.

for example:

First, webhook receive a alert A from Alertmanager. A few minutes later, Alertmanager receive a alert B from Prometheus, but the alert A is unsolved at this time and not until the `repeat_interval`. At this time in webhook, i will receive two alerts(A and B)

Is this normal or just designed like this? Or my method of use is wrong ？

**What did you expect to see?**

I just want to get the second (alert B without A)

* System information:

	Darwin 16.7.0 x86_64

* Alertmanager version:

	0.15.2

* Prometheus version:

	2.4.0

* Alertmanager configuration file:
```
global:
  resolve_timeout: 15s 
route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'default'
  webhook_configs:
  - send_resolved: true
    url: http://127.0.0.1:5002/
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: ['localhost:9093']
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "first_rules.yml"
#  - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090','127.0.0.1:9100']
      labels:
        my:  label
```
