### ISSUE TITLE
Alertmanager cannot separate emails

### ISSUE THREAD

**Issue by huynhducbk95** [prometheus/alertmanager#1644]
Hi anyone,
I am facing with a issue about prometheus alerts. Please tell me if this is a bug of alertmanager version v0.15.2 or I missed somethings when update version. Thanks!

**What did you expect to see?**

My expect is that all alerts of node exporter will be grouped together in a single mail with header [alerting][node-exporter] and all of cadvisor will be grouped together in a single mail with header [alerting][cadvisor].

**What did you see instead?**

When I use alertmanager v0.15.2, both alerts (node exporter and cadvisor) was only grouped in a single mail with with header [alerting]. It's not as expected.

when I use alertmanager v0.14.0, It perform as my expected

**Environment**

* System information: Linux 3.10.0-862.el7.x86_64 x86_64

* Prometheus version: 2.4.2

* Alertmanager configuration file:
My `alert.rules` file:
```
groups:
- name: monitor_service_down
  rules:
  - alert: monitor_service_down
    expr: up{job=~"cadvisor_ip.*"} < 1
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "[cadvisor]"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

- name: node_service_down
  rules:
  - alert: node_service_down
    expr: up{job=~"node_exporter.*"} < 1
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "[node-exporter]"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
```
and `alertmanager.yml` file:
```
route:
  receiver: 'my_email'

receivers:
  - name: 'my_email'
    email_configs:
      - to: 'duclh'
        from: 'duclh'
        send_resolved: true
        smarthost: stmp_server
        auth_username: 'duclh'
        auth_identity: 'duclh'
        auth_password: 'mypass'
        require_tls: false
        text: "{{ .CommonAnnotations.description }}"
        headers:
          subject: "[alerting]{{ .CommonAnnotations.summary }}"
```
* Logs:
I found in debug logs of Alertmanager v0.14.0:

```
level=debug ts=2018-11-29T10:07:33.735888075Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=node_service_down[838af74][resolved]
level=debug ts=2018-11-29T10:07:33.735900346Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=node_service_down[7c793e6][active]
level=debug ts=2018-11-29T10:07:33.73591157Z caller=dispatch.go:188 component=dispatcher msg="Received alert" alert=node_service_down[3e6eb5a][active]
level=debug ts=2018-11-29T10:07:34.106715246Z caller=dispatch.go:429 component=dispatcher aggrGroup="{}:{alertname=\"monitor_service_down\"}" msg=Flushing alerts="[monitor_service_down[0080a72][active] monitor_service_down[3a756c4][active] monitor_service_down[a8cf5fc][active] monitor_service_down[4842efc][active] monitor_service_down[8421772][active] monitor_service_down[b37b74f][active]]"
```
and some changes in `aggrGroup` when use Alertnamanger v0.15.2 :
```
level=debug ts=2018-11-29T09:44:47.563991152Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[ee70c67][active]
level=debug ts=2018-11-29T09:44:47.564039759Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[3ea5cbf][active]
level=debug ts=2018-11-29T09:44:47.564096953Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[c0ac06c][active]
level=debug ts=2018-11-29T09:44:47.564149898Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[25c3cbf][active]
level=debug ts=2018-11-29T09:44:47.56421311Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[71b272e][active]
level=debug ts=2018-11-29T09:44:47.564261406Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[ce4dde3][active]
level=debug ts=2018-11-29T09:44:47.564329746Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[6bba521][active]
level=debug ts=2018-11-29T09:44:47.564391213Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=blackbox_oss_tradition[2fe50e3][active]
level=debug ts=2018-11-29T09:44:47.945032321Z caller=dispatch.go:445 component=dispatcher aggrGroup={}:{} msg=Flushing alerts="[blackbox_oss_tradition[34e4ad8][active] blackbox_oss_tradition[06f2548][active] blackbox_oss_tradition[0d31f0b][active] blackbox_oss_tradition[0861476][active] blackbox_oss_tradition[fbf34b7][active] blackbox_oss_tradition[868506a][active] blackbox_oss_tradition[86475a3][active] blackbox_oss_tradition[5944417][active] blackbox_oss_tradition[a34a98b][active] blackbox_oss_tradition[2331a7b][active] blackbox_oss_tradition[a9b109b][active] blackbox_oss_tradition[16b09af][active] blackbox_oss_tradition[ec4356e][active]]"
```

**Comment by simonpasquier** [comment]
As you didn't specify the `group_by` parameter in the main route, AlertManager groups all alerts in the same mail notification. You can do this instead:

```yaml
route:
  receiver: 'my_email'
  group_by: [alertname]
```

See https://prometheus.io/docs/alerting/configuration/#%3Croute%3E for more details.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
