### ISSUE TITLE
Resolution notifications dependency on group_interval

### ISSUE THREAD

**Issue by kapodes** [prometheus/alertmanager#1660]
**What did you do?**
Sent an alert and waited for it to hit `resolve_timeout` and be resolved

**What did you expect to see?**
Notification about alert being resolved right away after it was resolved according to Alertmanager

**What did you see instead? Under which circumstances?**
Nothing until `group_interval` timer hit.

```
alertmanager, version 0.15.3 (branch: HEAD, revision: d4a7697cc90f8bce62efe7c44b63b542578ec0a1)
  build user:       root@4ecc17c53d26
  build date:       20181109-15:40:48
  go version:       go1.11.2
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m
route:
  group_wait: 5s
  group_interval: 5m
  receiver: slack-notifications

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#alerts"
        send_resolved: true
        ..........
```

* Logs:
```
level=debug ts=2018-12-12T15:36:34.910107275Z caller=dispatch.go:445 component=dispatcher aggrGroup={}:{} msg=Flushing alerts=[TestAlert[c508c62][active]]
level=debug ts=2018-12-12T15:41:34.910626655Z caller=dispatch.go:445 component=dispatcher aggrGroup={}:{} msg=Flushing alerts=[TestAlert[c508c62][resolved]]
```

If I decrease `group_interval` to something like `5s` I will see notification almost instantly after alert is resolved.

I think `send_resolved` logic shouldn't be dependent on `group_interval`. 
It's logical not to send new alert notifications from same group right away but resolution messages are not new alerts...
