### ISSUE TITLE
Alertmanager subject line with unwanted characters in NeoMutt

### ISSUE THREAD

**Issue by geekodour** [prometheus/alertmanager#1676]
**What did you do?**
I am trying to work with plaintext emails, I have a custom template `email.default.text` which formats the plaintext mail but the **subject line** when viewed from the NeoMutt email client produces unwanted `?` characters.

I override the default `__subject` template with the following simple template. the issue persists as shown below.
```go
{{ define "__subject" }}
  something happened
{{ end }}
```
The subject lines with HTML email in Gmail show properly.
![Alerts in Gmail](https://i.imgur.com/lSyW1K1.png)

The issue is when I use NeoMutt. I never faced this issue with any other mails in NeoMutt so I am not sure if this an Altermanager issue or of NeoMutt.

**What did you expect to see?**
No question marks and specified spaces.
```
   1   + Dec 20 alertmanager@pr ( 12K) something happened                                                                                                                                
   2   + Dec 20 alertmanager@pr (127K) [FIRING:45] HTTP 200 Check webserviceup_probe (http_get_200_check medium )                                                             
   3   + Dec 20 alertmanager@pr ( 11K) [FIRING:1] TestAlert1                                                                                                                        
   4   + Dec 20 alertmanager@pr (124K) [FIRING:44] HTTP 200 Check webserviceup_probe (http_get_200_check medium )    
```

**What did you see instead? Under which circumstances?**
Question marks and extra spaces
```
   1   + Dec 20 alertmanager@pr ( 12K) ?  something happened?                                                                                                                                  
   2   + Dec 20 alertmanager@pr (127K) ?  [FIRING:45]?  HTTP 200 Check webserviceup_probe?    ?    (http_get_200_check medium )?  ?                                                             
   3   + Dec 20 alertmanager@pr ( 11K) ?  [FIRING:1]?  TestAlert1?    ?                                                                                                                         
   4   + Dec 20 alertmanager@pr (124K) ?  [FIRING:44]?  HTTP 200 Check webserviceup_probe?    ?    (http_get_200_check medium )?  ?    
```

**Environment**

* System information:

`Linux 4.4.0-140-generic x86_64`

* Alertmanager version:
```
alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
```
* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@myorg.org'
  smtp_require_tls: false

templates:
- '/etc/alertmanager/templates/*.tmpl'

route:
  repeat_interval: 3h
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 1m
  receiver: team-mail

receivers:
- name: team-mail
  email_configs:
  - to: 'xxxx@gmail.com'
    html: '{{ template "email.default.html" . }}'
    text: '{{ template "email.default.text" . }}'
    send_resolved: false
```
