### ISSUE TITLE
Alert stuck in firing->resolved->firing from three instances cluster

### ISSUE THREAD

**Issue by CrazyNash** [prometheus/alertmanager#1684]
**What did you do?**

1. setup three Prometheus instances
2. setup three Alertmanager instances
3. set resolved_timeout with 30s

**What did you expect to see?**

alertmanager works fine

**What did you see instead? Under which circumstances?**

two instances alertmanager fires same alert one after another, then fixed one after another, then fire again...

check prometheus, the alert never stop after it's fired, so alertmanager should fire it once, and repeat it again 3h later.

**Environment**

 * System information:

	docker

* Alertmanager version:

	v0.15.0-rc.3

* Prometheus version:

	v2.2.1

* Alertmanager configuration file:
```
global:
  resolve_timeout: 30s

route:
  receiver: 'manage_custom'
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'manage_custom'
    webhook_configs:
      - send_resolved: true
        url: "https://placeholder"

```

* Prometheus configuration file:
```
The three instances share same config except for different dc label.

global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
  external_labels:
    dc: admin2
alerting:
  alert_relabel_configs:
  - source_labels: [dc]
    separator: ;
    regex: (.+)\d+
    target_label: dc
    replacement: $1
    action: replace
  alertmanagers:
  - static_configs:
    - targets:
      - 172.XXXXX
      - 172.XXXXX
      - 172.XXXXX
    scheme: http
    timeout: 10s
rule_files:
- /etc/prometheus/alert/*.rules
scrape_configs:
- job_name: nodes
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.XXXXXX
- job_name: cadvisior
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.XXXX

- job_name: process
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.XXXX
- job_name: pushgateway
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.XXXX
- job_name: container
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.XXXX
- job_name: proxysql-exporter
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.XXXXX
- job_name: alertmanager
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.XXXX
    - 172.XXXX
    - 172.XXXX
remote_write:
- url: http://172.18.176.145:9201/write
  remote_timeout: 30s
  queue_config:
    capacity: 100000
    max_shards: 1000
    max_samples_per_send: 100
    batch_send_deadline: 5s
    max_retries: 10
    min_backoff: 30ms
    max_backoff: 100ms
remote_read:
- url: http://172.18.176.145:9201/read
  remote_timeout: 1m
```

* Logs:
```
can't see any error except for notification log

```

I tried a lot of tests, it works fine from either change below:
1. setup with two alertmanger instances
2. change resolved_timeout to 1m or larger

Don't know why the resolved_timeout matters here.
