### ISSUE TITLE
"repeat_interval=1h",but i still going to get a repeat alarm in a short time

### ISSUE THREAD

**Issue by dengceltics** [prometheus/alertmanager#1685]
my alertmanager.yml 
```
global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://*****:3000'
    send_resolved: false
```

The repeat alarm is:

```
{ '{"receiver":"web\\.hook","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"TooMuchGoroutines","app":"prometheus","component":"core","instance":"10.233.118.160:9090","job":"kubernetes-endpoints","kubernetes_name":"prometheus","kubernetes_namespace":"monitoring","severity":"warning"},"annotations":{"description":"testing","summary":"too much goroutines of job prometheus."},"startsAt":"2018-12-27T06:53:30.090023826Z","endsAt":"2018-12-28T01:30:30.090023826Z","generatorURL":"http://prometheus-core-6b5dc8dd4d-z4dvl:9090/graph?g0.expr': 'go_goroutines > 100\\u0026g0.tab=1"}],"groupLabels":{"alertname":"TooMuchGoroutines"},"commonLabels":{"alertname":"TooMuchGoroutines","app":"prometheus","component":"core","instance":"10.233.118.160:9090","job":"kubernetes-endpoints","kubernetes_name":"prometheus","kubernetes_namespace":"monitoring","severity":"warning"},"commonAnnotations":{"description":"testing","summary":"too much goroutines of job prometheus."},"externalURL":"http://alertmanager-56797bdb65-x9sj5:9093","version":"4","groupKey":"{}:{alertname=\\"TooMuchGoroutines\\"}"}\n' }
{ '{"receiver":"web\\.hook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"TooMuchGoroutines","app":"prometheus","component":"core","instance":"10.233.118.160:9090","job":"kubernetes-endpoints","kubernetes_name":"prometheus","kubernetes_namespace":"monitoring","severity":"warning"},"annotations":{"description":"testing","summary":"too much goroutines of job prometheus."},"startsAt":"2018-12-27T06:53:30.090023826Z","endsAt":"2018-12-28T01:36:30.090023826Z","generatorURL":"http://prometheus-core-6b5dc8dd4d-z4dvl:9090/graph?g0.expr': 'go_goroutines > 100\\u0026g0.tab=1"}],"groupLabels":{"alertname":"TooMuchGoroutines"},"commonLabels":{"alertname":"TooMuchGoroutines","app":"prometheus","component":"core","instance":"10.233.118.160:9090","job":"kubernetes-endpoints","kubernetes_name":"prometheus","kubernetes_namespace":"monitoring","severity":"warning"},"commonAnnotations":{"description":"testing","summary":"too much goroutines of job prometheus."},"externalURL":"http://alertmanager-56797bdb65-x9sj5:9093","version":"4","groupKey":"{}:{alertname=\\"TooMuchGoroutines\\"}"}\n' }
{ '{"receiver":"web\\.hook","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"TooMuchGoroutines","app":"prometheus","component":"core","instance":"10.233.118.160:9090","job":"kubernetes-endpoints","kubernetes_name":"prometheus","kubernetes_namespace":"monitoring","severity":"warning"},"annotations":{"description":"testing","summary":"too much goroutines of job prometheus."},"startsAt":"2018-12-27T06:53:30.090023826Z","endsAt":"2018-12-28T01:36:30.090023826Z","generatorURL":"http://prometheus-core-6b5dc8dd4d-z4dvl:9090/graph?g0.expr': 'go_goroutines > 100\\u0026g0.tab=1"}],"groupLabels":{"alertname":"TooMuchGoroutines"},"commonLabels":{"alertname":"TooMuchGoroutines","app":"prometheus","component":"core","instance":"10.233.118.160:9090","job":"kubernetes-endpoints","kubernetes_name":"prometheus","kubernetes_namespace":"monitoring","severity":"warning"},"commonAnnotations":{"description":"testing","summary":"too much goroutines of job prometheus."},"externalURL":"http://alertmanager-56797bdb65-x9sj5:9093","version":"4","groupKey":"{}:{alertname=\\"TooMuchGoroutines\\"}"}\n' }
```

The alarm always turn firing to resolved ,and turn resolved to firing.But the metrics hasn't changed.

**Comment by simonpasquier** [comment]
Please provide Prometheus and AlertManager versions? What is the alerting rule definition?

**Comment by aixeshunter** [comment]
The alerts will be sent repeatedly when your `webhook` not return 200.

**Comment by beijiaxu** [comment]
same problem, how to solve?
![screenshot-3](https://user-images.githubusercontent.com/13776775/56726879-31c64e80-6782-11e9-846a-54a415cdd36c.png)

**Comment by aixeshunter** [comment]
> same problem, how to solve?
> ![screenshot-3](https://user-images.githubusercontent.com/13776775/56726879-31c64e80-6782-11e9-846a-54a415cdd36c.png)

what is your version?

**Comment by beijiaxu** [comment]
> > same problem, how to solve?
> > ![screenshot-3](https://user-images.githubusercontent.com/13776775/56726879-31c64e80-6782-11e9-846a-54a415cdd36c.png)
> 
> what is your version?

it was AlertManger: 0.15.2, 
           Prometheus: 2.3.2
But current environment also has same problem,
          AlertManger: 0.16.1, 
          Prometheus: 2.6.0

**Comment by aixeshunter** [comment]
> > > same problem, how to solve?
> > > ![screenshot-3](https://user-images.githubusercontent.com/13776775/56726879-31c64e80-6782-11e9-846a-54a415cdd36c.png)
> > 
> > 
> > what is your version?
> 
> it was AlertManger: 0.15.2,
> Prometheus: 2.3.2
> But current environment also has same problem,
> AlertManger: 0.16.1,
> Prometheus: 2.6.0

Please show me your `alertmanager.yaml` :)

**Comment by beijiaxu** [comment]
@aixeshunter 
this is alertmanager.yml
```
global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - alertname
  - job
  source_match:
    severity: critical
  target_match:
    severity: warning
receivers:
- name: smartcmp-default-webhook
  webhook_configs:
  - url: http://hpuliyang.natapp1.cc/alarm-activities/trigger   
route:
  continue: false
  group_by:
  - alertname
  - cluster
  - service
  group_interval: 1s 
  group_wait: 1s 
  receiver: smartcmp-default-webhook
  repeat_interval: 4h
  routes: []
templates:
- template/*.tmpl
```
I changed group_wait & group_interval to 15s & 1m, but it didn't work...
