### ISSUE TITLE
doesn't work custom email template

### ISSUE THREAD

**Issue by zakabluk** [prometheus/alertmanager#1705]
I am using alertmanager v0.15.3 by docker. I tried use custom template for email. I attempted a lot of variants, but I have had always one result:
`  due to unrecoverable error: executing email html template: html/template::1:12: no such template \"email.cloud.html\""`

My last attempted was as:
alertmanager.yml
```
....
templates:
- '/alertmanager/cloud.tpml'
....
- name: 'smtp'
  email_configs:
   
  - to: my@email.dom
    require_tls: true
    send_resolved: true
    html: '{{ template "email.cloud.html" . }}'
```
text for /alertmanager/cloud.tpml I took from 
https://github.com/prometheus/alertmanager/blob/master/template/default.tmpl
from row 85 to 211.
Only changed in row 86
from {{ define "email.default.html" }} to {{ define "email.cloud.html" }}

but, after restart alertmannager container I have had same error as I wrote before:

`no such template \"email.cloud.html\`
 
Why?

**Comment by stuartnelson3** [comment]
This is a support question. As stated in the issues template, this should be sent to prometheus-users@googlegroups.com where the community can benefit, and a wider audience would be available to support you.

**Comment by bcdslg** [comment]
I encountered the same problem, how did you solve it in the end?

**Comment by zakabluk** [comment]
> I encountered the same problem, how did you solve it in the end?

Hi! alertmanager.yml
```
- name: 'smtp'
  email_configs:
          #- to: a.zakabluk@hqsoftwarelab.com        
  - to: 'a.zakabluk@hqsoftwarelab.com, n.hancharov@hqsoftwarelab.com, a.kuzko@hqsoftwarelab.com'
    require_tls: true
    send_resolved: true
    html: '{{ template "email.cloud.html" . }}'
```
In the same folder exist email.cloud.tmpl .
which contain : 
https://gist.github.com/zakabluk/4754c413207d134fefb40976f6f256aa

I remember that I had issue with template content. It was a long time ago.
