### ISSUE TITLE
Unable to send email notification without SMTP authentication

### ISSUE THREAD

**Issue by ben-ntap** [prometheus/alertmanager#1721]
Alertmanager won't send an email notification if no SMTP authentication options are configured. These messages appear repeatedly in the log file:

```
level=error ts=2019-01-23T15:49:04.898510015Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="missing password for PLAIN auth mechanism; missing password for LOGIN auth mechanism"
level=error ts=2019-01-23T15:49:04.898681067Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="missing password for PLAIN auth mechanism; missing password for LOGIN auth mechanism"
```

Config:

```yaml
global:
  smtp_from: <my_email>
route:
  receiver: root-route-receiver
  group_by:
  - alertname
  group_wait: 2m
  group_interval: 1m
  repeat_interval: 24h
receivers:
- name: root-route-receiver
  email_configs:
  - to: <my_email>
    smarthost: <my_smtp_host>:25
    require_tls: false
```

Noticed this issue after updating to v0.16.0. My same configuration worked on 0.15.1.
