### ISSUE TITLE
No metrics for failed notifications due to a non-existent receiver

### ISSUE THREAD

**Issue by jutley** [prometheus/alertmanager#1759]
**What did you do?**
We refactored our receivers and routes, and accidentally misconfigured some routes to point to a non-existent receiver. We had alerts trigger that used this route, and went to the non-existent receiver.

**What did you expect to see?**
I thought that the `alertmanager_notifications_failed_total` metric would increase, which we have a separate monitoring system checking. If this didn't increase, then I would expect that there was a separate counter metric that would increase.

**What did you see instead? Under which circumstances?**
The specified metric did NOT increase, and there were no other metrics that reported the issue. We did see many log messages that looked like this:
```
level=error ts=2019-02-13T03:09:24.472247912Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
```

We were not checking the logs because we did not realize that anything was wrong. 

**Environment**

* System information:

```
/etc/alertmanager $ uname -srm
Linux 4.14.96-coreos x86_64
```

* Alertmanager version:

```
/etc/alertmanager $ alertmanager --version
alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
```

* Prometheus version:

Not relevant. 

* Alertmanager configuration file:

It's large, so I'll skip posting all of it unless specifically asked. Here is the snippet of the routing that was executed. The receiver `pagerduty-coretech` was non-existent (we had a typo).
```
  - match_re:
      alert_owner: ^(?:.+)$
      alert_target: ^(?:^$)$
    routes:
    - match:
        alert_owner: coretech
      routes:
      - receiver: slack-coretech-automation
        match:
          severity: warning
      - receiver: slack-coretech-alerts
        match:
          severity: critical
        continue: true
      - receiver: pagerduty-coretech
        match:
          severity: critical
```

* Prometheus configuration file:

Not relevant.

* Logs:
```
...
level=error ts=2019-02-13T02:22:15.263925808Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-13T02:24:24.463157291Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-13T02:27:15.266087294Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-13T02:29:24.471469919Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-13T02:32:15.266334191Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-13T02:34:24.470538053Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-13T02:37:15.266720423Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-13T02:39:24.470741861Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
...
```

**Comment by brian-brazil** [comment]
This should have been caught at config reload.

**Comment by jutley** [comment]
Here are the logs of the alertmanager container and the config-reload container at the time of reload:
```
2019/02/04 20:44:20 config map updated
2019/02/04 20:44:21 successfully triggered reload
level=info ts=2019-02-04T20:44:20.866667798Z caller=main.go:322 msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2019-02-04T20:44:21.073089037Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-04T20:49:21.073262712Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
level=error ts=2019-02-04T20:54:21.073484341Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="stage for receiver missing"
```

Note that we have an alert that's been firing for a long time, which is silenced. I believe this alert is why we see the "stage for receiver missing" error immediately after reload. 

When I look at the Prometheus metrics, they don't show a change in the `alertmanager_config_last_reload_success_timestamp_seconds`. This is really strange to me, because it clearly shows up in the logs, but not the metrics.

**Comment by jutley** [comment]
In a test alertmanager cluster running `v0.16.1` with active alerts, I updated the configuration to point to completely bogus receivers (as in, those receivers are not defined anywhere), and where the routing and receivers are otherwise completely valid.

I'm seeing that each alertmanager member successfully reloads its configuration, but then starts logging the error message I've posted previously. 

If this is supposed to be caught at config reload, this does not appear to be the behavior.

**Comment by simonpasquier** [comment]
@jutley could you try with the current `master` branch? I can't reproduce your issue there and the configuration management has been refactored a bit in https://github.com/prometheus/alertmanager/pull/1744.

**Comment by jutley** [comment]
Okay, I successfully reproduced this on master branch, and I understand why you probably couldn't. This bug only appears in at least two layers of routing. Here is what I did:

Run alertmanager:master:
```
docker run -p 9093:9093 --name alertmanager prom/alertmanager:master
```

Update the configuration with a sub-route pointing to a fake receiver:
```
➜  cat << EOF | docker exec -i alertmanager sh -c 'cat > /etc/alertmanager/alertmanager.yml'
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      foo: bar
    receiver: fake
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
EOF

➜  curl -X POST localhost:9093/-/reload
failed to reload config: undefined receiver "fake" used in route
```

As intended, this fails, as the `fake` receiver does not exist.

Now, repeat this, with a sub-sub-route:
```
➜  cat << EOF | docker exec -i alertmanager sh -c 'cat > /etc/alertmanager/alertmanager.yml'
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      foo: bar
    routes:
    - match:
        foo: bar
      receiver: fake
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
EOF

➜  curl -X POST localhost:9093/-/reload
```

This succeeds, as we see in the logs:
```
level=info ts=2019-03-01T23:16:49.0091745Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
level=info ts=2019-03-01T23:16:49.0095161Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/alertmanager.yml
```
