### ISSUE TITLE
slack receiver send_resolved unexpected results

### ISSUE THREAD

**Issue by tmegow** [prometheus/alertmanager#1761]
**What did you do?**
Created a new route/receiver matching `slack-no-resolves` severity label
```
  - receiver: slack-no-resolves
    match:
      severity: slack-no-resolves
    continue: true
```
    - name: slack-no-resolves
      slack_configs:
      - send_resolved: false
        http_config: {}
        api_url: <secret>
        channel: alerts
        username: alertmanager
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: 'Alert: {{ .CommonAnnotations.summary -}}'
        title_link: <>
        pretext: '{{ template "slack.default.pretext" . }}'
        text: '{{ template "slack.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: https://avatars.slack-edge.com/2017-04-22/172492516832_96357bf9662f2abf55ee_72.jpg

**What did you expect to see?**
No resolve notifications for alerts with `slack-no-resolves` severity label

**What did you see instead? Under which circumstances?**
Resolve notifications always received in Slack for alerts with `slack-no-resolves` severity label

**Environment**
```
Docker/k8s
```

* System information:
```
Linux 4.4.86+ x86_64
```

* Alertmanager version:

```
Version Information
Branch:
HEAD
BuildDate:
20181109-15:40:48
BuildUser:
root@4ecc17c53d26
GoVersion:
go1.11.2
Revision:
d4a7697cc90f8bce62efe7c44b63b542578ec0a1
Version:
0.15.3
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_from: Alertmanager <>
  smtp_hello: localhost
  smtp_smarthost: <>
  smtp_auth_username: <>
  smtp_auth_password: <secret>
  smtp_require_tls: true
  slack_api_url: <secret>
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: slack
  group_by:
  - alertname
  routes:
  - receiver: slack
    match:
      severity: slack|email
    continue: true
  - receiver: slack-no-resolves
    match:
      severity: slack-no-resolves
    continue: true
  - receiver: email
    match_re:
      severity: ^(?:email)$
    continue: true
    repeat_interval: 1h
  group_wait: 10s
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - cluster
  - service
receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    http_config: {}
    api_url: <secret>
    channel: alerts
    username: alertmanager
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: 'Alert: {{ .CommonAnnotations.summary -}}'
    title_link: {{ .Receiver }}
    pretext: '{{ template "slack.default.pretext" . }}'
    text: '{{ template "slack.text" . }}'
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: https://avatars.slack-edge.com/2017-04-22/172492516832_96357bf9662f2abf55ee_72.jpg
- name: slack-no-resolves
  slack_configs:
  - send_resolved: false
    http_config: {}
    api_url: <secret>
    channel: alerts
    username: alertmanager
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: 'Alert: {{ .CommonAnnotations.summary -}}'
    title_link: {{ .Receiver }}
    pretext: '{{ template "slack.default.pretext" . }}'
    text: '{{ template "slack.text" . }}'
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: https://avatars.slack-edge.com/2017-04-22/172492516832_96357bf9662f2abf55ee_72.jpg
- name: email
  email_configs:
  - send_resolved: false
    to: <>
    from: Alertmanager <>
    hello: localhost
    smarthost: <>
    auth_username: <>
    auth_password: <secret>
    headers:
      From: Alertmanager <>
      Subject: '{{- if .CommonLabels.test }} TEST{{ end }} Alert: {{ .CommonAnnotations.summary
        }}'
      To: <>
    html: '{{ template "email.text" . }}'
    require_tls: true
templates:
- /etc/alertmanager-templates/*.tmpl
```
