### ISSUE TITLE
Are groups intended to nest?

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/alertmanager#177]
With the `dev` branch syntax you can something like this for routing:
```yaml
routes:
  - group_by: [ 'alertname', 'instance' ]
    routes:
    - match_re:
      - severity: ^(minor|major|critical)$
      group_by: ['severity']
```
This parses as completely legal syntax, but has weird effects on grouping - I wind up with one big 'severity' group for anything matching in that tree, rather then more what I'd expect which is a group by `alertname` and `instance`, containing a subgroup of `severity` (with regards to the JSON output of `/api/v1/alerts/groups` and the web UI).

If nested groups aren't supported, I feel like that syntax should probably be made erroneus since it is mostly confusing and doesn't seem to contribute anything to the data presentation (i.e. any parsing code I attach to that endpoint could also just read the labels on all the alerts under that group).
