### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by Izmenoff** [prometheus/alertmanager#1772]
When I get alert with severity="major" all works and sends email , but if severity="critical" email doesn't send. However I can see alert in Alertmanager in both cases (major and critical).

**alertmanager config:**
```
- match_re:
       instance: "srv-mncacti"
           receiver: OSS
receivers:
- name: 'OSS'
  email_configs:
  - to: 'alert_OSS@mail.com.by'
```

**prometheus config:**
```
  - job_name: 'cacti'
    scrape_interval: "15s"
    static_configs:
    - targets: ['srv-mncacti']
      labels:
        group: 'test'
```

**test.yml**
```
groups:
- name: test
  rules:
  - alert: Cacti URL check
    expr: endpoint_check{group="test"} != 1
    for: 15s
    labels:
      severity: "critical"
    annotations:
      description: " {{ $labels.url }} is not reachable"
```
