### ISSUE TITLE
Alertmanager not using Pagerduty Event V2 API

### ISSUE THREAD

**Issue by Draczech** [prometheus/alertmanager#1773]
**What did you do?**
I send alerts from alertmanager to pagerduty and I'd like to use Events API v2. I would expect better support for Pagerduty Events API v2. Though it is supported for a while since #1054 I am still experiencing some trouble using it right now. Though there is following in alertmanager config `routing_key: <secret>, url: https://events.pagerduty.com/v2/enqueue`, I still see my alerts as Events API v1 messages in PD.

**Proposition**
Also I would expect some better options in [alertmanager configuration](https://prometheus.io/docs/alerting/configuration/#pagerduty_config) matching the [Events API v2 structure](https://v2.developer.pagerduty.com/docs/events-api-v2). Right now the example uses Event API v1 and internally it should just pass given fields to an event with API v2 structure. It would be much easier to have access to the fields directly so they could be accessed in alertmanager config directly.

**What did you expect to see?**
Event API v2 message in Pagerduty.
**What did you see instead? Under which circumstances?**
Event API v1 message in Pagerduty.
**Environment**

* System information:
`Linux 4.9.0-8-amd64 x86_64`
* Alertmanager version:
`Version: 0.16.1, BuildDate: 20190131-18:04:53, non-git`
* Prometheus version:
`Version: 2.6.1, BuildDate: 20190121-13:02:26, non-git`
* Alertmanager configuration file:
In configuration file:
```
- name: 'devops-pagerduty'
  pagerduty_configs:
  - routing_key: {{ <key from pillar> }}
    description: '{{if .CommonAnnotations.summary }}{{ .CommonAnnotations.summary }}{{ else }}{{ .GroupLabels.alertname }}{{ if .CommonLabels.instance }} {{ .CommonLabels.instance }}{{ end }}{{ end }}'
    severity: '{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower }}{{ else }}critical{{ end }}'
```
Applied:
```
- name: srch-devops-pagerduty
  pagerduty_configs:
  - send_resolved: true
    http_config:
      proxy_url: http://<proxy>
    routing_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{if .CommonAnnotations.summary }}{{ .CommonAnnotations.summary
      }}{{ else }}{{ .GroupLabels.alertname }}{{ if .CommonLabels.instance }} {{ .CommonLabels.instance
      }}{{ end }}{{ end }}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    severity: '{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower
      }}{{ else }}critical{{ end }}'
```
**Pagerduty**
If I check *Incidents* in Pagerduty and go to view message option following structure should be displayed there.

Expected event:
```
{
  "description": "<job>@<instance> stamp too old ( 48.01949361112383 h > 48)",
  "event_type": "trigger",
  "incident_key": "<incident_key>",
  "service_key": "<service_key>",
  "details": {
    "alertname": "job-not-finished-in-time",
    "cluster": "<cluster>",
    "exported_job": "<job_name>",
    "instance_short": "<instance>fridexlauncher.ko",
    "job": "<job>",
    "max_hours": "48",
    "severity": "critical",
    "team": "devops",
    "description": "MR job <job>@<instance> done stamp too old",
    "summary": "<job>@<instance> stamp too old ( 48.01949361112383 h > 48)"
  }
}
```
Actual event:
```
{
  "client": "AlertManager",
  "client_url": "http://server:9093/#/alerts?receiver=devops-pagerduty",
  "description": "<job>@<instance> stamp too old ( 48.01949361112383 h > 48)",
  "event_type": "trigger",
  "incident_key": "<incident_key>",
  "service_key": "<service_key>",
  "details": {
    "firing": "Labels:\n - alertname = job-not-finished-in-time\n - cluster = <cluster>\n - exported_job = <job_name>\n - instance_short = <instance>\n - job = <job>\n - max_hours = 48\n - severity = critical\n - team = devops\nAnnotations:\n - description = MR job <job>@<instance> done stamp too old\n - summary = <job>@<instance> stamp too old ( 48.01949361112383 h > 48)\nSource: <source>\n",
    "num_firing": "1",
    "num_resolved": "0",
    "resolved": ""
  }
}
```

I admit this specific problem can be subject of wrong configuration or so, I already started a [discussion in Prometheus users for it](https://groups.google.com/forum/#!topic/prometheus-users/eCBZgMuBYMg).
