### ISSUE TITLE
anonymous SMTP is Broken

### ISSUE THREAD

**Issue by athoune** [prometheus/alertmanager#1797]
**What did you do?**
Sending an email to mailhog, for a docker-compose demo.

**What did you expect to see?**
An email in Mailhog UI.

**What did you see instead? Under which circumstances?**
```
level=debug ts=2019-03-14T14:40:09.7477629Z caller=notify.go:670 component=dispatcher msg="Notify attempt failed" attempt=7 integration=email receiver=team-demo-mails err="missing password for PLAIN auth mechanism"
```

If I try to put a password and a user (mailhog doesn't care about auth), golang SMTP doesn't accept no TLS connection.

If I explicit set username to "", same error.

* Alertmanager version:

```
alertmanager, version 0.16.1 (branch: HEAD, revision: 571caec278be1f0dbadfdf5effd0bbea16562cfc)
  build user:       root@3000aa3a06c5
  build date:       20190131-15:05:40
  go version:       go1.11.5
```
Same behavior with HEAD and 0.16.1 docker image.

* Alertmanager configuration file:
```yaml
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: "mail:1025"
  smtp_from: alertmanager@example.com
  smtp_require_tls: false
```
