### ISSUE TITLE
receivers: email_configs: Not using additional variables with multiple to: destinations

### ISSUE THREAD

**Issue by xkilian** [prometheus/alertmanager#1801]
**What did you do?**
Configured to send alerts to tow receivers with an html template.

**What did you expect to see?**
The first receiver has all the correct information and sends the notification with the html template and all global options.
The second receiver does not use the template and does not have the global options as notifications are resent every minute few minutes.
When using the default html template I do not have this strange behaviour.

**What did you see instead? Under which circumstances?**
Use the html template and global notification options. All receivers should get notifications with the html template and appropriate notifications and repeat_intervals ,etc.

**Environment**
Ubuntu Linux vm

* System information:

Linux 3.2.0-69-virtual x86_64

* Alertmanager version:

0.15.3

* Prometheus version:

* Alertmanager configuration file:
```
templates:
  - /opt/prometheus/etc/alertmanager/templates/email.tmpl

receivers:
  -name: 'destination-one'
    email_configs:
      - to: 'email.domain.com'
        html: '{{ template "email.tmpl" . }}'
        send_resolved: true
  -name: 'destination-two'
    email_configs:
      - to: 'email2.domain.com'
        html: '{{ template "email.tmpl" . }}'
        send_resolved: true

Doing this also fails to load parameters correctly for the second destination: 

receivers:
  -name: 'destination-one'
    email_configs:
      - to: 'email.domain.com'
        html: '{{ template "email.tmpl" . }}'
        send_resolved: true
      - to: 'email2.domain.com'
        html: '{{ template "email.tmpl" . }}'
        send_resolved: true

THIS WORKS, strangely enough?!?

receivers:
  -name: 'destination-one'
    email_configs:
      - html: '{{ template "email.tmpl" . }}'
        to: 'email.domain.com'
        send_resolved: true
  -name: 'destination-two'
    email_configs:
      - html: '{{ template "email.tmpl" . }}'
        to: 'email2.domain.com'
        send_resolved: true
```
