### ISSUE TITLE
Alert Manager  SMTP Config - field tls_config not found in type config.plain 

### ISSUE THREAD

**Issue by dgteixeira** [prometheus/alertmanager#1805]
**What did you do?**
Configured e-mail alerts through SMTPS and SMTP + STARTTLS

**What did you expect to see?**
tls_config working to avoid certificate check

**What did you see instead? Under which circumstances?**
An error while trying to use tls_config inside email_config.

**NOTE:**
Previously, this setup was functioning through a non-authenticated smtp server.
Also, using "[swaks](http://www.jetmore.org/john/code/swaks/)" I managed to succeed in sending unitary e-mails through these smtp servers I'm trying to configure.

**Environment**

* System information:
```
	Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018
```
* Alertmanager version:
```
alertmanager, version 0.15.0 (branch: HEAD, revision: 462c969d85cf1a473587754d55e4a3c4a2abc63c)
  build user:       root@bec9939eb862
  build date:       20180622-11:58:41
  go version:       go1.10.3
```
* Prometheus version:
```
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2
```
* Alertmanager configuration file:
```
global:
  smtp_from: 'abc@ghi.com'
  smtp_hello: 'home_machine'
  smtp_auth_username: 'foo'
  smtp_auth_password: 'bar'
  smtp_require_tls: true
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 15s
  repeat_interval: 30s
  receiver: SMTP_STARTTLS
    
receivers:
- name: 'SMTPS'
  email_configs:
  - smarthost: 'smtps_server:465'
    to: 'foobar@ghi.com'
    send_resolved: true

- name: 'SMTP_STARTTLS'
  email_configs:
  - smarthost: 'smtp_starttls:587'
    to: 'foobar@ghi.com'
    send_resolved: true
    tls_config:
      insecure_skip_verify: true
```

* Logs:
```
3/18/2019 8:16:06 PMlevel=info ts=2019-03-18T20:16:06.059255849Z caller=main.go:311 msg="Loading configuration file" file=/data/alertmanager.yml
3/18/2019 8:16:06 PMlevel=info ts=2019-03-18T20:16:06.059317411Z caller=cluster.go:561 component=cluster msg="Waiting for gossip to settle..." interval=2s
3/18/2019 8:16:06 PMlevel=error ts=2019-03-18T20:16:06.059688625Z caller=main.go:314 msg="Loading configuration file failed" file=/data/alertmanager.yml err="yaml: unmarshal errors:\n  line 28: field tls_config not found in type config.plain"
```
