### ISSUE TITLE
missing Wechat CorpID in Wechat config

### ISSUE THREAD

**Issue by shiying2012** [prometheus/alertmanager#1808]
**What did you do?**

Use alertmanager to send wechat type alarms

**What did you expect to see?**

Start alertmananger

**What did you see instead? Under which circumstances?**

level=error ts=2019-03-22T06:59:19.518254371Z caller=main.go:337 msg="Loading configuration file failed" file=alertmanager.yml err="missing Wechat CorpID in Wechat config"

**Environment**

CentOS Linux release 7.3.1611 (Core) 

* System information:

Linux 3.10.0-514.el7.x86_64 x86_64

* Alertmanager version:

alertmanager, version 0.16.1 (branch: HEAD, revision: 571caec278be1f0dbadfdf5effd0bbea16562cfc)
  build user:       root@3000aa3a06c5
  build date:       20190131-15:05:40
  go version:       go1.11.5

* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m
  wechat_api_corp_id: 'xxxxxxxxxxxxxx'
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: "xxxxxxxxxxxxxx"

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'wechat'
receivers:
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    agent_id: '1000002'
    to_party: '4'
```

* Logs:
```
level=info ts=2019-03-22T06:59:19.434892681Z caller=main.go:177 msg="Starting Alertmanager" version="(version=0.16.1, branch=HEAD, revision=571caec278be1f0dbadfdf5effd0bbea16562cfc)"
level=info ts=2019-03-22T06:59:19.435018095Z caller=main.go:178 build_context="(go=go1.11.5, user=root@3000aa3a06c5, date=20190131-15:05:40)"
level=info ts=2019-03-22T06:59:19.478136301Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=172.16.2.2 port=9094
level=info ts=2019-03-22T06:59:19.480892586Z caller=cluster.go:632 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-03-22T06:59:19.517789823Z caller=main.go:334 msg="Loading configuration file" file=alertmanager.yml
level=error ts=2019-03-22T06:59:19.518254371Z caller=main.go:337 msg="Loading configuration file failed" file=alertmanager.yml err="missing Wechat CorpID in Wechat config"
level=info ts=2019-03-22T06:59:19.518323831Z caller=cluster.go:641 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=37.342917ms

```

When I use the global.wechat_api_corp_id configuration item, the alertmananger cannot be started, and the error of err="missing Wechat CorpID in Wechat config" is reported. When the configuration “corp_id“ of "receivers" is used, it can be started normally.
