### ISSUE TITLE
alertmanager telegram

### ISSUE THREAD

**Issue by luisgarcia1010** [prometheus/alertmanager#1815]
set up notifications in slack, I want to add that notifications would come in telegram, installed this [bot](https://github.com/inCaller/prometheus_bot) and started

`tcp6       0      0 :::9087                 :::*                    LISTEN      12549/prometheus_bot`

add to altermanager config.yml

```
route:
    receiver: 'slack'

route:
    receiver: 'telegram'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#prometheus'
            api_url: 'https://hooks.slack.com/services/myhook'

receivers: 'telegram'
    - name: 'telegram'
      webhook_configs:
          - send_resolved: true
             url: http://127.0.0.1:9087/alert/id_chat
```

but I get an error at startup
```
level=info ts=2019-03-26T12:32:50.038918999Z caller=main.go:334 msg="Loading configuration file" file=./config.yml
level=error ts=2019-03-26T12:32:50.039110011Z caller=main.go:337 msg="Loading configuration file failed" file=./config.yml err="yaml: line 16: did not find expected key"
level=info ts=2019-03-26T12:32:50.039168891Z caller=cluster.go:641 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=15.564931ms
```

what am I doing wrong, how do I set up notifications in both slack and telegram?
