### ISSUE TITLE
amtool check-config -  undefined receiver

### ISSUE THREAD

**Issue by sysincz** [prometheus/alertmanager#1827]
**What did you do?**
./amtool check-config ./alertmanager.yaml

**What did you expect to see?**
```
Checking './alertmanager.yaml'  FAILED: undefined receiver "d" used in route

amtool: error: failed to validate 1 file(s)
```
**What did you see instead? Under which circumstances?**
```
Checking './alertmanager.yaml'  SUCCESS
Found:
 - global config
 - route
 - 0 inhibit rules
 - 3 receivers
 - 1 templates
  SUCCESS
```

**Environment**

* System information:

	Linux 4.15.0-46-generic x86_64

* Alertmanager version:

```
alertmanager, version 0.16.1 (branch: HEAD, revision: 571caec278be1f0dbadfdf5effd0bbea16562cfc)
  build user:       root@3000aa3a06c5
  build date:       20190131-15:05:40
  go version:       go1.11.5

```
amtool --version
```

amtool, version 0.16.1 (branch: HEAD, revision: 571caec278be1f0dbadfdf5effd0bbea16562cfc)
  build user:       root@3000aa3a06c5
  build date:       20190131-15:05:40
  go version:       go1.11.5
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  smtp_smarthost: "address:25"
  smtp_from: "address@example.com"
  smtp_hello: "localhost"
  smtp_require_tls: false
templates:
- '/etc/alertmanager/*.tmpl'
route:
  receiver: 'a'
  routes:
  - match_re:
      namespace: test
    receiver: "b"
  - match:
      alertname: AlertName
    receiver: "b"
    repeat_interval: 5m
  - match_re:
      namespace: ^(test2)$
    receiver: c
    routes:
    - match:
        env_type: prod
      routes:
      - match_re:
          severity: ^(warning|critical)$
        receiver: c
    - match:
        env_type: preprod
      routes:
      - match_re:
          severity: ^(critical)$
        receiver: c
    - match:
        env_type: test
      routes:
      - match_re:
          severity: ^(critical)$
        receiver: d
receivers:
- name: "a"
- name: 'b'
- name: "c"

```
