### ISSUE TITLE
SMTP for sending alerts is not working

### ISSUE THREAD

**Issue by vrathore18** [prometheus/alertmanager#1829]
I am setting up the SMTP for sending the alerts notifications. Below is the setting I am using

```
receivers:
- name: email-me
  email_configs:
  - to: vickyrathore1212@gmail.com
    from: rathore.vikas@xxx.com
    smarthost: smtp.xxx.com:587
    auth_username: "rathore.vikas@xxx.com"
    auth_password: "xxxxxx"
```
I also tried with smtp.xxx.com:25 but on both the cases I am getting error:

`level=error ts=2019-04-10T10:35:38.517695841Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="dial tcp: lookup smtp.xxx.com on 172.xx.xx.10:53: no such host"`

How to fix this issue?
