### ISSUE TITLE
prometheus dont support use labels of rule in annotations?

### ISSUE THREAD

**Issue by szediktam** [prometheus/alertmanager#1831]
I create a prometheus alerting rule as following:
```
alert: cluster_cpu_alarm
expr: cluster_cpu_utilization  > 0.90
for: 1m
labels:
  severity: Medium
  cluster: dev
annotations:
  summary: the cpu utilization of cluster {{ $labels.cluster }} is more than 90%, now {{ $value }}.
```

When the alert is triggered to alertmanager, the {{ $labels.cluster }} in annotations.summary is empty, and {{ $value }} is a real cpu utilization.
Prometheus donot support use labels of alertingrule in annotations? 

@brancz
