### ISSUE TITLE
Wechat can not receive any alerts

### ISSUE THREAD

**Issue by Remember-Forever** [prometheus/alertmanager#1866]
Hi all, 
  I want to use wechat to receive the alerts. But I can't get any alerts. Log doesn't have any error. But it can be sure that the test alert is triggered. I can see the alert in my prometheus. 

  It seems related to k8s? Because I don't find the directory 'templates' in my pod. I try to create this file and put my custom wechat template into it. It is also useless.

  My alertmanager version 0.15.2. And here is my config is:
````
global: 
  resolve_timeout: 5m
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  wechat_api_secret: xxx
  wechat_api_corp_id: wxxxxxxxxxxxxxxxxa
receivers:
- name: WarningAlert
  wechat_configs:
  - api_secret: xxx
    corp_id: wxxxxxxxxxxxxxxxxa
    message: '{{ template "wechat.default.message" . }}'
    api_url: https://qyapi.weixin.qq.com/cgi-bin/
    to_user: '{{ template "wechat.default.to_user" . }}'
    to_party: "2"
    to_tag: '{{ template "wechat.default.to_tag" . }}'
    agent_id: "1000008"
````
