### ISSUE TITLE
PagerDuty notifier does not honor custom details section

### ISSUE THREAD

**Issue by vj396** [prometheus/alertmanager#1882]
**What did you do?**
I tried to update the pd integration with custom details section.

**What did you expect to see?**
i wanted it to show me custom details section.

**What did you see instead? Under which circumstances?**
the default details section
**Environment**

* System information:
Linux 4.15.0-48-generic x86_64
* Alertmanager version:
```./alertmanager --version
alertmanager, version 0.17.0 (branch: master, revision: 6749f9faa9b87f4ca153481e8ab4332c89f0360b)
  build user:       user@somesystem
  build date:       20190509-21:17:53
  go version:       go1.12.5
```
* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
global:
  smtp_smarthost: '<redacted>'
  smtp_from: '<redacted>'
route:
  group_by: [<some list of tags>]
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: test-receiver
  routes:
  - receiver: test-receiver
    continue: false
    match:
      param: 'value'
      severity: 'critical'
receivers:
- name: 'test-receiver'
  pagerduty_configs:
  - routing_key: '<redacted>'
    send_resolved: true
    client_url: '<redacted>'
    details:
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
      client_url: '{{ template "pagerduty.default.instances" .Alerts.Resovled }}'
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
