### ISSUE TITLE
OpsGenie Inconsistent Tags - Labels Mapping

### ISSUE THREAD

**Issue by nehalraf** [prometheus/alertmanager#1884]
**What did you do?**
I am mapping alertmanager labels to opsgenie tags field in configuration

**What did you expect to see?**
I expect opsgenie to receive tags with alert

**What did you see instead? Under which circumstances?**
I see inconsistent behavior where tags are passed to opsgenie sometime and other times not.

**Environment**
prometheus operator/kubernetes

* Alertmanager version: 
0.17.0

* Prometheus version:
v2.7.1

* Alertmanager configuration file:
```
global:
  opsgenie_api_key: 'REMOVE'

# The directory from which notification templates are read.
templates: 
- '/etc/alertmanager/config/*.tmpl'

route:
  group_by: ['alertname', 'rc_edgeid' ,'service']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 3h
  receiver: team-ops-genie

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'clusterid', 'service']

receivers:
- name: 'team-ops-genie'
  opsgenie_configs:
  - send_resolved: true
  - teams: Operations
  - tags: '{{ .CommonLabels.severity }}'
  - priority: '{{ range .Alerts }}{{ if eq .Labels.severity "critical"}}P1{{else}}P3{{end}}{{end}}'

```

* Alertmanager Logs:
```
level=debug ts=2019-05-13T23:42:04.509250832Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}:{alertname=\"FluentdNodeDown\", rc_edgeid=\"cluster-0\", service=\"fluentd\"}" msg=flushing alerts="[FluentdNodeDown[12d5250][active] FluentdNodeDown[ac50dw8][active]]"
```

* OpsGenie Logs:
```
Ops Genie receive message with empty "tags[]"
{
  "_incomingData": {
    "_parsedData": {
      "note": "null",
      "alertType": "Raw",
      "-actions": [],
      "-recipients": [],
      "source": "/alertmanager.ops/#/alerts?receiver=team-ops-genie",
      "message": "[FIRING:1] FluentdNodeDown core-0 fluentd",
      "priority": "P3",
      "_extraProperties": {},
      "-teams": [
        "Operations-Staging"
      ],
      "-tags": [],
      "alias": "9aa0aac3ab8dasfgertyeur5wetasdf3434",
      "user": "Alert API",
      "entity": ""
    },
    "integrationType": "Prometheus",
    "integrationName": "Operations-Staging_Prometheus",
    "incomingDataId": "a1387b75-2455-23ee-b0c5"
  },
  "_result": {
    "alertMessage": "[Prometheus]: [FIRING:1] FluentdNodeDown cluster-0 fluentd",
    "alertAction": "create",
    "integrationName": "Operations-Staging_Prometheus",
    "alertCount": "1",
    "integrationActionName": "Create Alert",
    "alertId": "85c8f6ac-adf9-wrss-1557785723628",
    "alertAlias": "9aa0aac3ab81489fcfd911722awredbe2abf6138c9d4ff2c25433411218",
    "user": "Alert API"
  }
}
```
