### ISSUE TITLE
Use default api_secret, the wechat recevier raise invalid APISecret error

### ISSUE THREAD

**Issue by MIBc** [prometheus/alertmanager#1887]
**What did you do?**
I set a wechat_api_secret in global section which would be a default paasword for wechat recevier.
Then I used script to send some alerts to alertmanager.
**What did you expect to see?**
Alerts send to wechat app.
**What did you see instead? Under which circumstances?**
It raised error: invalid APISecret for CorpID:xxxxxxxx.
**Environment**

* System information:

	Linux 3.10.0-229.el7.x86_64 x86_64

* Alertmanager version:

alertmanager, version 0.17.0 (branch: master, revision: 6749f9faa9b87f4ca153481e8ab4332c89f0360b)
  build user:       root@my-server
  build date:       20190515-02:22:02
  go version:       go1.12.4

* Alertmanager configuration file:
```
global:
  resolve_timeout: 2m
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_corp_id: 'xxxxxxxx'
  wechat_api_secret: 'h73FJ1L8qlcfLrnE82i8mi3C_uu_az6vZJ-0CSvInA8'
route:
  receiver: 'wechat'
  group_by: [alername]
  routes:
  - match_re:
      severity: ^warn.*
receivers:
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    to_party: 1
    agent_id: '1000003'
```

* Logs:
```
level=error ts=2019-05-15T02:25:01.951546027Z caller=notify.go:339 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"wechat\" due to unrecoverable error: invalid APISecret for CorpID: xxxxxxxx"
```

From the error log, the code location is at notify/impl.go:
if wechatToken.AccessToken == "" {
	return false, fmt.Errorf("invalid APISecret for CorpID: %s", n.conf.CorpID)
}
So I printed the `n.conf.APISecret` at this file, it returned {{ template "wechat.default.api_secret" . }}
If change the config like the below, it works.
```
global:
  resolve_timeout: 2m
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_corp_id: 'xxxxxxxx'
route:
  receiver: 'wechat'
  group_by: [alername]
  routes:
  - match_re:
      severity: ^warn.*
receivers:
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    to_party: 1
    agent_id: '1000003'
    api_secret: 'h73FJ1L8qlcfLrnE82i8mi3C_uu_az6vZJ-0CSvInA8'
```
