### ISSUE TITLE
Bad Request for Resolved Alerts with PagerDuty Integration

### ISSUE THREAD

**Issue by amalucelli** [prometheus/alertmanager#1890]
**What did you do?**

Notification of `resolved` alerts to PagerDuty are returning a `Bad Request (400)`.  Notification of `firing` alerts are working as expected.

Currenyly we're using the `routing_key` to use the `Events API v2`.

**What did you expect to see?**

When Alertmanager notify the `resolved` status of an alert, PagerDuty should receive this request and mark the incident as resolved.

**What did you see instead? Under which circumstances?**

When Alertmanager tries to notify `resolved` status, an error is raised at the logs: `unrecoverable error: unexpected status code 400` _(more info below)_.

**Environment**

* System information: 

```
Linux 4.15.0-1025-gcp x86_64
```

* Alertmanager version:

```
alertmanager, version 0.16.2 (branch: HEAD, revision: 308b7620642dc147794e6686a3f94d1b6fc8ef4d)
  build user:       root@1e9a48272b38
  build date:       20190405-12:27:40
  go version:       go1.11.6
```

* Alertmanager configuration file:

```
global:
  resolve_timeout: 5m
  http_config: {}
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
route:
  receiver: pagerduty
  group_by:
  - alertname
  - instance
  - severity
  routes:
  - receiver: pagerduty
    match:
      page: "true"
  group_wait: 5s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: pagerduty
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    routing_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    links:
    - href: '{{ range .Alerts }}{{ .GeneratorURL }}{{ end }}'
      text: See on Prometheus
```

* Logs:

```
level=error ts=2019-05-15T14:40:11.19242835Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: unexpected status code 400"
level=error ts=2019-05-15T14:40:11.192602994Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: unexpected status code 400"
```
