### ISSUE TITLE
Alertmanager Issues during set up of an SMTP connection

### ISSUE THREAD

**Issue by Lavair** [prometheus/alertmanager#1898]
**What did you do?**
I am trying to set up alertmanager on a virtual strato server with an SMTP connection to an email account to receive alert notifications from the alertmanager.
**What did you expect to see?**
I expected an established connection and emails in in case of certain events.
**What did you see instead? Under which circumstances?**
Inside the logs, it's clearly visible, that the config.yml file gets loaded successfully. Inside the alert.rules one can see, that I defined alerts, that should theoretically provoke immediate emails. But I didn't receive any mails.
**Environment**

* System information:

	Linux 4.15.0 x86_64
        Linux PRIVATE.stratoserver.net 4.15.0 #1 SMP Wed May 15 09:45:34 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux

* Alertmanager version:

	alertmanager, version 0.16.2 (branch: HEAD, revision: 308b7620642dc147794e6686a3f94d1b6fc8ef4d)
  build user:       root@1e9a48272b38
  build date:       20190405-12:27:40
  go version:       go1.11.6

* Prometheus version:

	irrelevant

* Alertmanager configuration file:
```
global:
  smtp_from: 'monitoring@PRIVATE_INFORMATION.com'
  smtp_smarthost: 'smtp.strato.de:587'
  smtp_auth_username: 'technicalUserAM'
  smtp_auth_password: "{{ vault_monitoring_alertmanager_technicalUser_password }}"

# The directory from which notification templates are read.
# templates: 
# - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: PRIVATE_INFORMATION_R

  routes:
  - match:
      service: files
    receiver: PRIVATE_INFORMATION_R

    routes:
    - match:
        severity: critical
      receiver: PRIVATE_INFORMATION_R

  - match:
      service: database
    receiver: PRIVATE_INFORMATION_R

    group_by: [alertname, cluster, database]

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']


receivers:
- name: 'PRIVATE_INFORMATION_R'
  email_configs:
  - to: 'PRIVATE_INFORMATION_C@PRIVATE_INFORMATION.de'
```

* Prometheus configuration file:
```
irrelevant
```

* Logs:
```
level=info ts=2019-05-23T10:55:36.675638651Z caller=main.go:177 msg="Starting Alertmanager" version="(version=0.16.2, branch=HEAD, revision=308b7620642dc147794e6686a3f94d1b6fc8ef4d)"
level=info ts=2019-05-23T10:55:36.675848002Z caller=main.go:178 build_context="(go=go1.11.6, user=root@1e9a48272b38, date=20190405-12:27:40)"
level=info ts=2019-05-23T10:55:36.68330956Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=172.25.0.8 port=9094
level=info ts=2019-05-23T10:55:36.688790138Z caller=cluster.go:632 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-05-23T10:55:36.714324555Z caller=main.go:334 msg="Loading configuration file" file=/etc/alertmanager/config.yml
level=info ts=2019-05-23T10:55:36.720223087Z caller=main.go:428 msg=Listening address=:9093
level=info ts=2019-05-23T10:55:38.689497016Z caller=cluster.go:657 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000145649s
level=info ts=2019-05-23T10:55:46.6901037Z caller=cluster.go:649 component=cluster msg="gossip settled; proceeding" elapsed=10.000771371s
level=error ts=2019-05-23T10:57:07.180652435Z caller=impl.go:307 msg="failed to close SMTP connection" err="tls: use of closed connection"
level=error ts=2019-05-23T10:57:10.320618302Z caller=impl.go:307 msg="failed to close SMTP connection" err="tls: use of closed connection"
level=error ts=2019-05-23T10:57:11.370613985Z caller=impl.go:307 msg="failed to close SMTP connection" err="tls: use of closed connection"

```

* Alert.rules
```
groups:
- name: targets
  rules:
  - alert: monitor_service_down
    expr: up == 1
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Monitor service non-operational"
      description: "Service {{ $labels.instance }} is down."

- name: host
  rules:
  - alert: high_cpu_load
    expr: node_load1 > 0
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server under high load"
      description: "Docker host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_memory_load
    expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 0
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server memory is almost full"
      description: "Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_storage_load
    expr: (node_filesystem_size_bytes{fstype="aufs"} - node_filesystem_free_bytes{fstype="aufs"}) / node_filesystem_size_bytes{fstype="aufs"}  * 100 > 0
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server storage is almost full"
      description: "Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

- name: containers
  rules:
  - alert: jenkins_down
    expr: absent(container_memory_usage_bytes{name="jenkins"})
    for: 1s
    labels:
      severity: critical
    annotations:
      summary: "Jenkins down"
      description: "Jenkins container is down for more than 1 second."

  - alert: jenkins_high_cpu
    expr: sum(rate(container_cpu_usage_seconds_total{name="jenkins"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 0
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Jenkins high CPU usage"
      description: "Jenkins CPU usage is {{ humanize $value}}%."

  - alert: jenkins_high_memory
    expr: sum(container_memory_usage_bytes{name="jenkins"}) > 0
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Jenkins high memory usage"

```
