### ISSUE TITLE
Error on notify" err="context deadline exceeded + MSTeam Receiver

### ISSUE THREAD

**Issue by vivekj11** [prometheus/alertmanager#1907]
Hello All,

I can see there are multiple issues already available for the above-mentioned error, but unfortunately, nothing is working for me.

Infra background-

1. I have my Prometheus and Alertmanager up and running. Also, my configured alert rules are visible on the Alertmanager dashboard.

2. I am trying to integrate it with Microsoft team/ mattermost to receive alerts. However I am getting above mentioned error in alertmanager logs.

3. When I tried to send alert manually using curl to my Microsoft Teams (from the same host machine), I successfully received the alert there.

can someone help me with it?

Also, I have a very small doubt- In my alert.rules files, the group name is XYZ and I am providing the same name in route.group_by: section of alertmanager. Is this correct? 

my alertmanager config file is available below. I also tried to put proxy urls at multiple places as suggested in different issues, but nothing helped - 

```
global:
  http_config:
    proxy_url: 'http://proxyurl:80/'

route:
  group_by: [alert-rules-group-name]
  # Send all notifications to me.
  receiver: prom-msteams
  group_interval: 1m
  repeat_interval: 2m
  group_wait: 30s

receivers:
  - name: prom-msteams
    webhook_configs:
    - send_resolved: true
#      http_config:
#        proxy_url: 'http://proxyurl:80'
      url: 'http://msteam url'
```
