### ISSUE TITLE
Docker-compose setup for alertmanager

### ISSUE THREAD

**Issue by vallettea** [prometheus/alertmanager#191]
Hello,
I'm trying to have a compose file that launches all the prometheus services. In a same directory, I have:
- `prometheus.yml`
- `ants.rules`
- `alertmanager.conf`
- `docker-compose.yml`
- `Dockerfile`

where `docker-compose.yml`:

```
prometheus:
  build: "./"
  ports:
    - "9090:9090"
  links:
    - "exporter:export"
    - "cadvisor:cadvisor"
    - "alertmanager:alertmanager"
  environment:
    - VIRTUAL_HOST=prometheus.ants.builders 
    - VIRTUAL_PORT=9090
  labels: 
    - "name=prometheus"
    - "version=0.16.1"

exporter:
  image: "prom/container-exporter"
  volumes:
    - /sys/fs/cgroup:/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "9104:9104"
  expose:
    - "9104"
  labels: 
    - "name=exporter"
    - "version=latest"

sqlite3:
  image: "prom/promdash"
  command:
    - "./bin/rake db:migrate"
  volumes:
    - "/tmp/prom:/tmp/prom"
  environment:
    - "DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3"

promdash:
  image: "prom/promdash"
  ports:
    - "3000:3000"
  expose:
    - "3000"
  volumes:
    - /tmp/prom:/tmp/prom
  environment:
    - "DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3"
    - VIRTUAL_HOST=promdash.ants.builders 
    - VIRTUAL_PORT=3000
  labels: 
    - "name=prom dashboard"
    - "version=latest"

cadvisor:
  image: "google/cadvisor"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  ports:
    - "8080:8080"
  expose:
    - "8080"
  environment:
    - VIRTUAL_HOST=cAdvisor.ants.builders 
    - VIRTUAL_PORT=8080
  labels: 
    - "name=cAdvisor"
    - "version=latest"

alertmanager: 
  image: "prom/alertmanager"
  ports:
    - "9093:9093"
  expose:
    - "9093" 
  volumes:
    - "/tmp/prom:/tmp/prom"
    - "$PWD/alertmanager.conf:/alertmanager/alertmanager.conf"
```
`prometheus.yml`:

```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).


# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "ants.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    target_groups:
      - targets: ['localhost:9090','cadvisor:8080']
```

`ants.rules`:

```
ALERT ContainerMissing
  IF absent(container_last_seen{name=~"pheromon|6element"}) or on (name) (time() - container_last_seen{name=~"pheromon|6element"} > 3600)
  WITH {}
  SUMMARY "Instance {{$labels.instance}} down"
  DESCRIPTION "{{$labels.instance}} of job {{$labels.job}} seems down."

ALERT HighMemoryAlert
  IF container_memory_usage_bytes > 1000000000
  FOR 1m
  WITH {}
  SUMMARY "High Memory usage for a container"
  DESCRIPTION "High Memory usage on {{$labels.instance}} for container {{$labels.name}} (current value: {{$value}})"

ALERT Test
  IF count_scalar(container_last_seen) > 1
  SUMMARY "TEST"
  DESCRIPTION "Test usage on {{$labels.instance}} for container {{$labels.name}} (current value: {{$value}})"
```

`alertmanager.conf`: 

```
notification_config {
    name: "6element_alert"
    email_config {
        email: "XXX"
    }

    slack_config {
        webhook_url: "XXX"
        channel: "alerts"
      }
}

aggregation_rule {
    repeat_rate_seconds: 3600
    notification_config_name: "6element_alert"
}
```

`Dockerfile`:

```
FROM prom/prometheus:0.16.1

ADD prometheus.yml /etc/prometheus/prometheus.yml
ADD ants.rules /etc/prometheus/ants.rules

RUN mkdir -p /etc/prometheus/targets.d

EXPOSE 9090

ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "-config.file=/etc/prometheus/prometheus.yml", \
             "-storage.local.path=/prometheus", \
             "-web.console.libraries=/etc/prometheus/console_libraries", \
             "-web.console.templates=/etc/prometheus/consoles", \
             "-web.listen-address=:9090", \
             "-alertmanager.url=http://alertmanager:9093"]
```

but I have no alerts ever triggered. What is wrong with my configuration ? How can I see if alerts are triggered ?
