### ISSUE TITLE
when use  groupby: [...],  ... is not invaild label name

### ISSUE THREAD

**Issue by gaopeiliang** [prometheus/alertmanager#1951]
I want to use groupby : [...]  config in alertmanager , but I get error in config file check ,,,

```
msg="Loading configuration file failed" file=/opt/alertmanager/alertmanager.yml err="\"...\" is not a valid label name"
``` 
```
route:
    group_by: [...]
    group_interval: 5m
    group_wait: 10s
    receiver: xyz
    repeat_interval: 1h
```

* Alertmanager version:
```
msg="Starting Alertmanager" version="(version=0.15.1, branch=HEAD, revision=8397de1830f154535a31150f9262da0072d8725d)"
```

I want to know how to config it ....
