### ISSUE TITLE
Not all receivers present in /api/v2/alerts/groups responses

### ISSUE THREAD

**Issue by prymitive** [prometheus/alertmanager#1959]
**What did you do?**

Query /api/v2/alerts/groups responses continuesly

**What did you expect to see?**

Based on my configuration alerts should go to all receivers, so groups should be generated for each receiver as well. Alerts are tagged with all configured receivers but groups for some receivers are missing.

**What did you see instead? Under which circumstances?**

With the configuration as below:

<details>
  <summary>Configuration</summary>

```YAML
global:
  resolve_timeout: 30s
route:
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 999h
  receiver: "default"
  routes:
    - receiver: "default"
      group_by: []
      match_re:
        alertname: .*
      continue: true
    - receiver: "by-cluster-service"
      group_by: ["alertname", "cluster", "service"]
      match_re:
        alertname: .*
      continue: true
    - receiver: "by-name"
      group_by: [alertname]
      match_re:
        alertname: .*
      continue: true
    - receiver: "by-cluster"
      group_by: [cluster]
      match_re:
        alertname: .*
      continue: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    # Apply inhibition if the alertname and cluster is the same in both
    equal: ["alertname", "cluster"]

receivers:
  - name: "default"
  - name: "by-cluster-service"
  - name: "by-name"
  - name: "by-cluster"
```
</details>

When I query api/v2/alerts/groups I will get alert groups for either `default` or `by-name` receiver, but never both. Responses keep switching between one or the other.
See captured respones with only Receiver field from the group object and from alert objects.
[1.txt](https://github.com/prometheus/alertmanager/files/3381740/1.txt)
[2.txt](https://github.com/prometheus/alertmanager/files/3381741/2.txt)
One shows default receiver groups present, the other by-name receiver groups.

**Environment**

* System information:

```Linux 5.1.16-300.fc30.x86_64 x86_64```

* Alertmanager version:

```
Version Information
Branch: HEAD
BuildDate: 20190708-14:31:49
BuildUser: root@868685ed3ed0
GoVersion: go1.12.6
Revision: 1ace0f76b7101cccc149d7298022df36039858ca
Version: 0.18.0
```

Same behaviour observed with 0.17.0

* Prometheus version:

N/A

* Alertmanager configuration file:

<details>
  <summary>Configuration</summary>

```YAML
global:
  resolve_timeout: 30s
route:
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 999h
  receiver: "default"
  routes:
    - receiver: "default"
      group_by: []
      match_re:
        alertname: .*
      continue: true
    - receiver: "by-cluster-service"
      group_by: ["alertname", "cluster", "service"]
      match_re:
        alertname: .*
      continue: true
    - receiver: "by-name"
      group_by: [alertname]
      match_re:
        alertname: .*
      continue: true
    - receiver: "by-cluster"
      group_by: [cluster]
      match_re:
        alertname: .*
      continue: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    # Apply inhibition if the alertname and cluster is the same in both
    equal: ["alertname", "cluster"]

receivers:
  - name: "default"
  - name: "by-cluster-service"
  - name: "by-name"
  - name: "by-cluster"
```
</details>

* Logs:
Didn't find any logs that would show API response information relevant to this
