### ISSUE TITLE
HTTP OPTIONS enabled 

### ISSUE THREAD

**Issue by nbirnel** [prometheus/alertmanager#1972]
**What did you do?**

Ran a Nexpose scan against Alertmanager

**What did you expect to see?**

No vulnerabilities found

**What did you see instead? Under which circumstances?**

HTTP OPTIONS Method Enabled

**Environment**

* System information:

	Linux 3.10.0-514.10.2.el7.x86_64

* Alertmanager version:

```
	alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  slack_api_url:  https://*******
templates:
- '/etc/alertmanager/template/*tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack_warnings'
  routes:
  - match:
      severity: warning
    receiver: slack_warnings
  - match:
      severity: critical
    receiver: slack_alerts
  - match:
      severity: info
    receiver: slack_info
  - match:
      alertname: DiskWillFillIn2Weeks
    repeat_interval: 24h
  - match:
      alertname: WinDiskWillFillIn2Weeks
    repeat_interval: 24h

receivers:
- name: 'slack_warnings'
  slack_configs:
  - channel: '#prod-warnings'

    title: "prometheus {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

- name: 'slack_alerts'
  slack_configs:
  - channel: '#prod-alerts'

    title: "prometheus {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

- name: 'slack_info'
  slack_configs:
  - channel: '#architecture-info'

    title: "prometheus {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
```
