### ISSUE TITLE
alertmanager don't update labels in alert

### ISSUE THREAD

**Issue by szediktam** [prometheus/alertmanager#1975]
I install a prometheus(v2.2.1) and alertmanager(v0.18.0) in a k8s cluster.
I create a alertingrule in prometheus, as following:
```
groups:
- name: general
  rules:
  - alert: node-alert
    expr: node_load15{instance="172.18.21.158:.*"} > 1
    for: 60s
    labels:
      alert_severity: high
```
and I notify it to my app via alertmanager's webhook.

But when update the alertingrule to:
```
groups:
- name: general
  rules:
  - alert: node-alert
    expr: node_load15{instance="172.18.21.158:.*"} > 1
    for: 60s
    labels:
      node_name: test
      node_ip: 172.18.21.158
      severity: high
```
The alert received from webhook has no the added labels in alerts.

I think the alert received from webhook should same to the alertingrule in prometheus.
May be it is a bug of alertmanager.
