### ISSUE TITLE
Can't set receiver `send_resolved` field

### ISSUE THREAD

**Issue by pdf** [prometheus/alertmanager#198]
Trying to set the `send_resolved` field in a receiver config:

```yaml
receivers:
- name: "test"
  email_configs:
    - to: 'user@example.com'
      send_resolved: true
```

Results in the following error:

```
level=error msg="Loading configuration file failed: unknown fields in email config: send_resolved" file="/etc/prometheus/alertmanager.yml" source="main.go:128"
```

I'm guessing some sort of unmarshalling problem with embedded structs for YAML.
