### ISSUE TITLE
Feature request: support for dynamically determining responders in opsgenie configuration

### ISSUE THREAD

**Issue by hrancic** [prometheus/alertmanager#1987]
Alertmanager v0.18.0 moved from `team` field to `responders` for alert routing in opsgenie. 

Having `team` field was useful for an use case where teams were determined dynamically after the alert fired, but before the alert was sent to opsgenie. If the list of teams responsible for the alert is not know before the alert is created, `responders` approach is not useful. 

Something along the lines of the following solution would be much appreciated:

```

#names contain comma separated list of teams

responders:
 - names: <tmpl_string>
   type: teams
```
