### ISSUE TITLE
nginx proxy for alertmanager: location problems

### ISSUE THREAD

**Issue by shipilovds** [prometheus/alertmanager#1992]
**What did you do?**
I was not able to find any old issues like this (similar - yes, but not the same). Sorry if I failed with it.
I am trying to get alertmanager behind nginx. 
location with only "/" works
```
nginx:
...
        location / {
          proxy_pass http://127.0.0.1:9093$request_uri;
        }
...
alertmanager:
--web.external-url=http://mymon.serv/
```
but "/alertmanager/" - does not:
```
nginx:
...
        location /alertmanager/ {
          proxy_pass http://127.0.0.1:9093$request_uri;
        }
...
alertmanager:
--web.external-url=http://mymon.serv/alertmanager/
```

And such way works with prometheus without any issues!

**What did you expect to see?**
I expect to see alertmanager interface on http://mymon.serv/alertmanager/

**What did you see instead? Under which circumstances?**
404

**Environment**

* System information:

Linux 3.10.0-957.12.2.el7.x86_64 x86_64

* Alertmanager version:

alertmanager, version 0.18.0 (branch: HEAD, revision: 1ace0f76b7101cccc149d7298022df36039858ca)
  build user:       root@868685ed3ed0
  build date:       20190708-14:31:49
  go version:       go1.12.6

* Prometheus version:

prometheus, version 2.11.1 (branch: HEAD, revision: e5b22494857deca4b806f74f6e3a6ee30c251763)
  build user:       root@d94406f2bb6f
  build date:       20190710-13:51:17
  go version:       go1.12.7

* Alertmanager configuration file:
```
global:

templates:
- 'alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 15m
  receiver: alertmanager

receivers:
- name: alertmanager
  webhook_configs:
  - send_resolved: true
    url: 'http://my_notify_bot_path/
```
