### ISSUE TITLE
export configuration as plain text with secrets?

### ISSUE THREAD

**Issue by zetaab** [prometheus/alertmanager#2004]
I am trying to export alertmanager configuration as plain text, because I am inserting it to kubernetes configmap. The problem is that when I marshal/unmarshal things the secrets are replaced with `<secret>`. Is there any way to avoid removing secrets from the configuration.

Example
```
	alertmanager := &config.Config{
		Receivers: []*config.Receiver{
			{
				Name: "kapi",
				WebhookConfigs: []*config.WebhookConfig{
					{
						NotifierConfig: config.NotifierConfig{
							VSendResolved: true,
						},
						HTTPConfig: &commoncfg.HTTPClientConfig{
							BearerToken: commoncfg.Secret("placeholder"),
						},
						URL: &config.URL{URL: "https://google.fi"},
					},
				},
			},
		},
		Route: &config.Route{
			Receiver:       "kapi",
			RepeatInterval: &dur,
		},
	}
```

alertmanager.String() will produce:

```
        route:
          receiver: kapi
          repeat_interval: 1d
        receivers:
        - name: kapi
          webhook_configs:
          - send_resolved: true
            http_config:
              bearer_token: <secret>
            url: https://google.fi
        templates: []
```

instead I would like to have
```
        route:
          receiver: kapi
          repeat_interval: 1d
        receivers:
        - name: kapi
          webhook_configs:
          - send_resolved: true
            http_config:
              bearer_token: placeholder
            url: https://google.fi
        templates: []
```

Of course I can run `strings.Replace(alertmanager.String(), "<secret>", "placeholder", -1)`. However, the problem starts when there are multiple secrets in configuration.
