### ISSUE TITLE
Alertmanager and NTLM 

### ISSUE THREAD

**Issue by gretamosa** [prometheus/alertmanager#2007]
**What did you do?**

Send email with alertmanager

**What did you expect to see?**

Send email successfully

**What did you see instead? Under which circumstances?**

Email didn't send because NTLM is not recognized

**Environment**

* System information:

> Linux 4.13.0-43-generic x86_64

* Alertmanager version:

> docker run prom/alertmanager --version
alertmanager, version 0.18.0 (branch: HEAD, revision: 1ace0f76b7101cccc149d7298022df36039858ca)
  build user:       root@868685ed3ed0
  build date:       20190708-14:31:49
  go version:       go1.12.6

* Prometheus version:

> docker run prom/prometheus --version
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8

* Alertmanager configuration file:
```
global:
  smtp_smarthost: 'x.y.z.a:587'
  smtp_auth_username: 'myauth'
  smtp_auth_password: 'mypass'
  smtp_from: 'sender'
  smtp_require_tls: false

route:
  receiver: 'team'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'team'
    email_configs:
    - to: 'receiver'
```

* Logs:
```
level=error ts=2019-08-21T16:21:05.776Z caller=notify.go:367 component=dispatcher msg="Error on notify" err="unknown auth mechanism: NTLM"
level=error ts=2019-08-21T16:21:05.776Z caller=dispatch.go:264 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="unknown auth mechanism: NTLM"
```
