### ISSUE TITLE
How can I get logs for sending notifications in container

### ISSUE THREAD

**Issue by wenj1104** [prometheus/alertmanager#2036]
**What did you do?**
I deployed Prometheus Operator in k8s, and I configured wechat notifications for alertmanager. But I didn't receive any notifications on wechat. 
In alertmanager pod, I can not find any logs for sending notifications. 

**What did you expect to see?**
I wanna see the logs for sending notifications.

**Environment**

* System information:

	Linux 4.14.44-coreos-r1 x86_64

* Alertmanager version:

	alertmanager, version 0.17.0 (branch: HEAD, revision: c7551cd75c414dc81df027f691e2eb21d4fd85b2)
  build user:       root@932a86a52b76
  build date:       20190503-09:10:07
  go version:       go1.12.4

* Prometheus version:

	prometheus, version 2.5.0 (branch: HEAD, revision: 67dc912ac8b24f94a1fc478f352d25179c94ab9b)
  build user:       root@578ab108d0b9
  build date:       20181106-11:40:44
  go version:       go1.11.1

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  smtp_smarthost: 'xxx'
  smtp_from: 'xxx'
  smtp_auth_username: 'xxx'
  smtp_auth_password: 'xxx'
  smtp_auth_secret: null
  smtp_auth_identity: ""
  smtp_require_tls: false 
  slack_api_url: null
  pagerduty_url: https://events.pagerduty.com/generic/2010-04-15/create_event.json
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/

templates:
- '/etc/alertmanager/configmaps/alertmanager-templates/*.tmpl'

route:
  group_by: ['severity', 'env']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
  receiver: wechat 
  routes:
  - match:
      severity: P1
    receiver: xxx 
  - match:
      severity: P2
    receiver: xxx
  - match:
      env: ENV
    receiver: xxx
  - match:
      env: ENV
    receiver: wechat

inhibit_rules:
  - source_match:
      severity: 'P1'
    target_match:
      severity: 'P2'
    equal: ['instance','alertname']

receivers:
- name: 'xxx'
  email_configs:
  - send_resolved: true
    to: 'xxx'
    from: 'xxx'
    smarthost: 'xxx'
    auth_username: 'xxx
    auth_password: 'xxx'
    auth_secret: null
    auth_identity: ""
    headers:
      From: 'xxx'
      Subject: '{{ template "email.default.subject" . }}'
      To: 'xxx'
    html: '{{ template "email.default.html" . }}'
    require_tls: false 

- name: 'wechat'
  wechat_configs:
  - corp_id: 'xxx'
    to_party: '2'
    agent_id: 'xxx'
    api_secret: 'xxx'
    send_resolved: true
    message: '{{ template "wechat.default.message" . }}'
    api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
```

* Logs:
```
$ kubectl -n monitoring logs alertmanager-main-1 alertmanager | tail -4
level=info ts=2019-09-17T05:54:04.032557474Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-09-17T05:54:04.033281864Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-09-17T06:02:54.100848767Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-09-17T06:02:54.101567953Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
```
