### ISSUE TITLE
v0.19: find auth mechanism: unknown auth mechanism: NTLM

### ISSUE THREAD

**Issue by daixiang0** [prometheus/alertmanager#2051]
This issue seems fixed in v0.16 but after upgrade from 0.15 to v0.19, i still hit it.
The following config works in v0.15 but failed in v0.19.
To confirm it, i download v0.15 and v0.19 release binary to test, Now i am sure it is a bug.

**What did you do?**
Run with below config but failed to send mail:
```
global:
  resolve_timeout: 5m
  smtp_smarthost: 'xx:25'
  smtp_from: 'xxx'
  smtp_auth_username: 'xxx'
  smtp_auth_password: 'xxx'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 4h
  receiver: warn

templates:
  - "/etc/alertmanager-templates/alertmanager-templates.yaml"

receivers:
- name: 'warn'
  email_configs:
  - send_resolved: true
    to: 'xxx'
    headers: { Subject: "[AlertManager] warn" }
```

**What did you expect to see?**

send warning mail.

**What did you see instead? Under which circumstances?**
```
level=info ts=2019-09-26T12:10:31.208Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.001081256s
level=debug ts=2019-09-26T12:20:00.903Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=NodeFilesystemUsage[311128f][active]
level=debug ts=2019-09-26T12:20:00.904Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=NodeFilesystemUsage[111353c][active]
level=debug ts=2019-09-26T12:20:30.906Z caller=dispatch.go:432 component=dispatcher aggrGroup="{}:{alertname=\"NodeFilesystemUsage\"}" msg=flushing alerts="[NodeFilesystemUsage[311128f][active] NodeFilesystemUsage[111353c][active]]"
level=debug ts=2019-09-26T12:20:30.913Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=1 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
level=debug ts=2019-09-26T12:20:31.552Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=2 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
level=debug ts=2019-09-26T12:20:37.456Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=3 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
level=debug ts=2019-09-26T12:20:37.462Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=4 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
level=debug ts=2019-09-26T12:20:38.577Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=5 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
level=debug ts=2019-09-26T12:20:40.631Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=6 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
level=debug ts=2019-09-26T12:20:50.378Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=7 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
level=debug ts=2019-09-26T12:20:58.635Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=8 integration=email receiver=skydiscovery err="find auth mechanism: unknown auth mechanism: NTLM"
```

**Environment**

CentOS7.4

* System information:

`Linux 3.10.0-693.el7.centos.x86_64 x86_64
`

* Alertmanager version:

```alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:01:40
  go version:       go1.12.8
```

* Prometheus version:

```
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8

```
