### ISSUE TITLE
promethues alert are shing in firing state up instance also in firing state and not receiving resovled alert. FIRING > RESVOLED> FIRING

### ISSUE THREAD

**Issue by babalsurer** [prometheus/alertmanager#2054]
HI,
I am using helm chart Prometheus and alert manger I ma getting only firing alert not getting resolved alert.

on Prometheus dashboard in an alert tab showing up  instance and down instance both are in firing state.
```
global_config:--
slack_configs:
       - channel: '#alertmanager'
         send_resolved: True
         title: '{{ if eq .Status "firing" }}:rotating_light: Dev-central-alerts {{ else }} :relaxed: Dev-central-alerts {{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }} '
         text: |-
           {{ range .Alerts }}
           *Alert:* {{ .Annotations.summary }}
           *Description:* {{ .Annotations.description }}
           *Graph:* <|:chart_with_upwards_trend:>
           Details:
           instance_ip: `{{ .Labels.instance }}`
           {{ range .Labels.SortedPairs }}  {{ if eq .Name "alertname"}} {{ .Name }}: `{{ .Value }}` {{ end }}
           {{ end }}
           {{ end }}


route:
  group_by: ['alertname', 'app']
  group_wait: 30s
  group_interval: 5m
  receiver: email_config
  repeat_interval: 5m
  routes:
    - match:
        severity: critical
      continue: true
      receiver: slack_config
      repeat_interval: 60m
    - match:
        severity: page
      repeat_interval: 5m
      receiver: slack_config
    - match:
        severity: warning
      repeat_interval: 5h
      receiver: slack_config
```
