### ISSUE TITLE
Change the default.tmpl but the notification is null

### ISSUE THREAD

**Issue by kaweit** [prometheus/alertmanager#2066]
**What did you do?**
I need to create a wechat.tmpl.

**What did you expect to see?**
I want to see a wechat.tmpl demo.

**What did you see instead? Under which circumstances?**
I use a demo in internet. but the notification is null.

* Alertmanager version:

I use prometheus-operator; Alertmanager version is 0.18.0

* Prometheus version:

Prometheus version is 2.11.0

* Alertmanager configuration file:
```
`global:
  resolve_timeout: "5m"
receivers:
- name: "null"
- name: "wechat_test"
  wechat_configs:
  - send_resolved: true
    agent_id: "xxx"
    corp_id: "xxxxxxxxxx"
    api_secret: "xxxxxxxxxxxxxxx"
    to_user: "TanJiaWei"
    message: '{{ template "wechat.tem.message" }}'
templates:
- '/etc/alertmanager/config/*.tmpl'
route:
  group_by:
  - job
  group_interval: "5m"
  group_wait: "30s"
  receiver: "null"
  repeat_interval: "10m"
  routes:
  - match:
      alertname: "Watchdog"
    receiver: "wechat_test"
  - match:
      alertname: "CPUThrottlingHigh"
    receiver: "wechat_test"
  - match:
      alertname: "KubePodNotReady"
    receiver: "wechat_test"
`
```
wechat.tmpl:
```
`{{ define "wechat.tem.message" }}
  {{ range $i, $alert := .Alerts }}
    [alerting]:{{ index $alert.Labels "alertname" }}
    [instance]:{{ index $alert.Labels "instance" }}
    [annotations]:{{ index $alert.Annotations "value" }}
    [beginning]:{{ $alert.StartsAt }}
  {{ end }}
{{ end }}
`
```

* Logs:

alertmanager.log:
![image](https://user-images.githubusercontent.com/49010542/66693715-b0865800-ecde-11e9-97c3-cdba04ebfd52.png)

Receiver：

![image](https://user-images.githubusercontent.com/49010542/66693730-d1e74400-ecde-11e9-9669-2c5113bd79b5.png)
