### ISSUE TITLE
Prometheus stops firing but alerts stay active

### ISSUE THREAD

**Issue by fight-for-future-and-family** [prometheus/alertmanager#2079]
**What did you do?**
I create a prometheus rule tu send a alert to alertmanager, however when the alert in prometheus web UI is disappered , the alertmanager is still sending the alert 

**What did you expect to see?**
what I want to see is when the alert in prometheus is disapper, the alertmanager send the resolved alert to us immetiately , not delay for about 4 minutes 

**What did you see instead? Under which circumstances?**

**Environment**
prometheus-2.9.2.linux-amd64
alertmanager-0.15.2.linux-amd64
CentOS Linux release 7.3.1611

* System information:

	Linux 4.11.2 x86_64

* Alertmanager version:

alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3

* Prometheus version:

prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4

* Alertmanager configuration file:
```
global:
  resolve_timeout: 10m
  routes:
    - receiver: 'wltest'
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 20s
      match:
        sql: 'cfytenant'
```

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
rule_files:
  - '/data/etc/prometheus-server/rules/*.rules.yml'
scrape_configs:
  - job_name: 'sql-exporter'
    metrics_path: '/triones'
    scrape_interval: 2s
    static_configs:
    - targets: ['1.2.3.4:9229']
      labels:
        sql: 'cfytenant'

# the rules as follows without  "for"
---
groups:
  - name: name
    rules:
      - alert: alert-name
        expr: sql_tenant{col="vcreated_tenants",modified='1'}>0
        labels:
          severity: critical
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
