### ISSUE TITLE
Prometheus not sending resolved notification when pods have restarted

### ISSUE THREAD

**Issue by maryjomcguinness** [prometheus/alertmanager#2089]
**What did you do?**
I am using the Elasticsearch-cluster-health alert file and it sends the alert ok to the Alertmanager when I bring some of the Elasticsearch pods down. However when the pods come up again the alert does not clear from the Alertmanager

**What did you expect to see?**
The alert disappearing from Alertmanager when the Elasticsearch pods come up again

**What did you see instead? Under which circumstances?**
The alert is still showing in Alertmanager

**Environment**
Prometheus configured on Kubernetes cluster with IBM Cloud Private

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
spec:
  data: |-
    groups:
      - name: elasticsearchClusterHealth
        rules:
          - alert: elasticsearchClusterHealth
            expr: elasticsearch_cluster_health_up != 1
            for: 1s
            annotations:
              description: Elasticsearch cluster's health status is not green.
              summary: Elasticsearch cluster not healthy
              type: Storage
  enabled: true


* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
