### ISSUE TITLE
repeate_interval not working when i set to 7d (7 days)

### ISSUE THREAD

**Issue by bientt210** [prometheus/alertmanager#2096]
can someone help me or explain when i set **repeate_interval** to **7d** or 168h but it's not working...

**Comment by srountree-fuze** [comment]
Did you configure a longer data retention value (--data.retention=<val>) than the default?  The default is 120 hours.

I've seen mention that the parser doesn't understand units larger than hours (h).  So, you would need to set it as larger/longer than 168h.

**Comment by bientt210** [comment]
> Did you configure a longer data retention value (--data.retention=) than the default? The default is 120 hours.
> 
> I've seen mention that the parser doesn't understand units larger than hours (h). So, you would need to set it as larger/longer than 168h.

Yes, i know that, i set (--data.retention=720h) but it's not working

**Comment by simonpasquier** [comment]
Can you provide more details about your setup (configuration, versions, logs) and what you observe vs. what you expect?
Are you sure that Alertmanager hasn't been restarted during that interval?

**Comment by bientt210** [comment]
> Can you provide more details about your setup (configuration, versions, logs) and what you observe vs. what you expect?
> Are you sure that Alertmanager hasn't been restarted during that interval?

I'm using version 0.19.0, 
when i set repeat_interval: 168h or 120h ...etc but it's always send periodically around 1 hour, when i set repeat_interval: around from 30m to 4h everything seem ok.
here is config :

```
route:
  group_by: ['alertname']
  group_wait: 1m
  group_interval: 5m
  continue: false
  repeat_interval: 1h
  receiver: 'default'

  routes:
   - receiver: 'telegram'
     continue: true
     match_re:
       send_telegram: 'true'
   - receiver: 'bientt210'
     repeat_interval: 168h
     match_re:
       email_receiver: 'bientt210'
```

and Logs:

```
Nov 13 09:53:18 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:18.709Z caller=main.go:217 msg="Starting Alertmanager" version="(version=0.19.0, branch=HEAD, revision=7aa5d19fea3f58e3d27dbdeb0f2883037168914a)"
Nov 13 09:53:18 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:18.709Z caller=main.go:218 build_context="(go=go1.12.8, user=root@587d0268f963, date=20190903-15:01:40)"
Nov 13 09:53:18 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:18.711Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=10.17.95.26 port=15020
Nov 13 09:53:18 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:18.714Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
Nov 13 09:53:18 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:18.762Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
Nov 13 09:53:18 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:18.764Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/alertmanager.yml
Nov 13 09:53:18 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:18.769Z caller=main.go:466 msg=Listening address=:9093
Nov 13 09:53:20 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:20.714Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000248027s
Nov 13 09:53:28 SVP00006842 alertmanager: level=info ts=2019-11-13T02:53:28.715Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.001649231s
```

**Comment by simonpasquier** [comment]
I tested with `repeat_interval: 121h` locally and Alertmanager honors the `repeat_interval` value. Which notifications are sent too frequently in your case?

**Comment by bientt210** [comment]
> I tested with `repeat_interval: 121h` locally and Alertmanager honors the `repeat_interval` value. Which notifications are sent too frequently in your case?

When i set to 168h as i config above, only config i set 168h send once  per hour, others notification still send as expect. I think the config i set to 168h it's using repeat_interval notification by default

**Comment by simonpasquier** [comment]
I tried again with `168h` and still can't reproduce... I suppose that there's something off with your configuration. Have you checked the configuration as displayed in the Status page of the UI?

**Comment by bientt210** [comment]
> I tried again with `168h` and still can't reproduce... I suppose that there's something off with your configuration. Have you checked the configuration as displayed in the Status page of the UI?

Here is my config on UI: 
```
route:
  receiver: default
  group_by:
  - alertname
  routes:
  - receiver: telegram
    match_re:
      send_telegram: "true"
    continue: true
  - receiver: DevOps
    match_re:
      email_receiver: DevOps
  - receiver: namnh68
    match_re:
      email_receiver: namnh68
  - receiver: bientt1
    match_re:
      email_receiver: bientt1
  - receiver: bientt1-hieupm7
    match_re:
      email_receiver: bientt1-hieupm7
  - receiver: locvx
    match_re:
      email_receiver: locvx
  - receiver: hieupm7
    match_re:
      email_receiver: hieupm7
  - receiver: yendth3
    match_re:
      email_receiver: yendth3-sonar
    repeat_interval: 30m
  - receiver: yendth3
    match_re:
      email_receiver: yendth3-jenkins
    repeat_interval: 1w
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
inhibit_rules:
- source_match:
    severity: critical
  target_match_re:
    severity: warning|server
- source_match:
    severity: warning
  target_match:
    severity: server
  equal:
  - alertname
  - cluster
receivers:
- name: default
  email_configs:
  - send_resolved: false
    to: bientt210@email.com
```
When I set to 1 week as ebove, I receive notify sequentially 5 minutes > 10 minutes > 5 minutes > 10 minutes and again and again .... haizzz
Can you check my configuration for me, so many thansk bro

**Comment by hoffie** [comment]
@bientt210 How do you send alerts to Alertmanager? Is it Prometheus? A single instance? Multiple instances? Are they all configured to send to all Alertmanager instances? What kind of alert triggers this? All? Even a simple one (like `expr: 1`)? Do you use any non-standard command line options?

Side note: I also run Alertmanager with 24h repeat_interval with no issues. So I rather suspect a problem in this specific setup. Also sounds like this might be a case where further debugging should be moved to the mailing list.

**Comment by bientt210** [comment]
@hoffie Hi, I set 7d for the rules below, can you help me to see this rules if something wrong: 

```
  - name: jenkins_rules
    rules:
    
      - alert: "Job fail too much"
        expr: jenkins_job_fail_consecutively{} >= 100
        for: 30s
        labels:
          severity: critical
          send_telegram: false
        annotations:
          summary: "[Jenkins] Job fail more than 100 times"
          description: "Job {{ $labels.job_name }} fail more than 100 times"
    
      - alert: "Job fail too much"
        expr: jenkins_job_fail_consecutively{} >= 50
        for: 30s
        labels:
          severity: warning
          send_telegram: false
        annotations:
          summary: "[Jenkins] Job fail more than 50 times"
          description: "Job {{ $labels.job_name }} fail more than 50 times"
        
      - alert: "Job building too long"
        expr: jenkins_jobs_building_time_seconds{status='building'} >= 36000
        for: 30s
        labels:
          severity: warning
          send_telegram: false
        annotations:
          summary: "[Jenkins] Job is building more than 10 hours"
          description: "Job {{ $labels.job_name }} is building more than 10 hours"

      - alert: "Job building too long"
        expr: jenkins_jobs_building_time_seconds{status='building'} >= 86400
        for: 30s
        labels:
          severity: critical
          send_telegram: false
        annotations:
          summary: "[Jenkins] Job is building more than 1 day"
          description: "Job {{ $labels.job_name }} is building more than 1 day"

      - alert: "Node off too long"
        expr: jenkins_node_last_change{status='offline'} >= 1209600
        for: 30s
        labels:
          severity: warning
          send_telegram: false
        annotations:
          summary: "[Jenkins] Node off more than 2 weeks"
          description: "Node {{ $labels.node_name }} offline more than 2 weeks"
        
      - alert: "Node off too long"
        expr: jenkins_node_last_change{status='offline'} >= 2419200
        for: 30s
        labels:
          severity: critical
          send_telegram: false
        annotations:
          summary: "[Jenkins] Node off more than 1 month"
          description: "Node {{ $labels.node_name }} offline more than 1 month"
        
      - alert: "Job in queue too long"
        expr: jenkins_queue_item_duration >= 36000
        for: 30s
        labels:
          severity: warning
          send_telegram: false
        annotations:
          summary: "[Jenkins] Job is in queue more than 10 hours"
          description: "Item has queue id {{ $labels.job_name }} is in queue more than 10 hours"

      - alert: "Job in queue too long"
        expr: jenkins_queue_item_duration >= 86400
        for: 30s
        labels:
          severity: critical
          send_telegram: false
        annotations:
          summary: "[Jenkins] Job is in queue more than 1 day"
          description: "Item has queue id {{ $labels.job_name }} is in queue more than 1 day"
```
Now, this rules temporary was terminated, everything about notify seem ok like before.
thanks you so much!
