### ISSUE TITLE
JSON de-serialization error on /status API call

### ISSUE THREAD

**Issue by okushchenko** [prometheus/alertmanager#2129]
**What did you do?**
I called the `StatusAPI.Get()` of the Alertmanager's Go client in order to get a server status info.  https://github.com/prometheus/alertmanager/blob/master/client/client.go#L125

**What did you expect to see?**
No errors being returned.

**What did you see instead? Under which circumstances?**
An error being returned in the format of `json: cannot unmarshal string into Go struct field GlobalConfig.configJSON.global.smtp_smarthost of type config.HostPort`.

**Environment**

* System information:

	Centos 7

* Alertmanager version:

	0.20.0-rc0

* Alertmanager configuration file:
```
global:
  http_config: {}
  smtp_from: prometheus@localhost
  smtp_require_tls: false
  smtp_smarthost: localhost:25

route:
  receiver: "test"
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m

receivers:
- name: "test"
  webhook_configs:
  - url: 'http://webhook.service:8080/api/webhooks/prometheus'
    send_resolved: true
    http_config:
      basic_auth:
        username: admin@localhost
        password: test
```
