### ISSUE TITLE
group_interval not working

### ISSUE THREAD

**Issue by sfoxdev** [prometheus/alertmanager#2130]
**What did you do?** 
Trying to send alerts to Slack.

**What did you expect to see?**
Expect that alerts will be grouped and send after 1m 

**What did you see instead? Under which circumstances?**
`group_interval` ignored and alerts sending only after 5m(the default value)

**Environment**

* System information:

Linux 4.15.0-1054-aws x86_64

* Alertmanager version:

alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:01:40
  go version:       go1.12.8

* Prometheus version:

prometheus, version 2.14.0 (branch: HEAD, revision: edeb7a44cbf745f1d8be4ea6f215e79e651bfe19)
  build user:       root@df2327081015
  build date:       20191111-14:27:12
  go version:       go1.13.4

* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m
route:
  receiver: 'slack-all'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
  group_by: [server]
  routes:
   - match:
       server: PROD
     receiver: 'slack-prod'
   - match:
       server: DEMO|DEV|TEST
     receiver: 'slack-all'
receivers:
  - name: 'slack-all'
    slack_configs:
      - send_resolved: true
        title: '{{ template "custom_slack_title" . }}'
        text: '{{ template "custom_slack_message" . }}'
        username: '${SLACK_USERNAME}'
        channel: '#${SLACK_CHANNEL_ALL}'
        api_url: '${SLACK_WEBHOOK_ALL}'
        http_config:
          tls_config:
            insecure_skip_verify: true
  - name: 'slack-prod'
    slack_configs:
      - send_resolved: true
        title: '{{ template "custom_slack_title" . }}'
        text: '{{ template "custom_slack_message" . }}'
        username: '${SLACK_USERNAME}'
        channel: '#${SLACK_CHANNEL_PROD}'
        api_url: '${SLACK_WEBHOOK_PROD}'
        http_config:
          tls_config:
            insecure_skip_verify: true
templates:
  - /etc/alertmanager/notifications.tmpl

```

* Logs:
No errors or warnings
```
12/4/2019 10:58:13 PM===== Checking AlertManager configuration =====
12/4/2019 10:58:13 PMChecking '/etc/alertmanager/alertmanager.yml'  SUCCESS
12/4/2019 10:58:13 PMFound:
12/4/2019 10:58:13 PM - global config
12/4/2019 10:58:13 PM - route
12/4/2019 10:58:13 PM - 0 inhibit rules
12/4/2019 10:58:13 PM - 2 receivers
12/4/2019 10:58:13 PM - 1 templates
12/4/2019 10:58:13 PM  SUCCESS
12/4/2019 10:58:13 PM
12/4/2019 10:58:13 PM===== Starting AlertManager =====
12/4/2019 10:58:13 PMlevel=info ts=2019-12-04T20:58:13.546Z caller=main.go:217 msg="Starting Alertmanager" version="(version=0.19.0, branch=HEAD, revision=7aa5d19fea3f58e3d27dbdeb0f2883037168914a)"
12/4/2019 10:58:13 PMlevel=info ts=2019-12-04T20:58:13.546Z caller=main.go:218 build_context="(go=go1.12.8, user=root@587d0268f963, date=20190903-15:01:40)"
12/4/2019 10:58:13 PMlevel=info ts=2019-12-04T20:58:13.546Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=10.42.164.191 port=9094
12/4/2019 10:58:13 PMlevel=info ts=2019-12-04T20:58:13.549Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
12/4/2019 10:58:13 PMlevel=info ts=2019-12-04T20:58:13.576Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
12/4/2019 10:58:13 PMlevel=info ts=2019-12-04T20:58:13.577Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/alertmanager.yml
12/4/2019 10:58:13 PMlevel=info ts=2019-12-04T20:58:13.581Z caller=main.go:466 msg=Listening address=:9093
12/4/2019 10:58:15 PMlevel=info ts=2019-12-04T20:58:15.549Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000119558s
12/4/2019 10:58:23 PMlevel=info ts=2019-12-04T20:58:23.550Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.0007205s
```
