### ISSUE TITLE
Bug: sent Opsgenie responder not correct

### ISSUE THREAD

**Issue by sandangel** [prometheus/alertmanager#2131]
**What did you do?**
Send alerts to Opsgenie with responders configured like this:

```yaml
- name: opsgenie
  opsgenie_configs:
  - send_resolved: true
    http_config: {}
    api_key: <secret>
    api_url: https://api.opsgenie.com/
    message: A new alert from Alert Manager!!! Something went wrong
    description: '{{ template "opsgenie.default.description" . }}'
    source: '{{ template "opsgenie.default.source" . }}'
    responders:
    - name: On Call Primary
      type: schedule
    - name: Alert Secondary if no Primary ACK for 5 minutes
      type: escalation
    - name: Alert Whole Team if no ACK for 10 minutes
      type: escalation
templates:
- /etc/alertmanager/default.tmpl

```

**What did you expect to see?**

I expect the responder fields alert detail on Opsgenie dashboard should contain all responders `On Call Primary`, `Alert Secondary if no Primary ACK for 5 minutes`...

**What did you see instead? Under which circumstances?**

I only see the team is the responder when I open the alert detail in Opsgenie dashboard:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/22189661/70249341-9ab58080-17bf-11ea-9dc9-484ff53d7817.png">

I should see something like this (test alert created on opsgenie dashboard):

<img width="673" alt="image" src="https://user-images.githubusercontent.com/22189661/70250226-e7e62200-17c0-11ea-9c90-9c118c3ea46b.png">

**Environment**

* System information:

	insert output of `uname -srm` here
```sh
uname -srm
Linux 4.14.146-120.181.amzn2.x86_64 x86_64
```
* Alertmanager version:

	insert output of `alertmanager --version` here

```sh
alertmanager --version
alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:01:40
  go version:       go1.12.8
```

* Alertmanager configuration file:
```yaml
global:
  resolve_timeout: 1h
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  opsgenie_api_key: <secret>
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: notifs-serious-alerts
  group_by:
  - alertname
  - severity
  - environment
  routes:
  - receiver: opsgenie
    match:
      oncall: "true"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - environment
receivers:
- name: notifs-serious-alerts
  slack_configs:
  - send_resolved: true
    http_config: {}
    api_url: <secret>
    channel: '#notifs-serious-alerts'
    username: '{{ template "slack.default.username" . }}'
    color: '{{ template "slack.serious_alerts.color" . }}'
    title: '{{ template "slack.serious_alerts.title" . }}'
    title_link: '{{ template "slack.serious_alerts.title_link" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: '{{ template "slack.serious_alerts.text" . }}'
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
- name: opsgenie
  opsgenie_configs:
  - send_resolved: true
    http_config: {}
    api_key: <secret>
    api_url: https://api.opsgenie.com/
    message: A new alert from Alert Manager!!! Something went wrong
    description: '{{ template "opsgenie.default.description" . }}'
    source: '{{ template "opsgenie.default.source" . }}'
    responders:
    - name: On Call Primary
      type: schedule
    - name: Alert Secondary if no Primary ACK for 5 minutes
      type: escalation
    - name: Alert Whole Team if no ACK for 10 minutes
      type: escalation
templates:
- /etc/alertmanager/default.tmpl
```

* Logs:
no logs related to this bug
```sh
level=debug ts=2019-12-05T15:14:17.659Z caller=cluster.go:306 component=cluster memberlist="2019/12/05 15:14:17 [DEBUG] memberlist: Failed to join 172.17.81.3: dial tcp 172.17.81.3:9094: connect: no route to host\n"
```
