### ISSUE TITLE
Prometheus alert rule label not in alert annotation summary

### ISSUE THREAD

**Issue by walterdolce** [prometheus/alertmanager#2141]
**What did you do?**
Defined a Prometheus alert rule and referenced the alert rule own label in its `annotations.summary`

**What did you expect to see?**
To see this:
```
summary: "No deployment replicas for '{{ $labels.deployment }}' in the '{{ $labels.environment }}' environment"
```

Become this, when the alert is sent by Alertmanager:
```
No deployment replicas for 'cert-manager' in the 'staging' environment"
```

**What did you see instead? Under which circumstances?**
Received this on Slack:
<img width="508" alt="Screenshot 2019-12-16 at 14 12 01" src="https://user-images.githubusercontent.com/6195629/70913508-101a2000-200e-11ea-947a-33dc38960bcd.png">

Seen this on Alertmanager's dashboard:
<img width="693" alt="Screenshot_2019-12-16_at_14_12_54" src="https://user-images.githubusercontent.com/6195629/70913674-64bd9b00-200e-11ea-8c13-280c66ac4b40.png">

I am not sure why it's not evaluating `$labels.environment`. It's clearly defined in the alert rule's labels. Am I missing something?

**Environment**

* System information:
N/A

* Alertmanager version:
`v0.18.0`

* Prometheus version:
`v2.13.1`

* Alertmanager configuration file:
Nothing out of the ordinary. Just a receiver that sends a notification on Slack. You might not even need sending the notification on Slack as the issue is already visible from within the Alertmanager dashboard.

* Prometheus configuration file:
```
# Alert rule
groups:
- name: cert-manager
  rules:
  - alert: NoDeploymentReplicasForCertManagerComponent
    expr: kube_deployment_status_replicas{deployment=~"cert-manager.*"} < 1
    for: 2m
#    for: 1h
    labels:
      severity: warning
      environment: staging
    annotations:
      summary: "No deployment replicas for '{{ $labels.deployment }}' in the '{{ $labels.environment }}' environment"
      description: "Some description"
```

* Logs:
N/A
