### ISSUE TITLE
Alert on alertmanager_notifications_failed_total 

### ISSUE THREAD

**Issue by freeseacher** [prometheus/alertmanager#2147]
**What did you do?**
I have and alert for alertmanager_notifications_failed_total 
```
  - alert: AlertmanagerNotificationsFailing
    expr: sum (increase(alertmanager_notifications_failed_total[1m])) by (integration) !=0
    labels:
      priority: P1
      service: alertmanager
    annotations:
      summary: 'Alertmanager is failing sending notications to {{$labels.integration}}'
```

It look like it should work fine but it is not. It is okay to get failure several times. 
What am i actually looking for is some metric showing that alert cannot be sent to upstream and alertmanager give up doing it

Any ideas ?
May be along with route label it will be much helpfull.
