### ISSUE TITLE
Feature request: Hierarchical alert receivers based on time

### ISSUE THREAD

**Issue by Xindahuang** [prometheus/alertmanager#2150]
Alertmanager can repeat sending alert to receiver or multi-receivers. But it cannot re-send the same alert to other receivers like supervisor. This feature avoids bothering everyone and delaying to solving alerts.

**Comment by simonpasquier** [comment]
This looks more like the responsibility of an incident management system (eg Pager Duty, OpsGenie, ...).
You could still emulate something similar with `continue`:

```yaml
routes:
- match:
    alertname: test
  receiver: receiver1
  continue: true
- match:
    alertname: test
  receiver: receiver2
  group_wait: 1h
```
