### ISSUE TITLE
alertmanager continuously sending email notifications for same alert

### ISSUE THREAD

**Issue by ddevault** [prometheus/alertmanager#2157]
Note: I would have gone to the mailing list, but I'm not going to make a Google account just for this. Consider moving to a real mailing list, not a fake one run by the world's largest privacy disaster.

**What did you do?**

This is the relevant subset of my alertmanager config:

```
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 8h
  receiver: interesting
  routes:
  - match:
      severity: important
    receiver: important
    routes:
    - match:
        security: true
      receiver: important_secure
# ...
receivers:
- name: interesting
  webhook_configs:
  - url: 'http://127.0.0.1:8667/' # irc
    send_resolved: false
- name: important
  webhook_configs:
  - url: 'http://127.0.0.1:8667/' # irc
    send_resolved: false
  email_configs:
  - to: '~sircmpwn/sr.ht-ops@lists.sr.ht'
    html: null
    text: '{{template "__subject"}}'
- name: important_secure
  email_configs:
  - to: 'sir@cmpwn.com'
    html: null
    text: '{{template "__subject"}}'
```

The alert rule which caused this behavior was:

```
groups:
- name: meta.sr.ht
  rules:
  - alert: High rate of login failures
    expr: delta(meta_logins_failed_total[10m]) > 5
    labels:
      severity: important
      security: true
    annotations:
      summary: "Unusual number of failed logins"
```

**What did you expect to see?**

A single notification email.

**What did you see instead? Under which circumstances?**

One notification email every few seconds.

**Environment**

* System information: Linux 5.4.6-0-virt x86_64

* Alertmanager version: 0.19.0, go1.13.4

* Prometheus version: 2.15.1
