### ISSUE TITLE
tree editor label missing for odd number of receivers

### ISSUE THREAD

**Issue by zswanson** [prometheus/alertmanager#2159]
**What did you do?**
Utilizing https://prometheus.io/webtools/alerting/routing-tree-editor/ Added an odd number (3, 5, 7 etc) of receivers to a config and pressed 'draw routing tree'. Receiver labels for "one" and "two" and drawn, but "three" is not visible. A line is drawn 90 degrees down to the bottom of the browser page, and no label is present - not knowing any better, I thought this line was the 'entry point' into the tree. This led to a lot of confusion as I thought my routing was broken. 

This simple config snippet illustrates the problem, and will show the result for any odd number of receivers added.

```
route:
  receiver: default
  routes:
  - receiver: one
  - receiver: two
  - receiver: three
```

**What did you expect to see?**
Expected to see all receiver names drawn on the tree. 
**What did you see instead? Under which circumstances?**
When using an odd number of receivers, one element is always drawn at the bottom of the page and the name of the receiver is outside the rendered area.
**Environment**
Tested on chrome and firefox, both under MacOS 

* Alertmanager configuration file:
```
route:
  receiver: default
  routes:
  - receiver: one
  - receiver: two
  - receiver: three
```
