### ISSUE TITLE
Feature Request: Send new notification for every alert posted via the API

### ISSUE THREAD

**Issue by fredhaug** [prometheus/alertmanager#2175]
I want to utilize the silencing capabilities of AlertManager, but at the same time forward alerts directly to the configured receivers for every POST request to the /alerts endpoint. I don't think this is possible at the moment.

A possible solution might be to set "resolve_timeout" to 0 and omit a value for the "endsAt" request to the /alerts API, but I don't know if this will work properly.

Any ideas?

**Comment by simonpasquier** [comment]
Not sure what you're trying to accomplish exactly but it looks like a very niche feature. 

If you want to send every alert generated by Prometheus to an external system, the best option is properly to have Prometheus do it directly:

```yaml
...
alerting:
  alertmanagers:
  - static_configs:
    # send to alertmanager.
    - targets:
      - localhost:9093
    # send somewhere else.
    - targets:
      - foo.example.com:8080
...
```

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
