### ISSUE TITLE
Alert constantly dropping/reappearing

### ISSUE THREAD

**Issue by jdevilla20** [prometheus/alertmanager#2183]
Hi.  I have configured alertmanager.  Most alerts work fine.  However, I have one alert which keeps toggling on and off.  I am running all of this on a kubernetes cluster.  Is there a reason that this alert keeps dropping/re-alerting?

**What did you do?**
I have created an alert defined as the following:
```        - alert: LagMinutes
          expr: <expression which determines the lag> > 10
          for: 60m
```
This took 5-6 seconds to complete.  So I replaced the expression with a recording rule that takes .1 second to complete.

I post when the alert fires / resolves on a slack channel

**What did you expect to see?**
I expect messages to slack on the following conditions:
```
1) Alert fires
2) Alert resolves
3) Change in state of alert (elements added/removed from the alert)
```

**What did you see instead? Under which circumstances?**
Instead of seeing the above, the alert is constantly firing/resolving itself within a few minutes.  When I look at the alert manager, I see that the alert shows up, then disappears, then shows up again.

**Environment**

* System information:
```
	Linux 4.14.138+ x86_64
```
* Alertmanager version:

```
/alertmanager $ alertmanager --version
alertmanager, version 0.17.0 (branch: HEAD, revision: c7551cd75c414dc81df027f691e2eb21d4fd85b2)
  build user:       root@932a86a52b76
  build date:       20190503-09:10:07
  go version:   
```

* Prometheus version:
```
prometheus, version 2.12.0 (branch: HEAD, revision: 
43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
/prometheus $ 
```

* Alertmanager configuration file:
```
 resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
route:
  receiver: "null"
  group_by:
  - alertname
  - cluster
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog

  - receiver: ap2-ingestion-slack
    match:
      ownership: apollo-2-ingestion-slack


  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
- name: ap2-ingestion-slack
  slack_configs:
  - send_resolved: true
    http_config: {}
    api_url: <secret>
    channel: <channel>
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '{{ .GroupLabels.alertname }} on {{ .GroupLabels.cluster }}'
    title_link: '{{ template "slack.default.titlelink" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: "Summary: {{ .CommonAnnotations.summary}}\nDescription: \n{{ range .Alerts
      }}{{ .Annotations.description }}\nLink: {{ .Annotations.link }}\n {{ end }}"
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
```

* Prometheus configuration file:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    cluster: cortex-prd1-us
    prometheus: monitoring/prometheus-prometheus-oper-prometheus
    prometheus_replica: prometheus-prometheus-prometheus-oper-prometheus-1
```
