### ISSUE TITLE
Configuration option group_wait does not work

### ISSUE THREAD

**Issue by andrii29** [prometheus/alertmanager#2191]
**What did you do?**
Send test alert from prometheus to alertmanager
**What did you expect to see?**
Alertmanager should send alert after 10 minutes after received it

https://prometheus.io/docs/alerting/configuration/#route
How long to initially wait to send a notification for a group
of alerts. Allows to wait for an inhibiting alert to arrive or collect
more initial alerts for the same group. (Usually ~0s to few minutes.)
[ group_wait: <duration> | default = 30s ]

**What did you see instead? Under which circumstances?**
Alertmanager send alerts after ~30s
**Environment**
docker container
* System information:
Linux 4.4.0-164-generic x86_64
* Alertmanager version:
alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  go version:       go1.13.5

* Prometheus version:
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  go version:       go1.13.8

* Alertmanager configuration file:
```
route:
  receiver: stag
  group_by:
  - instance
  - alertname
  routes:
  - receiver: sns
    group_by:
    - severity
    match:
      severity: disaster
    continue: true
    group_wait: 10m
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 2h
```

* Prometheus configuration file:
```
```

* Logs:
```
level=debug ts=2020-02-20T11:50:54.639Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}/{severity=\"disaster\"}:{alertname=\"Web Probe Failing\", instance=\"http://test.com\"}" msg=flushing alerts="[Web Probe Failing[5bcebc5][active]]"
level=debug ts=2020-02-20T11:51:54.639Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}/{severity=\"disaster\"}:{alertname=\"Web Probe Failing\", instance=\"http://test.com\"}" msg=flushing alerts="[Web Probe Failing[5bcebc5][active]]"
level=debug ts=2020-02-20T11:52:24.638Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert="Web Probe Failing[5bcebc5][active]"
level=debug ts=2020-02-20T11:52:54.639Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}/{severity=\"disaster\"}:{alertname=\"Web Probe Failing\", instance=\"http://test.com\"}" msg=flushing alerts="[Web Probe Failing[5bcebc5][active]]"
```
