### ISSUE TITLE
Severity not being set in pagerduty eventv2 call

### ISSUE THREAD

**Issue by byang223** [prometheus/alertmanager#2193]
I would like to create a receiver that's a pagerduty integration with severity set to 'warning' and create low urgency incidents in pagerduty. I wanted to check in here to see if I can confirm that the severity field is being set in the event v2 api call before going to pagerduty 

**What did you do?**
I updated my receivers to the following
```
receivers:
    - name: 'alerts'
      pagerduty_configs:
      - service_key: ${MY_KEY}
        severity: 'warning'
```

I also updated my pagerduty service to triage warnings as low urgency incidents

**What did you expect to see?**
I expected the Pagerduty to assign low urgency incidents but that is not the case. 

In Pagerduty I can view the event message and I expect to see a "severity" key. However, it may be that they cut that off (?)

**What did you see instead? Under which circumstances?**
I clicked view event message and see the following

```
{
  "client": "AlertManager",
  "client_url": "$MY_URL",
  "description": "[FIRING:1] MyAlert (labels)",
  "event_type": "trigger",
  "incident_key": "$MY_INCIDENT_KEY",
  "service_key": "$MY_SERVICE_KEY",
  "details": {
    "resolved": "",
    "num_resolved": "0",
    "num_firing": "1",
    "firing": "Labels//Instanceinfo//ETC"
  }
}
```

No severity key

**Environment**

* System information:

`Linux 4.19.95-coreos x86_64`

* Alertmanager version:

`v0.20.0`

* Alertmanager configuration file:
```
  pagerduty_configs:
  - send_resolved: true
    service_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    severity: warning
```

* Alertmanager logs
```
level=debug ts=2020-02-21T17:46:07.829Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}/{severity=\"warning\"}:{alertname=\"$MY_ALERT\"}" msg=flushing alerts=[SkynetServerRestart[aa46d17][active]]
level=debug ts=2020-02-21T17:46:07.830Z caller=pagerduty.go:251 integration=pagerduty incident="{}/{severity=\"warning\"}:{alertname=\"$MY_ALERT\"}" eventType=trigger
```
