### ISSUE TITLE
Duplicate alerts in UI

### ISSUE THREAD

**Issue by bigon** [prometheus/alertmanager#2196]
Hello,

Since I added multiple routes (with a `continue: true`) I see my alerts in double in the UI of alertmanager (version 0.20.0)

I find old bugs, but if I understand well that should be fixed already

Edit: If I remove the `continue: true` they are not duplicated

```yaml
global:
  resolve_timeout: 5m
  smtp_from: 'noreply@example.com'
  smtp_smarthost: 'smtpintern.example.com:25'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email.all'
  routes:
    - receiver: 'email.all'
      continue: true
    - receiver: 'web.Hangout'
receivers:
- name: 'web.Hangout'
  webhook_configs:
  - url: 'http://localhost:6000/create?room_name=Prometheusalerts'
- name: 'email.all'
  email_configs:
  - to: 'bigon@example.com'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
```

**Comment by simonpasquier** [comment]
I agree it's confusing but at the same time, it's kind of expected since alerts matche the 2 groups. The UI could be improved to indicate that the groups are for different receivers.

Side-note, instead of using `continue: true` you can configure multiple integrations within one receiver like this:

```yaml
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'receiverA'
receivers:
- name: 'receiverA'
  webhook_configs:
  - url: 'http://localhost:6000/create?room_name=Prometheusalerts'
  email_configs:
  - to: 'bigon@example.com'
```

**Comment by bigon** [comment]
I could indeed use that, but now I expanded my route to the following and grouping the receivers like that would not work I guess

```yaml
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email.all'
  routes:
    - receiver: 'email.all'
      continue: true
    - receiver: 'web.HangoutPRD'
      match:
        vdab_env: 'PRD'
    - receiver: 'web.Hangout'
```

**Comment by simonpasquier** [comment]
You can still avoid `continue: true` and avoid duplication with YAML anchors.

```yaml
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  routes:
    - receiver: 'PRD'
      match:
        environment: 'PRD'
    - receiver: 'notPRD'
receivers:
- name: 'PRD'
  webhook_configs:
  - url: 'http://localhost:6000/create?room_name=PRD'
  email_configs: &email.all
  - to: 'bigon@example.com'
- name: 'notPRD'
  webhook_configs:
  - url: 'http://localhost:6000/create?room_name=Prometheusalerts'
  email_configs: *email.all
```
