### ISSUE TITLE
Alerts are not replicated over multiple alerts managers

### ISSUE THREAD

**Issue by jomach** [prometheus/alertmanager#2198]
**What did you do?**
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.36/bundle.yaml
Kubectl apply from:
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: internal-alertmanager
spec:
  replicas: 3
  image: quay.io/prometheus/alertmanager:v0.20.0
  logLevel: debug
```
**What did you expect to see?**
If I send one alert to one of the replicas of the alertmanager I expect that the alert is replicated to all alert managers in the UI. 

**What did you see instead? Under which circumstances?**
When I send one alert to one of alertmanager managers only that instance hows the alert on the ui. 
The others are empty.

**Environment**
  minikube
* System information:
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff

* Alertmanager version:

	0.20

* Alertmanager configuration file:
ha mode from the prometheus operator

Note: The silences get replicated, what I don't know is if the silences are being replicated over gossip (UDP) 

Question is: Is this a wanted behaviour ?
