### ISSUE TITLE
Slack Blocks Notifications

### ISSUE THREAD

**Issue by mambax** [prometheus/alertmanager#2217]
Hi Prometheus

Currently [`<slack-config>`](https://prometheus.io/docs/alerting/configuration/#slack_config) is using [Simple formatting](https://api.slack.com/reference/surfaces/formatting).

This is marked by Slack themselves as `deprecated` (or at least most hints dropped say: Format using Block Kit).

The new way to go seems to be [Block-Kit](https://api.slack.com/block-kit).

I don't want to ask "Is there a plan?" as this would be a question. I'd like to pose as feature request to add something like:

`<slack_config_blocks>`
which would then accept stuff like:

![image](https://user-images.githubusercontent.com/5472171/77641279-16e4f700-6f5c-11ea-8972-95e947c60f9d.png)

And configuration like so (I am new to Yaml and Go Tmpl):
```
blocks:
- type: section
  text:
    type: mrkdwn
    text: ":fire: `Critical` alert in *production*: `ELK running out of shards (2
      left)`"
- type: section
  fields:
  - type: mrkdwn
    text: |-
      *Value before:*
      22
  - type: mrkdwn
    text: |-
      *Value now:*
      2
  - type: mrkdwn
    text: |-
      *Action:*
      Contact operations.
  - type: mrkdwn
    text: |-
      *Outcome:*
      X will happen.
- type: actions
  elements:
  - type: button
    text:
      type: plain_text
      emoji: true
      text: Victorops
    style: primary
    value: click_me_123
  - type: button
    text:
      type: plain_text
      emoji: true
      text: Silence
    style: danger
    value: click_me_123
```
Obvisouly my hardcoded strings would be replaced by `{{ .alertProperties }}`

Adding this I believe would make our DevOps plans (and hopefully others) dreams come true ❤️

**Comment by simonpasquier** [comment]
I'm worried that the configuration schema might quickly get out of control. But there's nothing preventing someone to try to come up with something reasonable.

**Comment by vanugrah** [comment]
Block kit makes formatting of messages SO much cleaner. If I could +1000 I would :)

**Comment by KarthikRangaraju** [comment]
+1 The possibilities are endless. These are all the things we can do: https://app.slack.com/block-kit-builder/T091CRSGH#%7B%22blocks%22:%5B%5D%7D

**Comment by niko2** [comment]
[Simple Formatting](https://api.slack.com/reference/surfaces/formatting) seems to be broken on Slack Desktop (at least for buttons).
Since  there is no more Slack support, this formatting could be completely broken soon.

**Comment by johanfleury** [comment]
Hey, I’m willing to make a PR for that.

I see two ways of doing that:

* `blocks` field in `slack_config` is a `tmpl_string` that must render the JSON object sent to slack:
```
blocks: >
  {
    "type": "header",
    "text": {
      "type": "plain_text",
      "text": "{{ template "slack.default.title" . }}",
      "emoji": true
    }
  },
  {{ range .Alerts.Firing }}
  {
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": "*Alert:* '{{ .Annotations.SUMMARY }} - `{{ .Labels.severity }}`'\n*Description:* '{{ .Annotations.DESCRIPTION }}'"
    }
  }, # Find a way to deal with comma after last block
  {{ end }}
```

* `blocks` field in `slack_config` is a complex object that replicate Slack API with added options like `repeat_for`:
```yaml
blocks:
  - type: header,
    text:
      type: plain_text
      text: '{{ template "slack.default.title" . }}',
  - type: section
    text:
      type: mrkdwn
      text: >-
        *Alert:* '{{ .Annotations.SUMMARY }} - `{{ .Labels.severity }}`'
        *Description:* '{{ .Annotations.DESCRIPTION }}'
      repeat_for: firing # Could be firing, resolved or all
```

As an administrator I prefer option 2, I find it clearer, but it’s **way** more work to implement it and it’s less flexible than option 1.

What do you think?

**Comment by tom0010** [comment]
I think it would make sense to go with the yaml formatting, just like @mambax said. With @johanfleury's option 2, it's like yaml, but doesn't seem to be valid as such. The comma's are not needed, hence why I said about @mambax's comment.

**Comment by johanfleury** [comment]
It was just bad copy/paste, I fixed the snippets.

**Comment by IppX** [comment]
@johanfleury I like your first approach for 3 reasons:
- as a user of this feature, I'll need to get familiar with the slack API and block features anyway. The best way to do so is to use the build kit viewer and get my formatting straight first and then I can just copy paste it here and add the necessary golang templating.
- it's more flexible regarding slack API changes.
- since it's easier to implement it would enable us to have the feature earlier.

**Comment by tom0010** [comment]
@IppX you are right about the JSON formatting being similar to the block kit builder, however there would be loops and variables in there payload anyway so you would still have to edit the payload, copy and paste would be invalid. `blocks` is also a list, whereas the JSON version does not really account and inform the user about it being a list, the YAML version does.
Option 2 also keeps the formatting the same, the Prometheus config is actually in YAML, so it would mean we would have a JSON string inside of a YAML file. 
IMO it makes more sense to keep the whole YAML file, in YAML. 
There are also various tools that do JSON to YAML conversion online, so that isn't really a problem regarding the block kit builder.

**Comment by johanfleury** [comment]
I started working on option 2 and I’m facing a bunch of issues (explaining below) and I think option 1 is a better option if we want to keep code clean.

> Option 2 also keeps the formatting the same, the Prometheus config is actually in YAML, so it would mean we would have a JSON string inside of a YAML file.

I definitely agree with that, I’d also rather have everything in YAML, but as I suspected when writing my first comment, this is a lot of work.

---

Now, regarding the issues I’m facing with option 1.

I don’t want to have to rewrite every block types, so I started creating a “generic” block type:

```go
type SlackConfig struct {
	// ...
	Blocks []*SlackBlock `yaml:"blocks,omitempty" json:"blocks,omitempty"`
	//...
}

type SlackBlock struct {
	RepeatFor string                 `yaml:"repeat_for,omitempty" json:"repeat_for,omitempty"`
	Config    map[string]interface{} `yaml:"config,omitempty" json:"config,omitempty"`
}
```

This would translate to a config that looks like that:

```yaml
slack_configs:
  - ...
    blocks:
      - config:
          type: header
          text:
            type: plain_text
            text: '{{ template "slack.default.title" . }}'
      - repeat_for: firing # Could be firing, resolved or all
        config:
          type: section
          text:
            type: mrkdwn
            text: >-
              *Alert:* '{{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* '{{ .Annotations.description }}'
```

Problem is, when go-yaml is parsing that config it unmarshals any maps (e.g. `config.text`) as a `map[interface{}]interface{}` which Go’s `encoding/json` cannot marshal back to json (see https://go.dev/play/p/486JtJW9Sjw).

This also brings issue with templating as we now need to recurse over the whole map to find any string value and apply the templating function.

Also, template’s context inside blocks with `repeat_for` will be different to any other templates (you would only have access to [Alert’s fields](https://pkg.go.dev/github.com/prometheus/alertmanager@v0.23.0/template#Alert) and not the whole [data](https://pkg.go.dev/github.com/prometheus/alertmanager@v0.23.0/template#Data)).

To be honest, I’m really not sure if there’s a way to keep both the code and the config clean at the same time.

I’ll create a draft PR for this option if someone wants to look at it, but I feel like it’s too messy and a bit too much work.
