### ISSUE TITLE
"repeat_interval=24h" but alertmanager starts to ignore it

### ISSUE THREAD

**Issue by Canavell** [prometheus/alertmanager#2220]
I set repeat_interval to 24h value and it works fine at least a couple of days. But after 3 days sometimes it starts to send me emails much often then 24h ours (about 3-4 emails every 5 minutes and then goes to sleep) about one unresolved warning related issue.

**I run docker containers.**

* System information (host machine):

`
Linux 3.10.0-693.11.6.el7.x86_64 x86_64
`

* Alertmanager version:

```
alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5
```

* Prometheus version:
```
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8
```

* Alertmanager configuration file:
```
global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "my@gmail.com"
  smtp_auth_username: "my@gmail.com"
  smtp_auth_password: "mypassword"

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h 
  receiver: team-base

receivers:
  - name: 'team-base'
    email_configs:
    - to: "me@gmail.com"
      send_resolved: true
    - to: "my_coworker@gmail.com"
      send_resolved: true
```

* Prometheus configuration file:

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s 
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus-local'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor-local'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter-local'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-exporter-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['service-url.ru:9113']

  - job_name: 'apache-exporter-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['service-url.ru:9117']

  - job_name: 'blackbox-https-service'
    metrics_path: /probe
    params:
      module:
        - https_200_module
    static_configs:
      - targets:
        - http://service-url.ru
        - https://service-url.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: service-url.ru:9115

  - job_name: 'process-exporter-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['service-url.ru:9256']


```

* Logs:

Unfortunately, I've recreated my containers and my logs are gone... It helps to temporarily resolve my issue for about 3 days when I recreate containers.

**Comment by Canavell** [comment]
![IMG_20200331_011604](https://user-images.githubusercontent.com/18348451/77967304-86a50a00-72ed-11ea-8b96-136e029a9233.jpg)

I expected to get this alerts one time at the day because they are not resolved. But I got 4 groupped alerts for one day.

**Comment by Canavell** [comment]
Ok, it happened again and I have some logs and screenshots.

Please pay attention to "SslCertificateWillExpireSoon" alerts, they are my headache. 
**I expected** to see one firing alert with SSL expiration info today at 22:05 (24 hours after last same alert), but **I got** three alerts at 13:47 (with firing status, it had come 8 hours earlier than should), at 13:45 (with wrong resolved status) and 13:52 (firing).

How you can see alerts ignore repeat_interval and one alert was with the wrong label "Resolved", but It wasn't resolved actually :) And after wrong "resolved" alert I've got one with firing again. 

First one:
![Screenshot_20200331_141920](https://user-images.githubusercontent.com/18348451/78020962-07e6b600-735b-11ea-8715-63deedab1913.png)



Second one (demonstrates misbehaviour)
![Screenshot_20200331_142056](https://user-images.githubusercontent.com/18348451/78020960-06b58900-735b-11ea-9b6b-8a89d708360d.png)


```
alertmanager --log.level=debug

level=info ts=2020-03-31T11:14:23.294Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
level=info ts=2020-03-31T11:14:23.294Z caller=main.go:232 build_context="(go=go1.13.5, user=root@00c3106655f8, date=20191211-14:13:14)"
level=debug ts=2020-03-31T11:14:23.294Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=
level=info ts=2020-03-31T11:14:23.295Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=192.168.144.3 port=9094
level=debug ts=2020-03-31T11:14:23.295Z caller=cluster.go:306 component=cluster memberlist="2020/03/31 11:14:23 [DEBUG] memberlist: Got bind error: Failed to start TCP listener on \"0.0.0.0\" port 9094: listen tcp 0.0.0.0:9094: bind: address already in use\n"
level=error ts=2020-03-31T11:14:23.295Z caller=main.go:256 msg="unable to initialize gossip mesh" err="create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 9094: listen tcp 0.0.0.0:9094: bind: address already in use"

```

And here:

```
 docker logs alertmanager
level=info ts=2020-03-30T18:59:55.054Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
level=info ts=2020-03-30T18:59:55.054Z caller=main.go:232 build_context="(go=go1.13.5, user=root@00c3106655f8, date=20191211-14:13:14)"
level=info ts=2020-03-30T18:59:55.056Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=192.168.144.3 port=9094
level=info ts=2020-03-30T18:59:55.096Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2020-03-30T18:59:55.158Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config.yml
level=info ts=2020-03-30T18:59:55.161Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config.yml
level=info ts=2020-03-30T18:59:55.169Z caller=main.go:497 msg=Listening address=:9093
level=info ts=2020-03-30T18:59:57.096Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000096701s
level=info ts=2020-03-30T19:00:05.113Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.017762956s

```

**Comment by alexjuchina** [comment]
pay attention to the labels. Even small difference will send new alerts.

**Comment by Canavell** [comment]
So I solved the problem by removing from prometheus.yml these lines 

```
  scrape_interval:     15s
  evaluation_interval: 15s 
```
And I removed these lines from targets
`
scrape_interval: 5s
`

Everything works fine now.

**Comment by simonpasquier** [comment]
It's hard to say more without seeing the alerting rule. As @alexjuchina noted, any difference in the alert labels will trigger a new notification.

I'm closing it for now. Feel free to reopen with more details if it happens again.

**Comment by Canavell** [comment]
Today this happend again :) about 10 minutes ago. As @simonpasquier mentioned I attach alert rule: 
```
  - alert: SslCertificateWillExpireSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "SSL certificate will expire soon (instance {{ $labels.instance }})"
      description: "SSL certificate expires in 30 days\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

It reproduces only with SslCertificateWillExpireSoon. My other rules:

```
groups:
- name: example
  rules:

  # Alert for any instance that is unreachable for >2 minutes.
  - alert: ServiceIsDown
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

  - alert: OutOfDiskSpace
    expr: 100 - ((node_filesystem_avail_bytes{mountpoint!~"/boot|/boot/efi", device!~'rootfs',fstype!="rootfs"} * 100) /  node_filesystem_size_bytes{mountpoint!~"/boot|/boot/efi", device!~'rootfs',fstype!="rootfs"}) < 10
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Out of disk space (instance {{ $labels.instance }})"
      description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  
  - alert: SslCertificateWillExpireSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "SSL certificate will expire soon (instance {{ $labels.instance }})"
      description: "SSL certificate expires in 30 days\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      
  - alert: SslCertificateExpired
    expr: probe_ssl_earliest_cert_expiry - time()  <= 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "SSL certificate expired (instance {{ $labels.instance }})"
      description: "SSL certificate has expired already\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: ProbeFailed
    expr: probe_success == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Probe failed (instance {{ $labels.instance }})"
      description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: DiskWillFillIn7Days
    expr: predict_linear(node_filesystem_avail_bytes{mountpoint!~"/boot|/boot/efi", device!~'rootfs',fstype!="rootfs"}[24h], 7*24*3600) <= 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Disk will fill in 7 days (instance {{ $labels.instance }})"
      description: "Disk will fill in 7 days at current write rate\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: ServerUnderHighLoad
    expr: avg(node_load5{job!="node-exporter-local"}) by (instance) / count(count(node_cpu_seconds_total{job!="node-exporter-local"}) by (cpu, instance)) by (instance) * 100 > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Server under high load"
      description: "Docker host is under high load, the avg load 5m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: SwapIsFillingUp
    expr: (((node_memory_SwapTotal_bytes-node_memory_SwapFree_bytes)/node_memory_SwapTotal_bytes)*100) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Swap is filling up (instance {{ $labels.instance }})"
      description: "Swap is filling up (>90%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HighCpuLoad
    expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU load (instance {{ $labels.instance }})"
      description: "CPU load is > 90%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: MysqlIsDown
    expr: mysql_up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Critical: MySQL is down on the host {{ $labels.instance }}."
      description: "MySQL has been down for more than 30 seconds"

  - alert: MysqlTooMuchConnections
    expr: (mysql_global_status_max_used_connections / mysql_global_variables_max_connections) * 100 > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Warning: MySQL connections utilization (>90%) on the host {{ $labels.instance }}"
      description: "MySQL connections utilization is {{ humanize $value}}%"
 
  - alert: MysqlTooMuchActiveThreads
    expr: mysql_global_status_threads_running > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Warning: MySQL active threads (>100) on the host {{ $labels.instance }}"
      description: "MySQL active threads is {{ humanize $value}}"

  - alert: OutOfMemory
    expr: ((node_memory_MemTotal_bytes) - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / (node_memory_MemTotal_bytes) * 100 > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: NginxIsDown
    expr: nginx_up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Critical: Nginx is down on the host {{ $labels.instance }}."
      description: "Nginx has been down for more than 30 seconds"

  - alert: NginxNotAllConnectionsAreHandled
    expr: rate(nginx_connections_handled[5m]) / rate(nginx_connections_accepted[5m]) <1 
    for: 2m
    labels:
      severity: warning
    annotations:
      description: "Warning: Nginx does not handle all accept connections on the host {{ $labels.instance }} for more than 3 minutes"
      summary: "Nginx issue with handling connections"

  - alert: NginxHighActiveConnections
    expr: nginx_connections_active > 3000
    for: 3m
    labels:
      severity: warning
    annotations:
      description: "Warning: Nginx high number active connections on the host {{ $labels.instance }} for more than 3 minutes"
      summary: "Nginx high number active connections"

  - alert: ApacheIsDown
    expr: apache_up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Critical: Apache is down on the host {{ $labels.instance }}."
      description: "Apache has been down for more than 30 seconds"

  - alert: SiteIsVerySlow
    expr: sum by (instance) (probe_http_duration_seconds) > 3
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "Warning: Site '{{ $labels.instance }}' is very slow(>3s) for more than 3 minutes"
      description: "Site {{ $labels.instance }} response for {{ humanize $value}}s"

  - alert: HostUnusualNetworkThroughputIn
    expr: sum by (instance) (irate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual network throughput in (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably receiving too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HostUnusualNetworkThroughputOut
    expr: sum by (instance) (irate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual network throughput out (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably sending too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HostUnusualDiskReadRate
    expr: sum by (instance) (irate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual disk read rate (instance {{ $labels.instance }})"
      description: "Disk is probably reading too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HostUnusualDiskWriteRate
    expr: sum by (instance) (irate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual disk write rate (instance {{ $labels.instance }})"
      description: "Disk is probably writing too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HostUnusualDiskReadLatency
    expr: rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual disk read latency (instance {{ $labels.instance }})"
      description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HostUnusualDiskWriteLatency
    expr: rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual disk write latency (instance {{ $labels.instance }})"
      description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: MysqlSlowQueries
    expr: rate(mysql_global_status_slow_queries[5m]) or irate(mysql_global_status_slow_queries[5m]) >= 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MySQL slow queries (instance {{ $labels.instance }})"
      description: "MySQL server is having some slow queries.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

**Comment by simonpasquier** [comment]
What do you get if you query for `ALERTS{alertname="SslCertificateWillExpireSoon"}` in the Prometheus UI?

**Comment by Canavell** [comment]
![Screenshot_20200410_214232-1](https://user-images.githubusercontent.com/18348451/79014848-65a5aa00-7b74-11ea-906e-17f90bb525e8.png)
![Screenshot_20200410_214256](https://user-images.githubusercontent.com/18348451/79014944-92f25800-7b74-11ea-89ac-bb221442aad7.png)
It was "pending" for a little while today...

**Comment by simonpasquier** [comment]
If the alert went pending again then at some point, the alert got resolved and Alertmanager correctly notified the resolution. I'm not sure why the alert went from firing to resolved but it doesn't look like an Alertmanager's problem.

**Comment by Canavell** [comment]
> If the alert went pending again then at some point, the alert got resolved and Alertmanager correctly notified the resolution. I'm not sure why the alert went from firing to resolved but it doesn't look like an Alertmanager's problem.

@simonpasquier, I changed "for" time in my rule to 10 minutes and my rule looks like that now:

```
 - alert: SslCertificateWillExpireSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
    for: **10m**
    labels:
      severity: warning
    annotations:
      summary: "SSL certificate will expire soon (instance {{ $labels.instance }})"
      description: "SSL certificate expires in 30 days\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
And I have no problems at this point. I don't know why this works, but it does. Evertying is fine at least 5 or 6 days.
