### ISSUE TITLE
Duplicate alerts returned by alertmanager API

### ISSUE THREAD

**Issue by c-stefan** [prometheus/alertmanager#2233]
**What did you do?**

I'm trying to send same alert to multiple receivers, grouping by same labels.
For the test purpose I posted the config file and a basic test alert.

It seems that the Alertmanager GUI but also the API returns same alert 2 times, one for each receiver?

* System information:

uname -srm
Linux 5.3.0-42-generic x86_64

* Alertmanager version:

alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5

* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m

route:
  group_by: [alertname, instance, job]
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1h

  receiver: 'blackhole'

  routes:
  - receiver: 'blackhole'
    group_wait: 1m
    group_interval: 1m
    repeat_interval: 1h
    match:
      alertname: DeadMansSwitch

  - receiver: 'blackhole1'
    group_by: [alertname, instance, job]
    group_wait: 1m
    group_interval: 1m
    repeat_interval: 1h
    continue: true
    match_re:
      receivers: .*(pagerduty).*
      severity: .*(critical).*
      resolved: .*(yes).*

  - receiver: 'blackhole2'
    group_by: [alertname, instance]
    group_wait: 1m
    group_interval: 1m
    repeat_interval: 1h 
    match_re:
      receivers: .*(slack).*
      severity: .*(critical).*
      resolved: .*(yes).*
  
receivers:

- name: 'blackhole'
  webhook_configs:

- name: 'blackhole1'
  webhook_configs:

- name: 'blackhole2'
  webhook_configs:
```

*Test alert:
```
testAlert='
[
   {
      "labels":{
         "alertname":"TEST122",
         "alias":"TEST",
         "category":"infrastructure",
         "description":"TEST",
         "env":"dev",
         "instance":"dev22-web",
         "job":"phpfpm",
         "receivers":"slack|pagerduty",
         "resolved":"yes",
         "severity":"critical",
         "uuid":"bAuFfhGW"
      },
      "annotations":{
         "description":"TEST.",
         "summary":"TEST.",
         "runbook": "URL"
      },
      "generatorURL":"URL"
   }
]'
 
 
while true; do
curl -XPOST -H "Authorization: Bearer mysecret" -H "User-Agent: Prometheus/2.14.0" -H "Content-Type: application/json" -d"$testAlert" http://127.0.0.1:9093/api/v1/alerts
sleep 20
done

```

* Logs:
```
level=debug ts=2020-04-15T13:17:19.995Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TEST122[c5db48d][active]
level=debug ts=2020-04-15T13:17:40.005Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TEST122[c5db48d][active]
level=debug ts=2020-04-15T13:18:00.014Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TEST122[c5db48d][active]

```
```
curl -s -XGET -H "Content-Type: application/json" http://127.0.0.1:9093/alertmanager/api/v2/alerts/groups | jq .
[
  {
    "alerts": [
      {
        "annotations": {
          "description": "TEST.",
          "runbook": "URL",
          "summary": "TEST."
        },
        "endsAt": "2020-04-15T16:35:36.500+03:00",
        "fingerprint": "125d2b1884ab0586",
        "receivers": [
          {
            "name": "blackhole1"
          },
          {
            "name": "blackhole2"
          }
        ],
        "startsAt": "2020-04-15T16:34:36.500+03:00",
        "status": {
          "inhibitedBy": [],
          "silencedBy": [],
          "state": "active"
        },
        "updatedAt": "2020-04-15T16:34:36.500+03:00",
        "generatorURL": "URL",
        "labels": {
          "alertname": "TEST122",
          "alias": "TEST",
          "category": "infrastructure",
          "description": "TEST",
          "env": "dev",
          "instance": "dev22-web",
          "job": "phpfpm",
          "receivers": "slack|pagerduty",
          "resolved": "yes",
          "severity": "critical",
          "uuid": "bAuFfhGW"
        }
      }
    ],
    "labels": {
      "alertname": "TEST122",
      "instance": "dev22-web"
    },
    "receiver": {
      "name": "blackhole2"
    }
  },
  {
    "alerts": [
      {
        "annotations": {
          "description": "TEST.",
          "runbook": "URL",
          "summary": "TEST."
        },
        "endsAt": "2020-04-15T16:35:36.500+03:00",
        "fingerprint": "125d2b1884ab0586",
        "receivers": [
          {
            "name": "blackhole1"
          },
          {
            "name": "blackhole2"
          }
        ],
        "startsAt": "2020-04-15T16:34:36.500+03:00",
        "status": {
          "inhibitedBy": [],
          "silencedBy": [],
          "state": "active"
        },
        "updatedAt": "2020-04-15T16:34:36.500+03:00",
        "generatorURL": "URL",
        "labels": {
          "alertname": "TEST122",
          "alias": "TEST",
          "category": "infrastructure",
          "description": "TEST",
          "env": "dev",
          "instance": "dev22-web",
          "job": "phpfpm",
          "receivers": "slack|pagerduty",
          "resolved": "yes",
          "severity": "critical",
          "uuid": "bAuFfhGW"
        }
      }
    ],
    "labels": {
      "alertname": "TEST122",
      "instance": "dev22-web",
      "job": "phpfpm"
    },
    "receiver": {
      "name": "blackhole1"
    }
  }
]

```
