### ISSUE TITLE
Alertmanager alerts with a ($) value that is below the threshold

### ISSUE THREAD

**Issue by johan974** [prometheus/alertmanager#2241]
**What did you do?**

We use a Prometheus alert (and node-exporter) to check whether we are running out of memory on a node. 

Issue: In many cases I get an alert with a $value that is below the threshold value in the expression. The expression is:

This is the alert code / expression: 
```
    alert: GettingOutOfMemory
    expr: max(sum
      by(instance) ((((node_memory_MemTotal_bytes) - (node_memory_MemFree_bytes + node_memory_Buffers_bytes
      + node_memory_Cached_bytes)) / (node_memory_MemTotal_bytes)) * 100)) >= 90
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Docker Swarm node {{ $labels.instance }} memory usage is at {{ humanize $value}}%.
      summary: Memory is getting low for Swarm node '{{ $labels.node_name }}'
```

I get messages saying that we ran out of memory at e.g. 63%. So that is the value of the $value. This is clearly below the 90% threshold.

**What did you expect to see?**

I expect only alerts when the threshold is exceeded. So below the expression of 90 I only expect alerts with a $value at or above 90. 

**What did you see instead? Under which circumstances?**

Nearly each time (every 4 hours) I see alert messages having a $value of 63%, 83%, etc. 

**Environment**

Prometheus Docker. 

* System information:

* Alertmanager version:

	insert output of `alertmanager --version` here

* Prometheus version:

Build information (docker version): 2.17.1

* Alertmanager configuration file:
```
See above. 
```

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: monitoring
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    path_prefix: /alertmanager
    timeout: 10s
    api_version: v1
rule_files:
- /etc/prometheus/alert.rules

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /prometheus/metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  dns_sd_configs:
  - names:
    - tasks.node-exporter
    refresh_interval: 30s
    type: A
    port: 9100

```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
