### ISSUE TITLE
Feature Request: metric matcher enhancement

### ISSUE THREAD

**Issue by OhBonsai** [prometheus/alertmanager#2249]
At present, there are only two kind of matcher
- matcher
- regex match

Although regular expressions can be used to represent complex matching logic. But It will
bring the following problems

- **slow:**  If i wanna to express `or`, the only way I can do is set regex match `(one|two)`, regex is slow 😢 
- **unfriendly:**  In many case, alarm setting are used by non-technical personal. Writing regular expressions with then is like asking then to do a science experiment 😭  

**What did you expect to see?**

##### Plan a: match_expression
```
match:
    __expression: "label1 = 'abc' and label2 != 3 or label3 ~= '^hello$' and (not label4 > 5)"
```

##### Plan b: match_condition (I think it's better)

Firstly, Add some compare operator 
- equal: 
- contain
- regexp
- lt
- lte
- gt
- gte
- has_field

And bool operator 
- or
- and
- not

So a complex match will be like 
```
match:
    label1: abc
    and:
         contain:
              label2: a
         has_field: 
              - label7
              - label8
```

**Is this feature worth doing?**  We are willing work on this issue 😄
