### ISSUE TITLE
GET /silences API filters out regex silences counter-intuitively

### ISSUE THREAD

**Issue by ajalab** [prometheus/alertmanager#2283]
**What did you do?**

![913bfc7371918b1772cc721605ff6974](https://user-images.githubusercontent.com/276860/83937571-b6e6b880-a808-11ea-8470-5fbe037b4122.gif)

I created two silences in Alertmanager UI

- `alertname=~(foo|bar)`
- `alertname=baz`

and tried to filter them out by clicking each label (internally it uses `GET /api/v2/silences` API).

**What did you expect to see?**

When we click `alertname=~(foo|bar)` label, it should show the list of silences which have the corresponding matcher, as it does so when we click `alertname=baz` label.

**What did you see instead? Under which circumstances?**

When we click `alertname=~(foo|bar)` label, it doesn't show silences that have the corresponding label (as shown in the screen capture).

---

In [`api.gettableSilenceMatchesFilterLabels`](https://github.com/prometheus/alertmanager/blob/12da9d6570ce0f487f98eed1be32e9c7e53da6b1/api/v2/api.go#L641), it judges whether a silence passes a filter by checking that the silence label value as a raw text matches the filter value as a regex pattern. That is, it checks whether a text `(foo|bar)` matches the regex pattern `(foo|bar)`, but obviously it doesn't.

IMO the right behavior should be that it won't use regex match but only checks the equivalence of labels, values, and the use of regex between a silence and a filter. I'm willing to fix the issue but also would like to discuss the way to fix here (or ML).

---

**Environment**

* System information:

```
$ uname -srm
Darwin 19.4.0 x86_64
```

* Alertmanager version:

```
$ docker run  prom/alertmanager --version
alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5
```

* Alertmanager configuration file:

<details>
<summary>
alertmanager.yml
</summary>
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: web.hook
  group_by:
  - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - dev
  - instance
receivers:
- name: web.hook
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://127.0.0.1:5001/
templates: []
```
</details>
