### ISSUE TITLE
Notification failures metric doesn't increase when templating fails

### ISSUE THREAD

**Issue by chancez** [prometheus/alertmanager#2301]
**What did you do?**

I wrote an invalid Go template in my alertmanager config, and upon trying to send the alert notification, alertmanager produced errors in it's logs like so:

```
level=error ts=2020-06-16T17:03:01.483Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: failed to template PagerDuty v2 message: template: :2: unexpected \")\" in input"
```

**What did you expect to see?**

I expected these logs, and the `alertmanager_notifications_failed_total` metric to be incremented.

**What did you see instead? Under which circumstances?**

The `alertmanager_notifications_failed_total` is 0 for all integrations/instances.

**Environment**

* Alertmanager version:

`v0.20.0`

* Prometheus version:

This was using Grafana to send alerts to Alertmanager, but how the alert is sent shouldn't matter much.

* Alertmanager configuration file:
```
templates:
  - '*.tmpl'
global:
  resolve_timeout: 5m
route:
  group_interval: 5m
  group_wait: 30s
  repeat_interval: 12h

  receiver: test

receivers:
  - name: "test"
    pagerduty_configs:
      - send_resolved: true
        routing_key: $(INFRA_PAGERDUTY_ROUTING_KEY)
        url: https://events.pagerduty.com/v2/enqueue
        details:
          # this had a few mistakes, eg the extra unmatched )
          test: '{{ if (index .Alerts.Firing 0).Annotations.image) }} {{ (index .Alerts.Firing 0).Annotations.image) }} {{ end }}'
```

* Logs:

```
level=error ts=2020-06-16T17:02:46.842Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: failed to template PagerDuty v2 message: template: :2: unexpected \")\" in input" context_err=null
level=error ts=2020-06-16T17:02:46.842Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: failed to template PagerDuty v2 message: template: :2: unexpected \")\" in input"
level=error ts=2020-06-16T17:03:01.483Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: failed to template PagerDuty v2 message: template: :2: unexpected \")\" in input" context_err=null
level=error ts=2020-06-16T17:03:01.483Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: failed to template PagerDuty v2 message: template: :2: unexpected \")\" in input"

```
