### ISSUE TITLE
[Proposal] Change Config Format

### ISSUE THREAD

**Issue by bigangryrobot** [prometheus/alertmanager#2302]
### **Problem**
One of the largest hindrances to enabling end user additions or modifications to alertmanager is that it has a single pipeline for its alerts which is stored as a single file. This forces teams to implement work arounds like running many alertmanagers, or mutating the configuration with external config management systems. Further evidenced here within the prometheus-operator project and the work arounds they are attempting to accommodate this

https://github.com/coreos/prometheus-operator/issues/2927
https://github.com/coreos/prometheus-operator/issues/2766
https://github.com/coreos/prometheus-operator/issues/1528
https://github.com/coreos/prometheus-operator/issues/1498
https://github.com/coreos/prometheus-operator/issues/2957

Currently this single file design of alertmanager creates one alert route that then branches off with additional routes, and separate inhibition rules that act at a global level. This design allows for rules to easily clobber other routes if the continue flag is not set to true, and inhibit rules incorrectly applied can do similar.

### **Proposal**
Multi(branch) the routes!
![multipass](https://cdn.instructables.com/FJQ/0XEF/IEB8CSUQ/FJQ0XEFIEB8CSUQ.LARGE.jpg?auto=webp&frame=1&width=300&height=300&fit=bounds)
* The alerting pipeline should flow freely, like a stream that configs can tap into
* There is no "one" root route, but instead multiple that never interact
* Configs for the route, inhibition, and receivers should be configurable inline as they are currently OR by file inclusion similar to how prometheus does this
* Inhibition rules are tied to the route branch that they target and not global

### **Specific changes**
root route called out with a **name field**
```
route:
  name: 'route-team1'
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [cluster, alertname]
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.
  routes:
  # All alerts with service=mysql or service=cassandra
  # are dispatched to the database pager.
  - receiver: 'database-pager'
    group_wait: 10s
    match_re:
      service: mysql|cassandra
  # All alerts with the team=frontend label match this sub-route.
  # They are grouped by product and environment rather than cluster
  # and alertname.
  - receiver: 'frontend-pager'
    group_by: [product, environment]
    match:
      team: frontend
```
inhibit now has a **target_route** that signifies which route root to apply to
```
inhibit:
  target_route: 'route-team1'
  # Matchers that have to be fulfilled in the alerts to be muted.
  target_match:
    [ <labelname>: <labelvalue>, ... ]
  target_match_re:
    [ <labelname>: <regex>, ... ]
  
  # Matchers for which one or more alerts have to exist for the
  # inhibition to take effect.
  source_match:
    [ <labelname>: <labelvalue>, ... ]
  source_match_re:
    [ <labelname>: <regex>, ... ]
  
  # Labels that must have an equal value in the source and target
  # alert for the inhibition to take effect.
  [ equal: '[' <labelname>, ... ']' ]
```

I've forked the code and am willing / have started to complete the work if there is agreement on this design direction. I need this in many production areas right now (45 alertmanagers deployed globally) so im fairly motivated to iron this out
