### ISSUE TITLE
amtool throws error 'field hipchat_api_url not found'

### ISSUE THREAD

**Issue by samuelb** [prometheus/alertmanager#2307]
**What did you do?**

`amtool config routes test --alertmanager.url=http://...`

**What did you expect to see?**

The usual output like:
```
Testing alert routes, script exits with 1 if a route does not match
victorops_default,slack_default,alert_stream
slack_default,alert_stream
```

**What did you see instead? Under which circumstances?**

amtool throws following error:
```
Testing alert routes, script exits with 1 if a route does not match
amtool: error: yaml: unmarshal errors:
  line 7: field hipchat_api_url not found in type config.plain

amtool: error: yaml: unmarshal errors:
  line 7: field hipchat_api_url not found in type config.plain
```
... and exits with exit code 1. 

We don't use the HipChat integration. It's nowhere mentioned in configuration.

It's probably related to the recent removal of HipChat from alertmanager: https://github.com/prometheus/alertmanager/pull/2281

With the release v0.20.0 of alertmanager there was no issue. The issue appeared with v0.21.0.

**Environment**

* System information:

- Linux 4.9.0-12-amd64 x86_64
- Darwin 19.5.0 x86_64

* Alertmanager version:

```
alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5
```

amtools was installed with `GO111MODULE=on go get -u github.com/prometheus/alertmanager/cmd/amtool@v0.21.0`
```
amtool, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.14.3
```

* Alertmanager configuration file:

I shortened the configuration. Tell me if this was not OK.
```
global: {}
  # slack_api_url: ''

receivers:
  - name: victorops_default
    victorops_configs:
[...]

  - name: slack_default
    slack_configs:
[...]

  - name: alert_stream
    slack_configs:
[...]

  - name: blackhole
    # Deliberately left empty to not deliver anywhere.

templates:
  - '/etc/message-templates/*.tmpl'

route:
  group_wait: 10s
  group_interval: 5m
  group_by:
    - environment
    - cluster
    - alertname
    - severity
    - namespace
    - app
    - instance
    - instance_id
    - db_instance_identifier
    - maintainer_team
    - sre
  receiver: slack_default
  repeat_interval: 4h
  routes:
[...]

inhibit_rules:
[...]
```
