### ISSUE TITLE
send email throgh proxy

### ISSUE THREAD

**Issue by pretendhigh** [prometheus/alertmanager#2319]
My kubernetes cluser is in the local area network and cannot access internet. I have a http proxy http://10.1.1.30:3128 through which I can access internet. I want the alertmanager-server pod in k8s cluster to sent mail to my 163 email through the http proxy.

My alertmanager.yml:
```
---
apiVersion: v1
data:
  alertmanager.yml: |
    global:
      http_config:
        proxy_url: 'http://10.1.1.30:3128'
      smtp_smarthost: '220.181.12.14:25'
      smtp_from: 'example@163.com'
      smtp_auth_username: 'example@163.com'
      smtp_auth_password: 'password'
      smtp_require_tls: false
    route:
      receiver: default-receiver
      group_wait: 10s
      group_interval: 60s
      repeat_interval: 3h
    receivers:
      - name: default-receiver
        email_configs:
          - to: 'example@163.com'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-configmap
```

But it didn't work. The alertmanager-server pod's log:
```
level=error ts=2020-07-07T02:04:16.220Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="establish connection to server: dial tcp 220.181.12.14:25: i/o timeout" context_err="context deadline exceeded"
```
I used tcpdump catched the traffic:
```
09:44:56.671425 IP k8s02.43670 > 220.181.12.14.smtp: Flags [S], seq 1137580976, win 28200, options [mss 1410,sackOK,TS val 3478017542 ecr 0,nop,wscale 7], length 0
```

It seems that the alertmanager-server didn't send mail throuth the http proxy. It just directly tried to  connect with the smtp server. Finally the error raised, because the pod is in local area network. It must use the proxy to access  smtp server but it didn't.

Can you git me some sugesstion?  Thanks!

**Environment**

* System information:

        centos7.6
        kubernetes 1.11.5

* Alertmanager version:

	docker image: prom/alertmanager-server:v0.15.0

* Prometheus version:

	docker image: prom/prometheus:v2.2.1
