### ISSUE TITLE
alertmanager sending duplicate notifications in slack 

### ISSUE THREAD

**Issue by perumalla-giridhar** [prometheus/alertmanager#2327]
**What did you do?**
Running alertmanager in replica = 1

**What did you expect to see?**
I expect to see only one notification for a alert group

**What did you see instead? Under which circumstances?**
I see four notifications sent at the same time in my slack channel for the same alert group. 
**Environment**
`OS: Ubuntu:18.04.3`

* System information:

	`Linux 5.3.0-1023-aws x86_64`

* Alertmanager version:
`alertmanager:v0.21.0`
using the image: `quay.io/prometheus/alertmanager:v0.21.0`
* Prometheus version:

image: `quay.io/prometheus/prometheus:v2.17.2`

* Alertmanager configuration file:
```
global:
  slack_api_url: 'slack_webhook'
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 20m
  receiver: 'slack'
receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
  - api_url: 'slack_webhook'
  - channel: 'alerts'
  - text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
```

* Logs:
```
level=info ts=2020-07-20T08:46:55.557Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
level=info ts=2020-07-20T08:46:55.557Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee35927357f, date=20200617-08:54:02)"
level=info ts=2020-07-20T08:46:55.582Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2020-07-20T08:46:55.583Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2020-07-20T08:46:55.585Z caller=main.go:485 msg=Listening address=:9093
```

**Comment by simonpasquier** [comment]
Your config declares 4 receivers. Try this instead:

```yaml
receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
    api_url: 'slack_webhook'
    channel: 'alerts'
    text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
```
