### ISSUE TITLE
Alertmanager periodically sending empty templated message field to OpsGenie

### ISSUE THREAD

**Issue by cwadley** [prometheus/alertmanager#2329]
**What did you do?**
Running Prometheus and Alertmanager on AKS K8s. We recently discovered that several newly-applied alerts were firing in Prometheus, but were occasionally not being sent to OpsGenie. Upon inspection of the Alertmanager logs, we discovered multiple instances, across several firing alerts, of this log message:
```
level=debug ts=2020-07-21T19:41:13.697Z caller=notify.go:668 component=dispatcher msg="Notify attempt failed" attempt=1 integration=opsgenie receiver=opsgenie-receiver err="unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"message\":\"Message can not be empty.\"},\"took\":0.001,\"requestId\":\"<UUID>\"}"

level=error ts=2020-07-21T19:41:13.697Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"message\":\"Message can not be empty.\"},\"took\":0.001,\"requestId\":\"<UUID>\"}" context_err=null

level=error ts=2020-07-21T19:41:13.697Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"message\":\"Message can not be empty.\"},\"took\":0.001,\"requestId\":\"<UUID>\"}"
```
I set up a dummy web server and configured the OpsGenie API URL in Alertmanager to point to my server, and so managed to capture the request body coming from Alertmanager, shown below. Indeed, the message field was empty, along with a missing description field.

We are using templates in the Alertmanager configuration (also shown below) to map annotations to the message and description fields, and I suspect that this template substitution may be failing to populate. The team template, however, did seem to be populated. Further complicating this, the issue appears to be non-deterministic, since late in the day it started working without any obvious cause.

We have many other similar alert rules on other Prometheus instances, and have never encountered this issue before.

**What did you expect to see?**
Alertmanager sends a request to OpsGenie with the message field populated, as well as a description field:

Captured by redirecting requests to the alternate webserver:
```
RemoteAddr: 10.171.72.6:59576
Host: webhooky.webhooky.svc.cluster.local:8080
Method: POST
URL: /v2/alerts
RequestURI: /v2/alerts
Headers:
   map[Authorization:[GenieKey <lolkey>] Content-Length:[395] Content-Type:[application/json] User-Agent:[Go-http-client/1.1]]
Body:
{"alias":"<long-identifier>","message":"Fake service has STOPPED on vm3","description":"Fake service has entered a STOPPED state on vm3","details":{},"source":"https://k8s.monitoring.example.io/alertmanager-k8s-b/#/alerts?receiver=opsgenie-receiver","responders":[{"name":"Test","type":"team"}]}

```
**What did you see instead? Under which circumstances?**
Alertmanager sends a request with an empty message and no description.
```
RemoteAddr: 10.171.72.19:55072
Host: webhooky.webhooky.svc.cluster.local:8080
Method: POST
URL: /v2/alerts
RequestURI: /v2/alerts
Headers:
   map[Authorization:[GenieKey <lolkey>] Content-Length:[296] Content-Type:[application/json] User-Agent:[Go-http-client/1.1]]
Body:
{"alias":"<long-identifier>","message":"","details":{},"source":"https://k8s.monitoring.example.io/alertmanager-k8s-b/#/alerts?receiver=opsgenie-receiver","responders":[{"name":"Test","type":"team"}]}
```
**Environment**

* System information:
K8s - AKS

* Alertmanager version:
prom/alertmanager:v0.21.0

* Prometheus version:
prom/prometheus:v2.17.2

* Alertmanager configuration file:
```
---
global:
  slack_api_url: "{{SLACK_URL}}"
  opsgenie_api_key: "{{OPSGENIE_API_KEY}}"
  opsgenie_api_url: "https://api.opsgenie.com/"
receivers:
  - name: default-receiver
    slack_configs:
      - icon_url: https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Prometheus_software_logo.svg/1033px-Prometheus_software_logo.svg.png
        title: Alertmanager Default Receiver
        text: "{{ .CommonAnnotations.description }}"
  - name: opsgenie-receiver
    opsgenie_configs:
      - message: "{{ .CommonAnnotations.summary }}"
        description: "{{ .CommonAnnotations.description }}"
        priority: "{{ .CommonAnnotations.severity }}"
        responders:
          - name: "{{ .CommonAnnotations.team }}"
            type: team
  - name: slack-receiver
    slack_configs:
      - icon_url: https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Prometheus_software_logo.svg/1033px-Prometheus_software_logo.svg.png
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"

route:
  group_interval: 5m
  group_wait: 15s
  receiver: default-receiver
  repeat_interval: 10m

  routes:
    - match:
        receivername: slack
      receiver: slack-receiver
    - match:
        receivername: opsgenie
      receiver: opsgenie-receiver
```

* Prometheus configuration file:
```
---
groups:
  - name: alert.rules
    rules:
      - alert: fake-windows-service-stopped
        expr: wmi_service_state{name=~"fake.*", state="stopped"} == 1
        for: 30s
        labels:
          severity: P2
          receivername: opsgenie
        annotations:
          summary: "Fake service has STOPPED on {{ $labels.vm_name }}"
          description: "Fake service has entered a STOPPED state on {{ $labels.vm_name }}"
          team: "Test"
```
