### ISSUE TITLE
Does it support multiple repeat_interval settings?

### ISSUE THREAD

**Issue by mymtak** [prometheus/alertmanager#2336]
I want to set an alert notification interval for each group.

- alert_rules.yml
```
groups:
- name: http_alert1
  rules:
  - alert: xxxx1
    expr: probe_success{instance="http://xx.xx.xx.xx/foo"} == 0 # instanceCondition is down.
    for: 1m  # instance is down for 1 minutes.
    labels:
      severity: critical
    annotations:
      summary: '{{ $labels.instance }} '
      description: '{{ $labels.instance }} is down.'

- name: http_alert2
  rules:
  - alert: xxxx2
    expr: probe_success{instance="http://xx.xx.xx.xx/bar"} == 0 # instanceCondition is down.
    for: 1m  # instance is down for 1 minutes.
    labels:
      severity: critical
    annotations:
      summary: '{{ $labels.instance }} '
      description: '{{ $labels.instance }} is down.'
```
