### ISSUE TITLE
repeat_interval is active after alertmanager container restart

### ISSUE THREAD

**Issue by dykow** [prometheus/alertmanager#2339]
**What did you do?**
Run alertmanager with docker container `quay.io/prometheus/alertmanager:v0.21.0`. Alert notifications are being correctly sent to `pushover` after discovery. After container restart the remaining `repeat_interval` time is being remembered - at least it seems to me like that

**What did you expect to see?**
All notifications should be resent after container restart and successful discovery. Or should them?

**What did you see instead? Under which circumstances?**
Have to wait remaining `repeat_interval` time before notifications will be resent - even after container restart

**Environment**
```
╰─$ docker --version                                                                                                                                                                   125 ↵
Docker version 19.03.12, build 48a66213fe
```

* System information:
```
╰─$ uname -srm
Linux 5.4.0-42-generic x86_64
```

* Alertmanager version:
``quay.io/prometheus/alertmanager:v0.21.0``

* Prometheus version:
`prom/prometheus:v2.19.2`

* Alertmanager configuration file:
```
route:
  receiver: 'pushover'
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 10m

receivers:
  - name: 'pushover'
    pushover_configs:
      - token: #token 
        user_key: #secret
```
