### ISSUE TITLE
Slack notification button gets ignored on desktop app, but not on mobile

### ISSUE THREAD

**Issue by t1hom7as** [prometheus/alertmanager#2344]
**What did you do?**
I am trying to send a button with a hyperlink to a URL.
This works if I change it to:
`url: 'http://google.com'`
But this does not work if I use my internal host/alertmanager:
`url: 'http://<site>-<env>-<service>-001:9093'`

**What did you expect to see?**
The button to show and the link to work.
Works for http://google.com but not for my URL.

**What did you see instead? Under which circumstances?**
The button is not shown when using my internal URL.

**Environment**
Docker: prom/alertmanager
* System information:

Linux 4.18.0-193.14.2.el8_2.x86_64 x86_64

* Alertmanager version:

/alertmanager $ alertmanager --version
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4

* Prometheus version:

/prometheus $ prometheus --version
prometheus, version 2.19.3 (branch: HEAD, revision: 657ba532e42f1db8d7c77bf802378643da0d3118)
  build user:       root@b99e50bced7c
  build date:       20200724-12:20:53
  go version:       go1.14.6

* Alertmanager configuration file:
```
---
global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/STRINGGGGG'
route:
  group_by: ['...']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 360h # set to 2 weeks, hoping no dupe alerts
  receiver: 'slack-notifications'
inhibit_rules:
  - source_match:
      severity: 'critical'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#test'
    icon_url: 'https://cdn.rancher.com/wp-content/uploads/2015/05/27094511/prometheus-logo-square.png'
    color: '{{ if eq .Status "firing" }}danger{{ else }}36a64f{{ end }}'
    send_resolved: true
    title: '{{ template "slack.my.title" . }}'
    text: '{{ template "slack.my.text" . }}'
    actions:
    - type: button
      text: 'Silence :warning:'
      url: 'http://<site>-<env>-<service>-001:9093'
      #url: 'http://google.com
templates:
- 'my.tmpl'
```

* Prometheus configuration file:
N/A

* Logs:
```
docker-compose up
Creating alertmanager ... done
Attaching to alertmanager
alertmanager    | level=info ts=2020-08-05T19:03:37.985Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
alertmanager    | level=info ts=2020-08-05T19:03:37.985Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee35927357f, date=20200617-08:54:02)"
alertmanager    | level=info ts=2020-08-05T19:03:37.986Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=172.17.0.3 port=9094
alertmanager    | level=info ts=2020-08-05T19:03:37.987Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
alertmanager    | level=info ts=2020-08-05T19:03:38.022Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yml
alertmanager    | level=info ts=2020-08-05T19:03:38.022Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/alertmanager.yml
alertmanager    | level=info ts=2020-08-05T19:03:38.026Z caller=main.go:485 msg=Listening address=:9093
alertmanager    | level=info ts=2020-08-05T19:03:39.987Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000123636s
alertmanager    | level=info ts=2020-08-05T19:03:47.988Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.00102647s

```

* docker-compose:

```
---
version: "2"
services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./my.tmpl:/etc/alertmanager/my.tmpl:ro
    ports:
      - 9093:9093
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.external-url=http://<site>-<env>-<service>-001:9093"
      - "--data.retention=360h"

```
