### ISSUE TITLE
Pagerduty_url configuration ignored when service_key is set

### ISSUE THREAD

**Issue by janboll** [prometheus/alertmanager#2347]
**What did you do?**
I tried to overwrite the pagerduty_url property

**What did you expect to see?**
Requests are sent towards this URL

**What did you see instead? Under which circumstances?**
Requests are always sent to _https://events.pagerduty.com/v2/enqueue_ endpoint
This also happens when setting _pagerduty_configs.url_

**Environment**

* Alertmanager version:
```
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:56:57
  go version:       go1.14.4
```

* Alertmanager configuration file:
```
global:
  pagerduty_url: "http://localhost:8080/incidents"

route:
  group_by: ['alertname', 'cluster', 'service']
  receiver: test1

receivers:
  - name: test1
    pagerduty_configs:
    - service_key: "ffffffffff"
```
