### ISSUE TITLE
Whitespace in matchers on the "New Silence" form results in all alerts being selected

### ISSUE THREAD

**Issue by ResDiaryLewis** [prometheus/alertmanager#2354]
**What did you do?**

- Opened the `New Silence` form
- Correctly populated the time, creator and description fields
- Added an arbitrary number of matchers
- Alter one matcher to have a key with a trailing space, e.g. `testing `
- Click `Preview Alerts`

**What did you expect to see?**

The form should:
- show a warning, or
- disallow trailing whitespace

No alerts should have been affected in the preview.

**What did you see instead? Under which circumstances?**

All alerts are listed as `Affected alerts`, despite not fulfilling any matchers.

**Environment**

* System information:

```
Linux 4.19.76-linuxkit x86_64
```

* Alertmanager version:

```shell
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4
```

* Prometheus version:

```shell
prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5
```

* Alertmanager configuration file:

```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
templates: []
```

* Prometheus configuration file:
Don't think this is relevant, and may contain sensitive data. I can censor it and provide it if deemed necessary. 

* Logs:
No logs were generated
