### ISSUE TITLE
Question : About the time when slack is notified

### ISSUE THREAD

**Issue by mymtak** [prometheus/alertmanager#2355]
**What did you do?**
I want the current status to match the alert alertmanager notifies to slack.
**What did you expect to see?**
The alert sent to slack is correct.

**What did you see instead? Under which circumstances?**
Alerts sent to slack are data more than 12 hours ago.
**Environment**
windows10(64bit)

* Alertmanager version: 0.21.0

* Prometheus version: 2.19.2

* Alertmanager configuration file:
```
global:
  http_config:
    proxy_url: http://XXXXXX:8080
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/XXXXXX'
route:
  receiver: 'server_alert'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2h
  repeat_interval: 2h
receivers:
- name: 'server_alert'
  slack_configs:
  - send_resolved: true
    channel: '#1_server_alert'
    title: 'server_alert'
    text: "{{ range .Alerts }}{{ .Annotations.description }} \n {{ end }}"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
```
