### ISSUE TITLE
Can't access `.ExternalURL` on Slack actions `gotpl` templates

### ISSUE THREAD

**Issue by carlosjgp** [prometheus/alertmanager#2359]
**What did you do?**

Create a custom template for Slack button for silences

**What did you expect to see?**

A button to create silences

**What did you see instead? Under which circumstances?**

Nothing on Slack. Error on Alertmanager logs

**Environment**

* System information:

EKS 1.16 with AWS eks AMIs

```
Linux 4.14.186-146.268.amzn2.x86_64 x86_64
```

* Alertmanager version:

```
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4
```

* Prometheus version:
```
prometheus, version 2.20.1 (branch: HEAD, revision: 983ebb4a513302315a8117932ab832815f85e3d2)
  build user:       root@7cbd4d1c15e0
  build date:       20200805-17:26:58
  go version:       go1.14.6
```

* Alertmanager configuration file:

My silence link `gotpl` function... expecting having access to the full context (`Data` on the Alertmanger page https://prometheus.io/docs/alerting/latest/notifications/)
```
            {{ define "util.generate.silence.link" }}
                {{ .ExternalURL }}/#/silences/new?filter=%7B
                {{- range .CommonLabels.SortedPairs -}}
                    {{- if ne .Name "alertname" -}}
                        {{- .Name }}%3D"{{- .Value | urlquery -}}"%2C%20
                    {{- end -}}
                {{- end -}}
                alertname%3D"{{ .CommonLabels.alertname }}"%7D
            {{ end }}
```

receiver
```
            receivers:
              - name: infrastructure-alert
                slack_configs:
                - channel: '#infrastructure-alerts'
                  send_resolved: true
                  icon_emoji: '{{ template "slack.webhook.icon_emoji" . }}'
                  color: '{{ template "slack.resolve.color" . }}'
                  text: '{{ template "slack.generic.text" . }}'
                  title: '{{ template "slack.generic.title" . }}'
                  username: prometheus-monitor
                  actions:
                  - type: button
                    text: 'Run book :hammer_and_spanner:'
                    url: '{{ template "util.generate.runbook.url" (index .Alerts 0) }}'
                  - type: button
                    text: 'Logs :book:'
                    url: '{{ template "util.generate.logs.url" (index .Alerts 0) }}'
                  - type: button
                    text: 'Dashboard :bar_chart:'
                    url: '{{ template "util.generate.dashboard.url" (index .Alerts 0) }}'
                  - type: button
                    text: 'Silence :no_bell:'
                    url: '{{ template "util.generate.silence.link" . }}'
                  - type: button
                    text: 'Code :github:'
                    url: '{{ template "util.generate.github.repo.url" (index .Alerts 0) }}'
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=error ts=2020-08-21T15:35:51.150Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="infrastructure-alert/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: template: utils.tmpl:64:9: executing \"util.generate.silence.link\" at <.ExternalURL>: can't evaluate field ExternalURL in type template.Alert"
```
Slack URL templated here
https://github.com/prometheus/alertmanager/blob/master/notify/slack/slack.go#L141

using this function
https://github.com/prometheus/alertmanager/blob/master/notify/util.go#L83

which uses the context extracted from this function
https://github.com/prometheus/alertmanager/blob/master/notify/util.go#L132
==>
https://github.com/prometheus/alertmanager/blob/master/template/template.go#L280:20
