### ISSUE TITLE
send alert message to email failed

### ISSUE THREAD

**Issue by xyyp224** [prometheus/alertmanager#2365]
**What did you do?**

send alert message to email..

* Alertmanager version:

	latest

* Prometheus version:

	latest

* Alertmanager configuration file:
```
global:
  smtp_smarthost: 'smtp.mxhichina.com:587'
  smtp_from: 'pm_dchain@anycore.cn'
  smtp_auth_username: 'pm_dchain@anycore.cn'
  smtp_auth_password: '*************'
  smtp_require_tls: false

route: 
  group_by: ['user']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  email_configs:
  - to: `'xyyp224@163.com'
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['host-deploy.hh:9093']
      # - alertmanager:9093

rule_files:
  - "node_down.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['host-deploy.hh:9090']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['host-deploy.hh:7200']
  - job_name: 'node'
    scrape_interval: 8s
    static_configs:
      - targets: ['host-deploy.hh:7100','host-service-1.hh:7100','host-service-2.hh:7100','host-gateway.hh:7100','host-base.hh:7100','host-db.hh:7100']
  - job_name: 'postgres'
    static_configs:
     - targets: ['host-db.hh:9187']
```

* node_down configuration file:
```
groups:
- name: node_down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      user: test
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
```
* logs:
```
level=warn ts=2020-09-01T10:39:19.646Z caller=notify.go:674 component=dispatcher receiver=live-monitoring integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="*smtp.plainAuth auth: unencrypted connection"
level=warn ts=2020-09-01T10:39:24.499Z caller=notify.go:674 component=dispatcher receiver=live-monitoring integration=email[0] msg="Notify attempt failed, will retry later" attempts=5 err="establish connection to server: dial tcp 42.120.226.4:587: i/o timeout"
level=error ts=2020-09-01T10:39:24.499Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="live-monitoring/email[0]: notify retry canceled after 6 attempts: establish connection to server: dial tcp 42.120.226.4:587: i/o timeout"
level=warn ts=2020-09-01T10:39:24.654Z caller=notify.go:674 component=dispatcher receiver=live-monitoring integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="*smtp.plainAuth auth: unencrypted connection"
level=error ts=2020-09-01T10:39:34.499Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="live-monitoring/email[0]: notify retry canceled after 6 attempts: *smtp.plainAuth auth: unencrypted connection"
level=warn ts=2020-09-01T10:39:39.672Z caller=notify.go:674 component=dispatcher receiver=live-monitoring integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="*smtp.plainAuth auth: unencrypted connection"
level=error ts=2020-09-01T10:39:44.499Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="live-monitoring/email[0]: notify retry canceled after 5 attempts: *smtp.plainAuth auth: unencrypted connection"
level=warn ts=2020-09-01T10:39:49.673Z caller=notify.go:674 component=dispatcher receiver=live-monitoring integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="*smtp.plainAuth auth: unencrypted connection"
level=error ts=2020-09-01T10:39:54.499Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="live-monitoring/email[0]: notify retry canceled after 6 attempts: establish connection to server: dial tcp 42.120.219.29:587: i/o timeout"
level=warn ts=2020-09-01T10:39:54.666Z caller=notify.go:674 component=dispatcher receiver=live-monitoring integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="*smtp.plainAuth auth: unencrypted connection"
level=error ts=2020-09-01T10:40:04.499Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="live-monitoring/email[0]: notify retry canceled after 6 attempts: *smtp.plainAuth auth: unencrypted connection"
level=warn ts=2020-09-01T10:40:09.662Z caller=notify.go:674 component=dispatcher receiver=live-monitoring integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="*smtp.plainAuth auth: unencrypted connection"
level=error ts=2020-09-01T10:40:14.500Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="live-monitoring/email[0]: notify retry canceled after 5 attempts: *smtp.plainAuth auth: unencrypted connection"
```
