### ISSUE TITLE
send _plain_ text emails as alerts

### ISSUE THREAD

**Issue by pellywog** [prometheus/alertmanager#2374]
**What did you do?**

I want to configure prometheus-alertmanager to send plain text emails. For this I did:

/etc/prometheus-alertmanager/alertmanager.yml
```
[...]
templates:
  - "/etc/prometheus-alertmanager/templates/email.example.tmpl"

receivers:
  - name: example
    email_configs:
      - to: 'plaintest@example.com'
        send_resolved: true
        text: '{{ template "email.my.text" . }}'
[...]
```

/etc/prometheus-alertmanager/templates/email.example.tmpl
```
{{ define "__subject" }}
{{ .CommonLabels.priority }} {{ .CommonLabels.instance }} {{ .CommonLabels.alertname }} {{ .Status }}
{{ end }}

{{ define "__text_alert_list" }}{{ range . }}
Labels:
{{ range .Labels.SortedPairs }}{{ if lt (len .Name) 5 }}  {{ .Name }}:{{ "\t" }}{{ "\t" }}{{ .Value }}{{ else }}  {{ .Name }}:{{ "\t" }}{{ .Value }}{{ end }}
{{ end }}Annotations:
{{ range .Annotations.SortedPairs }}{{ if lt (len .Name) 5 }}  {{ .Name }}:{{ "\t" }}{{ "\t" }}{{ .Value }}{{ else }}  {{ .Name }}:{{ "\t" }}{{ .Value }}{{ end }}
{{ end }}Source:
{{ .GeneratorURL }}
{{ end }}{{ end }}

{{ define "__alert_silence_link" -}}
    {{ .ExternalURL }}/#/silences/new?filter=%7B
    {{- range .CommonLabels.SortedPairs -}}
        {{- if ne .Name "alertname" -}}
            {{- .Name }}%3D"{{- .Value -}}"%2C%20
        {{- end -}}
    {{- end -}}
    alertname%3D"{{ .CommonLabels.alertname }}"%7D
{{- end }}



{{ define "email.comfault.subject" }}{{ template "__subject" . }}{{ end }}

{{ define "email.example.text" }}
{{ if gt (len .Alerts.Firing) 0 -}}
# Alerts firing

{{ template "__text_alert_list" .Alerts.Firing }}
{{- end }}

{{ if gt (len .Alerts.Resolved) 0 -}}
# Alerts resolved

{{ template "__text_alert_list" .Alerts.Resolved }}
{{- end }}

Manage notification:
{{ template "__alert_silence_link" . }}
{{- end }}
```

**What did you expect to see?**

The email should not contain any html at all. There should be a config option in alertmanager that does not append any html. The email body should look (roughly) like this:
```
Return-Path: <monitoring@mycompanymail.com>
Delivered-To: monitoring+customer@example.org
Received: <mail transmission log here>
Subject: P1_https://blog.mycompany.com_BlackboxProbeFailed_firing
To: monitoring+customer@example.org
From: monitoring@mycompanymail.com
Message-Id: <1600244720648963585.13401906031646598495@my-prometheus-server.de>
Date: Wed, 16 Sep 2020 10:25:20 +0200
Content-Type: text/plain

--aae1ee956c911b2bf2752d58e2547a85bd008ebceb1c8ea49f7b287c2d73
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8


# Alerts firing


Labels:
 alertname: BlackboxProbeFailed
 instance: https://blog.mycompany.com
 job: blackbox_exporter at my-php-server.com for http_2xx
 priority: P1
Annotations:
 summary: blackbox check failed:=20
Source:
https://my-prometheus-server.com/prometheus/graph?g0.expr=3Dprobe_success+%3D%3D+0=
&g0.tab=3D1




Manage notification:
https://my-prometheus-server.com/foobar

--aae1ee956c911b2bf2752d58e2547a85bd008ebceb1c8ea49f7b287c2d73--
```

**What did you see instead? Under which circumstances?**

Instead I get an email with a lot of html below the text part (that is not required). Please note the subject as well as the message itself.

```
Return-Path: <monitoring@my-company-mail.com>
Delivered-To: monitoring+customer@example.org
Received: (mail transmission logs here)
Subject: =?utf-8?q?=0AP1_https://blog.mycompany.com_BlackboxProbeFailed_firing=0A?=     <====== HERE ====
To: monitoring+customer@example.org
From: monitoring@my-company-mail.com
Message-Id: <1600244720648963585.13401906031646598495@my-prometheus-server.de>
Date: Wed, 16 Sep 2020 10:25:20 +0200
Content-Type: multipart/alternative; boundary=aae1ee956c911b2bf2752d58e2547a85bd008ebceb1c8ea49f7b287c2d73
MIME-Version: 1.0

--aae1ee956c911b2bf2752d58e2547a85bd008ebceb1c8ea49f7b287c2d73
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8


# Alerts firing


Labels:
 alertname: BlackboxProbeFailed
 instance: https://blog.mycompany.com
 job: blackbox_exporter at my-php-server.com for http_2xx
 priority: P1
Annotations:
 summary: blackbox check failed:=20
Source:
https://my-prometheus-server.com/prometheus/graph?g0.expr=3Dprobe_success+%3D%3D+0=
&g0.tab=3D1




Manage notification:
https://my-prometheus-server.com/foobar
--aae1ee956c911b2bf2752d58e2547a85bd008ebceb1c8ea49f7b287c2d73
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

============== FOLLOWING HERE ==============

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns=3D"http://www.w3.org/199=
9/xhtml" style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-ser=
if; box-sizing: border-box; font-size: 14px; margin: 0;">
<head style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;=
 box-sizing: border-box; font-size: 14px; margin: 0;">
<meta name=3D"viewport" content=3D"width=3Ddevice-width" style=3D"font-fami=
ly: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box;=
 font-size: 14px; margin: 0;" />
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8" st=
yle=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-siz=
ing: border-box; font-size: 14px; margin: 0;" />
<title style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif=
; box-sizing: border-box; font-size: 14px; margin: 0;">
P1 https://blog.mycompany.com BlackboxProbeFailed firing
</title>

</head>

<body itemscope=3D"" itemtype=3D"http://schema.org/EmailMessage" style=3D"f=
ont-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: bor=
der-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text=
-size-adjust: none; height: 100%; line-height: 1.6em; width: 100% !importan=
t; background-color: #f6f6f6; margin: 0; padding: 0;" bgcolor=3D"#f6f6f6">

<table style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif=
; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #=
f6f6f6; margin: 0;" bgcolor=3D"#f6f6f6">
 <tr style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;=
 box-sizing: border-box; font-size: 14px; margin: 0;">
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-seri=
f; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;=
" valign=3D"top"></td>
 <td width=3D"600" style=3D"font-family: 'Helvetica Neue', Helvetica, Ar=
ial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: t=
op; display: block !important; max-width: 600px !important; clear: both !im=
portant; width: 100% !important; margin: 0 auto; padding: 0;" valign=3D"top=
">
 <div style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-s=
erif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: b=
lock; margin: 0 auto; padding: 0;">
 <table width=3D"100%" cellpadding=3D"0" cellspacing=3D"0" style=3D"=
font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: bo=
rder-box; font-size: 14px; border-radius: 3px; background-color: #fff; marg=
in: 0; border: 1px solid #e9e9e9;" bgcolor=3D"#fff">
 <tr style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, san=
s-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, s=
ans-serif; box-sizing: border-box; font-size: 16px; vertical-align: top; co=
lor: #fff; font-weight: 500; text-align: center; border-radius: 3px 3px 0 0=
; background-color: #E6522C; margin: 0; padding: 20px;" align=3D"center" bg=
color=3D"#E6522C" valign=3D"top">
 1 alert for=20
 alertname=3DBlackboxProbeFailed
 =20
 instance=3Dhttps://blog.mycompany.com
 =20
 </td>
 </tr>
 <tr style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, san=
s-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, s=
ans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; ma=
rgin: 0; padding: 10px;" valign=3D"top">
 <table width=3D"100%" cellpadding=3D"0" cellspacing=3D"0" sty=
le=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizi=
ng: border-box; font-size: 14px; margin: 0;">
 <tr style=3D"font-family: 'Helvetica Neue', Helvetica, Aria=
l, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Ar=
ial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: t=
op; margin: 0; padding: 0 0 20px;" valign=3D"top">
 <a href=3D"https://my-prometheus-server.com/alertmanager/#/ale=
rts?receiver=3DP1" style=3D"font-family: 'Helvetica Neue', Helvetica, Arial=
, sans-serif; box-sizing: border-box; font-size: 14px; color: #FFF; text-de=
coration: none; line-height: 2em; font-weight: bold; text-align: center; cu=
rsor: pointer; display: inline-block; border-radius: 5px; text-transform: c=
apitalize; background-color: #348eda; margin: 0; border-color: #348eda; bor=
der-style: solid; border-width: 10px 20px;">View in AlertManager</a>
 </td>
 </tr>
 =20
 <tr style=3D"font-family: 'Helvetica Neue', Helvetica, Aria=
l, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Ar=
ial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: t=
op; margin: 0; padding: 0 0 20px;" valign=3D"top">
 <strong style=3D"font-family: 'Helvetica Neue', Helveti=
ca, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"=
>[1] Firing</strong>
 </td>
 </tr>
 =20
 =20
 <tr style=3D"font-family: 'Helvetica Neue', Helvetica, Aria=
l, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Ar=
ial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: t=
op; margin: 0; padding: 0 0 20px;" valign=3D"top">
 <strong style=3D"font-family: 'Helvetica Neue', Helveti=
ca, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"=
>Labels</strong><br style=3D"font-family: 'Helvetica Neue', Helvetica, Aria=
l, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
 alertname =3D BlackboxProbeFailed<br style=3D"font-fami=
ly: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box;=
 font-size: 14px; margin: 0;" />instance =3D https://blog.mycompany.com<br st=
yle=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-siz=
ing: border-box; font-size: 14px; margin: 0;" />job =3D blackbox_exporter a=
t my-php-server.com for http_2xx<br style=3D"font-family: 'Helvet=
ica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size:=
 14px; margin: 0;" />priority =3D P1<br style=3D"font-family: 'Helvetica Ne=
ue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;=
 margin: 0;" />
 <strong style=3D"font-family: 'Helvetica Neue', Helveti=
ca, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"=
>Annotations</strong><br style=3D"font-family: 'Helvetica Neue', Helvetica,=
 Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
 summary =3D blackbox check failed: <br style=3D"font-fa=
mily: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-bo=
x; font-size: 14px; margin: 0;" />
 <a href=3D"https://my-prometheus-server.com/prometheus/graph?g=
0.expr=3Dprobe_success&#43;%3D%3D&#43;0&amp;g0.tab=3D1" style=3D"font-famil=
y: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; =
font-size: 14px; color: #348eda; text-decoration: underline; margin: 0;">So=
urce</a><br style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-=
serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
 </td>
 </tr>
 =20

 =20
 =20
 </table>
 </td>
 </tr>
 </table>

 <div style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans=
-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; =
color: #999; margin: 0; padding: 20px;">
 <table width=3D"100%" style=3D"font-family: 'Helvetica Neue', Hel=
vetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin:=
 0;">
 <tr style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, s=
ans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Arial,=
 sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; =
text-align: center; color: #999; margin: 0; padding: 0 0 20px;" align=3D"ce=
nter" valign=3D"top"><a href=3D"https://my-prometheus-server.com/alertmanager" sty=
le=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizi=
ng: border-box; font-size: 12px; color: #999; text-decoration: underline; m=
argin: 0;">Sent by AlertManager</a></td>
 </tr>
 </table>
 </div></div>
 </td>
 <td style=3D"font-family: 'Helvetica Neue', Helvetica, Arial, sans-seri=
f; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;=
" valign=3D"top"></td>
 </tr>
</table>

</body>
</html>


--aae1ee956c911b2bf2752d58e2547a85bd008ebceb1c8ea49f7b287c2d73--
```

**Environment**

Production? :P

Not sure if information that I did not provide below in the issue is required here, let me know if I need to paste anything else.

* System information:

Linux 4.9.0-13-amd64 x86_64, Debian 9

* Alertmanager version:

$ prometheus-alertmanager --version
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4

* Prometheus version:

$ prometheus --version
prometheus, version 2.20.0 (branch: HEAD, revision: e5a06b483527d4fe0704b8fa3a2b475b661c526f)
  build user:       root@ac954b6d5c6e
  build date:       20200722-18:51:45
  go version:       go1.14.6

* Alertmanager configuration file:
```
$ cat /etc/prometheus-alertmanager/alertmanager.yml 
global:
  smtp_smarthost: '127.0.0.1:25'
  smtp_from: 'prometheus@my-prometheus-server.de'
  smtp_require_tls: false

route:
  group_by:
    - alertname
    - instance
    - service
  group_wait: 1s
  group_interval: 5m
  repeat_interval: 999d
  receiver: 'P5'
  routes:
    - receiver: P1
      repeat_interval: 30d
      match:
        priority: P1
    - receiver: P2
      repeat_interval: 30d
      match:
        priority: P2
    - receiver: P3
      repeat_interval: 30d
      match:
        priority: P3
    - receiver: P4
      repeat_interval: 30d
      match:
        priority: P4
    - receiver: P5
      repeat_interval: 30d
      match:
        priority: P5

templates:
  - "/etc/prometheus-alertmanager/templates/email.example.tmpl"

receivers:
  - name: P1
    email_configs:
      - to: 'signal@example.com'
        send_resolved: true
        text: '{{ template "email.example.text" . }}'
  - name: P2
    email_configs:
      - to: 'signal@example.com'
        send_resolved: true
        text: '{{ template "email.example.text" . }}'
  - name: P3
    email_configs:
      - to: 'monitoring+customer@example.org'
        send_resolved: true
        text: '{{ template "email.example.text" . }}'
  - name: P4
    email_configs:
      - to: 'monitoring+customer@example.org'
        send_resolved: true
        text: '{{ template "email.example.text" . }}'
  - name: P5
    email_configs:
      - to: 'monitoring+customer@example.org'
        send_resolved: true
        text: '{{ template "email.example.text" . }}'
```

* Prometheus configuration file:

I do not think this config is relevant for this issue (let me know if I'm wrong).

* Logs:

Nothing relevant in the logs.

**Comment by roidelapluie** [comment]
By looking at the cpde, if you set:

```
html: ""
```


It should not send any html.

**Comment by pellywog** [comment]
In which config file / section of it?

**Comment by roidelapluie** [comment]
```
global:
  smtp_smarthost: '127.0.0.1:1025'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false

# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for
  # all alerts. It needs to have a receiver configured so alerts that do not
  # match any of the sub-routes are sent to someone.
  receiver: 'team-Y-mails'
  group_wait: 0s



# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
# We use this to mute any warning-level notifications if the same alert is
# already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  # CAUTION: 
  #   If all label names listed in `equal` are missing 
  #   from both the source and target alerts,
  #   the inhibition rule will apply!
  equal: ['alertname']


receivers:
- name: 'team-Y-mails'
  email_configs:
  - to: 'team-Y+alerts@example.org'
    html: ''
    text: 'foo'

```

generates:


```
---------- MESSAGE FOLLOWS ----------
Subject: [FIRING:5]  (DiskRunningFull)
To: team-Y+alerts@example.org
From: alertmanager@example.org
Message-Id: <1600325923941601058.1281467554276247373@oxygen>
Date: Thu, 17 Sep 2020 08:58:43 +0200
Content-Type: multipart/alternative;  boundary=9690d604db3fb9df66e252fc9ee8633e4079d98741d5ceb341850b1de322
MIME-Version: 1.0
X-Peer: 127.0.0.1

--9690d604db3fb9df66e252fc9ee8633e4079d98741d5ceb341850b1de322
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

foo
--9690d604db3fb9df66e252fc9ee8633e4079d98741d5ceb341850b1de322--
------------ END MESSAGE ------------
```

**Comment by pellywog** [comment]
Excellent, works, thank you :+1: The subject still has an extra encoding. Can that be disabled too?
```
Subject: =?utf-8?q?=0Ap3_10501.example.net_FOOOOO10501_firing=0A?=
```

**Comment by devopstales** [comment]
You can owerride the html template with plain text too:
 ```
global:
  smtp_smarthost: '127.0.0.1:1025'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false
route:
  receiver: 'team-Y-mails'
  group_wait: 0s
receivers:
- name: 'team-Y-mails'
  email_configs:
  - to: 'team-Y+alerts@example.org'
    html: 'You have the following alerts: {{ .CommonLabels.alertname }} in {{ .CommonLabels.namespace }}'
 ```
