### ISSUE TITLE
[feature request] allow matched values from source_match_re in target_match

### ISSUE THREAD

**Issue by jmurphyau** [prometheus/alertmanager#2395]
**Feature Request**
It would be awesome if the `target_match` and/or `target_match_re` from `inhibit_rules` was able to use matched values from `source_match_re` - this would allow you to inhibit a range of different rules based on some values from the `source_match_re`.

Looking at the code and docs I couldn't see that this was possible, and I did a quick search of the GitHub issues and couldn't find anything similar.

**Example Config**
```
inhibit_rules:
  - source_match_re:
      alertname: 'esx-host-down'
      instance: 'syd-esx-(\d+).mycompany.com'
    target_match:
      alertname: 'vm-not-responding'
      esx_host: 'syd-esx-$1.mycompany.com'
```

**Result**
All alerts for `vm-not-responding` for VMs that have `esx_host=syd-esx-01.mycompany.com` will be suppressed.

**Note**
Not sure how this would work in terms of multiple matched values in different keys under `source_match_re` (do you just use index `$1` `$2` `$3` etc, or do you somehow also include the key from `source_match_re`? Like `$instance.1` (or similar)

**Comment by simonpasquier** [comment]
I fear that it would lead to very complex and hard to debug configurations for something that can be achieved in other ways.
If you modify your `esx-host-down` alert to copy the `instance` label to the `esx_host` label then your example would convert to:

```
inhibit_rules:                                                                                                                                                                              
- source_match_re:
    alertname: 'esx-host-down'
  target_match:
    alertname: 'vm-not-responding'
  equal:                                                                                                                                                                                      
  - esx_host
```
