### ISSUE TITLE
Sometimes AlertManager does not send 'Resolved' messages

### ISSUE THREAD

**Issue by M0rdecay** [prometheus/alertmanager#2398]
**What did you do?**
We have an alert that can often change its state. For clarity, here is its graph:
![image](https://user-images.githubusercontent.com/50422107/96839091-5e2f5980-1451-11eb-8187-1cf2b2c40eea.png)
Please note that the alert changed its state six times in a three-hour period.

**What did you expect to see?**
Each fired alert will also receive the `resolved` update.

**What did you see instead? Under which circumstances?**
Sometimes AlertManager does not send Resolved messages.  
The final recipient received four notifications because some of the alert state transitions took less time than specified in `group_interval` or `resolve_timeout` (this is exactly what we use alertManager for 👍).
These are records from InfluxDB, where we store the history of alerts:
![image](https://user-images.githubusercontent.com/50422107/96840519-39d47c80-1453-11eb-8060-cb887102b601.png)

This seems to happen when the time between resolving the previous alert and firing new alert  is close to `group_interval` or `resolve_timeout`.

I also noticed that this usually does not happen on the first day after restart of the AlertManager.

**Environment**

* System information:
RHEL 7 Linux 3.10.0-1062.12.1.el7.x86_64 x86_64

* Alertmanager version:
Branch: HEAD
BuildDate: 20200617-08:54:02
BuildUser: root@dee35927357f
GoVersion: go1.14.4
Revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d
Version: 0.21.0

* Alertmanager configuration file:
```yaml
global:
  resolve_timeout: 10m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: common_receiver
  group_by:
  - stand_name
  - scope
  - severity
  - product
  routes:
  - match:
      scope: area
    continue: true
    routes:
    - receiver: no_resolved_receiver
      match:
        severity: application/container
  - match:
      scope: application
    continue: true
    routes:
    - receiver: no_resolved_receiver
      match:
        severity: application/container
  - match:
      scope: business
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
inhibit_rules:
- source_match:
    alertname: TSDB Connection Alert
receivers:
- name: common_receiver
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://127.0.0.1:9099/influx
    max_alerts: 0
  - send_resolved: true
    http_config: {}
    url: http://127.0.0.1:9099/file # debug
    max_alerts: 0
- name: no_resolved_receiver
  webhook_configs:
  - send_resolved: false
    http_config: {}
    url: http://127.0.0.1:9099/influx
    max_alerts: 0
templates: []
```

* Logs:
Nothing in logs since the start of the application.

But I have incoming messages for this alert. 
I have deleted records of other alerts and confidential information:
```json
{
   "alerts":[
      {
         "annotations":{
            "description":"Алерт: Превышение нормализованной средней нагрузки за минуту  \nПорог: 90% за последние пять минут",
            "summary":"Avg. Load (1 min) Alert"
         },
         "endsAt":"0001-01-01T00:00:00Z",
         "generatorURL":"http://localhost:3001/d/JpOo_MXZz/alerts-host?fullscreen\u0026edit\u0026tab=alert\u0026panelId=86\u0026orgId=1",
         "labels":{
            "alertname":"Avg. Load (1 min) Alert",
            "host":"couchbase",
            "scope":"area",
            "severity":"host/node",
            "stand_name":"............................."
         },
         "startsAt":"2020-10-22T05:22:10Z",
         "status":"firing"
      },
.......
   ],
   "commonAnnotations":{
      
   },
   "commonLabels":{
      "host":"couchbase",
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "externalURL":"http://alertmanager_host:9095",
   "groupLabels":{
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "receiver":"common_receiver",
   "status":"firing",
   "version":"4",
   "groupKey":"{}/{scope=\"area\"}:{scope=\"area\", severity=\"host/node\", stand_name=\".............................\"}"
}

{
   "alerts":[
      {
         "annotations":{
            "description":"Алерт: Превышение нормализованной средней нагрузки за минуту  \nПорог: 90% за последние пять минут",
            "summary":"Avg. Load (1 min) Alert"
         },
         "endsAt":"2020-10-22T10:57:10.083299816+05:00",
         "generatorURL":"http://localhost:3001/d/JpOo_MXZz/alerts-host?fullscreen\u0026edit\u0026tab=alert\u0026panelId=86\u0026orgId=1",
         "labels":{
            "alertname":"Avg. Load (1 min) Alert",
            "host":"couchbase",
            "scope":"area",
            "severity":"host/node",
            "stand_name":"............................."
         },
         "startsAt":"2020-10-22T05:36:10Z",
         "status":"resolved"
      },
........
   ],
   "commonAnnotations":{
      
   },
   "commonLabels":{
      "host":"couchbase",
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "externalURL":"http://alertmanager_host:9095",
   "groupLabels":{
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "receiver":"common_receiver",
   "status":"firing",
   "version":"4",
   "groupKey":"{}/{scope=\"area\"}:{scope=\"area\", severity=\"host/node\", stand_name=\".............................\"}"
}

{
   "alerts":[
      {
         "annotations":{
            "description":"Алерт: Превышение нормализованной средней нагрузки за минуту  \nПорог: 90% за последние пять минут",
            "summary":"Avg. Load (1 min) Alert"
         },
         "endsAt":"0001-01-01T00:00:00Z",
         "generatorURL":"http://localhost:3001/d/JpOo_MXZz/alerts-host?fullscreen\u0026edit\u0026tab=alert\u0026panelId=86\u0026orgId=1",
         "labels":{
            "alertname":"Avg. Load (1 min) Alert",
            "host":"couchbase",
            "scope":"area",
            "severity":"host/node",
            "stand_name":"............................."
         },
         "startsAt":"2020-10-22T06:04:10Z",
         "status":"firing"
      },
.........
   ],
   "commonAnnotations":{
      
   },
   "commonLabels":{
      "host":"couchbase",
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "externalURL":"http://alertmanager_host:9095",
   "groupLabels":{
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "receiver":"common_receiver",
   "status":"firing",
   "version":"4",
   "groupKey":"{}/{scope=\"area\"}:{scope=\"area\", severity=\"host/node\", stand_name=\".............................\"}"
}

{
   "alerts":[
      {
         "annotations":{
            "description":"Алерт: Превышение нормализованной средней нагрузки за минуту  \nПорог: 90% за последние пять минут",
            "summary":"Avg. Load (1 min) Alert"
         },
         "endsAt":"0001-01-01T00:00:00Z",
         "generatorURL":"http://localhost:3001/d/JpOo_MXZz/alerts-host?fullscreen\u0026edit\u0026tab=alert\u0026panelId=86\u0026orgId=1",
         "labels":{
            "alertname":"Avg. Load (1 min) Alert",
            "host":"couchbase",
            "scope":"area",
            "severity":"host/node",
            "stand_name":"............................."
         },
         "startsAt":"2020-10-22T06:35:10Z",
         "status":"firing"
      },
.............
   ],
   "commonAnnotations":{
      
   },
   "commonLabels":{
      "host":"couchbase",
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "externalURL":"http://alertmanager_host:9095",
   "groupLabels":{
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "receiver":"common_receiver",
   "status":"firing",
   "version":"4",
   "groupKey":"{}/{scope=\"area\"}:{scope=\"area\", severity=\"host/node\", stand_name=\".............................\"}"
}

{
   "alerts":[
      {
         "annotations":{
            "description":"Алерт: Превышение нормализованной средней нагрузки за минуту  \nПорог: 90% за последние пять минут",
            "summary":"Avg. Load (1 min) Alert"
         },
         "endsAt":"2020-10-22T12:25:10.063520892+05:00",
         "generatorURL":"http://localhost:3001/d/JpOo_MXZz/alerts-host?fullscreen\u0026edit\u0026tab=alert\u0026panelId=86\u0026orgId=1",
         "labels":{
            "alertname":"Avg. Load (1 min) Alert",
            "host":"couchbase",
            "scope":"area",
            "severity":"host/node",
            "stand_name":"............................."
         },
         "startsAt":"2020-10-22T06:35:10Z",
         "status":"resolved"
      },
............
   ],
   "commonAnnotations":{
      
   },
   "commonLabels":{
      "host":"couchbase",
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "externalURL":"http://alertmanager_host:9095",
   "groupLabels":{
      "scope":"area",
      "severity":"host/node",
      "stand_name":"............................."
   },
   "receiver":"common_receiver",
   "status":"firing",
   "version":"4",
   "groupKey":"{}/{scope=\"area\"}:{scope=\"area\", severity=\"host/node\", stand_name=\".............................\"}"
}
```
Perhaps something else is required?
