### ISSUE TITLE
Multiple clusters sending to VictorOps sometimes causes alerts to be considered the same as entity_id overlaps

### ISSUE THREAD

**Issue by gboor** [prometheus/alertmanager#2408]
**What did you do?**
Set up alertmanager on several clusters and integrate it with VictorOps, which integrates with Slack.

**What did you expect to see?**
Different cluster messages to be routed to different Slack channels.

**What did you see instead? Under which circumstances?**
When 2 or more of the same alerts are happening on different clusters, all alerts are sent to just one channel.

**Environment**

* System information:

Kubernetes 1.16.13-gke.401

* Alertmanager version:

v0.21.0

* Prometheus version:

v2.18.2

* Alertmanager configuration file:
Relevant bits only
```
    receivers:
    - name: victorops
      victorops_configs:
      - api_key: xxxx
        routing_key: yyy
        message_type: '{{ .CommonLabels.severity }}'
        entity_display_name: '{{ .CommonLabels.alertname }}'
        state_message: "{{ range .Alerts }}{{ .Annotations.message }}\n{{ end }}"
        monitoring_tool: yyy
```

* Prometheus configuration file:
Not relevant

* Logs:
Not relevant

I know exactly why this happens; in the VictorOps integration here https://github.com/prometheus/alertmanager/blob/master/notify/victorops/victorops.go#L127 the entity_id for VictorOps is set to the hash of the group key. The group key is not unique per se across different clusters, causing this issue, as VictorOps considers the new alerts updates to an alert it already has firing.

This only occurs if 2 clusters fire similar alerts, like TargetDown on a common service. In that case, both alerts end up being treated as the same alert.

It should be possible to solve by changing how the entity_id is generated and using some sort of (configurable?) prefix to the group key before hashing it. Or making entity_id configurable, just like state_message and such, though that might be potentially dangerous.

**Comment by brian-brazil** [comment]
Can you please share your full configuration, and sample alert labels? The grouping key should never need to be configurable, it sounds like you're missing a label in your group_by.

**Comment by gboor** [comment]
Here is the alertmanager config, mostly generated by deploying prometheus-operator.

```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: "null"
  group_by:
  - alertname
  - instance
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
  - receiver: "null"
    match:
      alertname: KubeCPUOvercommit
  - receiver: "null"
    match:
      alertname: KubeAPILatencyHigh
  - receiver: victorops
    group_by:
    - alertname
    - instance
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 3h
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
- name: victorops
  victorops_configs:
  - send_resolved: true
    http_config: {}
    api_key: <secret>
    api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
    routing_key: yyyy
    message_type: '{{ .CommonLabels.severity }}'
    state_message: |-
      {{ range .Alerts }}{{ .Annotations.message }}
      {{ end }}
    entity_display_name: '{{ .CommonLabels.alertname }}'
    monitoring_tool: yyyy
templates: []
```

I don't think this is a label issue. Prometheus-operator generates a whole bunch of standard Kubernetes alerts, which are the same on all clusters. It stands to reason that the entity_id for victorops would also be the same for all these alerts, regardless of where they originate. I have no control over these alerts unless I want to manually rewrite all of them into my deployment config and miss out on updates.

Here is the definition of a general rule in the prometheus-operator config;

```
alert: TargetDown
expr: 100
  * (count by(job, namespace, service) (up == 0) / count by(job, namespace, service)
  (up)) > 10
for: 10m
labels:
  severity: warning
annotations:
  message: '{{ printf "%.4g" $value }}% of the {{ $labels.job }}/{{ $labels.service
    }} targets in {{ $labels.namespace }} namespace are down.'
```

If that triggers from 2 different clusters at the same time, the entity_id will be the same for both and it will overlap, causing VictorOps to consider the 2 alerts the same alert and to not look at the routing key.
