### ISSUE TITLE
Alertmanager UI status endpoint is not working

### ISSUE THREAD

**Issue by mshivanna** [prometheus/alertmanager#2409]
**What did you do?**
Accessed https://alertmanager.ourcompany/#/status

**What did you expect to see?**
Status, Cluster Status Version Information and Config details. 

**What did you see instead? Under which circumstances?**
Unexpected response from api: Problem with the value at json.cluster: { "peers": [], "status": "disabled" } Expecting an OBJECT with a field named name

**Environment**

* System information:
Running inside kubernetes:
uname -srm
Linux 3.10.0-957.10.1.el7.x86_64 x86_64

* Alertmanager version:

alertmanager --version
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
receivers:
- name: slack_webhook
  slack_configs:
  - api_url: https://hooks.slack.com/services/ourkey
    channel: '#in-cluster-stats-ext'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
    pretext: '{{ .CommonAnnotations.summary }}'
    send_resolved: true
    text: |-
      {{ range .Alerts }}
       *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
       *Description:* {{ .Annotations.description }}
       *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
      {{ end }}
    title: '{{ template "slack.default.title" . }}'
    title_link: '{{ template "slack.default.titlelink" . }}'
    username: '{{ template "slack.default.username" . }}'
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: slack_webhook
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
```
