### ISSUE TITLE
dict order matters or 'field email_config not found in type config.plain' error

### ISSUE THREAD

**Issue by rbabyuk** [prometheus/alertmanager#2413]
**create config for alertmanager where defined 'rereivers' email config, as a result if dict keys are sorted AM argues with error**

**AM works al right**

**error message in logs "field email_config not found in type config.plain"**

**k8s**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
        build user:       root@dee35927357f
        build date:       20200617-08:54:02
        go version:       go1.14.4

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
receivers:
- name: "null"
- name: opsgenie
  opsgenie_configs:
  - api_key: REDUCTED
- email_config:
  - to: REDUCTED@nosnch.in
  name: deadsmansnitch
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: opsgenie
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: "null"
templates: []
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=info ts=2020-11-04T11:04:09.025Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2020-11-04T11:04:09.028Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 8: field email_config not found in type config.plain"
```
