### ISSUE TITLE
alertmanager  route  pls help me

### ISSUE THREAD

**Issue by jicki** [prometheus/alertmanager#2416]
```yaml
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: team-X-mails
  routes:
  - match_re:
      service: ^(foo1|foo2|baz)$
    receiver: team-X-mails
    routes:
    - match:
        severity: critical
      receiver: team-X-pager
```

* Is it possible to write like this ?

```yaml

    routes:
    - match:
        severity: critical
        service: foo1
      receiver: team-X-pager

```
