### ISSUE TITLE
Critical recovery alarms will be sent repeatedly

### ISSUE THREAD

**Issue by sev7ndayyoo** [prometheus/alertmanager#2442]
**What did you do?**

When a critical problem is solved, the recovery alarm will be sent repeatedly more than ten times

**What did you expect to see?**

Send only once

**What did you see instead? Under which circumstances?**

Sent more than ten times

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

	`2.8.1`

* Alertmanager configuration file:
```
global:

  resolve_timeout: 60m
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'monitoring@163.com'
  smtp_auth_username: 'monitoring@163.com'
  smtp_auth_password: 'FA'
  smtp_require_tls: false

  # The Slack webhook URL.
  # slack_api_url: ''

route:
  # A default receiver
  receiver: "longhu_dba"

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  # group_by: ['env','instance','alertname','type','group','job']
  group_by: ['instance','alertname']
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait:      30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval:  5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 30m

  routes:
  - match:
      level: emergency
    receiver: longhu_dba
  - match:
      level: critical
    receiver: longhu_dba
  - match:
      level: warning
    receiver: longhu_dba

receivers:
- name: 'longhu_dba'
  webhook_configs:
  - send_resolved: true
    url: 'http://ares.longhu.net/api/call_the_police'
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
