### ISSUE TITLE
How to see which AlertManager server is configured from Prometheus?

### ISSUE THREAD

**Issue by yzhengwei** [prometheus/alertmanager#2451]
I found AlertManager Pod through K8s's POD discovery rule, but how can I see which POD I found on Prometheus?

```yaml
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  external_labels:
    prometheus: monitor/k8s
alerting:
  alertmanagers:
  - kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - monitor
    relabel_configs:
    - action: keep
      source_labels:
      - __meta_kubernetes_pod_name
      regex: alertmanager.*
rule_files:
- /etc/prometheus/rules/*.yml

```
