### ISSUE TITLE
alertmanager-config.yaml file for pagerduty_configs.details does not respect EventApi v2 spec

### ISSUE THREAD

**Issue by NargiT** [prometheus/alertmanager#2477]
**What did you do?**
Generate a nested object for pagerduty_configs.details field inside alertmanager-config.yaml

**What did you expect to see?**
amtool should not fail and alertmanager must allow nested objects as it's compatible with pagerduty event api v2

**What did you see instead? Under which circumstances?**

Error when running amtool and alertmanager 

**Environment**

* System information:

	Linux 5.3.0-46-generic x86_64

* Alertmanager version:

	alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
          build user:       root@dee35927357f
          build date:       20200617-08:54:02
          go version:       go1.14.4

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
global:
  resolve_timeout: "10m"

templates:
  - '/etc/alertmanager/secrets/pagerduty.integration.key.tmpl'

route:
  group_by: [ '...' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'black-hole'

  routes:
    - match_re:
        severity: "warning|critical"
      receiver: "all"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: [ 'alertname' ]

receivers:
  - name: "all"
    pagerduty_configs:
      - routing_key: '{{ template "pagerduty.integration.key" . }}'
        details:
          firing:       '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
          resolved:     '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
          num_firing:   '{{ .Alerts.Firing | len }}'
          num_resolved: '{{ .Alerts.Resolved | len }}'
          toto: [ "hello", "hoho" ] #this line will fail
```

* Logs:
```
level=error ts=2021-02-05T10:57:07.101Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/
alertmanager.yaml err="yaml: unmarshal errors:\n  line 91: cannot unmarshal !!seq into string"
```

This is of course expected as alertmanager is not able to handle the `toto` list we added, but if I craft the same with a curl and contact directly `events.pagerduty.com/v2/enqueue` it get what I wanted.

```
curl -X POST -d '{"routing_key": "XXXX", "event_action": "trigger", "payload": {"summary": "one alert", "source": "curl", "severity": "critical", "custom_details": { "toto": ["hello", "hoho"]}}}' https://events.pagerduty.com/v2/enqueue
```
