### ISSUE TITLE
field max_alerts not found in type config.plain

### ISSUE THREAD

**Issue by taolint** [prometheus/alertmanager#2503]
**What did you do?**
when reload alertmanager.yml with webhook config which has max_alerts set

**What did you expect to see?**
alcf.Load success, and reload should succeed

**What did you see instead? Under which circumstances?**
fail to reload and get the error:  field max_alerts not found in type config.plain"

* Alertmanager version:
v0.21.0

* Alertmanager configuration file:
```
    global:
      smtp_smarthost: ***
      smtp_from: ***
      smtp_require_tls: true
      smtp_auth_username: ***
      smtp_auth_password: ***
      resolve_timeout: 1h

    receivers:
    - name: alertstorage-receiver
      webhook_configs:
      - url: 'http://alertstorage:2113/webhook'
        send_resolved: false
        max_alerts : 1

    route:
      group_wait: 10s
      group_interval: 5m
      receiver: alertstorage-receiver
      repeat_interval: 3h
```
