### ISSUE TITLE
Slack app support ?

### ISSUE THREAD

**Issue by eddycharly** [prometheus/alertmanager#2513]
Sorry if the question has already been answered. 

Is there any plan to support regular slack app ?

It looks like webhooks are quite limited, especially in the area of sending notifications to different channels.

**Comment by weakcamel** [comment]
Erm, but there already is one: https://prometheus.io/docs/alerting/latest/configuration/#slack_config

**Comment by joshm91** [comment]
@weakcamel You're correct in that is a way to send alerts to Slack, but what OP is talking about is support for an actual [Slack App](https://slack.com/intl/en-gb/apps) which, among other things, would allow a single app for posting to multiple channels rather than the current method of needing to create a separate webhook in Slack and a separate `slack_config` for each channel you want to send alerts to (ie, different team channels).

**Comment by weakcamel** [comment]
I see, thanks for elaborating @joshm91 .

Given this statement: https://github.com/prometheus/alertmanager/pull/1422#issuecomment-398448667

> The intended way to do arbitrary integrations is to write something designed to take in the webhook, and then it will send out an appropriately encoded request to the system you wish to integrate with. It's not intended that the webhhook will directly integrate with arbitrary other protocols, as that would be intractable from a maintenance standpoint.

I  wouldn't hope that this is ever implemented yet of course, no harm in expressing interest.

**Comment by eddycharly** [comment]
Yeah, i have the feeling that chances regular slack app is supported is pretty low.

FWIW i managed to solve the issue with a legacy webhook app (this particular app can post messages is multiple channels by overriding the target channel in the message payload).
Not perfect but it did the job in my case.

**Comment by roidelapluie** [comment]
Hello,

We have reverted the moratorium and so I would accept this if someone writes a PR.

**Comment by tom0010** [comment]
It seems the grafana team have integrated alertmanager from version 8.x, from their version they have the ability to insert a slack bot token, see photo attached. Maybe this can be looked into because of this: https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifiers/slack.go

Is there a possibility in looking into this again? 
It seems the slack functionality is becoming increasingly outdated, the current version of alertmanager is still using legacy messaging formatting: https://github.com/prometheus/alertmanager/issues/2217 

![image](https://user-images.githubusercontent.com/41154665/133255638-4b274dbe-6a40-4795-b592-a0aa1f9715ba.png)

**Comment by dmitriishaburov** [comment]
For anyone interested: it seems it's already possible to set up with existing functionality, due to `chat.postMessage` method accepting same format as webhook.
I've managed to send notifications as Slack App with following config:
```
slack_configs:
- send_resolved: true
  channel: "#my-channel"
  api_url: https://slack.com/api/chat.postMessage
  http_config:
    authorization:
      credentials: xoxb-my-bot-token
```

**Comment by bizrad** [comment]
I had this same issue when setting up grafana cloud for the first time. The kubernetes integration uses alertmanager.

Here is my config from my tenant from my config page at a URL like: https://mystack.grafana.net/alerting/admin?alertmanager=grafanacloud-mystack-ngalertmanager

```
{
  "template_files": {},
  "template_file_provenances": {},
  "alertmanager_config": {
    "global": {
      "http_config": {
        "bearer_token": "xoxb-YOUR-TOKEN-HERE"
      },
      "resolve_timeout": "5m",
      "slack_api_url": "https://slack.com/api/chat.postMessage",
      "smtp_require_tls": false
    },
    "receivers": [
      {
        "name": "k8s",
        "slack_configs": [
          {
            "api_url": "https://slack.com/api/chat.postMessage",
            "channel": "#YOUR-CHANNEL-HERE",
            "link_names": false,
            "send_resolved": true,
            "short_fields": false
          }
        ]
      }
    ],
    "route": {
      "continue": false,
      "group_by": [
        "grafana_folder",
        "alertname"
      ],
      "group_interval": "5m",
      "group_wait": "30s",
      "matchers": [],
      "mute_time_intervals": [],
      "receiver": "k8s",
      "repeat_interval": "1h",
      "routes": [
        {
          "continue": false,
          "group_by": [],
          "group_interval": "5m",
          "group_wait": "30s",
          "matchers": [
            "severity=warning"
          ],
          "mute_time_intervals": [],
          "receiver": "k8s",
          "repeat_interval": "30m",
          "routes": []
        }
      ]
    }
  }
}
```
Would be great if this were fixed in documentation here some day: https://prometheus.io/docs/alerting/latest/configuration/

Hope this helps anyone trying to do this with Grafana Cloud.

**Comment by su-tiko** [comment]
I was looking into this and while it's true that using `https://slack.com/api/chat.postMessage` as `apiURL` works well, it's still impossible to use it as default receiver without _leaking_ the slack token. I mean, you can get it to work if you add the slack `Authorization` bearer token in `httpConfig`, however this means that it will be sent to any other receiver, leaking the token.

Some fixes to this I can think of are:

1. Add global `slack_api_token` and `slack_api_token_file` settings to set this token value and then include it on Slack's default httpConfig.
2. Define httpConfigs per receiver or per host. Similar to that, something like a global `slack_api_http_config`.

I believe the first is easy to implement and also easy to understand. I can work on a MR for this if you find it useful 😄

**Comment by ArsenyBelorukov** [comment]
a part of my config with sending alerts to different public channels:
```
      route:
        <...>
        routes:
        <...>
        - receiver: 'slack-team-receiver'
          matchers:
            - slack_channel =~ ^#[a-z0-9._-]+$
      receivers:
      <...>
      - name: 'slack-team-receiver'
        slack_configs:
          - api_url: "https://slack.com/api/chat.postMessage"
            channel: '{{ index ((index .Alerts 0).Labels) "slack_channel" }}'
            icon_emoji: ":prometheus:"
            send_resolved: true
            title: '{{ template "slack.title" .  }}'
            text: '{{ template "slack.text" .  }}'
            http_config:
              authorization:
                credentials_file: /etc/alertmanager/secrets/slack-credentials/bearer-token
```
