### ISSUE TITLE
Allow logic on send_resolved fields

### ISSUE THREAD

**Issue by oholdswo** [prometheus/alertmanager#2524]
**Change request**
It'd be useful to have certain alerts fire when resolved but not others. For example, "info" alerts could fire once but not again when resolved, since some alerts are resolved instantly and just fire the resolved notification after the group_interval.

An example of such an alert is the following to alert when a container restarts:
```
- alert: Container Restarted
    annotations:
      summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} namespace was restarted
      severity: info
    expr: |
      sum(increase(kube_pod_container_status_restarts_total{namespace!="kube-system",pod_template_hash=""}[1m])) by (container,pod,namespace) > 0
    for: 0m
``` 

In that example I'd want to use the severity annotation to decide the value for the `send_resolved` field, e.g.:
```
send_resolved: '{{ if eq .CommonAnnotations.severity "info" -}}false{{- else -}}true{{- end }}'
```

This change should be achievable by changing the `send_resolved` fields in the various `X_config` blocks to a `tmpl_string` instead of a `boolean`, to allow for some logic to be performed on the alerts labels/annotations. 

**Environment**
Alertmanager version: 0.21
