### ISSUE TITLE
Repeat interval rules

### ISSUE THREAD

**Issue by aclowkey** [prometheus/alertmanager#2595]
This is a common case I see in my organization. There are lots of alerts. And many of them don't get addressed for a long time which can be weeks, months, never. However, the receivers are configured for a repeat interval of "4h" - which creates a lot of spam email notification

I was wondering if a more complex repeat interval would make sense in such a case? i.e. After 1 week slows down the duration to once a day, then once a week, etc.

What do you think?

Here's my general idea 
```yaml
# Instead of a single repeat interval value, have several which will be selected
# based on the duration of the alert.
# repeat_interval: 4h
repeat_intevals:
- duration_interval: 1d
  repeat_interval: 4h
- duration_interval: 7d
  repeat_interval: 1d
# ..etc
```
When the alert has been firing for 1d or less, it will send a notification every 4 hours. same for 7d, etc.
