### ISSUE TITLE
Different evaluation_interval for each alert rule

### ISSUE THREAD

**Issue by sam75mmm** [prometheus/alertmanager#2598]
I have different rules in my alert rules file and need different  evaluation_interval for every rule,
for example rule1 needs to evaluate every 5 minutes and  rule2 needs to evaluate on daily base, I other words I don't need more than one alerts email per day for rule2. 
I tried to use "for" in my alert-rules file:

```
groups:
- name: <alert name>
  rules:
  - alert: rule1
    expr: probe_success == 0
    for: 5m
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"

  - alert: rule2
    expr: ( probe_ssl_earliest_cert_expiry - time() ) < 1209600  #two week
    for: 1d
    labels:
      severity: "critical"
    annotations:
      summary: "Server {{ $labels.instance }} SSL is expiring"
```
and in my alertmanager config file:
```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval:  5m
  repeat_interval: 1h
  receiver: Monitoring-team
```
It seems  **for: 1d**  is not working I even tried using hours, minutes or seconds but didn't work too, 
I'm just wondering is this a bug or something like that?
