### ISSUE TITLE
Yaml configuration does not work

### ISSUE THREAD

**Issue by nadiasvertex** [prometheus/alertmanager#261]
I'm using the latest image from Docker hub.

alertmanager -config.file /etc/prometheus/alertmanager.yml

```
alertmanager, version 0.0.4 (master@917c055) 
 build user:       @afbbf75ae75d 
 build date:       20151209-13:37:33
 go version:       1.5.1 
 msg="Error loading configuration from /etc/prometheus/alertmanager.yml: line 1.0: unknown field name \"global\" in io_prometheus_alertmanager.AlertManagerConfig" file=load.go line=49

```
config file is:

```
global:
  smtp_smarthost: '12.12.12.12:25'
  smtp_from: 'email@address'

receivers:
- name: 'interested-parties'
  email_configs:
  - to: 'me@address'

route:
  receiver: 'interested-parties'
  group_wait: 60s
  group_interval: 5m
  repeat_interval: 8h

```

Note that the previous brace-based configuration works fine.
