### ISSUE TITLE
Opsgenie Integration send_resolved doesn't work

### ISSUE THREAD

**Issue by florianbeer** [prometheus/alertmanager#2616]
**What did you do?**
Configured alerts in Prometheus and set up Alertmanager to send firing alerts to Opsgenie. Set `send_resolved` to `true`.

**What did you expect to see?**
When alerts are no longer firing, I expect them to be closed in Opsgenie.

**What did you see instead? Under which circumstances?**
Alerts stay open in Opsgenie, even if they are no longer visible in Alertmanager and have to be closed manually in Opsgenie.

**Environment**

* System information:
Linux 4.19.0-12-amd64 x86_64

* Alertmanager version:
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4

* Prometheus version:
prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_from: <redacted>
  smtp_hello: localhost
  smtp_smarthost: <redacted>
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.eu.opsgenie.com/
  opsgenie_api_key: <secret>
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: opsgenie
  group_by:
  - '...'
  routes:
  - receiver: deadmansswitch
    match:
      alertname: DeadMansSwitch
    repeat_interval: 1m
  - receiver: opsgenie
    continue: true
    group_wait: 10s
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 30m
receivers:
- name: deadmansswitch
  email_configs:
  - send_resolved: false
    to: <redacted>
    from: <redacted>
    hello: localhost
    smarthost: <redacted>
    headers:
      From: <redacted>
      Subject: '{{ template "email.default.subject" . }}'
      To:<redacted>
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: opsgenie
  opsgenie_configs:
  - send_resolved: true
    http_config: {}
    api_key: <secret>
    api_url: https://api.eu.opsgenie.com/
    message: '{{ range .Alerts }}{{ .Annotations.title }}{{ end }}'
    description: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    source: '{{ template "opsgenie.default.source" . }}'
    responders:
    - name: k8s
      type: escalation
    priority: '{{ range .Alerts }}{{ .Labels.severity }}{{ end }}'
templates: []
```

**Comment by vyshakrupeek** [comment]
Any updates on this?

**Comment by bizrad** [comment]
I have a similar config and am also seeing this issue.

**Comment by florianbeer** [comment]
Hello, sorry the status is still the same on my installation.
`group_interval` is left on default (5m) but recoveries are not arriving at Opsgenie. How would I be able to switch on debug logs on Alertmanager when it is deployed via Helm on a Kubernetes Cluster?

My Config at the moment:
```
    route:
      group_by: [...]
      group_wait: 10s
      receiver: "opsgenie"
      repeat_interval: 30m
...
    receivers:
      - name: "opsgenie"
        opsgenie_configs:
          - responders:
              - name: 'k8s'
                type: 'escalation'
            send_resolved: true
            priority: '{{ range .Alerts }}{{ .Labels.severity }}{{ end }}'
            message: '{{ range .Alerts }}{{ .Annotations.title }}{{ end }}'
            description: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
```
