### ISSUE TITLE
Multiple receivers not working as expected

### ISSUE THREAD

**Issue by talonx** [prometheus/alertmanager#2617]
**What did you do?**
Set up two receivers to different Slack channels. The relevant config is as follows 

```
route:
  receiver: 'slack1'

  group_by: ['cloud_service']
  group_wait: 30s
  group_interval: 15s

  repeat_interval: 5m

  routes:
  - receiver: 'slack2'
    matchers:
    - severity="critical"

receivers:
- name: 'slack1'
  slack_configs:
  - channel: 'alerts1'
    send_resolved: true
    api_url: 'xxxx'
- name: 'slack2'
  slack_configs:
  - channel: 'alerts2'
    send_resolved: true
    api_url: 'xxx'
```
`api_url` s for each are different. There is no global URL defined in the global section.

**What did you expect to see?**
Alerts that have critical severity should go to slack2, and all other alerts should go to slack1

**What did you see instead? Under which circumstances?**
I tested this where alerts were sent to Alertmanager, one group with critical and another with warning severity. Only the ones with warning went to slack1 and nothing was received on slack2. 

**Environment**
Ubuntu 18.04.5

* System information:

Linux 5.4.0-72-generic x86_64

* Alertmanager version:

```
alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build user:       root@b595c7f32520
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64
```
* Prometheus version:
v2.15.2

* Alertmanager configuration file:
```
See above.
```

* Prometheus configuration file:
```
Not relevant
```
I ran AM in debug mode. What I could see was that both the kinds of alerts (warning and critical) were received in AM from Prometheus but AM was firing to only one channel. 

Anything I'm doing wrong here in the configuration?
