### ISSUE TITLE
Feature Req: Trigger alert if any of the match_re(or match) matches.

### ISSUE THREAD

**Issue by shubhamc183** [prometheus/alertmanager#2629]
`Alertmanager` > `routes` > `match_re` > CAN we Trigger Alert if **ANY** match_re condition matches?

I have two kinds of alerts;

1. 1st one has a `namespace` label but doesn't team_tag label
2. 2nd one has a `team_tag` label but doesn't have a `namespace` label

I want to catch both kinds of alerts in **ONE receiver**. The below route is just for one team like this we have N teams.
```
routes:
- receiver: 'devops-critical'
  match:
    severity: 'critical'
  match_re:
    # ---> WANT TO TRIGGER ALERT IF namespace OR team_tag regex matches
    namespace: '(ingress-nginx|istio-.*|keda|kube-.*|logging|loki|)'
    team_tag: '(devops-tools)'
```

Thought possible solutions

1. I can add two `receiver` pointing to same the same endpoint(slack channel/teams/email...) and use them to check separately once for namespace and once for team_tag. But this will result in duplication.
2. I can maybe use `alert_relabel_configs` on the Prometheus side to inject dummy values either when `namespace` or `team_tag` is missing and append that dummy value to in above regex. But this will increase complexity on others SREs.
