### ISSUE TITLE
Problem with alertmanager inhibit rule

### ISSUE THREAD

**Issue by jeyrce** [prometheus/alertmanager#2638]
Alertmanager version: 0.21.0

problem:

> The inhibit rules took no effect to resolved alerts.

```
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warn
  equal:
  - _alertingTargetUuid
  - _alertingRuleUuid
```

The configuration worked for "firing" alerts, but while resolved, I received both critical and warn level alert info the seem label pair
