### ISSUE TITLE
alertmanager cluster node diff

### ISSUE THREAD

**Issue by hw4liu** [prometheus/alertmanager#2656]
The same message is sent to the same cluster (three nodes). Normally, one message will be sent, but I have received three messages from different nodes. The startTime is a few seconds apart. This is the scenario where I am doing a stress test. What happened, is my way of using it wrong?

i need help, brother~

**Environment**

* System information:

Linux 5.4.0-40-generic x86_64

* Alertmanager version:

	0.22.0

* Alertmanager configuration file:
```
iglobal:
  resolve_timeout: 30d

route:
  group_by: ['app', 'id', 'rule', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'webhook'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['id']

```
![image](https://user-images.githubusercontent.com/76958850/127295882-107b0025-06d8-4e44-8f24-9eddc486ff33.png)

![image](https://user-images.githubusercontent.com/76958850/127296088-27d2ca0e-1f4b-4a8a-bf73-40005e5cd685.png)

![image](https://user-images.githubusercontent.com/76958850/127296215-c77273c3-6602-4067-b99c-8842d88b7298.png)
