### ISSUE TITLE
match_re is not working while configuring reciever

### ISSUE THREAD

**Issue by ankurnigam** [prometheus/alertmanager#2661]
Hi Team ,

I configured to use alert name to send alerts to slack,but it's not working :

```yaml
 - receiver: 'fdi-slack'
    group_by: '["alertname","oci_region","dbname","prd_pod","instance","resource_name","resource_type"]'
    match_re:
      alertname: "fusion:instance:status.*"
```

I can see alert is getting fired in prometheus , I can see slack URL is also correct.

I am not sure if I can use alertname for match or not.

Please help.
