### ISSUE TITLE
The request body sent through webhook is empty

### ISSUE THREAD

**Issue by LeonYanghaha** [prometheus/alertmanager#2664]
I use the following configuration. When alert occurs, I can normally receive mail using my mailbox, but when I use webhook, I find that the request body is empty and I can't parse any information of alert. What's the matter? Who can tell me, thank you very much。

```

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1m
  receiver: 'web_hook'
 
receivers:
  - name: 'email'
    email_configs:
    - to: 'my-email@a.com'
  - name: 'web_hook'
    webhook_configs:
    - url: 'http://localhost:8080/prometheusalert'

```

This is my version information ,I installed it on the MAC using docker, and Prometheus installed it the same way
```
Version Information
Branch: HEAD
BuildDate:20210602-07:50:37
BuildUser:root@b595c7f32520
GoVersion:go1.16.4
Revision:44f8adc06af5101ad64bd8b9c8b18273f2922051
Version:0.22.2
```
