### ISSUE TITLE
Wrong extra labels added to a firing alert

### ISSUE THREAD

**Issue by nedvna** [prometheus/alertmanager#2676]
**What did you do?**

Created an alerting rule (with fewer labels than usual)

**What did you expect to see?**

Alerting rule only with existing labels (the few ones)

**What did you see instead? Under which circumstances?**

Got extra labels that I didn't expect, some had wrong values.

We have alerting for BIRD routing daemon (using bird-exporter), several rules.
It's actually 2 alerts with same name but different severity, warning when 1 session is down, and critical when all of them are down.
Critical one is below:

```
  - alert: BirdNoImports
    annotations:
      description: All {{ $labels.proto }} sessions are unused! External connectivity
        affected
      details: '{{ $value }} prefixes imported totally'
      grafana: /d/35hmwqyMz/bird?orgId=1&from=now-30m&to=now&var-source=prometheus_...
      summary: Bird No Imports
    expr: sum by (instance,import_filter,proto) (bird_protocol_prefix_import_count{proto="BGP"})
      == 0
    labels:
      responsible: cloudinfra
      severity: critical
```

Labels for time series for critical alert looked as follows (from Prometheus GUI, I suppose):

```
{alertname="BirdNoImports", alertstate="firing", import_filter="import_default", instance="haproxy-1.staging.companyname.org:9324", proto="BGP", responsible="cloudinfra", severity="critical"}
{alertname="BirdNoImports", alertstate="firing", import_filter="import_default", instance="haproxy-2.staging.companyname.org:9324", proto="BGP", responsible="cloudinfra", severity="critical"}
```

The virtual machines originally had a label "environment=staging" in fact but it's not here.
Which kinda made sense, as due to sum by() I lost the environment label and some other stuff.
So the time series look OK for now. To me it looks that the prometheus part of alerting flow works normally.

The weird thing was that in fact it in the end they got the environment="production" label somehow and that's how I got alert via webhook with labels filled :)
The warning alert, which has no sum by, worked fine, labels were preserved and ended up being correct.

I decided to check the alertmanager inner state.
```
cat /var/lib/alertmanager/nflog | strings
...
{}/{severity=~"^(?:critical|problem)$"}/{environment="production"}/{department="cloudops"}/{responsible="cloudinfra"}:{alertname="BirdNoImports", datacenter="virtual", environment="production", project="infrastructure", severity="critical"}
alerts-cloud-infra
webhook
...
```

that was... surprising.
Department and environment labels shouldn't have been there. Looks like the AM added them.

So, to sum up, what we have here is.
Typically, we have the label "environment" in the "original" time series stored in prometheus.
Due to the way I created the alert rule (sum by), it was removed during evaluation later, which is logical.
But sometime on the way from prometheus to alertmanager (and the to webhook), the label was re-added, and got a wrong value assigned to it, which ended up being sent via webhook.
I checked the label source one more time (it's our custom label and it originates from our DCIM discovery, doesn't really matter here though), and for these nodes it couldn't have had the "production" value. Actually, it's never been "production", as it's the "staging" pool.

My guess is that this label does exist somewhere and was taken from some other node's alert in the firing state but I have no idea how it ended up it the wrong node's alert.
Maybe some structure is re-used when creating alerts for different nodes, if the current node has certain labels they're written into it and are correct but if it doesn't have any, labels from the previous one are not overwritten/ cleared and thus remain?..

I can't publish the AM nflog or look up original metrics (ALERTS) in prometheus (only in remote_write storage) anymore, as it's past retention time now but I think the issue is still reproducible.
You just have some firing alerts with custom labels still active and then fire another alert with labels fewer than usual. Or maybe it's the "alert-with-same-name" thing and the "critical" one inherited the "warning"'s labels, not sure.

**Environment**

* System information:

Linux 4.15.0-76-generic x86_64

* Alertmanager version:

alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build user:       root@b595c7f32520
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64

* Prometheus version:

prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
  build user:       root@2915dd495090
  build date:       20210701-15:20:10
  go version:       go1.16.5
  platform:         linux/amd64
