### ISSUE TITLE
Alert manager SNS receiver have option to publish message with json format

### ISSUE THREAD

**Issue by qinxx108** [prometheus/alertmanager#2678]
A lot of use-case for sns is to use lambda to post process message and publish to slack etc..
It will be helpful if we can have an option to enable the web-hook similar json format for sns messages so that post-processing will be easier 

webhook: https://prometheus.io/docs/alerting/latest/configuration/#webhook_config

* Alertmanager configuration file:
```
alertmanager_config: |
  global:
    resolve_timeout: 5s
  route:
    receiver: example-sns
    group_interval: 1m
    group_by: [cluster, alertname]
  receivers:
    - name: example-sns
      sns_configs:
      - api_url: https://sns.us-west-2.amazonaws.com
        topic_arn: arn:aws:sns:us-west-2:xxx:My-Topic
        attributes:
          key: severity
          value: SEV2
  inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['low_connected_users']
```
