### ISSUE TITLE
AlertManager cluster HA getting failed

### ISSUE THREAD

**Issue by allaboutopensource** [prometheus/alertmanager#2681]
**What did you do?**
I setup 2 alert managers and trying to setup HA between them using --cluster.peer address but it is failing. i am using:

/usr/local/bin/alertmanager --cluster.peer=<ip-of-alert-manager-2>:9094

**What did you expect to see?** i want to see the cluster state as ready with the peer ip addresses in GUI. 

**What did you see instead? Under which circumstances?** i am seeing the cluster ready state but with the ip address of the self host only not the peer ip address.

**Environment**

* System information:
alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build user:       root@
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64

	insert output of `uname -srm` here
Linux 4.18.0-147.el8.x86_64 x86_64

* Alertmanager version: 0.22.2

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

2.29.0-rc.2
--
	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
global:
  resolve_timeout: 3m
  slack_api_url: <api>
templates:
- '/etc/alertmanager/templates/*.tmpl'
receivers:
- name: slack
  slack_configs:
  - channel: '#alert-slack'
    send_resolved: true

route:
  group_by:
  - alertname
  - cluster
  - service
  group_interval: 5m
  group_wait: 30s
  receiver: slack
  repeat_interval: 3h

```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=info ts=2021-08-18T19:05:42.164Z caller=cluster.go:184 component=cluster msg="setting advertise address explicitly" addr=<ip-address> port=9094
level=error ts=2021-08-18T19:05:42.164Z caller=main.go:246 msg="unable to initialize gossip mesh" err="create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 9094: listen tcp 0.0.0.0:9094: bind: address already in use"

```
