### ISSUE TITLE
Feature: Exclude existing alerts in group notification

### ISSUE THREAD

**Issue by FireEmerald** [prometheus/alertmanager#2686]
**What did you do?**
Let's say you got 2 firing alerts **in a single group** in alertmanager.

```
[firing]
alertname=ServerOff
server=EUW1
[firing]
alertname=ServerOff
server=EUW2
```

If now one alert is resolved or added, the alertmanager creates a notification about this change but the notification includes **all existing alerts** of that group and **not only** the alerts with **state changes**.

Perhaps i missed a config value which enables this feature already(?) 🤔

**What did you expect to see?**
Expected notification content:
```
[resolved]
alertname=ServerOff
server=EUW2
```

**What did you see instead? Under which circumstances?**
Actual notification content when EUW2 gets resolved:
```
[firing]
alertname=ServerOff
server=EUW1
[resolved]
alertname=ServerOff
server=EUW2
```

**Environment**

* Alertmanager configuration file:
```
route:
  # Root node as fallback if none child route matches.
  receiver: fallback
  group_by:
  - alertname
```
