### ISSUE TITLE
Warning: msg="Notify attempt failed, will retry later" attempts=1 err="'require_tls' is true (default) but \"localhost:25\" does not advertise the STARTTLS extension"

### ISSUE THREAD

**Issue by cmonty14** [prometheus/alertmanager#2688]
**What did you do?**
systemctl start prometheus-alertmanager.service
**What did you expect to see?**
No warnings, no errors.
**What did you see instead? Under which circumstances?**
`Sep 01 15:19:35 vlcspsumamon prometheus-alertmanager[9723]: level=warn ts=2021-09-01T13:19:35.843Z caller=notify.go:674 component=dispatcher receiver=lve-admin-mails integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="'require_tls' is true (default) but \"localhost:25\" does not advertise the STARTTLS extension"`

**Environment**

* System information:
Linux 5.3.18-24.78-default x86_64

* Alertmanager version:
alertmanager, version 0.21.0 (branch: non-git, revision: non-git)
 build user:       abuild@goat14
 build date:       20210119-17:11:12
 go version:       go1.11.13

* Prometheus version:
prometheus, version 2.27.1 (branch: non-git, revision: non-git)
 build user:       abuild@goat02
 build date:       20210726-09:57:55
 go version:       go1.16.6
 platform:         linux/amd64

* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: "localhost:25"
  smtp_from: "alertmanager@vlcspsumamon.devsys.net.sap"
[...]
```

In my understanding the default setting is STARTLS.
However, this local SMTP is not using STARTLS.

How must I configure alertmanager to overcome this warning?

THX
