### ISSUE TITLE
Mattermost channel with upper case letter not accepted

### ISSUE THREAD

**Issue by antonionappi88** [prometheus/alertmanager#2692]
Hello,
I'm trying to configure AlertManager to send notification to Mattermost. I don't have control of the mattermost server so i cannot install the plugin. I tried via webhook without luck, until I switch to slack_configs.

But I'm still having some issue with channels that have capital letters in the name. When I add capital letters the AlertManager cannot find the channel in mattermost, if I change to lower case the name of the channel and update the AlertManager configuration it works. 
Basically this doesn't work:

```
receivers:
- name: 'mattermost'
  slack_configs:
    - api_url: "https://my-mattermost.url.com/hooks/whatever"
      channel: 'MY-alerting' # Real name MY-alerting
```

but this yes:
```
receivers:
- name: 'mattermost'
  slack_configs:
    - api_url: "https://my-mattermost.url.com/hooks/whatever"
      channel: 'my-alerting' # Real name my-alerting
```

* Alertmanager version:

alertmanager, version 0.23.0 (branch: HEAD, revision: 61046b17771a57cfd4c4a51be370ab930a4d7d54)
* Alertmanager configuration file:
```
global:
route:
  receiver: mattermost
  group_by:
  - environment
  group_wait: 1s
  repeat_interval: 1s
receivers:
- name: 'mattermost'
  slack_configs:
    - api_url: "https://my-mattermost.url.com/hooks/whatever"
      channel: 'MY-alerting'```
```

* Logs:
```
level=error ts=2021-09-03T13:53:11.306Z caller=dispatch.go:354 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="mattermost/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"MY-alerting\": unexpected status code 404: {\"id\":\"web.incoming_webhook.channel.app_error\",\"message\":\"Couldn't find the channel.\",\"detailed_error\":\"\",\"request_id\":\"d9jgt6a9ibrrxexskrtkoxcmbh\",\"status_code\":404}"
```
