### ISSUE TITLE
amtool support multiple alertmanagers

### ISSUE THREAD

**Issue by igaskin** [prometheus/alertmanager#2704]
**What did you do?**
When managing multiple alertmanagers, it is required to either update the `--alertmanager.url` flag or update the `~/.config/amtool/config.yml` with the new alertmanager URL.  This is inconvenient for admins that manage multiple alertmanagers.

**What did you expect to see?**
Similar to the concept of a  "context" in a `KUBECONFIG` `amtool` should also support executing against a given alertmanager in a context or optionally all alertmanagers.

**What did you see instead? Under which circumstances?**

**Environment**

* Alertmanager version:

```
 amtool --version
amtool, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.16.5
  platform:         darwin/amd64
  ```

* Amtool configuration file:
_example proposal config file_
```
current-context: bar.local
alertmanagers:
- alertmanager.url: 'https://bar.local'
  author: igaskin
  require-comment: false
  tls.insecure.skip.verify: false
  name: bar.local
- alertmanager.url: 'https://foo.local'
  author: igaskin
  require-comment: true
  tls.insecure.skip.verify: false
  name: foo.local
```

This change would require modifying the current unmarshaling behavior, which assumes that the `config.yml` used by amtool only contains a map of string<->string.
https://github.com/prometheus/alertmanager/blob/main/cli/config/config.go#L48
