### ISSUE TITLE
unknown auth mechanism：NTLM

### ISSUE THREAD

**Issue by bilibilibalala** [prometheus/alertmanager#2723]
**What did you do?**

When using alertmanager in enterprise, which often come with a closed network and private email server (exchange server). Thus email notify with NTLM auth support is needed

**What did you expect to see?**

alertmanager should send email notify through exchange server

**What did you see instead? Under which circumstances?**
smtp_require_tls: false
unknown auth mechanism：NTLM
**Environment**

* System information:

	kubernetes 1.14

* Alertmanager version:

	alertmanager 0.18.0

* Prometheus version:

	prometheus 2.11

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  smtp_smarthost: "1xxxx:25"
  smtp_from: "xxxx"
  smtp_auth_username: "xxxx"
  smtp_auth_password: "xxxx"
  smtp_require_tls: false
route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: "test-mails"
 
receivers:
- name: "test-mails"
  email_configs:
  - to: "xxxxx"
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
``
![截屏2021-09-30 15 55 49](https://user-images.githubusercontent.com/46049544/135411283-43a55ea1-ffa7-4d12-96a6-88a88caedf32.png)
`
