### ISSUE TITLE
Alertmanager route alert incorrectly

### ISSUE THREAD

**Issue by sunlintong** [prometheus/alertmanager#2738]
**What did you do?**
Alertmanager can't route my alert rightly. And this's occasionally.

**What did you expect to see?**
```json
{
    "endsAt": "0001-01-01T00:00:00Z",
    "labels": {
        "id": "/kubepods/burstable/podf9aa1ee1-e88e-4171-99d0-fec0c9b82530",
        "job": "kubelet",
        "pod": "slt-5555446dff-p7gs5",
        "node": "k8s-node2-125",
        "cluster": "dev",
        "service": "kube-promethe-kubelet",
        "endpoint": "https-metrics",
        "instance": "172.16.23.125:10250",
        "severity": "error",
        "alertname": "container-memory-limit-big",
        "namespace": "istio-system",
        "prometheus": "gemcloud-monitoring-system/gemcloud",
        "gems_alertname": "container-memory-limit-big",
        "gems_namespace": "qqq",
        "k8s_cloud_cluster": "dev"
    },
    "status": "firing",
    "startsAt": "2021-10-13T09:11:29.281Z",
    "annotations": {
        "value": "1.073741824e+09",
        "message": "istio-system slt-5555446dff-p7gs5 memory limit 1.073741824e+09"
    },
    "fingerprint": "bd727f22aec141aa",
    "generatorURL": "http://prometheus.gemcloud-minitoring-system:9090/graph?g0.expr=container_spec_memory_limit_bytes+%3E+1.7825792e%2B08&g0.tab=1"
}
```
As you see, this alert has a label `namespace: istio-system`, I **don't** want to receive it at receiver `qqq-gemcloud-gemcloud-default-webhook`. But actually, I receved.
And it occurs occasionally, why?

**What did you see instead? Under which circumstances?**
 I receved.

**Environment**
K8s environment,  3 alertmanager replicas, 1 prometheus replicas.

* System information:

Linux 5.4.0-050400rc1-generic x86_64

* Alertmanager version:

```bash
$ alertmanager --version
alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build user:       root@b595c7f32520
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64
```

* Prometheus version:
```
$ prometheus --version
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64
```

* Alertmanager configuration file:
```yaml
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: "null"
  group_by:
    - job
  continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  routes:
    - receiver: qqq-gemcloud-null
      group_by:
        - gems_namespace
      match:
        namespace: qqq
      continue: true
      routes:
        - receiver: qqq-gemcloud-webhook-site
          group_by:
            - gems_namespace
          match:
            gems_alertname: container-memory-limit-big
            gems_namespace: qqq
          continue: true
          group_interval: 1m
          repeat_interval: 1m
        - receiver: qqq-gemcloud-gemcloud-default-webhook
          group_by:
            - gems_namespace
          match:
            gems_alertname: container-memory-limit-big
            gems_namespace: qqq
          continue: true
          group_interval: 1m
          repeat_interval: 1m
inhibit_rules:
  - source_match:
      gems_alertname: container-memory-limit-big
      namespace: qqq
      severity: critical
    target_match:
      gems_alertname: container-memory-limit-big
      namespace: qqq
      severity: error
    equal:
      - gems_namespace
      - pod
receivers:
  - name: qqq-gemcloud-gemcloud-default-webhook
    webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        url: http://gems-agent.gemcloud-system:8041/alert
        max_alerts: 0
  - name: qqq-gemcloud-webhook-site
    webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        url: https://webhook.site/3ee7543a-40c7-4e8c-9ce6-a096cfd2ff54
        max_alerts: 0
  - name: qqq-gemcloud-null
templates: []
```
