### ISSUE TITLE
basic_auth_users not work

### ISSUE THREAD

**Issue by MrYHM** [prometheus/alertmanager#2743]
error log err="yaml: unmarshal errors:\n  line 1: field basic_auth_users not found in type config.plain"

**What did you do?**

alertmanager.yml add parameter basic_auth_users

**What did you expect to see?**

Access to alertmanager web requires login with username and password

* System information:

	`docker images quay.io/prometheus/alertmanager:v0.23.0`

* Alertmanager version:

	`v0.23.0` 

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
basic_auth_users:
  testuser: haha
global:
  resolve_timeout: 5m
  http_config:
    xxxx: xxx
route:
  xxx: xx
receivers:
  xxx: xx

```

* Logs:
```
level=error ts=2021-10-18T10:42:47.456Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" file=/etc/config/alertmanager.yml err="yaml: unmarshal errors:\n  line 1: field basic_auth_users not found in type config.plain"
```
