### ISSUE TITLE
Alertmanager is sending non existing alert

### ISSUE THREAD

**Issue by tretos53** [prometheus/alertmanager#2744]
**What did you do?**
I installed alert manager with prometheus using this chart: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml

`prometheus-community:Chart:14.10.0:App:2.26.0`

**What did you expect to see?**
I have an alert in Prometheus:
```
    - alert: PrometheusTargetMissing
      expr: up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        identifier: '{{ $labels.instance }}'
        summary: Prometheus target missing `{{ $labels.instance }}`
        description: "A Prometheus target has disappeared. An exporter might be crashed. `{{ $labels.cluster }}`"
```
- When I go to https://prometheus/alerts this alert is not there.
- When I go to https://alertmanager/#/alerts this alert is not there.
- When I go to `https://prometheus/graph?g0.expr=up%20%3D%3D%200&g0.tab=1&g0.stacked=0&g0.range_input=1h` I don't get any results

- I get below alert to my slack every 5 minutes (together with other current alerts):
```
AlertManagerAPP  12:36
[FIRING:28] Monitoring Event Notification
Alert: Prometheus target missing xxx - critical
 Description: A Prometheus target has disappeared. An exporter might be crashed. xxx
 Details:
  • alertname: PrometheusTargetMissing
  • beta_kubernetes_io_arch: amd64
Show more

AlertManagerAPP  12:41
[FIRING:21] Monitoring Event Notification
Alert: Prometheus target missing xxx - critical
 Description: A Prometheus target has disappeared. An exporter might be crashed. ``
 Details:
  • alertname: PrometheusTargetMissing
  • endpoint: metrics
Show more

[FIRING:25] Monitoring Event Notification 12:46
Alert: Prometheus target missing xxx - critical
 Description: A Prometheus target has disappeared. An exporter might be crashed. ``
 Details:
  • alertname: PrometheusTargetMissing
  • endpoint: metrics
Show more
```

**What did you see instead? Under which circumstances?**
Alertmanager shouldn't be sending this alert.

**Environment**

* System information:
```
/alertmanager $ uname -srm
Linux 4.14.243-185.433.amzn2.x86_64 x86_64
```

* Alertmanager version:
```
/alertmanager $ alertmanager --version
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4
```

* Prometheus version:
```
/prometheus $ prometheus --version
prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  slack_api_url: <secret>
  pagerduty_url: xxx
  opsgenie_api_url: xxx
  wechat_api_url: xxx
  victorops_api_url: xxx
route:
  receiver: slack
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    http_config: {}
    api_url: <secret>
    channel: '#xxx'
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
    title_link: '{{ template "slack.default.titlelink" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: |-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }}
        *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
templates: []
```

* Prometheus configuration file:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 1m
<Config is long so only added the first few lines>
```

* Logs:
```
How to get logs?
```
