### ISSUE TITLE
PagerDuty configuration: unable to set severity field using template

### ISSUE THREAD

**Issue by Shanti-G** [prometheus/alertmanager#2757]
**What did you do?**
I am trying to set the severity using templated label with below pagerduty configuration in alertmanager:

```
  pagerduty_configs:
  - send_resolved: true
    routing_key: xxx
    description: |-
      test-cluster.{{ range .Alerts }}{{ .Annotations.summary }}.
      {{ end }}
    severity: '{{ .Labels.pdseverity }}'
```
I am setting `.Labels.pdseverity` on an alert in Prometheus.

**What did you expect to see?**
The alertmanager should be able to trigger a PD alert with its severity set based on the templated label.

**What did you see instead? Under which circumstances?**
PagerDuty v2 API allows severity of alert to be set, default being `error`. 
With the above configuration, though an alert is in `firing` state in Prometheus, I don't see the triggered alert in PD.

However, when I directly set the value, like below, I get to see the incident in PD with the given severity, i.e. warning:
```
  pagerduty_configs:
  - send_resolved: true
    routing_key: xxx
    description: |-
      test-cluster.{{ range .Alerts }}{{ .Annotations.summary }}.
      {{ end }}
    severity: 'warning'
```
Would like to know how to set the severity field with templated value. Thanks in advance.

**Environment**
* Alertmanager version: 
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4

* Prometheus version:
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64

* Logs: No error logs from alertmanager to indicate configuration error.
