### ISSUE TITLE
send alert directly from grafana to alertmanager ? 

### ISSUE THREAD

**Issue by saibug** [prometheus/alertmanager#2773]
Hi folks, 

I know  it's not a good way to ask question,

**What i need :** 

Send alerting from grafana directly to AlerManager. 

**AlertManager Config** 

```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'mattermost_notif'
receivers:
- name: 'mattermost_notif'
  slack_configs:
  - send_resolved: true 
    api_url: 'https://mattermost.tech/hooks/d6ypspsz7jg69x4qiyiessaxdr'
    channel: 'alerting'
    http_config:
      proxy_url: 'http://local-proxy:3128'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
```

**Issue**

alert notification sent to grafana does not contain desctiption, thresholds, etc ... 

 screen below 
 
 
![image](https://user-images.githubusercontent.com/32570331/143424072-407a104d-73be-4738-9d3c-b10445bdbf95.png)

Thank you in advance
