### ISSUE TITLE
New feature: Mute when time is outside time_interval

### ISSUE THREAD

**Issue by dubyte** [prometheus/alertmanager#2778]
Currently mute_intervals allow to express the interval where the alarm won't be sent. 
But would be useful to mute in the complement of the mute_time_interval.

Let's check at this example:
```
  routes:
  - receiver: devs
    mute_time_intervals:
      - offhours
      - holidays
    continue: true
  - receiver: monitoring
    active_time_intervals: 
      - offhours
      - holidays
  time_intervals:     
  - name: offhours
    time_intervals:
    - ...
  - name: holidays
    time_intervals:
    - ...

```
"mute_time_intervals" keyword to describe the intervals will be deprecated. Instead the configuration will use "time_intervals". When in a route there is active and mute time intervals, the mute_time_interval will have higher precedence.
For example:
```
 - receiver: group_a
    active_time_intervals:
    - officeHours
   mute_time_intervals:
   - lunchHour
```
Let's imagine that there is a time interval for officeHours 9am - 5pm and a lunch hour in the middle of the day. With this the alert will be sent during officeHours but it wont receive during the lunch.  

Updated about:
- Deprecation of mute_time_interval
- new time_intervals config
- mute_time_interval has higher precedence than active_time_intervals
