### ISSUE TITLE
alertmanager_notifications_failed_total metric not contains url tag

### ISSUE THREAD

**Issue by like-inspur** [prometheus/alertmanager#2786]
**What did you do?**
I found alertmanager_notifications_failed_total metric only contains integration tag, not contains url tag
When there are multi urls under one integration such as webhook like below
If multi urls don't work. there is only one alert becuse alertmanager_notifications_failed_total metric don't distinguish url

**What did you see instead? Under which circumstances?**
alertmanager_notifications_failed_total{host="mgt09",instance="alertmanager-2:9093",integration="webhook",job="lma"}	98299

**Environment**

* Alertmanager version:
0.23.0

* Alertmanager configuration file:
```
    receivers:
    - name: default
      webhook_configs:
      - send_resolved: true
        url: http://alert-analyzer.logging:8299/rca/v1/alerts/action/check
      - send_resolved: true
        url: http://10.110.110.110:80/test
```
