### ISSUE TITLE
Add notification sent count and duration metrics with tag receiver name

### ISSUE THREAD

**Issue by zhaojinxin409** [prometheus/alertmanager#2793]
**What did you expect to see?**

Add notification sent count and duration metrics with tag `receiver name`, i think it will be useful to know the receiver status.

* Example:

Alertmanager config:

```
receivers:
- name: notify-a
  webhook_configs:
  - url: http://url-a
- name: notify-b
  webhook_configs:
  - url: http://url-b
```

Metrics:

```
alertmanager_notification_sent_total{recevier="notify-a"} 2
alertmanager_notification_sent_failed_total{recevier="notify-a"} 1
alertmanager_notification_sent_duration{recevier="notify-a", le=0.1} 1
```
