### ISSUE TITLE
Alternannger TSL Verrify false,please help !!!

### ISSUE THREAD

**Issue by huanghe1993** [prometheus/alertmanager#2801]
TSL verfiy fasle
```

receivers:
- name: 'web.hook'
  webhook_configs:
    - url: 'https://******:9301/monitor/serviceAlert'
      http_config:
        tls_config:
          ca_file: /StarAtlas/certificate/root.pem
          cert_file: /StarAtlas/certificate/server.crt
          key_file: /StarAtlas/certificate/server.key
          insecure_skip_verify: false
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=info ts=2021-10-13T02:34:52.339Z caller=tls_config.go:191 msg="TLS is disabled." http2=false 
```
