### ISSUE TITLE
I hope when alert in silence status, I can receive the notice that alert has been resolved 

### ISSUE THREAD

**Issue by hw4liu** [prometheus/alertmanager#2805]
**What did you expect to see?**

I hope when an alert is in silence status, I can receive the notice that the alert has been resolved .

when I use alertmanager, I am sure the message be sent to alertmanager must has endsAt time， 

Let me describe how we used,
1. when an alert has been sent to the user
2. user ack this alert, make the alert be silenced 15 minutes
3. but just 5 minutes this alert has been resolved, and now this alert during be silenced time, I want to receive resolved message 

* Alertmanager version:

```
  alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 30d

route:
  group_by: ['app', 'id', 'rule', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'webhook'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['id']

receivers:
- name: 'webhook'
  webhook_configs:
    - url: 'http://127.0.0.1:8888/xxxxx'
```
