### ISSUE TITLE
Prometheus link in Alertmanager notification loads latest data

### ISSUE THREAD

**Issue by igtsekov** [prometheus/alertmanager#2852]
**What did you do?**

I have an Alertmanager up and running. I created an alert rule that check the status of the RS:
``` yaml
      - alert: ReplicaSetReplicasDown
        expr: |
            kube_replicaset_status_replicas 
            - kube_replicaset_status_ready_replicas > 0
        for: 10m
        labels:
          severity: critical
        annotations:
          description: "*Count:* `{{ $value }}` \n
            *ReplicaSet:* `{{ $labels.replicaset }}` \n
            *Namespace:* `{{ $labels.namespace }}` \n
            *Cluster:* `{{ $labels.monitor }}`"
          summary: ReplicaSet pods are down
```
Everything is working as expected. When the pods are down I get a notification in Slack. Today I was investigating an old alert and saw that the link that the alert manager sends to Slack is loading the latest data in Prometheus.

**What did you expect to see?**

If the alert was triggered at 15:06 on 17.02.22 I expect the link in the notification to open the Prometheus and load the metrics from that timeframe.

**What did you see instead? Under which circumstances?**

Every time I open the link I am presented with the current data.

Is there a way to achieve the desired behaviour? I go over the documentation but did not find anything.
