### ISSUE TITLE
Setting web.external-url doesn't work for "Source" link

### ISSUE THREAD

**Issue by aleksvujic** [prometheus/alertmanager#2858]
I am running Alert manager behind reverse proxy (Traefik). I set `web.external-url` in `docker-compose.yml` to my public URL so that all users can access Alert manager by clicking links in emails. Setting `web.external-url` doesn't seem to solve this problem completely. Here is the email that I received from Alert manager:

![image](https://user-images.githubusercontent.com/17112542/159502222-1dfa5a49-3d11-4871-a1b7-b27447bac552.png)

This is my `docker-compose.yml` file:

```yml
alertmanager:
  image: prom/alertmanager:v0.23.0
  volumes:
    - ./alertmanager:/etc/alertmanager
  command:
    - '--config.file=/etc/alertmanager/config.yml'
    - '--storage.path=/alertmanager'
    - '--web.external-url=https://alertmanager-test.company.com'
  deploy:
    replicas: 1
  restart_policy:
    condition: on-failure
```

Links marked with green rectangle lead to correct URL (`https://alertmanager-test.company.com`), but link marked with red rectangle leads to `<Docker container ID>/graph?...`.

Am I doing something wrong or is this a bug?
