### ISSUE TITLE
Proposal: allow to mute individual alerts with mute_time_interval

### ISSUE THREAD

**Issue by anemyte** [prometheus/alertmanager#2861]
Hi!

I need to mute an alert with a specific set of labels during specific day time. At this moment, I can do that by creating a dedicated route and assigning a `mute_time_interval` to it, or by injecting this logic into the alert expression. Either way it would be a mess.

I thought that my requirement could be fulfilled by mixing together an inhibition rule and a mute time interval. That is, instead of `source_matchers` and `equal` I could have used a name of a mute time interval. Something like this:
```yaml
- target_matchers:
    - alertname=foo
    - instance=bar
    - job=spam
    - type=eggs
  mute_time_intervals:
    - night
```

What do you think?
