### ISSUE TITLE
Emails not being received via Sendgrid

### ISSUE THREAD

**Issue by obrienrobert** [prometheus/alertmanager#2871]
**What did you do?**
Configured Alertmanager to send email alerts via Sendgrid. I created an email route and receiver and provided the correct Sendgrid credentials. The emails are not being received via Sendgrid.

After enabling debug levels logs in Alertmanager, the logs indicate that the alert has been successfully received, and the email successfully sent (see the logs section at the bottom of this issue).

**What did you expect to see?**
I expect to see emails being received in my inbox via Sendgrid.

**What did you see instead? Under which circumstances?**
The email is not received. I have tested the route and receiver using the Gmail SMTP server and the alerts are received successfully into my inbox. I have also successfully sent an email to SendGrid via a curl command from one of the pods inside the Openshift cluster.

**Environment**

* System information:

	`Linux 4.18.0-305.34.2.el8_4.x86_64 x86_64`

* Alertmanager version:

	```
  alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4
	```

* Prometheus version:

     ```
  prometheus, version 2.22.2 (branch: HEAD, revision: de1c1243f4dd66fbac3e8213e9a7bd8dbc9f38b2)
  build user:       root@f7d7e91063f0
  build date:       20201116-12:43:43
  go version:       go1.15.5
  platform:         linux/amd64
    ```

* Alertmanager configuration file:
     ```
      global:
        resolve_timeout: 5m
        smtp_smarthost: smtp.sendgrid.net:587
        smtp_from: test@alerts.com
        smtp_auth_username: <SENDGRID_USERNAME>
        smtp_auth_password: <SENDGRID_API_KEY>
      route:
        receiver: default-receiver
        group_wait: 5m
        group_interval: 30s
        repeat_interval: 12h
        routes:
        - receiver: smtp
          match:
            severity: warning
      receivers:
      - name: smtp
        email_configs:
        - send_resolved: true
          to: user@mydomain.com
     ```

* Logs:
   ```
   level=debug ts=2022-03-31T10:37:06.695Z caller=dispatch.go:138 component=dispatcher msg="Received alert" 
   alert=alertName[e8c3eda][active]
   level=debug ts=2022-03-31T10:37:12.383Z caller=notify.go:685 component=dispatcher receiver=smtp integration=email[0] 
   msg="Notify success" attempts=1
   ```
