### ISSUE TITLE
Pagerduty Integration (events API V2): Updates same alert instead of creating new one

### ISSUE THREAD

**Issue by mindhash** [prometheus/alertmanager#2874]
**What did you do?**
Setup Alert manager integration with Pagerduty.  The configuration is setup to group by ['alertname']. I also have event orchestration setup in PD to create incident against the alert. 

**What did you expect to see?**
Each alert with different name in alert manager should result in a separate alert (+incident) in pager duty. 

**What did you see instead? Under which circumstances?**
For some reason, pagerduty considers every new alert as an update to existing alert and performs the update. 
![image](https://user-images.githubusercontent.com/10277894/161273202-593e1834-0d3b-4c3d-9fa9-451c5bb8e196.png)
In this image, each of the updates are in fact separate alerts (different alert name)

**Environment**
AlertManager, Pagerduty 

* System information:

	insert output of `uname -srm` here
        Darwin 19.6.0 x86_64
* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)
        0.23.0 

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```

global:
  resolve_timeout: 5m 
  http_config:
      follow_redirects: true
  smtp_from: alertmanager@x.io
  smtp_hello: localhost
  smtp_smarthost: localhost:25
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
    receiver: default-receiver
    continue: false
    routes:
        - receiver: p1
        continue: true
        group_wait: 30s
        group_interval: 30s
        repeat_interval: 4h
    receivers:
        - name: default-receiver
        email_configs:
            - send_resolved: false
            to: default@email.com
            from: alertmanager@example.org
            hello: localhost
            smarthost: localhost:25
            html: '{{ template \"email.default.html\" . }}'
            require_tls: true
        - name: p1
        pagerduty_configs:
            - send_resolved: true
            http_config:
                follow_redirects: true
            routing_key: <secret>
            url: https://events.pagerduty.com/v2/enqueue
            client: SigNoz Alert Manager
            client_url: http://localhost:8080/alerts
            description: "description"
            severity: '{{ (index .Alerts 0).Labels.severity }}'
            component: test2111}}
                
templates: []
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
