### ISSUE TITLE
Alerts being queued and eventually pruned for unknown reason

### ISSUE THREAD

**Issue by nathanaelweber** [prometheus/alertmanager#2881]
**What did you do?**
We connected 3 prometheus instances to a pair of alertmanager (2 Peers) with different alert rule state each of that instance with a pair HA couple.
We tried to reproduce the issue with artificial alert data, but it seems the issue is not reproducable with artificial load, we can process multiple thousands of artificial alerts, however on real alerts the issue is appearing under thousand alerts.
A longer investigation within sourcecode did not (yet) lead to finding the root cause of the problem.

We would like to receive support for this issue and are willing to compensate work expenses provided previous agreement.
**What did you expect to see?**
We expected alerts being processed and cpu / memory / network used to process as many alerts as possible.

**What did you see instead? Under which circumstances?**
A ratio of alerts are being queued and not processed after a specific amount of load and the increase of cpu / memory / network resources does not seem to help and cpu / memory consumption keeps low while alerts are being queued and eventually dropped at the regular queue pruning interval.

**Environment**
Prometheus and Alertmanager within openshift pods

* System information:

$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.9.15    True        False         58d     Cluster version is 4.9.15

* Alertmanager version:
docker.bin.sbb.ch/prom/alertmanager:v0.21.0

* Prometheus version:
docker.bin.sbb.ch/prom/prometheus:v2.31.1

* Alertmanager configuration file:
```
global:
  smtp_from: [details in favor of privacy omitted]
  smtp_smarthost: [details in favor of privacy omitted]

route:
  receiver: 'test-iMON'
  group_by: [...]
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 5h
  routes:
  - match:
      alertname: quite_hour
    receiver: blackhole
    group_by: ['app', 'stage', 'instance', 'service', 'severity']
  - match_re:
      stage: "PROD"
      alertname: "ADL.*"
      clusterStatus: ACTIVE
    receiver: ADL
    group_by: ['app', 'stage', 'instance', 'service', 'severity']
  - match:
      receiver: DevRel
    receiver: DevRel
    group_by: [receiver]
  - match:
      receiver: Peng
    receiver: Peng
    group_by: [receiver]

  # Teams receiver matching:
  
  - match:
      receiver: DevRelTeams
    receiver: DevRelTeams
    group_by: [receiver]
  - match:
      receiver: TestTeams
    receiver: TestTeams
    group_by: ['app', 'stage', 'instance', 'service', 'severity']
    repeat_interval: 24h
  - match:
      receiver: PengTeams
    receiver: PengTeams
    group_by: [receiver]
    repeat_interval: 24h
  - match:
      receiver: PengDevRelTeams
    receiver: PengDevRelTeams
    group_by: [receiver]
  # End of teams receiver matching section

  - match:
      receiver: Delfin
    receiver: Delfin
    group_by: [receiver]
  - match:
      receiver: ADL
    receiver: ADL
    group_by: [receiver]
  - match_re:
      type: heartbeat
      instance: PRCS|ARCS|IRCS|TRCS|VICTOR
    repeat_interval: 3s
    group_wait: 3s
    group_interval: 3s
    receiver: 'prod-iMON'
  - match_re:
      sendSolved: 0
      instance: PRCS|ARCS|IRCS|TRCS|VICTOR
    receiver: prod-no-resolve-iMON
  - match:
      type: heartbeat
    repeat_interval: 3s
    group_wait: 3s
    group_interval: 3s
    receiver: 'test-iMON'
  - match:
      sendSolved: 0
    receiver: test-no-resolve-iMON
  - match_re:
      instance: PRCS|ARCS|IRCS|TRCS|VICTOR
    receiver: 'prod-iMON'

inhibit_rules:
# No notifications outside of business hours or at weekend.
- source_match:
    alertname: quite_hour
  target_match_re:
    time_window: 6to21

receivers:
- name: DevRel
  email_configs:
  - to: xxx
  - to: xxx

- name: Peng
  email_configs:
  - to: xxx

- name: ADL
  email_configs:
  - to: xxx
  - to: xxx

- name: Delfin
  email_configs:
  - to: xxx

# Teams receiver definitions:
- name: TestTeams
  webhook_configs:
  - url: [receiver details in favor of privacy omitted]
    send_resolved: true

- name: PengTeams
[receiver details in favor of privacy omitted]
- name: DevRelTeams
[receiver details in favor of privacy omitted]
- name: PengDevRelTeams
[receiver details in favor of privacy omitted]
# End of Teams channel section

- name: 'prod-iMON'
  webhook_configs:
  - url: [receiver details in favor of privacy omitted]
    send_resolved: true
    # this is the maximum concurrent alerts that are allowed to be firing for this endpoint,
    # supplement alerts are put onto queue "alertmanager_cluster_messages_queued" and dumped on regularly basis (all 15 Minutes)
    max_alerts: 1000
  - url: [receiver details in favor of privacy omitted]
    send_resolved: true
    max_alerts: 1000
  - url: [receiver details in favor of privacy omitted]
    send_resolved: true
    max_alerts: 1000
  
- name: 'prod-no-resolve-iMON'
  webhook_configs:
  - url:[receiver details in favor of privacy omitted]
    send_resolved: false
    max_alerts: 1000
  - url: [receiver details in favor of privacy omitted]
    send_resolved: false
    max_alerts: 1000
  - url: [receiver details in favor of privacy omitted]
    send_resolved: true
    max_alerts: 1000

- name: 'test-iMON'
  webhook_configs:
  - url: [receiver details in favor of privacy omitted]
    send_resolved: true
    max_alerts: 1000
  
- name: 'test-no-resolve-iMON'
  webhook_configs:
  - url: [receiver details in favor of privacy omitted]
    send_resolved: false
    max_alerts: 1000

- name: blackhole
```

* Prometheus configuration file:
```
global:
    scrape_interval:     15s
    evaluation_interval: 2m
    external_labels:
      prometheus: monalesy-monitoring-rcs
      prometheus_replica: $(HOSTNAME)
alerting:
  alert_relabel_configs:
    - action: labeldrop
      regex: prometheus_replica
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - monalesy-alertpreprocessor-a-dev-1:8487
      - monalesy-alertpreprocessor-b-dev-1:8487

rule_files: ['/etc/prometheus/self_monitoring.rules', '/etc/prometheus/generated_rules/*.rules', '/etc/prometheus/static_config_rules/*.rules']

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 10s
  static_configs:
  - targets:
    - localhost:9090

# more scrape targets omitted since they are not subject to be relevant here...

###### Generated config head: job_extra_argument ######
#tls_config:
#  ca_file: /etc/prometheus_secret/ca.crt
#  cert_file: /etc/prometheus_secret/prometheus.crt
#  key_file:  /etc/prometheus_secret/prometheus.key
#  insecure_skip_verify: true
######
###### Generated config start ######
###### Generated config end ######
```

* Logs:
```
Alertmanager log (repeated the following message):
level=warn ts=2022-03-21T09:29:49.001Z caller=delegate.go:272 component=cluster msg="dropping messages because too many are queued" current=12405 limit=4096
```
![alertmanager-source-trackdown](https://user-images.githubusercontent.com/40006685/162394951-bcb48708-8367-4c46-9f23-f72a5e85eaeb.png)
