### ISSUE TITLE
Expose Alert data structure in alert fields

### ISSUE THREAD

**Issue by jrkt** [prometheus/alertmanager#2911]
**What did you do?**
Tried to use the `StartsAt` field on the [alert](https://prometheus.io/docs/alerting/latest/notifications/#alert) data structure in an alert notification template.

**What did you expect to see?**
Access to the [alert](https://prometheus.io/docs/alerting/latest/notifications/#alert) data structure in the templates.

**What did you see instead? Under which circumstances?**
The only fields available in the alert templates are .Value, .Labels, .ExternalLabels, and .ExternalURL. 

We have annotations in our alerts that link to the logs and dashboard for the particular service. I want to be able to timebox my logs and dashboard urls to the timeframe of when the alert fired in case the alert is not checked right away so that at any time these urls are clicked on for an alert, it links directly to the timeframe of when the alert occurred.

Example of what I need to be able to do:
```yaml
  groups:
  - name: test-rule
    rules:
    - alert: test-alert
      annotations:
        logs_url: https://www.my-logs-url.com?starts-at={{ .Alert.StartsAt }}
        dashboard_url: https://www.my-dashboard-url.com?starts-at={{ .Alert.StartsAt }}
```

Is there any reason why .Alert is not accessible in these templates?
