### ISSUE TITLE
Handle envirement var

### ISSUE THREAD

**Issue by KoVaLsKy2010** [prometheus/alertmanager#2917]
**handle envirement vars**
*.yml files dose not handle envirement  deom docker

**Environment**

* Alertmanager configuration file NOW:
```
 receivers:
      - name: 'telegram'
        telegram_configs:
          - send_resolved: true
            api_url: 'https://api.telegram.org'
            bot_token: '123456:ASDFGH-:LKHHGFGD-WERWERWER'
            chat_id: 12345
            parse_mode: 'Markdown'
```
For example
```
receivers:
      - name: 'telegram'
        telegram_configs:
          - send_resolved: true
            api_url: 'https://api.telegram.org'
            bot_token: ${TELEGRAM_TOKEN}
            chat_id: ${TELEGRAM_ADMIN}
            parse_mode: 'Markdown'
```
docker-compose.yml

```
alertmanager:
        image: prom/alertmanager
        ports:
            - 9093:9093
        environment:
            - TELEGRAM_ADMIN=12345
            - TELEGRAM_TOKEN='123456:ASDFGH-:LKHHGFGD-WERWERWER'
```
