### ISSUE TITLE
Time intervals don't check all fields

### ISSUE THREAD

**Issue by soreshin** [prometheus/alertmanager#2935]
**What did you do?**
I made this config.
```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - receiver: 'web.hook'
      matchers:
        - alertname ="TestAlert"
      active_time_intervals:
        - wednesdays
​
time_intervals:     
  - name: wednesdays
    time_intervals:
    - times:
      - start_time: 12:00
        end_time: 19:00
    - weekdays:
      - wednesday
```

**What did you expect to see?**
I expected that alerts with alertname="TestAlert" will be sent only on Wednesday  during exact time since 12:00 till 19:00.
And I expected that these alerts (alertname="TestAlert") will be muted all other time.

**What did you see instead? Under which circumstances?**
Instead of my expectation - alertmanager sent notifications about this alert (alertname="TestAlert") **EVERY** day during time since 12:00 till 19:00.

I made few tries and noticed that if I use config without `<time_range>`, then option `active_time_intervals:` works properly - Alertmanager sends alerts only on one specified day.
For example:
```
time_intervals:     
  - name: wednesdays
    time_intervals:
    - weekdays:
      - wednesday
```

There is a quote in [documentation](https://prometheus.io/docs/alerting/latest/configuration/#time_interval-0):
> For an instant of time to match a complete time interval, **all** fields must match.

But in my case it looks like time interval matches either `<weekday_range>` or `<time_range>` instead of.

**Environment**

* System information:

```
[root@prometheus alertmanager]# uname -srm
Linux 3.10.0-1160.66.1.el7.x86_64 x86_64
```

* Alertmanager version:

```
[root@prometheus alertmanager]# ./alertmanager --version
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64
```

* Prometheus version:

```
[root@prometheus prometheus]# ./prometheus --version
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'web.hook'

  routes:
    - receiver: 'web.hook'
      group_by: [...]
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30s
      match:
        alertname: InstanceIsDown
      active_time_intervals:
        - wednesdays

time_intervals:
  - name: wednesdays
    time_intervals:
    - weekdays:
      - wednesday
    - times:
      - start_time: 12:00
        end_time: 19:00

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:9087/alert/222488922'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
```

* Prometheus configuration file:
It isn't relevant

* Logs:
There are not any errors in logs.

**Comment by roidelapluie** [comment]
Please try

```
time_intervals:
- name: wednesdays
  time_intervals:
  - times:
    - start_time: 12:00
      end_time: 19:00
    weekdays:
    - wednesday
```
