### ISSUE TITLE
telegram: Bad Request: can't parse entities: Unsupported start tag \"\" at byte offset

### ISSUE THREAD

**Issue by rmalenko** [prometheus/alertmanager#2960]
Hello,
I have got this error
```
ts=2022-06-23T08:16:30.131Z caller=notify.go:732 level=warn component=dispatcher receiver=telegram integration=telegram[0] msg="Notify attempt failed, will retry later" attempts=1 err="telegram: Bad Request: can't parse entities: Unsupported start tag \"\" at byte offset 265 (400)"
```

```yaml
global:
  http_config:
    follow_redirects: true
  resolve_timeout: 1m
  telegram_api_url: https://api.telegram.org
inhibit_rules:
- equal:
  - alertname
  - cluster
  - service
  source_matchers:
  - severity="critical"
  target_matchers:
  - severity="warning"
receivers:
- name: telegram
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 23825:AA
    chat_id: 217****
    disable_notifications: false
    http_config:
      follow_redirects: true
    parse_mode: HTML
    send_resolved: true
route:
  group_by:
  - alertname
  - cluster
  - service
  - alerttype
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: telegram
  repeat_interval: 1m
  routes:
  - matchers:
    - severity=~"warning|critical"
    receiver: telegram
```

**Comment by reitermarkus** [comment]
I am getting a similar error

```
ts=2022-06-25T23:47:56.079Z caller=notify.go:732 level=warn component=dispatcher receiver=telegram integration=telegram[0] msg="Notify attempt failed, will retry later" attempts=1 err="telegram: Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\\' (400)"
```

with this receiver config:

```yaml
      - name: telegram
        telegram_configs:
          - api_url: https://api.telegram.org
            bot_token: '{{ telegram.bot_token }}'
            chat_id: {{ telegram.chat_id }}
            parse_mode: MarkdownV2
            send_resolved: true
```

Seems like the message is not properly escaped.


----


In another script I am using I escaped it using this

```sh
      escape() {
        sed -E 's/(\\|_|\*|\[|]|\(|\)|`|~|>|#|\+|-|=|\||\{|}|\.|!)/\\\1/g'
      }
```
