### ISSUE TITLE
ERROR: function "default" not defined

### ISSUE THREAD

**Issue by Rohlik** [prometheus/alertmanager#2975]
**What did you do?**
I Created API v2 integration in PagerDuty service.
Then I tried bash script (bellow), basically cURL, to generate dummy alert to see if PagerDuty integration will work.

*The Script:*
```
#!/usr/bin/env bash

name=fooAlert
url='http://localhost:9093/alertmanager/api/v1/alerts'
bold=$(tput bold)
normal=$(tput sgr0)
runbook_url='https://runbooks.prometheus-operator.dev/runbooks/general/targetdown/'
generate_post_data() {
  cat <<EOF
[{
  "status":"$1",
  "labels": {
    "alertname":"${name}",
    "service":"dummy",
    "severity":"error",
    "pod":"alertmanager-kps-$RANDOM-0",
    "container":"alertmanager",
    "cluster":"aws1",
    "namespace":"monitoring",
    "runbook":"${runbook_url}"
  },
  "annotations": {
    "summary": "High latency is high!",
    "description": "There is more than too much latency"
  }
  $2
  $3
}]
EOF
}

echo "${bold}Firing alert ${name} ${normal}"
printf -v startsAt ',"startsAt" : "%s"' $(date --rfc-3339=seconds | sed 's/ /T/')
POSTDATA=$(generate_post_data 'firing' "${startsAt}")
curl $url --data "$POSTDATA" --trace-ascii /dev/stdout
echo -e "\n"

echo "${bold}Press enter to resolve alert ${name} ${normal}"
read

echo "${bold}Sending resolved ${normal}"
printf -v endsAt ',"endsAt" : "%s"' $(date --rfc-3339=seconds | sed 's/ /T/')
POSTDATA=$(generate_post_data 'firing' "${startsAt}" "${endsAt}")
curl $url --data "$POSTDATA" --trace-ascii /dev/stdout
echo -e "\n"
```

**What did you expect to see?**
Dummy alert should be created in PagerDuty.
Problem is not with script itself as it works well with different Alertmanager configured against _Prometheus_ (API v1) PagerDuty integration.

**What did you see instead? Under which circumstances?**
PagerDuty alert wasn't created and I can see error in log (see bellow).

**Environment**

* System information:

	`Linux 5.10.0-15-amd64 x86_64`

* Alertmanager version:

      alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
        build user:       root@265f14f5c6fc
        build date:       20220325-09:31:33
        go version:       go1.17.8
        platform:         linux/amd64

* Prometheus version:

`N/A`

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
route:
  receiver: monitoring_pd_low
  group_by:
  - alertname
  routes:
  - receiver: "null"
    matchers:
    - alertname = InfoInhibitor
  - receiver: "null"
    matchers:
    - alertname = Watchdog
  - receiver: "null"
    matchers:
    - severity = info
  - receiver: monitoring_pd
    matchers:
    - severity =~ "warning|critical|error"
    repeat_interval: 24h
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
inhibit_rules:
- target_matchers:
  - severity = warning
  source_matchers:
  - severity = critical
  equal:
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - severity = warning
  equal:
  - namespace
- target_matchers:
  - severity = info
  source_matchers:
  - alertname = InfoInhibitor
receivers:
- name: "null"
- name: monitoring_pd
  pagerduty_configs:
  - routing_key: <redacted>
    description: '{{ template "pd.gd.title" . }}'
    details:
      container: |
        {{ range .Alerts }} {{printf "%s \n" .Labels.container }} {{ end }}
      description: |
        {{ range .Alerts }} {{ printf "%s \n" .Annotations.description }} {{ end }}
      runbook_url: '{{ template "pd.gd.runbook" . }}'
      summary: >
        {{ range .Alerts }}
        {{printf "%s \n" .Annotations.summary }}
        {{ end }}
    severity: '{{ .CommonLabels.severity | default("critical") | toLower }}'
    class: '{{ .Labels.alertname }}'
    component: '{{ range .Alerts }}{{ .Labels.pod }}{{ end }}'
    group: '{{ range .Alerts }}{{ .Labels.namespace }}{{ end }}'
templates:
- /etc/alertmanager/*.tmpl
```
pd.tmlp:
```
{{ define "pd.gd.title" }}
  [{{ .CommonLabels.cluster_name | toUpper }}]
    {{- if eq .Status "firing" }}
      [{{ .Status | toUpper }}:{{ .Alerts.Firing | len }}]
    {{ end }}
    {{- printf " - " }}
    {{- if gt (len .Alerts.Firing) 1 }}
      {{- .CommonLabels.alertname }}
    {{- else }}
      {{- .CommonLabels.alertname }}
      {{ if .CommonLabels.pod }}
        ({{ .CommonLabels.pod }})
      {{ end }}
    {{- end }}
  {{- end }}
```

* Prometheus configuration file:
```
I have just Alertmanager.
```

* Logs:
```
ts=2022-07-01T14:40:04.297Z caller=dispatch.go:165 level=debug component=dispatcher msg="Received alert" alert=fooAlert[ea0b4a4][active]
ts=2022-07-01T14:40:34.297Z caller=dispatch.go:517 level=debug component=dispatcher aggrGroup="{}/{severity=~\"warning|critical|error\"}:{alertname=\"fooAlert\"}" msg=flushing alerts=[fooAlert[ea0b4a4][active]]
ts=2022-07-01T14:40:34.297Z caller=pagerduty.go:293 level=debug integration=pagerduty incident="{}/{severity=~\"warning|critical|error\"}:{alertname=\"fooAlert\"}" eventType=trigger
ts=2022-07-01T14:40:34.298Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="monitoring_pd_low/pagerduty[0]: notify retry canceled due to unrecoverable error after 1 attempts: failed to template PagerDuty v2 message: template: :1: function \"default\" not defined"
```
