### ISSUE TITLE
Inhibit alerts by groupname matcher

### ISSUE THREAD

**Issue by sed-i** [prometheus/alertmanager#2984]
Currently an inhibit rule can take `alertname` as a matcher, e.g.:

```yaml
inhibit_rules:
- source_match:
    alertname: InstanceDown
```

It could be handy if it was possible to use `groupname` as a matcher as well, to be able to:
- inhibit entire alert groups.
- have alerts with the same name but in different groups, and inhibit only one of them.

```yaml
groups:
- name: Instances
  rules:
  - alert: InstanceDown
    expr: up == 0
```
