### ISSUE TITLE
Pushover user_keys and tokens are visible

### ISSUE THREAD

**Issue by joker234** [prometheus/alertmanager#299]
The config options Pushover `user_key` and Pushover `token` are visible on the status web page. They should be shown as `<hidden>` like `hipchat_auth_token`.

```
receivers:
- name: 'default'
  pushover_configs:
  - user_key: 'abcdefgh...'
    token: 'xyzabcde...'
```

I don't actually understand why they are not shown as `<hidden>`. The keys are marked as `Secret` in the `PushoverConfig` struct.
https://github.com/prometheus/alertmanager/blob/5158926bc3b3cc625b9acf43416d29406e5dd378/config/notifiers.go#L322
