### ISSUE TITLE
Error in telegram notify

### ISSUE THREAD

**Issue by madwolf96** [prometheus/alertmanager#2997]
Hi, I was able to face this issue in telegram notify, some of alerts not able to send to telegram. Despite using parse_mode: HTML.

log: 
```
ts=2022-07-11T06:41:07.631Z caller=notify.go:732 level=warn component=dispatcher receiver=telegram_alert integration=telegram[0] msg="Notify attempt failed, will retry later" attempts=1 err="telegram: Bad Request: can't parse entities: Unsupported start tag \"\" at byte offset 91 (400)"
```

alertmanager.yaml:
```
global:
  resolve_timeout: 5m
route:
  receiver: telegram_alert
  group_by:
  - namespace
  - instance
  - container
  routes:
  - receiver: telegram_alert
    matchers:
    - alertname =~ "InfoInhibitor|Watchdog"
  group_wait: 30s
  group_interval: 2h
  repeat_interval: 12h
inhibit_rules:
- target_matchers:
  - severity =~ warning|info
  source_matchers:
  - severity = critical
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - severity = warning
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - alertname = InfoInhibitor
  equal:
  - namespace
receivers:
- name: telegram_alert
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 689621231261204996:AAHBFWsOasdXPF4ohgmc23EC3LU3T4lgKbi7dcvv
    chat_id: -100140657701222996
    message: '{{ template "telegram.message" . }}'
    parse_mode: HTML
templates:
- /etc/alertmanager/config/*.tmpl
```

telegram.tmpl:
```
{{ define "telegram.message" }}
{{if eq .Status "firing"}}
Status: <b>{{.Status | toUpper}} 🔥</b>
{{end -}}
{{if eq .Status "resolved"}}
Status: <b>{{.Status | toUpper}} ✅</b>
{{end }}
{{ range .Alerts }}
Alert: {{ .Labels.alertname }}
Description: {{ .Annotations.description }}
Details:
  {{ range .Labels.SortedPairs }} - {{ .Name }}: {{ .Value }}
  {{ end }}
Graph: {{ .GeneratorURL }}
{{$severity := .Labels.severity -}}
{{if eq $severity "warning" -}}
Severity: {{$severity}} ⚠️
{{else if eq $severity "critical" -}}
Severity: {{$severity}} 🚨
{{else -}}
Severity: {{$severity}}
{{- end -}}
{{ end }}
{{ end }}
```
