### ISSUE TITLE
when I reload route config, the alerts in aggrGroup will be missed

### ISSUE THREAD

**Issue by arvonh** [prometheus/alertmanager#3097]
**What did you do?**
 reload route config

**What did you expect to see?**
I wish the alerts in aggrGroup can be sent at least once.

**What did you see instead? Under which circumstances?**
I saw that the alerts in aggrGroup miss sent.

**Environment**
mac os

* System information:

	Darwin 20.6.0 x86_64

* Alertmanager version:

	v0.23.0

* Prometheus version:

	Na

* Alertmanager configuration file:
```
route:
  group_by: ['alertname']
  group_wait: 3s
  group_interval: 5s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'https://oapi.dingtalk.com/robot/send?access_token=69a59a57befc758a2dc2a088c98cf866163f23fc497c280c05738b4fc4046780'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

```

* Prometheus configuration file:
Na

* Logs:
Na
