### ISSUE TITLE
alertmanager error when i apply alarm rules

### ISSUE THREAD

**Issue by bruse-peng** [prometheus/alertmanager#3098]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here
Linux 5.4.119-19-0009.1 x86_64

* Alertmanager version:

	v0.24.0

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
apiVersion: v1
data:
config.yml: |-
global:
resolve_timeout: 5m
route:
group_by: ['alertname']
group_wait: 30s
group_interval: 5m
repeat_interval: 24h
receiver: 'wechat'
receivers:
- name: 'wechat'
webhook_configs:
- send_resolved: true
url: 'http://wechat-alarm/webhook_send'
```

* Prometheus configuration file:
```
apiVersion: v1
data:
  node.yaml: |
    groups:
    - name: node
      rules:
      - alert: NodeMemoryUsage
        expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 > 30
        for: 1m
        labels:
          source: node
          severity: critical
        annotations:
          告警主题: "Node节点{{$labels.instance}} 内存使用率高"
          告警详情: "node节点{{$labels.instance}}内存使用率大于30%"
          当前值: "{{ $value }}%"
```

* Logs:
```
ts=2022-10-09T05:45:41.384Z caller=api.go:345 level=error component=api version=v2 path=/api/v2/alerts method=POST msg="Failed to validate alerts" err="invalid annotations: invalid name \"告警详情\""
ts=2022-10-09T05:45:56.325Z caller=api.go:345 level=error component=api version=v2 path=/api/v2/alerts method=POST msg="Failed to validate alerts" err="invalid annotations: invalid name \"当前值\"; invalid annotations: invalid name \"告警主题\"; invalid annotations: invalid name \"告警环境\"; invalid annotations: invalid name \"告警环境\"; invalid annotations: invalid name \"告警详情\"; invalid annotations: invalid name \"告警环境\"; invalid annotations: invalid name \"告警环境\"; invalid annotations: invalid name \"告警主题\"; invalid annotations: invalid name \"告警主题\"; invalid annotations: invalid name \"告警环境\"; invalid annotations: invalid name \"当前值\"; invalid annotations: invalid name \"告警主题\""
ts=2022-10-09T05:45:56.376Z caller=api.go:345 level=error component=api version=v2 path=/api/v2/alerts method=POST msg="Failed to validate alerts" err="invalid annotations: invalid name \"告警主题\""
```
