### ISSUE TITLE
Proposal: allow alert manager to read from secret resources

### ISSUE THREAD

**Issue by qinxx108** [prometheus/alertmanager#3108]
### Problem
The prometheus alert manager (open source) right now support read password from file for part of the receivers, see [issue](https://github.com/prometheus/prometheus/issues/8551) (https://github.com/prometheus/prometheus/issues/8551). And also besides read from file, we want to also be able to read from the other password provider for example AWS secret manager, Azure Key Vault provider etc. 

We do have the secrets store [CSI driver](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html) (https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html) to mount the secrets to pod so that we can use the receivers’s {KEY_NAME}_file to read the password. However that require user’s to maintain the additional CSI inside of the same cluster.

The ideal solution will be the alert manager itself can resolve the secrets in itself and cache that for a configurable time, re-fetch the secrets after timeout

###  Proposed  configuration
In <pagerduty_config>

```
# The following two options are mutually exclusive.
# The PagerDuty integration key (when using PagerDuty integration type `Events API v2`).
routing_key: [<tmpl_secret>]
# The PagerDuty integration key (when using PagerDuty integration type `Prometheus`).
service_key: [<tmpl_secret>]
```

Will accept two new configuration 

```
# The following two options are mutually exclusive.
# The PagerDuty integration key (when using PagerDuty integration type `Events API v2`).
routing_key_config: [<secret_config>]
# The PagerDuty integration key (when using PagerDuty integration type `Prometheus`).
service_key_config: [<secret_config>]
```

A new configuration type of  <secret_config> will be introduced, the config will have the following fields so that users will use this to configure the type and id of the secrets to fetch from. 

```
# "file", "aws_secret_manager", "azure_key_vault", etc.
type: <string>

aws_secret_manager: 
  
  # The arn of the secrets to fetch from
  secret_arn: <tmpl_string>
  
  # How long secrets stay in the memory. After timeout the secret will be refetch from the source
  [ timeout: <duration> | default = 5s ]
  
  # Configures AWS's Signature Verification 4 signing process to sign requests.
  sigv4:
    [ <sigv4_config> ]
  
file: 
  path: <filepath>

```

###   Examples
aws_secret_manager type example
```
global:
  resolve_timeout: 5s
route:
  receiver: 'pager-duty-notifications'
  group_by: [alertname, datacenter, app]

receivers:
- name: 'pager-duty-notifications'
  pagerduty_configs:
    - service_key_config:
        type: aws_secret_manager
        aws_secret_manager: 
          secret_arn: 'arn:aws:secretsmanager:us-west-2:111:secret:test-123'
          sigv4:
            region: us-west-2

```

Please let me know what do you think

**Comment by simonpasquier** [comment]
It sounds interesting but it needs to be consistent across all Prometheus projects (first and foremost Prometheus itself). Did you file a similar issue in github.com/prometheus/prometheus?

**Comment by qinxx108** [comment]
A corresponding issue cut in prometheus: https://github.com/prometheus/prometheus/issues/11477

**Comment by qinxx108** [comment]
Merge the prometheus issue into this one as discussion on the kubecon Contribfest

**Comment by davidpellcb** [comment]
can we please just got support for environment variables in the config files 😭 😭

**Comment by bwplotka** [comment]
Thanks for this! @qinxx108 - we spoke on ContribFest, and I think it makes total sense.

Indeed we could revisit env vars - but you can do the same by reloading the secret file, so I don't think the environment variable helps here.

I think it makes sense to support more popular secret providers by default - the same as we have for service discovery. I think we should have some entry in the `authorization` section, perhaps, with `aws_secret_manager` as an option. Thoughts @simonpasquier @roidelapluie ?

**Comment by simonpasquier** [comment]
> can we please just get support for environment variables in the config files

I think that it's a bit different from the original request so I wouldn't conflate the 2 issues. As @bwplotka said, maybe it should be revisited but it's a different discussion to have.

> I think we should have some entry in the authorization section, perhaps, with aws_secret_manager as an option.

I believe that integration with popular password managers is wider than just for HTTP authentication. In @qinxx108's example, the use case is to inject the PagerDuty key. For Prometheus, it could be useful for many service discoveries too (e.g. inject `token` into Consul SD configuration).

**Comment by roidelapluie** [comment]
I agree with @simonpasquier , I think we should aim for more than http. probably storing all the secrets configuration in a top level section would make sense as well, then just refering to a secret name at the localtion we need access to the secret.

```
secrets:
- name: hello
  source: vault
  path: secret/data/hello
```


```
basic auth:
   username: bar
   password_secret_name: <string>
```


I am however 100% against secrets in templates. Templates should not get access to secret data, this seems to be a too high risk.

**Comment by jeremych1000** [comment]
Envvar support would be a great first step. Don't think there would be much pushback against envvars?

**Comment by juliusv** [comment]
Without diving fully into this discussion, just a side link to a previous exploration of env vars in config files Prometheus:

* Issue: https://github.com/prometheus/prometheus/issues/2357
* Referenced Prometheus team vote (with initial elaboration in the thread): https://groups.google.com/g/prometheus-developers/c/tSCa4ukhtUw/m/J-j0bSEYCQAJ

**Comment by lstellway** [comment]
Not very elegant, but I found a [pretty neat example in the Loki documentation](https://github.com/grafana/loki/blob/45b127cfd62d8dedd46b189081d4259e6416ca24/examples/getting-started/docker-compose.yaml#L93-L110) for how to write a file in the entrypoint _(allowing for using environment variables)_. 

I was able to get this working by:
1. Creating an environment of the file contents
2. Dumping the environment variable into the configuration file location in the entrypoint
    - Notice the double `$$` for referencing the `$ALERTMANAGER_CONFIG` variable .. this is required so the variable is not replaced by Docker. 

Here is an example [`docker-compose.yml`](https://docs.docker.com/compose/compose-file/compose-file-v3/):

```yml
# docker-compose.yml
version: "3.8"
services:
  alertmanager:
    container_name: alertmanager
    # Configuration
    # @see https://prometheus.io/docs/alerting/latest/configuration/
    entrypoint:
      - sh
      - -euc
      - |
        # mkdir -p /etc/alertmanager
        echo "$${ALERTMANAGER_CONFIG}" > /etc/alertmanager/alertmanager.yml
        /bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager
    environment:
      ALERTMANAGER_CONFIG: |
        # Place the entire contents of your alertmanager.yml file here.
        # Reference environment variables as usual with ${VARIABLE_NAME}
        # ...

        global:
          # The smarthost and SMTP sender used for mail notifications.
          smtp_smarthost: smtp.sendgrid.net:465
          smtp_from: alertmanager@example.com
          smtp_auth_username: apikey
          smtp_auth_password: ${SENDGRID_API_KEY}

    image: prom/alertmanager:v0.26.0
    ports:
      - 9093:9093
    restart: unless-stopped
```
