### ISSUE TITLE
webhook custom style

### ISSUE THREAD

**Issue by xuchongchong** [prometheus/alertmanager#3110]
Is it possible to make alertmanager webhook like this https://github.com/opsgenie/kubernetes-event-exporter#webhookshttp
https://github.com/opsgenie/kubernetes-event-exporter/blob/master/config.example.yaml
```
  - name: "pipe"
    webhook:
      endpoint: "http://localhost:3000"
      headers:
        X-API-KEY: "123-456-OPSGENIE-789-ABC"
        User-Agent: "kube-event-exporter 1.0"
      streamName: "applicationMetric"
      layout:
        endpoint: "localhost2"
        eventType: "kube-event"
        createdAt: "{{ .GetTimestampMs }}"
        details:
          message: "{{ .Message }}"
          reason: "{{ .Reason }}"
          tip: "{{ .Type }}"
          count: "{{ .Count }}"
          kind: "{{ .InvolvedObject.Kind }}"
          name: "{{ .InvolvedObject.Name }}"
          namespace: "{{ .Namespace }}"
          component: "{{ .Source.Component }}"
          host: "{{ .Source.Host }}"
          labels: "{{ toJson .InvolvedObject.Labels}}"
```
