### ISSUE TITLE
Resolution alerts generated by alert manager on non resolved alert

### ISSUE THREAD

**Issue by alegalwx** [prometheus/alertmanager#3112]
**What did you do?**
Create new alert rule on a specific datasource (MEM consumption of a server in %)

**What did you expect to see?**
- Message sent with raised alert (alert is raised when MEM consumption is ≥ 20%) ➜ OK
- NO "resolved" alert message sent (MEM consumption of server is never below 80%)

**What did you see instead? Under which circumstances?**
- One minute after rule creation, my server receives properly message with alert raised. Value inside alert is right (MEM = 84%)
- Then every `group_interval` (5m) I receive message with multiple alerts
  - One `resolved` alert per minute since last message (i.e., 5 `resolved` alerts in message) for this rule, although alert shall not be resolved (value in each alert is correct, beyond 80%)
  - One new `firing` alert for same rule, that should not be necessary as initial firing shall not be resolved
  - Note : after multiple group intervals some `resolved` alerts are repeated, leading to a maximum of 20 alerts per message (19 `resolved` and 1 `firing`)

**Environment**
- Kubernetes cluster (single node) v1.23.7
- Single Prometheus server POD and single alert manager POD, deployed with Helm chart version 15.14.0

* System information:

Not sure what is needed here. I can provide deployment description.

* Alertmanager version:

```
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64
```

* Prometheus version:

```
prometheus, version 2.36.2 (branch: HEAD, revision: d7e7b8e04b5ecdc1dd153534ba376a622b72741b)
  build user:       root@f051ce0d6050
  build date:       20220620-13:21:35
  go version:       go1.18.3
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
Name:         scar-prometheus-alertmanager
Namespace:    scar
Labels:       app=prometheus
              app.kubernetes.io/managed-by=Helm
              chart=prometheus-15.14.0
              component=alertmanager
              heritage=Helm
              release=scar
Annotations:  meta.helm.sh/release-name: scar
              meta.helm.sh/release-namespace: scar

Data
====
alertmanager.yml:
----
global: {}
receivers:
- name: scar-devicesupervision
  webhook_configs:
  - send_resolved: true
    url: http://scar-devicesupervision:2113
route:
  group_interval: 5m
  group_wait: 10s
  receiver: scar-devicesupervision
  repeat_interval: 3h

allow-snippet-annotations:
----
false

BinaryData
====

Events:  <none>
```

* Prometheus configuration file:
```
Name:         scar-prometheus-server
Namespace:    scar
Labels:       app=prometheus
              app.kubernetes.io/managed-by=Helm
              chart=prometheus-15.14.0
              component=server
              heritage=Helm
              release=scar
Annotations:  meta.helm.sh/release-name: scar
              meta.helm.sh/release-namespace: scar

Data
====
alerting_rules.yml:
----
groups:
    - name: thresholds
      rules:
        - alert: threshold_1
          expr: system_mem_perc{device_id="2"} >= 20
          labels:
            dsIdentifier: system_mem_perc
            dsTitle: Memory usage
            dsUnit: '%'
            thresholdLevel: "20"
            thresholdPolarity: upper
            thresholdSeverity: major
            valueReached: '{{ $value }}'

alerts:
----
{}

allow-snippet-annotations:
----
false
prometheus.yml:
----
global:
  evaluation_interval: 1m
  scrape_interval: 10s
  scrape_timeout: 10s
rule_files:
- /etc/config/recording_rules.yml
- /etc/config/alerting_rules.yml
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- honor_timestamps: true
  job_name: scar
  scrape_interval: 10s
  static_configs:
  - targets:
    - scar-connectorcontroller:2112
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - scar-prometheus-alertmanager

recording_rules.yml:
----
{}

rules:
----
{}


BinaryData
====

Events:  <none>
```

* Logs:

No log after start-up logs, except config map update log for server

**Comment by simonpasquier** [comment]
The label `valueReached: '{{ $value }}'` explains what you're seeing. Because the `valueReached` value changes with every rule evaluation, Alertmanager assumes that it's a new alert (the identity of the alert is defined by its label keys/values).
Removing the label from the alert definition should solve the problem. It's ok to have an annotation carrying the value though.

**Comment by alegalwx** [comment]
Hello,

Moving `valueReached: '{{ $value }}'` from labels to annotations fixes the problem,  thanks a lot Simon !
See below new rule in server config :

```
alerting_rules.yml:
----
groups:
    - name: thresholds
      rules:
        - alert: threshold_2
          expr: system_mem_perc{device_id="1"} >= 20
          labels:
            dsIdentifier: system_mem_perc
            dsTitle: Memory usage
            dsUnit: '%'
            thresholdLevel: "20"
            thresholdPolarity: upper
            thresholdSeverity: critical
          annotations:
            valueReached: '{{ $value }}'
```
