### ISSUE TITLE
multi matcher in one receiver how does it work?

### ISSUE THREAD

**Issue by csrlsm** [prometheus/alertmanager#3113]
I want know how does it work when I config multi matcher in on receiver,? for example:
```
- receiver: 'email'
  matcher:
    - severity=warning
    - team=teamA
  group_wait: 10s
  continue: true
```

the matcher between"severity" and "team" is “and” or "or"?
