### ISSUE TITLE
Alertmanager Text only emails no longer working

### ISSUE THREAD

**Issue by kalel-k** [prometheus/alertmanager#3118]
**what did you do**
configured email_config in one receiver to ignore html email by using html: '' so it would only use the text: '{{ template "email.custom.txt" . }}' config

**What did you expect to see?**
Alertmanager not send html emails for that reciever

**What did you see instead? Under which circumstances?**
Alertmanager auto added:
html: '{{ template "email.default.html" . }}'
replacing html:''
And sent html email

**Environment**
Kubernetes
* System information:

	insert output of `uname -srm` here
Linux 5.4.0-126-generic x86_64

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)
v0.23.0 and v0.24.0
* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)
v2.33.4
* Alertmanager configuration file:
```
insert configuration here
global:
  smtp_auth_password: password
  smtp_auth_username: myusername
  resolve_timeout: 5m
  smtp_from: k8s.alertmanager@mycompany.com
  smtp_smarthost: auth-forwarder.mycompany.com:25
receivers:
- email_configs:
  - headers:
      subject: '{{ template "__subject" . }}'
    html: '{{ template "email.custom.html" . }}'
    send_resolved: true
    to: k8s-support-team@mycompany.com
  name: email-receiver
- email_configs:
  - headers:
      subject: '{{ template "__subject" . }}'
    send_resolved: false
    text: '{{ template "email.custom.txt" . }}'
    html: ''
    to: monitoringevents@mycompany.com
  name: ITSM-receiver
route:
  group_by: []
  group_interval: 5m
  group_wait: 30s
  receiver: email-receiver
  repeat_interval: 2h
  routes:
  - continue: true
    match_re:
      alertname: .+
      severity: warning|critical
    receiver: ITSM-receiver
  - match_re:
      severity: warning|critical
    receiver: email-receiver
templates:
- /etc/alertmanager/configmaps/alert-template/*.tmpl

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by dineshk26** [comment]
Hi Team,

We are also facing the same issue where Alert manager is not able to send the text only email to the receiver, it is sent in HTML format due to which we are facing Incident management issues. Could some one review this issue and let us know?

Thanks in advance.

**Comment by simonpasquier** [comment]
Can you share the output from `curl <alertmanager host>/api/v2/status  | jq -cr '.config.original'`? I don't see the issue with my local setup.

**Comment by kalel-k** [comment]
output below its adding html: '{{ template "email.default.html" . }}'  even though config file has html: ''

global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_from: k8s.alertmanager@me.com
  smtp_hello: localhost
  smtp_smarthost: smtp-forwarder
  smtp_auth_username: <username>
  smtp_auth_password: <secret>
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: email-receiver
  continue: false
  routes:
  - receiver: ITSM-receiver
    match_re:
      alertname: .+
      severity: warning|critical
    continue: true
  - receiver: email-receiver
    match_re:
      severity: warning|critical
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
receivers:
- name: email-receiver
  email_configs:
  - send_resolved: false
    to: k8s-team@me.com
    from: k8s.alertmanager@me.com
    hello: localhost
    smarthost: smtp-forwarder:25
    auth_username: <username>
    auth_password: <secret>
    headers:
      From: k8s.alertmanager@me.com
      Subject: '{{ template "__subject" . }}'
      To: k8s-team@me.com
    html: '{{ template "email.custom.html" . }}'
    require_tls: true
- name: ITSM-receiver
  email_configs:
  - send_resolved: false
    to: monitoringevents@me.com
    from: k8s.alertmanager@me.com
    hello: localhost
    smarthost: auth-forwarder.me.com:25
    auth_username: <username>
    auth_password: <secret>
    headers:
      From: k8s.alertmanager@me.com
      Subject: '{{ template "__subject" . }}'
      To: monitoringevents@me.com
    html: '{{ template "email.default.html" . }}'
    text: '{{ template "email.custom.txt" . }}'
    require_tls: true
templates:
- /etc/alertmanager/configmaps/alert-template/*.tmpl

**Comment by simonpasquier** [comment]
I've tried with your config file and with `html: ""` , I can't see the same issue. Can you double check the configuration file on disk?

**Comment by liz-86** [comment]
Hi,
we have also faced the same issue. Our workaround: define a new blank html template and refer to this new template in your config.
Then you should only receive your email with your desired text.

**Comment by R0peE** [comment]
Hi, 

Same issue here, unfortunately if we specify an empty template, an e-mail is sent out with 2 bodies, 1 containing the plaintext context type, and the other empty with the html context type.

Waiting on some news on this, as it is affecting most of our systems :)

Cheers!

**Comment by simonpasquier** [comment]
@R0peE feel free to share a complete reproducer for the issue. As I said earlier, I tried something locally but couldn't reproduce.

**Comment by adcsikos** [comment]
@R0peE 

This is how we solve the issue:

Inside the prometheus operator values file we add the followings:
```

    receivers:
      - name: 'P1'
        email_configs:
          - to: 'something@something.com' 
            send_resolved: false
            text: '{{ template "email.default.html" . }}'
```


And  here we define the email.default.html:

```
receivers.tmpl: |-
      {{ define "email.default.html" }}
        <!DOCTYPE html>
        <html>
          <body>
              &lt;some text here<br>
              &lt;some other text in a new line<br>
          </body>
        </html>   
      {{ end }}
```
