### ISSUE TITLE
Time_intervals not applicatable

### ISSUE THREAD

**Issue by kotloki** [prometheus/alertmanager#3120]
I wrote route and time intervals. If I use mute_time_intervals in route, I receive alert through default route.
Part of my config:

```
global:
  smtp_smarthost: <my email server>
  smtp_from: <my email address>
  smtp_require_tls: false

route:
  receiver: 'default team'
  group_by: ['alertname', 'location']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  routes:
  - receiver: 'slack-monitoring'
    group_wait: 10s
    matchers:
    - alertname="Slack-test"
    continue: true
    mute_time_intervals:
    - offtime
    
receivers:
    - name: 'slack-monitoring'
  slack_configs:
  - api_url: '<slack_webhook_address>'
    send_resolved: true
    
time_intervals:
- name: offtime
  time_intervals:
  - times:
    - start_time: '00:00'
      end_time: '06:00'
    - start_time: '16:00'
      end_time: '23:59'
```
