### ISSUE TITLE
[feature-request] Generate JSON and base64 encode to generate silence payload for Karma

### ISSUE THREAD

**Issue by carlosjgp** [prometheus/alertmanager#3127]
**What did you do?**

Trying to create silence link for [Karma](https://github.com/prymitive/karma) (GH [discussion](https://github.com/prymitive/karma/discussions/4411))

I can't see a function to encode a string on base64

**What did you expect to see?**

GoTemplate to base 64 encode a JSON string

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

```
Linux 5.10.135 x86_64
```

* Alertmanager version:

```
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64
```

* Prometheus version:

```
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
inhibit_rules:
  - source_matchers:
      - 'severity = critical'
    target_matchers:
      - 'severity =~ warning|info'
    equal:
      - 'namespace'
      - 'alertname'
  - source_matchers:
      - 'severity = warning'
    target_matchers:
      - 'severity = info'
    equal:
      - 'namespace'
      - 'alertname'

route:
  group_by:
    - 'namespace'
    - 'alertname'
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 6h
  receiver: 'slack'
  routes:
    - receiver: 'null'
      matchers:
        - alertname =~ "Watchdog"

receivers:
  - name: 'null'
  - name: 'slack'
    slack_configs:
      - channel: '#<CHANNEL>'
        send_resolved: true
        api_url: <WEBHOOK>
        title: 'Alert'
        text: '{{ (index .Alerts 0).Annotations.message }}'
        actions:
        - type: button
          text: 'Silence'
          url: |
            {{ .ExternalURL }}/?m={{ template "__karma_json_silence" . | base64encode }}

templates:
  - '/etc/alertmanager/config/*.tmpl'
```

Where I would have a template file to create the JSON string for karma

the final JSON string should look like
```json
{
  "am": [{ "label": "prod", "value": ["prod"] }],
  "m": [
    { "n": "alertname", "r": false, "e": true, "v": ["KubeHpaMaxedOut"] },
    { "n": "cluster", "r": false, "e": true, "v": ["prod"] },
    { "n": "container", "r": false, "e": true, "v": ["kube-state-metrics"] },
    { "n": "endpoint", "r": false, "e": true, "v": ["http"] },
    {
      "n": "horizontalpodautoscaler",
      "r": false,
      "e": true,
      "v": ["my-app"]
    },
    { "n": "instance", "r": false, "e": true, "v": ["10.0.19.254:8080"] },
    { "n": "job", "r": false, "e": true, "v": ["kube-state-metrics"] },
    { "n": "namespace", "r": false, "e": true, "v": ["my-app"] },
    {
      "n": "pod",
      "r": false,
      "e": true,
      "v": ["prometheus-operator-kube-state-metrics-6c8fcc998-xmdwq"]
    },
    {
      "n": "prometheus",
      "r": false,
      "e": true,
      "v": ["observability/prometheus-operator-prometheus"]
    },
    {
      "n": "service",
      "r": false,
      "e": true,
      "v": ["prometheus-operator-kube-state-metrics"]
    },
    { "n": "severity", "r": false, "e": true, "v": ["warning"] }
  ],
  "d": 60,
  "c": ""
}
```

Where `m` is the collection of `.CommonLabels` and `am` is the Alertmanager on the Karma servers section

* Prometheus configuration file:
N/A

* Logs:
N/A
