### ISSUE TITLE
Alertmanager not dropping alerts based on "match" rule

### ISSUE THREAD

**Issue by Migueljfs** [prometheus/alertmanager#3128]
**What did you do?**
I set up alertmanager using kube-prometheus rules and Prometheus Operator. I added matching routes to drop alerts based on low severity and to send slack alerts on high severity.

Here's an example of what I see in slack:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/25540481/199969900-53888b56-091d-4e51-b8f0-25ce52677389.png">

As you can see, both "critical" and "info" alert were sent to slack

**What did you expect to see?**
I expect alerts with matching severity to be routed to the correct receiver.

**What did you see instead? Under which circumstances?**
Instead, all alerts are being sent to slack, regardless of severity

**Environment**

* System information:
`Linux 5.10.109+ x86_64`

* Alertmanager version:

```
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64

```

* Prometheus version:

```
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: prometheus-alert-manager-config
  namespace: monitoring
  labels:
    alertmanagerConfig: config
spec:
  route:
    groupBy: ['alertname', 'cluster', 'job', 'env']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'null'
    routes:
      - match:
          severity: 'critical'
        receiver: 'slack-notifications'

      - match:
          severity: 'error'
        receiver: 'slack-notifications'
      
      - match:
          severity: 'warning'
        receiver: 'null'

      - match:
          severity: 'info'
        receiver: 'null'

      - match:
          severity: 'none'
        receiver: 'null'
  receivers:
    - name: 'null'
    - name: slack-notifications
      slackConfigs:
      - apiURL:
          key: apiSecret
          name: alertmanager-slack-config
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Event Notification'
        pretext: '{{ .CommonAnnotations.summary }}'
        text: |-
          {{ range .Alerts }}
            {{- if or .Annotations.summary .Annotations.description }}*Alert:* {{ .Annotations.summary }}{{ .Annotations.description }} - `{{ .Labels.severity }}`{{- end }}
            {{ if .Annotations.message }}*Message:* {{ .Annotations.message }}{{ end }}
            {{ if or .Annotations.graph .Annotations.graphUrl }}*Graph:* <{{ .Annotations.graph }}{{ .Annotations.graphUrl }}|:chart_with_upwards_trend:>{{ end }}{{ if or .Annotations.grafana .Annotations.grafanaUrl }}*Grafana:* <{{ .Annotations.grafana }}{{ .Annotations.grafanaUrl }}|:bar_chart:>{{ end }} {{ if or .Annotations.runbook .Annotations.runbook_url }} *Runbook:* <{{ .Annotations.runbook }}{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        sendResolved: true
```

* Prometheus configuration file:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.35.0
  name: k8s
  namespace: monitoring
spec:
  replicas: 2
  image: quay.io/prometheus/prometheus:v2.39.1
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.28.1
    objectStorageConfig:
      key: thanos.yaml
      name: prometheus-thanos-objstore-config
  additionalScrapeConfigs:
    name: prometheus-additional-scrape-configs
    key: prometheus-additional.yaml
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  enableFeatures: []
  externalLabels:
    cluster: qa-microservices-primary-us-west1
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.35.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 16Gi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.38.0
```

* Logs:
No visible logs relevant to the issue
