### ISSUE TITLE
Alertmanager - Bad configuration in one namespace preventing config load from other namespaces

### ISSUE THREAD

**Issue by praveenjindal62** [prometheus/alertmanager#3138]
**What did you do?**

We have deployed AlertManager using `kube-prometheus-stack (version - 41.5.1)`. We have configured Alertmanager to be able to load configuration from different namespaces. In one of the namespace, Alertmanager configuration was incorrect and Alertmanager was complaining (as expected). But this issue has prevented Alertmanager to stop loading configuration from all the other namespaces as well 

BAD Config (Focus on `matchers`, values contain a `name` as `label-key` which is not acceptable as '-' not allowed)

 
**What did you expect to see?**

Alertmanager should provide some errors for bad configuration (Which it is already doing) but it should also continue loading configuration from other namespaces also.

**What did you see instead? Under which circumstances?**

Alertmanager stopped loading from other namespaces.

**Environment**

DEV - But this issue is available in Prod also

* Alertmanager version:

	v0.24.0

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: my-ns
spec:
  receivers:
    - name: 'null'
  route:
    groupBy:
      - alertname
      - job
    groupInterval: 5m
    groupWait: 30s
    receiver: null
    repeatInterval: 30m
    routes:
      - matchers:
          - matchType: '='
            name: label-key
            value: label-value
        receiver: 'null'
```

* Logs:
Container - `alertmanager`
```
caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="bad matcher format: label-key=\"label-value\""
```
Container - `config-reloader`
```
level=error ts=2022-11-02T09:45:52.908112969Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
```
