### ISSUE TITLE
Feature ask: Alertmanager-webhook_configs-url support utf8 characters for parameters

### ISSUE THREAD

**Issue by LronDC** [prometheus/alertmanager#3142]
**What did you do?**
Set up Prometheus and Alertmanager in local env via docker latest image.

### critical configuration
```yaml
receivers:
   - name: 'flask'
      webhook_configs:
      - url: 'http://xxx.xxx.xxx:5000/alertmanager?query=中文
``` 
As you see I passed an utf8 character(Chinese character) as query parameters on the webhook URL

**What did you expect to see?**

I want to catch the query parameters correctly.

e.g. in flask
```python
import request

def handler():
...
    args = request.args.get("query")
    print(args)
```
```console
中文
```
**What did you see instead? Under which circumstances?**

*messy code* like 
![image](https://user-images.githubusercontent.com/59912384/202982873-ff75ba9b-5e2b-4d23-a189-760da74a53f2.png)

**Environment**

Latest Prometheus and Alertmanager image

* Alertmanager configuration file:
```yaml
global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'flask'
receivers:
  - name: 'flask'
    webhook_configs:
    - url: 'http://10.64.0.175:5000/alertmanager?aa=中文'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
```

* Prometheus configuration file:
```yaml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['10.64.0.175:9093']

rule_files:
  - "/etc/prometheus/rules.yml"
```

So does Alertmanager work on webhook support for utf8 characters?
