### ISSUE TITLE
Very big bug

### ISSUE THREAD

**Issue by xxd819240366** [prometheus/alertmanager#3148]
**What did you do?**
when i click /alerts  in local:9093, the front-end looks like in dead loop, detail message you can see in Logs
**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:
        Linux 3.10.0-1160.15.2.el7.x86_64 x86_64

* Alertmanager version:
       0.24.0

* Prometheus version:

2.28-21.10_beta

* Alertmanager configuration file:
```
!!com.xxxx.common.AlertManagerConfig
global:
  resolve_timeout: 5m
  smtp_auth_password: xxxxx
  smtp_auth_username: xxxxx.com
  smtp_from: xxxx
  smtp_hello: xxxx
  smtp_require_tls: false
  smtp_smarthost: xxxx:xx
receivers:
- email_configs:
  - send_resolved: false
    to: none
  name: admin
route:
  group_by:
  - alertname
  group_interval: 5m
  group_wait: 30s
  receiver: admin
  repeat_interval: 5m
templates:
- '/etc/prometheus/deafule-template.tmpl'
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

# Remote write configuration (for Graphite, OpenTSDB, InfluxDB or Clickhouse).
remote_write:
    - url: "http://localhost:9201/write"
remote_read:
    - url: "http://localhost:9201/read"
```

* Logs:
```
Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at Content.isSelection (chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/js/content.js:1:20792)
    at Content.handleSelection (chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/js/content.js:1:20478)
isSelection @ content.js:1
handleSelection @ content.js:1
4291script.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at n (script.js:1:18963)
    at n (script.js:1:19059)
    at n (script.js:1:19059)
    at Sr (script.js:1:19123)
    at jr (script.js:1:19185)
    at script.js:1:21013
    at a (script.js:1:21229)
n @ script.js:1
n @ script.js:1
n @ script.js:1
Sr @ script.js:1
jr @ script.js:1
(anonymous) @ script.js:1
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
requestAnimationFrame (async)
a @ script.js:1
```
