### ISSUE TITLE
Alertmanager receivers won't use the proxy_url from global config.

### ISSUE THREAD

**Issue by groenator** [prometheus/alertmanager#3149]
**What did you do?**
I configured Alertmanager to use a proxy for all the receivers. The global http_config has the proxy URL assigned. When I tested Opsgenie heartbeat, the heartbeat is not reading the global proxy URL. 

**What did you expect to see?**
I want all the receivers to use the same `global.http_config proxy URL`, instead of assigning the proxy URL for each receiver.

**What did you see instead? Under which circumstances?**
The alertmanager webhooks are not using the global proxy configuration. It only works If I set the `proxy_url` at the receiver level.

**Environment**

* System information:

	insert output of `Linux 4.18.0-305.57.1.el8_4.x86_64 x86_64` here

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)
```
alertmanager, version 0.23.0
```

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)
```
prometheus, version 2.32.1
```

* Alertmanager configuration file:
```
global:
  http_config:
    proxy_url: '<http-proxy-url>'
  resolve_timeout: 1m
receivers:
- name: none
- name: opsgenie-heartbeat
  webhook_configs:
  - url: '<opsgenie-heartbeat-url>'
    send_resolved: false
    http_config:
      basic_auth:
        password: <token>
- name: <opsgenie-name>
  opsgenie_configs:
  - api_key: <token>
    message: |
      [{{len .Alerts}} Alerts]: {{ range .Alerts }}{{ .Annotations.message }} {{ end }}
    description: |-
      {{ .ExternalURL }}

      Alerts:
      {{ range .Alerts }}
      {{ .Status }}
      {{ .Annotations.message }}

      {{ end }}
- name: <slack-name>
  slack_configs:
  - api_url: '<slack-webhook-url>'
    channel: "<slack-channel>"
    username: <heartbeat-name>
    text: |
      [{{len .Alerts}} Alerts]: {{ range .Alerts }}{{ .Annotations.message }} {{ end }}
route:
  group_by:
  - job
  group_interval: 1m
  group_wait: 30s
  receiver: none
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: opsgenie-heartbeat
    repeat_interval: 10s
  - match:
      severity: critical
    receiver: <slack-name>
  - match:
      severity: critical
    receiver: <opsgenie-name>

```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=error ts=2022-11-29T12:09:04.571Z caller=dispatch.go:354 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="opsgenie-heartbeat/webhook[0]: notify retry canceled after 2 attempts: Post \"https://api.opsgenie.com/v2/heartbeats/<heartbeat-name>/ping\": context deadline exceeded"
```

**Comment by simonpasquier** [comment]
The global HTTP config will only be applied when the receiver's HTTP config is nil:

https://github.com/prometheus/alertmanager/blob/1b202b91bf269b737d9fae2930fe4fb1a5c43ab2/config/config.go#L355-L359

In other words, Alertmanager doesn't do a deep-merge operation between the global HTTP config and the receiver's HTTP config. While it was surprising to you, changing the actual logic could break existing users. 

```
- name: opsgenie-heartbeat
  webhook_configs:
  - url: '<opsgenie-heartbeat-url>'
    send_resolved: false
    http_config:
      proxy_url: '<http-proxy-url>'
      basic_auth:
        password: <token>
```
