### ISSUE TITLE
Cert-related problems with TLS cluster setup

### ISSUE THREAD

**Issue by cthu1hoo** [prometheus/alertmanager#3159]
I'm trying to deploy two alertmanagers in a cluster configuration and I'm running into weird certificate problems I can't explain: 
for some reason alertmanager expects its own certificate while connecting to its peer. 

We have a standardized process to issue certificates using Vault and Ansible, non cluster parts of Alertmanager (and many other services) seemingly use them just fine.

It feels like I'm missing something obvious here. Please help. :)

Peer 01, error message:

```
Dec 02 05:20:00 test-gl-gcpew1b-vic-vmalert01 alertmanager[42828]: ts=2022-12-02T05:20:00.284Z caller=cluster.go:470 level=warn component=cluster msg=refresh result=failure addr=10.157.192.197:9094 err="1 error occurred:\n\t* Failed to join 10.157.192.197:9094: failed to dial: x509: certificate is valid for localhost, test-gl-gcpew3c-vic-vmalert02.gl.mx, not test-gl-gcpew1b-vic-vmalert01.gl.mx\n\n"
```

Peer 01, command line arguments & IP address:

```
/usr/local/bin/alertmanager --cluster.listen-address=10.157.191.196:9094 --cluster.peer=test-gl-gcpew3c-vic-vmalert02.gl.mx:9094 --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/var/lib/alertmanager --web.listen-address=0.0.0.0:9093 --web.config.file=/etc/alertmanager/web.yml --cluster.tls-config=/etc/alertmanager/cluster-tls.yml --web.external-url=https://test-gl-gcpew1b-vic-vmalert01.gl.mx:9093/

root@test-gl-gcpew1b-vic-vmalert01:~# ip -4 a | grep 10.157
    inet 10.157.191.196/32 brd 10.157.191.196 scope global dynamic ens4
```

Peer 01, cluster-tls config:

```
tls_server_config:
  cert_file: /etc/alertmanager/ssl/test-gl-gcpew1b-vic-vmalert01.gl.mx.pem
  client_auth_type: RequireAndVerifyClientCert
  client_ca_file: /etc/alertmanager/ssl/ca.pem
  key_file: /etc/alertmanager/ssl/test-gl-gcpew1b-vic-vmalert01.gl.mx.key


tls_client_config:
  cert_file: /etc/alertmanager/ssl/test-gl-gcpew1b-vic-vmalert01.gl.mx.pem
  key_file: /etc/alertmanager/ssl/test-gl-gcpew1b-vic-vmalert01.gl.mx.key
  server_name: test-gl-gcpew1b-vic-vmalert01.gl.mx
```

Peer 02:

```
Dec 02 05:27:16 test-gl-gcpew3c-vic-vmalert02 alertmanager[41231]: ts=2022-12-02T05:27:16.483Z caller=cluster.go:470 level=warn component=cluster msg=refresh result=failure addr=10.157.191.196:9094 err="1 error occurred:\n\t* Failed to join 10.157.191.196:9094: failed to dial: x509: certificate is valid for localhost, test-gl-gcpew1b-vic-vmalert01.gl.mx, not test-gl-gcpew3c-vic-vmalert02.gl.mx\n\n"
```

```
alertma+   41231  0.4  0.4 728616 36788 ?        Ssl  05:18   0:01 /usr/local/bin/alertmanager --cluster.listen-address=10.157.192.197:9094 --cluster.peer=test-gl-gcpew1b-vic-vmalert01.gl.mx:9094 --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/var/lib/alertmanager --web.listen-address=0.0.0.0:9093 --web.config.file=/etc/alertmanager/web.yml --cluster.tls-config=/etc/alertmanager/cluster-tls.yml --web.external-url=https://test-gl-gcpew3c-vic-vmalert02.gl.mx:9093/

root@test-gl-gcpew3c-vic-vmalert02:~#  ip -4 a | grep 10.157
    inet 10.157.192.197/32 brd 10.157.192.197 scope global dynamic ens4
```

```
root@test-gl-gcpew3c-vic-vmalert02:~# cat /etc/alertmanager/cluster-tls.yml
tls_server_config:
  cert_file: /etc/alertmanager/ssl/test-gl-gcpew3c-vic-vmalert02.gl.mx.pem
  client_auth_type: RequireAndVerifyClientCert
  client_ca_file: /etc/alertmanager/ssl/ca.pem
  key_file: /etc/alertmanager/ssl/test-gl-gcpew3c-vic-vmalert02.gl.mx.key


tls_client_config:
  cert_file: /etc/alertmanager/ssl/test-gl-gcpew3c-vic-vmalert02.gl.mx.pem
  key_file: /etc/alertmanager/ssl/test-gl-gcpew3c-vic-vmalert02.gl.mx.key
  server_name: test-gl-gcpew3c-vic-vmalert02.gl.mx
```

Just in case, the certs, on both nodes:

```
root@test-gl-gcpew1b-vic-vmalert01:~# openssl x509 -in /etc/alertmanager/ssl/test-gl-gcpew1b-vic-vmalert01.gl.mx.pem -text | grep vmalert
        Subject: CN = test-gl-gcpew1b-vic-vmalert01.gl.mx
                DNS:localhost, DNS:test-gl-gcpew1b-vic-vmalert01.gl.mx, IP Address:10.157.191.196, IP Address:127.0.0.1

root@test-gl-gcpew3c-vic-vmalert02:~# openssl x509 -in /etc/alertmanager/ssl/test-gl-gcpew3c-vic-vmalert02.gl.mx.pem -text | grep vmalert
        Subject: CN = test-gl-gcpew3c-vic-vmalert02.gl.mx
                DNS:localhost, DNS:test-gl-gcpew3c-vic-vmalert02.gl.mx, IP Address:10.157.192.197, IP Address:127.0.0.1
```

Our environment is Debian 11 running in GCP.

```
root@test-gl-gcpew3c-vic-vmalert02:~# uname -srm
Linux 5.10.0-19-cloud-amd64 x86_64

root@test-gl-gcpew1b-vic-vmalert01:~# /usr/local/bin/alertmanager --version
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64
```

If I need to provide more information, please tell me I'll gather everything that's needed. Thanks in advance for any help.
