### ISSUE TITLE
Add dynamic duration variable for the repeat_interval

### ISSUE THREAD

**Issue by wotkddl21** [prometheus/alertmanager#3186]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

For managing the repeat interval of the same alert, there is a configuration repeat_interval in the alertmanager below
`
repeat_interval : <duration>  
`
The `<duration>` only supports for the pattern that matches regular expression below.  
`((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0)   `

In my case, I want to set different repeat_interval for each prometheusrule in my k8s cluster.  
Now, I can set "route" to change repeat_interval, but it could make the route configuration so dirty.  
Example)  
If I want to set 4 different repeat_intervals that depend on the alert severity, then there are 4 additional lines for every route config.  
Let assume that there are 4 (severity, repeat_interval) pairs.  (warning, 1h) (major, 30m) (critical, 10m) and (emergency, 1m)
Then the route should be... 
```
route:
-  receiver: receiver1
   matchers:
   - severity="warning"
     repeat_interval: 1h
-  receiver: receiver1
   matchers:
   - severity="major"
     repeat_interval: 30m
-  receiver: receiver1
   matchers:
   - severity="critical"
     repeat_interval: 10m
-  receiver: receiver1
   matchers:
   - severity="emergency"
     repeat_interval: 1m
```

If there are several receivers, then the configuration would be 1000+ lines.  

If there could be 
repeat_inverval: {{ $labels.repeat }} instead of 
repeat_interval: static string, 
the configuration would be shorter and people could use repeat_interval much more flexible.
