### ISSUE TITLE
Alertmanager Doesnt send resolved email

### ISSUE THREAD

**Issue by amirad1** [prometheus/alertmanager#3196]
**Hey 
I have configured an alertmanager and it sends alerts properly
But it does not send resolved email.
I have tried different amount of time for resovled timeout but it did not work 
here is my configuration** 

---------define sender configuration----------------------
global:
  smtp_from: 'mymail@mail.com'
  smtp_smarthost: 'mail.server:25'
  smtp_auth_username: ''
  smtp_auth_password: 'mypassword'
  smtp_auth_identity: 'username'
  smtp_require_tls: false
smtp_ssl_auth_enable: false
  resolve_timeout: 1m
------------define default route for alerts that do not match sub children-------
route:
  receiver: 'default-receiver'
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1h
  group_by: [cluster, alertname]
--------define sub route-----------------------------------
  routes:
------define  second sub route-----------------------------
  - receiver: 'devops'
    group_by: [product, environment]
    matchers:
    - service="DevOps"
------------define receivers email addresses-----------------
receivers:
  - name: 'devops'
    email_configs:
      - to: 'mail1@mail.com'
      - to: 'mail2@mail.com' 
      - to: 'mail3@mail.com'
        send_resolved: true

  - name: 'default-receiver'
    email_configs:
      - to: 'mail1@mail.com'
        send_resolved: true

it is also one of my rules:

groups:

- name: DISK USAGE
  rules:
  - alert: DEV-DISK-USAGE-CRITICAL-196
    expr: 100 - ((node_filesystem_avail_bytes{instance="192.168.100.200:9100",job="Docker-node-exporter",mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{instance="192.168.100.200:9100",job="Docker-node-exporter",mountpoint="/",fstype!="rootfs"}) > 80
    for: 5m
    labels:
      service: "DevOps"
    annotations:
      summary: "Server 200 DISK USAGE CRITICAL"
      description: "disk usage is critical"

**I would be happy to have your help guys**

**Comment by simonpasquier** [comment]
I bet that you have an issue in the definition of the email receiver:

```
receivers:
  - name: 'devops'
    email_configs:
      - to: 'mail1@mail.com'
      - to: 'mail2@mail.com' 
      - to: 'mail3@mail.com'
        send_resolved: true
```

This creates 3 different integrations and only the latest will send the resolved notification. You probably want

```
receivers:
  - name: 'devops'
    email_configs:
      - to: 'mail1@mail.com, mail2@mail.com, mail3@mail.com'
        send_resolved: true
```
