### ISSUE TITLE
slack image_url does not support go template

### ISSUE THREAD

**Issue by NivEz** [prometheus/alertmanager#3207]
**What did you do?**
I have a slack webhook integrated with alertmanager.
I tried to use the `image_url` field in the slack config and send an image according to the logic:
If the alert is in `firing` status send image and if the alert is in `resolved` status send different image. 

**What did you expect to see?**
To get in the message the the firing image when alert is firing and resolved image when the alert is resolved.

**What did you see instead? Under which circumstances?**
None of the images. Got the slack message only with the other fields (`text` content).

**Environment**
Kubernetes cluster (RKE)

* System information:
The cluster runs on ubuntu 22.
The pod that runs alertmanager system information - Linux 5.15.0-50-generic x86_64

* Alertmanager version:

	0.24.0

* Prometheus version:

	2.39.1

* Alertmanager configuration file:
```
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  alertmanager.yaml: |-
    route:
      receiver: "null"
      group_by:
        - cluster
        - alertname
      group_wait: 0s
      group_interval: 5m
      repeat_interval: 2h
      routes:
      - receiver: slack-notifications-devops
        matchers:
          - author = self
          - team = devops
      - receiver: slack-notifications-developers
        matchers:
        - author = self
        - team = developers
    receivers:
      - name: "null"
      - name: slack-notifications-devops
        slack_configs:
          - channel: "#my-channel"
            send_resolved: true
            api_url: ${SLACK_TOKEN}
            title: "[Alert] [{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
            text: "severity: {{ (index .Alerts 0).Labels.severity | toUpper }}\n
                  {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}
                  {{ if eq .Status `resolved` }} actually firing {{ else }} now resolved {{ end }}"
      - name: slack-notifications-developers
        slack_configs:
          - channel: "#my-channel"
            send_resolved: true
            api_url: ${SLACK_TOKEN}
            title: "[Alert] [{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
            text: "severity: {{ (index .Alerts 0).Labels.severity | toUpper }}\n
                     {{ range .Alerts }}{{ .Annotations.description }}\n
                     {{ end }}"
            image_url: "{{ if eq .Status `resolved` }} https://media.tpt.cloud/rewire/uploads/2020/11/AdobeStock_274892386GoodStudio-scaled.jpeg {{ else }} https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/OK-button_-_Macro_photography_of_a_remote_control.jpg/1200px-OK-button_-_Macro_photography_of_a_remote_control.jpg {{ end }}"
    templates:
      - /etc/alertmanager/config/*.tmpl

```

* Logs:
no logs are sent (probably not an error in alertmanager).

#### This is probably mistake in the documentation which the `image_url` field is described as `<tmpl_string>` like the `text` field. Unlike the text field the image_url field does not support go templating. I just assume that since the `image_url` is not a valid url (since using go template), slack can't display the image.
