### ISSUE TITLE
Clarify lack of route time interval inheritance in docs

### ISSUE THREAD

**Issue by gebn** [prometheus/alertmanager#3211]
The [`<route>`](https://prometheus.io/docs/alerting/latest/configuration/#route:~:text=optional%20configuration%20parameters%20are%20inherited%20from%20its%20parent%20node%20if%20not%20set) docs state _optional configuration parameters are inherited from its parent node if not set_. `active_time_intervals` and `mute_time_intervals` are currently [copied](https://github.com/prometheus/alertmanager/blob/ecb66f76b0058957e5045114ae01f8b98994451e/dispatch/route.go#L63) as part of `RouteOps`, however they are then [overwritten](https://github.com/prometheus/alertmanager/blob/ecb66f76b0058957e5045114ae01f8b98994451e/dispatch/route.go#L120-L121) without the `nil` check that guards other parameters, removing the inheritance. Is this intentional?

The effect is a parent will not implicitly mute its children, e.g. given the following, `a` and `b` will still receive every alert all the time:

```yaml
...
route:
  receiver: default
  routes:
  - routes:
    - receiver: a
      continue: true
    - receiver: b
    mute_time_intervals:
    - everyday
time_intervals:
- name: everyday
  time_intervals:
  - weekdays:
    - sunday:saturday
```

This tripped us up, as we wanted to notify two receivers with the same mute condition, and the only way to do this is to move the mute down into each child, e.g.

```yaml
route:
  receiver: default
  routes:
  - routes:
    - receiver: a
      mute_time_intervals:
      - everyday
      continue: true
    - receiver: b
      mute_time_intervals:
      - everyday
```

If this is intended behaviour, I think it's worth making more explicit in the docs. I'm happy to submit a PR on confirmation.
