### ISSUE TITLE
Unexpected notification sent timestamp

### ISSUE THREAD

**Issue by leifhanack** [prometheus/alertmanager#322]
Hi there, 

I'm using Prometheus 0.18.0 with Alertmanager 0.1.1. and I have trouble to understand the scheduling of notifications. 

From the docs:

```
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first 
  # notification.
  group_wait: 1s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 3m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 3h 
```

What I expect from the above setting is, that when Prometheus sends an new alert to the Alertmanager a notification should be sent immediately (group_wait: 1s). Unfortunately this notification is sent after ~3 minutes (group_interval: 3m). Same when resolving the alert. Instead of immediately it took ~3 minutes.

Is my expectation wrong? Am I missing s.th.?

Thanks a lot and best regards, Leif

PS: 

Only when setting `group_interval: 1s` notifications are sent immediately.

My current alertmanager.yml:
```
global:
  slack_api_url: 'https://hooks.slack.com/services/foo/bar'

route:
  receiver: 'slack-notifications'
  group_by: []
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1d

  routes:
  - match:
      env: 'prod'
      severity: 'critical'
    repeat_interval: 1h

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#incidents'
    send_resolved: true
```
