### ISSUE TITLE
OpsGenie - Update Alert Tags

### ISSUE THREAD

**Issue by coolguy357** [prometheus/alertmanager#3230]
Can we optionally also update alerts' tags in OpsGenie?

**What did you do?**
I configured two receivers, one for business hours alerts, and one for off hours alerts. Both point to the same OpsGenie integration, but differ in their tags, which would be used for routing within OpsGenie. Alerts created during "business hours" are not updated with the tags appropriate for their receiver when fired during "off hours", and vice versa. Their routes within OpsGenie are tied to their initial firing receiver.
**What did you expect to see?**
If tags change on an alert in Alertmanager, I expect the tags to be updated in OpsGenie

**What did you see instead? Under which circumstances?**

* Alertmanager configuration file:
```
...
  - receiver: 'opsgenie-business-time'
    matchers:
      - service="inhouse-service"
    mute_time_intervals:
      - offhours
    continue: true

  - receiver: 'opsgenie-off-hours'
    matchers:
      - service="inhouse-service"
    active_time_intervals:
      - offhours
...
receivers:
    - name: 'opsgenie-business-time'
      opsgenie_configs:
      - responders:
        - name: 'team1'
          type: 'team'
        tags: "something-something,businesstime"

    - name: 'opsgenie-off-hours'
      opsgenie_configs:
      - responders:
        - name: 'team1'
          type: 'team'
        tags: "something-something,offhours"      
      
```
