### ISSUE TITLE
Notification template no longer working on v0.25.0

### ISSUE THREAD

**Issue by chrism417** [prometheus/alertmanager#3238]
**What did you do?**

Upgraded from Alertmanager 0.24.0 to 0.25.0. 

**What did you expect to see?**

No changes in existing functionality.

**What did you see instead? Under which circumstances?**

Alerts are constantly failing to send to Slack with the following error:

`ts=2023-02-02T17:19:19.679Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="sysops-slack/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: template: :1:12: executing \"\" at <{{template \"common_title\" .}}>: template \"common_title\" not defined"`

**Environment**

* Alertmanager version: v0.25.0

* Prometheus version: v2.41.0

* Alertmanager configuration file:
```
{{ define "common_title" -}}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
    {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
      {{" "}}(
      {{- with .CommonLabels.Remove .GroupLabels.Names }}
        {{- range $index, $label := .SortedPairs -}}
          {{ if $index }}, {{ end }}
          {{- $label.Name }}="{{ $label.Value -}}"
        {{- end }}
      {{- end -}}
      )
    {{- end }}
{{- end }}

{{ define "common_text" -}}
{{ with index .Alerts 0 -}}
  :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
  {{- if .Annotations.runbook }}   :notebook: *<{{ .Annotations.runbook }}|Runbook>*{{ end }}
{{ end }}

*Alert details*:

{{ range .Alerts -}}
*Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
*Description:* {{ .Annotations.description }}{{ .Annotations.message }}
*Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
{{- end }}

{{ define "sysops_slack_severity_channel" -}}#alerts-{{- .CommonLabels.severity -}}{{- end }}
```
Slack config:

```
- name: 'sysops-slack'
  slack_configs:
  - api_url: 'blah'
    channel: '#alerts-dev'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    send_resolved: true
    title: '{{ template "common_title" . }}'
    text: '{{ template "common_text" . }}'
```
