### ISSUE TITLE
Using repetitive blocks for slack_config in alertmanager config file

### ISSUE THREAD

**Issue by Aracki** [prometheus/alertmanager#3248]
How we can omit having repetitive blocks for similar slack_configs. Is there a chance defining just `-channel` and define all other fields in only one place within alertmanager config file...?

These are my receivers:
```
receivers:
  - name: 'slack-admin'
    slack_configs:
    - channel: '#slack-admin'
      send_resolved: true
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      title: '{{ template "slack.slack_alert.title" .}}'
      text: '{{ template "slack.slack_alert.text" .}}'

  - name: 'slack-ch1'
    slack_configs:
    - channel: '#slack-ch1'
      send_resolved: true
      icon_url: https://avatars3.githubusercontent.com/u/3380462  
      title: '{{ template "slack.slack_alert.title" .}}'
      text: '{{ template "slack.slack_alert.text" .}}'
```

I'd like if I can define them something like this:
```
  - name: 'slack-admin'
    slack_configs: '{{ template slack.slack_config admin }}'
  - name: 'slack-ch1'
    slack_configs: '{{ template slack.slack_config ch1 }}'
```
and define other fields in template files like we do for `title` & `text`  for example.

**Comment by timmow** [comment]
I raised a similar issue on the [prometheus mailing list](https://groups.google.com/g/prometheus-users/c/SEDcTW0i9e4/m/kvy11aJ_BAAJ) and got no response

We do template this using jsonnet to make it less repetitive, but the generated config is still extremely verbose and we've hit issues like [this one](https://github.com/prometheus-operator/prometheus-operator/pull/4906) that we've had to workaround

**Comment by sandipb** [comment]
Use yaml aliases.

```yaml
.slack_common: &slack_common
  api_url_file: /etc/alertmanager/secrets/alertmanager-receiver-secrets/url
  username: monitoring
  # yamllint disable-line rule:line-length
  title: "[{{ .Status | toUpper }}{{ if eq .Status \"firing\" }}:{{ .Alerts.Firing | len }}{{ end }}]"
  fields:
    - title: Cluster
      value: "{{ .CommonLabels.cluster }}"
    - title: Summary
      value: "{{ .CommonAnnotations.summary }}"
    - title: Namespace
      value: "{{ .GroupLabels.namespace }}"
    - title: Description
      value: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    - title: Source
      value: "{{ range .Alerts }}<{{ .GeneratorURL }}|View in Prometheus>{{ end }}"
  send_resolved: true # Send resolved alerts to Slack
...
      receivers:
        - name: 'team-sre'
          slack_configs:
            - channel: '#alerts'
              <<: *slack_common
```
