### ISSUE TITLE
alertmanager.yml: How to use- SMTP_AUTH_USERNAME  SMTP_AUTH_PASSWORD?

### ISSUE THREAD

**Issue by mokshpooja** [prometheus/alertmanager#327]
Moved to the latest syle of yaml for alert manager and building from master. But I am not receiving any email notifications. Also I have noticied that although I can see the alerts on prometheus side I cannot see the alerts on the alertmanager alert page.

Is the below use of SMTP_AUTH_USERNAME  SMTP_AUTH_PASSWORD wrong?
```
global:
 resolve_timeout: 5m
  # The smarthost and SMTP sender used for mail notifications.
 smtp_smarthost: smtp.gmail.com:587
 smtp_from: sender@gmail.com
 SMTP_AUTH_USERNAME: sender@gmail.com
 SMTP_AUTH_PASSWORD: sender_password

route:
  group_by: [alertname]
  repeat_interval: 1h 
  receiver: live-monitoring

receivers:
- name: live-monitoring
  email_configs:
  - to: receiver@gmail.com 
```
