### ISSUE TITLE
How about change the route.routes.receiver to list?

### ISSUE THREAD

**Issue by wotkddl21** [prometheus/alertmanager#3274]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
As-Is, we could route the alerts with their labels.
To do so, we set route.routes like below 
``` yaml
route:
  routes:
  - receiver: dev-receiver
    matchers:
    - test="true"
    continue: false
    repeat_interval: 6h
  - receiver: default-receiver
    matchers:
    - test="false"
    continue: false
    repeat_interval: 6h
  - receiver: another-receiver
    matchers:
    - test="true"
    continue: false
    repeat_interval: 6h
```
If alerts are fired, then the alertmanager would check the label "test" to route those alerts. 
If the label "test" has value "true", then "dev-receiver"  would receive the alert from the alertmanager, but "another-receiver" will get no alert.

Alerts could be sent to multiple receivers, like if some nodes are down then the infra, platform and developer team should get alerts.
In this case, the receiver would proxy the alert from the alertmanager to another receiver "infra, platform and dev", which is adding one more hop in the alert system.
If alertmanager could send the alerts to several receivers, then we could make the alert system fit.
So finally, the alertmanager.yaml would be 
``` yaml
route:
  routes:
  - receiver: 
    - dev-receiver
    - another-receiver
    matchers:
    - test="true"
    continue: false
    repeat_interval: 6h
  - receiver: 
    - default-receiver
    matchers:
    - test="false"
    continue: false
    repeat_interval: 6h
```
