### ISSUE TITLE
Race condition in ExecuteTextString

### ISSUE THREAD

**Issue by grobinson-grafana** [prometheus/alertmanager#3277]
**What did you do?**

I have been looking into a data corruption issue in Slack notifications in Grafana (https://github.com/grafana/grafana/issues/63584) and have found a race condition in `ExecuteTextString` in Alertmanager that I suspect to be the cause. I have been able to reproduce this bug in `main`, commit `41eb121`.

I have the following Alertmanager configuration:

```
receivers:
- name: test
  slack_configs:
  - api_url: redacted
    title: '{{ template "slack.title" . }}'
route:
  receiver: test
  group_by: ['...']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 15s
templates:
  - templates/*.tmpl
```

and the following template in `test.tmpl`:

```
{{ define "slack.title" }}
  {{ reReplaceAll ":" "-" .ExternalURL | title }}
{{ end }}
```

I created a single rule that has 4 alert instances:

![Screenshot 2023-03-03 at 15 34 44](https://user-images.githubusercontent.com/85952834/222761479-cad444de-1e0c-4a8e-b4b4-c492d32a1ed5.png)

**What did you expect to see?**

I expected to see the following in all messages:

```
Http-//Georges-Air.fritz.box-9093
Http-//Georges-Air.fritz.box-9093
Http-//Georges-Air.fritz.box-9093
Http-//Georges-Air.fritz.box-9093
```

**What did you see instead? Under which circumstances?**

However most messages are corrupted. For example:

```
HHtt//EegeeS-Air..tz.box-9093
Http-//Georges-Air.fritz.box-
Http-//Georges-Air.fritz.box-9093
Ht
```

I think the issue is related to how Alertmanager uses `text/template` across goroutine as the bug is no longer reproducible with the following changes:

```
diff --git a/template/template.go b/template/template.go
index a42cf03d..9e56bf1f 100644
--- a/template/template.go
+++ b/template/template.go
@@ -23,6 +23,7 @@ import (
        "regexp"
        "sort"
        "strings"
+       "sync"
        tmpltext "text/template"
        "time"

@@ -38,6 +39,7 @@ import (
 type Template struct {
        text *tmpltext.Template
        html *tmplhtml.Template
+       mu   sync.Mutex

        ExternalURL *url.URL
 }
@@ -131,6 +133,8 @@ func (t *Template) FromGlob(path string) error {

 // ExecuteTextString needs a meaningful doc comment (TODO(fabxc)).
 func (t *Template) ExecuteTextString(text string, data interface{}) (string, error) {
+       t.mu.Lock()
+       defer t.mu.Unlock()
        if text == "" {
                return "", nil
        }
```
