### ISSUE TITLE
empty email for resolved status

### ISSUE THREAD

**Issue by hoggle64** [prometheus/alertmanager#3290]
**What did you do?**
I've added "send_resolved: true" to get notification when an alert is gone

**What did you expect to see?**
A mail including all details for the vanished alert

**What did you see instead? Under which circumstances?**
An empty email

**Environment**

* System information:
Linux 3.10.0-1160.80.1.el7.x86_64 x86_64

* Alertmanager version:
alertmanager, version 0.25.0

* Prometheus version:
prometheus, version 2.42.0

* Alertmanager configuration file:
```
route:
  receiver: 'default-receiver'
  group_wait: 3m
  group_interval: 5m
  repeat_interval: 4h
  group_by: [ alertname, hostname]
  routes:
  - receiver: 'email'
    matchers:
      - hostname!~"[A-Za-z_\-]+[0-9]+(r|t).*"
      - hostname!~"tomcat[0-9]+s.*"
      - hostname!~".*testrac.*"
      - severity!="info"
      - severity!="warning"

receivers:
- name: 'default-receiver'
- name: 'email'
  email_configs:
  - to: 'betrieb@somecompany.org'
    from: 'prometheus@somecompany.org'
    smarthost: mta.somecompany.org:25
    headers:
      subject: '{{ template "custom_mail_subject" . }}'
    html: '{{ template "custom_mail_html" . }}'
    send_resolved: true
```

email.template:
```
{{ define "custom_mail_subject" }}{{ range .Alerts.Firing }}{{ if ne .Annotations.title "" }}{{ .Annotations.title }}{{else}}{{ .Labels.alertname }}{{ end }} ({{ .Labels.hostname }}){{ end }}{{ end }}
{{ define "custom_mail_html" }}
<html>
<head>
<title>Monitoring Alert</title>
</head>
<body>

{{ range .Alerts.Firing }}

<p style="font-family: Gill Sans,Gill Sans MT,Calibri,sans-serif;" >{{ .Labels.alertname }} on {{ .Labels.hostname }}<br/>
<a href="{{ .GeneratorURL }}">Check this in Prometheus</a><br/>
{{ if ne .Annotations.summary "" }}{{ .Annotations.summary }}{{ end }}</p>
<p style="font-family: Gill Sans,Gill Sans MT,Calibri,sans-serif;"><b><u>Details:</u></b></p>
<p style="font-family: Gill Sans,Gill Sans MT,Calibri,sans-serif;"> {{ range .Annotations.SortedPairs }}
  {{ .Name }} = {{ .Value }}<br/> {{ end }}{{ range .Labels.SortedPairs }} {{ .Name }} = {{ .Value }}<br/>
{{ end }}
</p>
<br>
{{ end }}

</body></html>
{{ end }}
```
