### ISSUE TITLE
Is that my configuration properly？

### ISSUE THREAD

**Issue by guxia** [prometheus/alertmanager#330]
```
global:
  smtp_smarthost: 'smtp.126.com:25'
  smtp_from: 'guxia286675100@126.com'
  smtp_auth_username: 'guxia286675100@126.com'
  smtp_auth_password: 'xxxxxxx'
  hipchat_auth_token: '1234556789'           -->What this is mean?And is it vital?
  hipchat_url: 'https://hipchat.foobar.org/'     -->What this is mean?And is it vital?
templates: 
- '~/myGopath/src/github.com/prometheus/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: team-X-mails
  routes:
  - match_re:
      service: ^(foo1|foo2|baz)$
    receiver: team-X-mails
    routes:
    - match:
        severity: critical
      receiver: team-X-pager
  - match:
      service: files
    receiver: team-Y-mails
    routes:
    - match:
        severity: critical
      receiver: team-Y-pager
      service: database
    receiver: team-DB-pager
    group_by: [alertname, cluster, database]
    routes:
    - match:
        owner: team-X
      receiver: team-X-pager
    - match:
        owner: team-Y
      receiver: team-Y-pager
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'team-X-mails'
  email_configs:
  - to: '286675100@qq.com'
- name: 'team-X-pager'
  email_configs:
  - to: '286675100@qq.com'
  pagerduty_configs:
  - service_key: <team-X-key>
- name: 'team-Y-mails'
  email_configs:
  - to: '286675100@qq.com'
- name: 'team-Y-pager'
  pagerduty_configs:
  - service_key: <team-Y-key>
- name: 'team-DB-pager'
  pagerduty_configs:
  - service_key: <team-DB-key>
- name: 'team-X-hipchat'
  hipchat_configs:
  - auth_token: <auth_token>
    room_id: 85
    message_format: html
    notify: true
```

Prometheus.rules:
```
ALERT APIHighRequestLatency
  IF histogram_labels_metric_bucket{le="0.5"} > 1
  FOR 1m
  ANNOTATIONS {description="{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)", summary="High request latency on {{ $labels.instance }}"}
```

If i want to receive mail use by '286675100@qq.com'。Do I have to do anything else? It seems a little complex for me。Do you have a relevant example configuration？
