### ISSUE TITLE
Why do i still can't receive email?

### ISSUE THREAD

**Issue by guxia** [prometheus/alertmanager#335]
Sorry,it's still about alertmanager sending email.There already have some alert informations at http://localhost:9090/alerts.
`Alerts
APIHighRequestLatency (2 active)

ALERT APIHighRequestLatency
  IF histograms_labels_metric_bucket{le="0.5"} > 10
  FOR 1m
  ANNOTATIONS {description="{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)", summary="High request latency on {{ $labels.instance }}"}

Labels 	State 	Active Since 	Value 	Silence
exported_job="some_job" group="test" instance="localhost:9091" job="some_job" lable="b" le="0.5" 	firing 	2016-04-29 02:00:37.804 +0000 UTC 	694
exported_job="some_job" group="test" instance="localhost:9091" job="some_job" lable="a" le="0.5" 	firing 	2016-04-29 02:00:37.804 +0000 UTC 	694
Test (1 active)

ALERT Test
  IF sum(counter_noLabels_metric) > 100
  FOR 1h
  ANNOTATIONS {description="{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)", summary="High request latency on {{ $labels.instance }}"}

Labels 	State 	Active Since 	Value 	Silence
	pending 	2016-04-29 06:05:22.804 +0000 UTC 	730.9515828284094`

And i can go to the page which link is http://localhost:19091/#/status,with the alertmanager configuration:
```
templates: 
- '~/myGopath/src/github.com/prometheus/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname']
  receiver: email-me
receivers:
- name: email-me
  email_configs:
  - to: 286675100@qq.com
    from: guxia286675100@126.com
    smarthost: smtp.126.com:25
    auth_username: "guxia286675100@126.com"
    auth_identity: "guxia286675100@126.com"
    auth_password: "xxxxxx"
```
And nginx configuration:
```
server {
        listen 127.0.0.1:19091;
        location / {
                proxy_pass  http://localhost:9093;
                post_action @forward;
        }
        location @forward {
        proxy_pass http://127.0.0.1:9093;
        }
   }
```
Why do i still cant' receive email  in 286675100@qq.com?
