### ISSUE TITLE
silence affected all alerts with wrong

### ISSUE THREAD

**Issue by xxjwwf** [prometheus/alertmanager#3366]
**What did you do?**
when i use `key=value` to silence a alert is work
when i conifg a any type of this `key="value"` to silence , this silence config will affected all alerts(but in alerts section you also will find this alerts)

**What did you expect to see?**
1.i know this type `key=value` is correct to affected the alert i want
2.i dont know whether  `key="value"` is correct, if this config is wrong , i think this silence config should not affected any silences

**What did you see instead? Under which circumstances?**

**Environment**

* System information:
`Linux 3.10.0-1062.el7.x86_64 x86_64`

* Alertmanager version:
`alertmanager: v0.18`

* Prometheus version:
`prometheus:v2.11.0`

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: default-receiver
  group_by:
  - env_name
  - rule_type
  - service
  - instance
  - app_name
  group_wait: 30s
  group_interval: 3m
  repeat_interval: 10m
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - service
  - instance
  - rule_type
  - alertname
- source_match:
    severity: critical
  target_match:
    severity: info
  equal:
  - service
  - instance
  - rule_type
  - alertname
- source_match:
    severity: warning
  target_match:
    severity: info
  equal:
  - service
  - instance
  - rule_type
  - alertname
receivers:
- name: default-receiver
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: ###
templates: []
```
