### ISSUE TITLE
need option to fire all currently firing alerts after mute time interval is over.

### ISSUE THREAD

**Issue by anilmoris** [prometheus/alertmanager#3367]
**What did you do?**
I have a mute time interval of 2 hours.

mute_time_intervals:
  - name: maintenance-times
    time_intervals:
     - weekdays: ['Sunday']
     - times:
       - start_time: '10:00'
         end_time: '12:00'

and I have a   repeat_interval of 4 hours.

  repeat_interval: 4h

**What did you expect to see?**

We need an option to fire all currently  firing alerts as soon as the mute time interval complets.

**What did you see instead? Under which circumstances?**

firing alerts do not get fired after the mute time interval is over.

they get fired only after 4 hours.  

**Environment**

* System information:

	Linux 3.10.0-1062.el7.x86_64 x86_64

* Alertmanager version:

	0.25.0

* Prometheus version:
       2.37.8

* Alertmanager configuration file:
```
omitting irrelevant conf.

mute_time_intervals:
  - name: maintenance-times
    time_intervals:
     - weekdays: ['Sunday']
     - times:
       - start_time: '10:00'
         end_time: '12:00'

and I have a   repeat_interval of 4 hours.

  repeat_interval: 4h


```

* Prometheus configuration file:
```
Irrelevant ```

* Logs:
```
Irrelevant ```
