### ISSUE TITLE
Alerts are not closed at Opsgenie receiver

### ISSUE THREAD

**Issue by amanmahajan26** [prometheus/alertmanager#3384]
**What did you do?**
I am using AlertManager to send alerts to Opsgenie. When the alert is resolved on backend (Prometheus/Alertmanager), I just receive another email about the alert but it remains open in Opsgenie. 

**What did you expect to see?**
Alert being marked as closed in Opsgenie when it gets resolved in Prometheus

**What did you see instead? Under which circumstances?**
I just get notified by email about the alert, just like in the case when alert gets created.

**Environment**

* System information:
Darwin 22.4.0 arm64

* Alertmanager version:
v0.25.0

* Prometheus version:
v2.37.2

* Alertmanager configuration file:
```
route:
  receiver: opsgenie-dispatcher
  routes:
  - matchers:
      - send_to=opsgenie
    receiver: opsgenie-dispatcher
    repeat_interval: 6h
    group_interval: 1m
    group_wait: 1m
    group_by: ['team', 'environment', 'alertname']

receivers:
- name: opsgenie-dispatcher
  opsgenie_configs:
  - send_resolved: true
    api_url: https://api.opsgenie.com
    api_key: <API_KEY>
    message: '{{ .CommonLabels.alertname }}'
    description: '{{ template "opsgenie.description" . }}'
    priority: '{{ .CommonLabels.priority }}'
    responders:
    - type: team
      name: '{{ .CommonLabels.team }}'

templates:
  - ./template/*.tmpl
 ```

* Prometheus configuration file:
```
global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564'
```
alert.yml
```
groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown 
        expr: up{job="services"} == 0 
        for: 0m
        labels:
          send_to: opsgenie
          priority: "P2"
          team: test-prometheus-integration
        annotations:
          description: "Instance {{$labels.instance}} is down for over 1m"
```

* Logs:
When alert is created:
```
ts=2023-06-06T10:03:16.884Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[c2e4e72][active]
ts=2023-06-06T10:04:16.884Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}/{send_to=\"opsgenie\"}:{alertname=\"InstanceDown\", team=\"test-prometheus-integration\"}" msg=flushing alerts=[InstanceDown[c2e4e72][active]]
ts=2023-06-06T10:04:16.885Z caller=opsgenie.go:139 level=debug integration=opsgenie alert="{}/{send_to=\"opsgenie\"}:{alertname=\"InstanceDown\", team=\"test-prometheus-integration\"}"
ts=2023-06-06T10:04:17.315Z caller=notify.go:743 level=debug component=dispatcher receiver=opsgenie-dispatcher integration=opsgenie[0] msg="Notify success" attempts=1
```

When alert is resolved:
```
ts=2023-06-06T10:08:16.881Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=InstanceDown[c2e4e72][resolved]
ts=2023-06-06T10:08:16.885Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}/{send_to=\"opsgenie\"}:{alertname=\"InstanceDown\", team=\"test-prometheus-integration\"}" msg=flushing alerts=[InstanceDown[c2e4e72][resolved]]
ts=2023-06-06T10:08:16.885Z caller=opsgenie.go:139 level=debug integration=opsgenie alert="{}/{send_to=\"opsgenie\"}:{alertname=\"InstanceDown\", team=\"test-prometheus-integration\"}"
ts=2023-06-06T10:08:17.069Z caller=notify.go:743 level=debug component=dispatcher receiver=opsgenie-dispatcher integration=opsgenie[0] msg="Notify success" attempts=1
```

<img width="1425" alt="Screenshot 2023-06-06 at 12 22 59" src="https://github.com/prometheus/alertmanager/assets/2391125/8ef768be-f6f3-43f3-932d-768c5112f6e0">

**Comment by grobinson-grafana** [comment]
While I don't have an OpsGenie account, I have at least tested that the OpsGenie code calls the [`/v2/alerts/:identifier/close`](https://docs.opsgenie.com/docs/alert-api#close-alert) endpoint for resolved alerts.

Here is the configuration I used:

```yml
receivers:
  - name: opsgenie
    opsgenie_configs:
      - api_url: http://127.0.0.1:8080
        api_key: test
        send_resolved: true

route:
  receiver: opsgenie
  group_by: [alertname]
  group_wait: 5s
  group_interval: 5m
  repeat_interval: 15s
```

Here I have used `http://127.0.0.1:8080` as the `api_url`. This is a simple Go HTTP server that logs the URL and JSON from all incoming requests:

```
/v2/alerts
2023/06/08 14:55:56 {"alias":"cc9772a1ec901d26ef71dae861793e4d08979fa5030a3f0a5f3ba549f1f2d0b6","message":"[FIRING:1]  (bar)","description":"\nAlerts Firing:\nLabels:\n - foo = bar\nAnnotations:\nSource: \n\n","details":{"foo":"bar"},"source":"http://Georges-Air.fritz.box:9093/#/alerts?receiver=opsgenie"}
```

```
/v2/alerts/cc9772a1ec901d26ef71dae861793e4d08979fa5030a3f0a5f3ba549f1f2d0b6/close?identifierType=alias
2023/06/08 15:00:56 {"source":"http://Georges-Air.fritz.box:9093/#/alerts?receiver=opsgenie"}
```

At least from the above we can be confident that the Alertmanager calls [close-alert](https://docs.opsgenie.com/docs/alert-api#close-alert) in the OpsGenie v2 API.
