### ISSUE TITLE
 routing problem

### ISSUE THREAD

**Issue by jycgxds** [prometheus/alertmanager#3392]
I hope to use multiple alarm message templates for the tag category, but it has not been possible. Please help me to see what the problem is. The configuration is as follows

```
global:
  resolve_timeout: 5m

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  routes:
  - receiver: 'host'
    match_re:
      tag: OA

receivers:
- name: 'host'
  wechat_configs:
    - corp_id: '***************'
      to_tag: '8'
      agent_id: '1000048'
      api_secret: '***************'
      send_resolved: true
  templates:
    - 'host.tmpl'
templates:
  - '*.tmpl'

```

The error log is as follows
ts=2023-06-12T12:22:55.492Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/alertmanager.yml err="yaml: unmarshal errors:\n  line 21: field templates not found in type config.plain"
