### ISSUE TITLE
a batch of alarms resend all the time

### ISSUE THREAD

**Issue by 5codes** [prometheus/alertmanager#3417]
**What did you do?**
I got a lot of alerts, and then I find a batch of alerts resend all the time.
Finally I restart prometheus, and alerts stop sending

**What did you expect to see?**
These alerts just report once

**What did you see instead? Under which circumstances?**
I received thousands of emails and messages,and these are the same alerts. 

* Alertmanager version:
alertmanager, version 0.21.0

* Prometheus version:
prometheus, version 2.38.0

* Alertmanager configuration file:
```
route:
  receiver: mail
  group_by:
  - alertname
  - instance
  - alert_type
  group_wait: 20s
  group_interval: 30s
  repeat_interval: 12h
receivers:
- name: mail
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://127.0.0.1:10040/webhook
    max_alerts: 0
  - send_resolved: true
    http_config: {}
    url: http://172.22.67.38:8081/webhook
    max_alerts: 0
templates: []
```

* Prometheus configuration file:(this alert rule like this)
```
groups:
  - name: Kubernetes alerts
    rules:
      - alert: Kubernetes--POD NOT HEALTHY
        expr: min_over_time(sum by (namespace, pod,business,project,phase) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[5m:1m]) > 0
        for: 0m
        labels:
          severity: critical
          type: Kubernetes
        annotations:
          summary: Kubernetes Pod not healthy namespace:{{ $labels.namespace }},POD:{{ $labels.pod }},current：{{ $labels.phase }}
```

Is it the expression issue? it does not take out the label "instance"
