### ISSUE TITLE
Source-Button in dashboard doesn't lead to the alert source

### ISSUE THREAD

**Issue by max06** [prometheus/alertmanager#3450]
**What did you do?**
I clicked the source-button next to an active alert.

**What did you expect to see?**
I expected to see a (new) page with a prometheus graph/table.

**What did you see instead? Under which circumstances?**
The alerts page on alertmanager did reload with all alerts collapsed.

**Environment**

* System information:

```
Linux 5.4.0-153-generic x86_64
Docker version 24.0.5, build ced0996
```        

* Alertmanager version:

```
alertmanager, version 0.25.0 (branch: HEAD, revision: 258fab7cdd551f2cf251ed0348f0ad7289aee789)
(using prom/alertmanager:v0.25.0)
```

* Prometheus version:

```
prometheus, version 2.46.0 (branch: HEAD, revision: cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)
(using prom/prometheus:v2.46.0)
```

* Alertmanager configuration file:

```yaml
global:
  slack_api_url_file: '/etc/alertmanager/slack.url'

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters.
route:
  group_by: ['alertname', 'cluster', 'service']
  receiver: slack
  repeat_interval: 24h
  group_wait: 45s
  group_interval: 5m
  routes:

receivers:
- name: slack
  slack_configs:
    - channel: '#monitoring'
      color: '{{ template "slack.color" . }}'
      title: '{{ template "slack.title" . }}'
      text: '{{ template "slack.text" . }}'
      send_resolved: true
      short_fields: true
      fields:
        - title: Hostname
          value: '{{ .CommonLabels._hostname }}'
        - title: IP
          value: '{{ .CommonLabels._ip }}'
        - title: Environment
          value: '{{ .CommonLabels._environment }}'
        - title: Zone
          value: '{{ .CommonLabels._node_az }}'


      actions:
        - type: button
          text: 'Runbook :green_book:'
          url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
        - type: button
          text: 'Query :mag:'
          url: '{{ (index .Alerts 0).GeneratorURL }}'
        - type: button
          text: 'Dashboard :chart_with_upwards_trend:'
          url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
        - type: button
          text: 'Silence :no_bell:'
          url: '{{ template "__alert_silence_link" . }}'
```

* Alertmanager commandline options:

```
      --config.file=/etc/alertmanager/alertmanager.yml
      --storage.path=/alertmanager
      --web.external-url=https://monitoring.somedomain.io/alertmanager
      --web.route-prefix=/

(traefik: traefik.http.middlewares.strip-alertmanager.stripprefix.prefixes: /alertmanager)
```

* Prometheus configuration file:

```
(not relevant)
```

* Logs:

```
(not relevant)
```

* Dashboard Infos

![image](https://github.com/prometheus/alertmanager/assets/7556827/388e216b-35a3-4172-9abf-04e73ceb0d6a)

(Active alert)

```html
<a class="btn btn-outline-info border-0" href="https://monitoring.somedomain.io/prometheus/graph?g0.expr=up+%3D%3D+0&amp;g0.tab=1"><i class="fa fa-line-chart mr-2"></i>Source</a>
```

(Source button next to the alert)

![image](https://github.com/prometheus/alertmanager/assets/7556827/4886f122-640e-41dc-a4b9-01e90b2525be)

(Click handler attached to said button). Removing this handler fixes the issue.
