### ISSUE TITLE
HipChat Question

### ISSUE THREAD

**Issue by 4ydx** [prometheus/alertmanager#348]
I assume that the room_id should be the same number present in the url when viewing the hipchat room in the browser correct?

> time="2016-05-11T11:44:27Z" level=warning msg="Notify attempt 16 failed: unexpected status code 401" source="notify.go:193" 

```
  hipchat_configs:
  - auth_token: '<my-token>'
    room_id: <my-room>
    message_format: html
    notify: true
```
