### ISSUE TITLE
Notifications are not resilient to bad templates

### ISSUE THREAD

**Issue by jmcarp** [prometheus/alertmanager#3490]
**What did you do?**

Mis-configured a notification such that a template string was invalid and could not be rendered.

**What did you expect to see?**

* I expected `amtool check-config` to detect template errors in notifier configuration, and/or
* I expected notifiers to make a best-effort to attempt to notify despite configuration bugs, since failing to notify is a very bad outcome. A notification with incomplete data would be much more useful than no notification.

**What did you see instead? Under which circumstances?**

Validation with `amtool` didn't show any errors, and notifications were dropped.

**Environment**

We're running alertmanager 0.25, but I believe this issue affects all versions.

Logs look like this:

alertmanager ts=2023-08-25T20:43:03.251Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="opsgenie-receiver/opsgenie[0]: notify retry canceled due to unrecoverable error after 1 attempts: templating error: template: :1: bad character U+002D '-'"

I would be happy to write a pr to either cause amtool to check for invalid templates or to enable notifiers to send partial notifications on template errors—for example, dropping fields that fail to render. Or if there's a better approach, let me know!

**Comment by jmcarp** [comment]
Sorry I was unclear about this! This is a [templating error](https://github.com/prometheus/alertmanager/blob/main/notify/opsgenie/opsgenie.go#L289-L291) that happens before we even make a request to the opsgenie api. So aiui it should be possible to detect statically.

**Comment by grobinson-grafana** [comment]
Apologies, I have indeed misread the issue! What is the output of amtool when testing this template with the same data?

**Comment by simonpasquier** [comment]
@jmcarp can you share the config that triggered the error?

**Comment by jmcarp** [comment]
Here's a simplified version:

```
route:
  receiver: opsgenie
receivers:
- name: opsgenie
  opsgenie_configs:
  - send_resolved: false
    api_key: redacted
    message: '{{ .GroupLabels.alertname }'
```

There's a missing closing brace in the message template, so all opsgenie notifications will fail during templating, before we send a request to the api. And we don't detect any problems with amtool, because aiui amtool doesn't look at templated fields within receivers (although it does look at the top-level templates field, which I'm not using here):

```
❯ amtool check-config am.yaml
Checking 'am.yaml'  SUCCESS
Found:
 - global config
 - route
 - 0 inhibit rules
 - 1 receivers
 - 0 templates
```

So to restate the ask in context: I would like amtool to throw an error on this example configuration file, and/or I would like the opsgenie notifier to optionally log a warning and omit invalid fields from the request, but not block notification on template errors. I'm happy to write a patch for either feature if maintainers are open to it.

**Comment by grobinson-grafana** [comment]
I think what's happening here is that `am.yaml` contains an inline template in the message field rather than executing a template in `templates`, and inline templates are not checked.

Here is an example of how it would look using template files:


```yml
route:
  receiver: opsgenie
receivers:
- name: opsgenie
  opsgenie_configs:
  - send_resolved: false
    api_key: redacted
    message: '{{ template "opsgenie.message" . }}'
templates:
  - tmpls/*.tmpl
```

That said, I think your argument is still valid because you could also have an error in the inline template `{{ template "opsgenie.message" . }}`.
