### ISSUE TITLE
altermanger always send resolved messge,about hunders message

### ISSUE THREAD

**Issue by bruse-peng** [prometheus/alertmanager#3504]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

victoriametrics/vmselect:v1.89.1-cluster
prom/alertmanager:v0.24.0

* Alertmanager configuration file:
```
[root@VM_2_15_centos /opt/pengx/prometheus-Alertmanager]# cat vmalertmanager-config-new.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: webhook
  namespace: monitoring
  labels:
    alertmanagerConfig: sams-qa
spec:
  route:
    group_by: ['alertname','alertgroup','InstanceName']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    receiver: 'webhook'
  receivers:
  - name: 'webhook'
    webhook_configs:
    - url: 'http://wechatalarm/webhook_send'
      send_resolved: true
  inhibit_rules:
  - source_matchers:
      - time_range_out="true"
    target_matchers:
      - alertname="kafka分区消息积压告警"
    equal: ['alertname','env','ip','topic']
[root@VM_2_15_centos /opt/pengx/prometheus-Alertmanager]# 
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
