### ISSUE TITLE
Alertmanager didnt post all the alerts to Webhook

### ISSUE THREAD

**Issue by amitvermaa3101** [prometheus/alertmanager#3506]
**What did you do?** On 31st Aug, there was an network outage due to which bulk alerts were fired by Prometheus and sent to alertmanager. But alertmanager didnt POST all the alerts to webhook .

Also many alerts are grouped into one event in Splunk sent through webhook .

**What did you expect to see?** Alertmanager should POST all the alerts to webhook secondly, alerts must not be merged into one event in Splunk .

**What did you see instead? Under which circumstances?** all the alerts were not POST to Webhook and many alerts got merged into single event even there is no group by used in alertmanager config
**Environment** Prod 

* System information:

	insert output of `uname -srm` here

Linux 4.18.0-425.19.2.el8_7.x86_64 x86_64
* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

```

Version:
0.25.0

```

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

Version | 2.44.0

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: multiple_targets
  continue: false
  repeat_interval: 1d
inhibit_rules:
- source_match:
    severity: critical
  target_match_re:
    severity: ^(warning|info)$
  equal:
  - alertname
  - instance
- source_match:
    alertname: Node_down
  target_match_re:
    alertname: (PrometheusTargetMissing|PostgresExporterDown")
  equal:
  - app
  - instance
- target_match_re:
    alertname: PrometheusAlertmanagerE2eDeadManSwitch
    severity: info
receivers:
- name: multiple_targets
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    url: https://splunk:8088/services/collector/raw?token=XXXXXXXXXXXXXXXXXXXXXXXXXX
    max_alerts: 0
templates: []
```

* Prometheus configuration file:
```

global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  query_log_file: /tsdb/prometheus_app/prometheus/querylog/query.log
alerting:
  alertmanagers:
  - basic_auth:
      username: admin
      password: <secret>
    follow_redirects: true
    enable_http2: true
    scheme: https
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - XXXX1:9093
      - XXXXX2:9093
      
rule_files:
- /tsdb/prometheus_app/prometheus/prometheus_rules.yml
- /tsdb/prometheus_app/prometheus/server_rules.yml
- /tsdb/prometheus_app/prometheus/postgres_rules.yml
scrape_configs:
- job_name: prometheus service
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  basic_auth:
    username: admin
    password: <secret>
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - XXXXX:9090
    labels:
      app: Prometheus_Server1
  - targets:
    - XXXXX2:9090
    labels:
      app: Prometheus_Server2
  - targets:
    - XXXXXX3:9090
    labels:
      app: Prometheus_Server3
  - targets:
    - XXXXXX4:9090
    labels:
      app: Prometheus_Server4
  - targets:
    - XXXXXX5:9090
    labels:
      app: Prometheus_Server5
  - targets:
    - XXXXXX6:9090
    labels:
      app: Prometheus_Server6
- job_name: postgres_exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: ${1}:9187
    action: replace
  file_sd_configs:
  - files:
    - /tsdb/prometheus_app/prometheus/host.yaml
    refresh_interval: 5m
- job_name: node_exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: ${1}:9100
    action: replace
  file_sd_configs:
  - files:
    - /tsdb/prometheus_app/prometheus/host.yaml
    refresh_interval: 5m
```
* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
