### ISSUE TITLE
how to sendmail with non-anonymous user

### ISSUE THREAD

**Issue by jaminlai** [prometheus/alertmanager#355]
hi, we want to notify message with alertmanager by send email.

however,the smtp server response 'Client was not authenticated', the detail tcp produce as below:
```
220 GD2-CAS01.corp.aaa.com Microsoft ESMTP MAIL Service ready at Fri, 20 May 2016 15:47:13 +0800
EHLO localhost
250-GD2-CAS01.corp.aaa.com Hello [10.xx.xx.xx]
250-SIZE 36700160
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-AUTH LOGIN
250-8BITMIME
250-BINARYMIME
250 CHUNKING
MAIL FROM:<san.zhang@aaa.com> BODY=8BITMIME
530 5.7.1 Client was not authenticated
QUIT
```

I think that the go connect smtp without carry the SMTP_AUTH_USERNAME and SMTP_AUTH_PASSWORD so take me as anonymous user

Here is the part of alertmanager.yml configure:
```
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: '192.xxx.xxx.xxx:25'
  smtp_from: 'san.zhang@aaa.com'
  smtp_auth_username: '****'
  smtp_auth_identity: '****'
  smtp_auth_password: '****'
```

and I have also set 2 environment variables:
SMTP_AUTH_USERNAME=xxx
SMTP_AUTH_PASSWORD=xxx

please help me ,thanks
