### ISSUE TITLE
Should Alertmanager allow duplicate groups?

### ISSUE THREAD

**Issue by grobinson-grafana** [prometheus/alertmanager#3564]
**What did you do?**

While testing some behavior for #3520, I noticed that it's possible to create a configuration where Alertmanager to has two or more aggregation groups with the same group key at the same time.

For example, take the following configuration:

```
receivers:
  - name: test
route:
  receiver: test
  group_wait: 15s
  group_interval: 30s
  routes:
    - receiver: test
      matchers:
        - alertname=test
      continue: true
    - receiver: test
      matchers:
        - alertname=test
      continue: true
```

and then post an alert to `/api/v2/alerts`:

```
curl -H "Content-Type: application/json" http://127.0.0.1:9093/api/v2/alerts -d '[{"labels":{"alertname":"test"}}]'
```

Two aggregation groups will be created, one per route, but with the same group keys:

```
ts=2023-10-19T20:17:27.833Z caller=dispatch.go:515 level=info component=dispatcher aggrGroup="{}/{alertname=\"test\"}:{}" msg="This is an aggregation group"
ts=2023-10-19T20:17:27.833Z caller=dispatch.go:515 level=info component=dispatcher aggrGroup="{}/{alertname=\"test\"}:{}" msg="This is an aggregation group"
```

Where this starts to get weird is when the routes have different group timers (i.e. Group wait, or Group interval), active or mute time intervals. When this happens it's no longer possible to tell which of the two groups flushed or were muted by a mute time interval.

Is it possible this behavior is intentional? If so, is there a use case for this that I haven't understood?
