### ISSUE TITLE
Discord messages not correctly formatted/delivered

### ISSUE THREAD

**Issue by dnnnvx** [prometheus/alertmanager#3576]
**What did you do?**
- Set up kube-stack on a k8s cluster (Alertmanager deployed via Prometheus Operator)
- Configured Alertmanager for discord notifications following the [official blog article guide](https://promlabs.com/blog/2022/12/23/sending-prometheus-alerts-to-discord-with-alertmanager-v0-25-0/)

**What did you expect to see?**
Discord notifications correctly delivered

**What did you see instead? Under which circumstances?**
Alertmanager cannot deliver the message, prints the error log:
```
ts=2023-10-30T16:27:09.440Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="discord/discord[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: {\"embeds\": [\"0\"]}"
```

Such response from Discord means that some Embeds are bad configured, so I guess the JSON payload created is not well formatted. Couldn't find a way to debug the created payload (via `logLevel=debug`)

Here's the simple alert I'm testing which always trigger the alert (as stated via the UI too):
```yaml
- alert: TestAlert
  expr: |
    test_metrics_count > 1
  for: 1m
  labels:
    severity: critical
  annotations:
    title: "Test Alert"
    description: "Test Alert"
```

**Environment**

* System information:
`Linux 5.15.117 x86_64`

* Alertmanager version:
```
alertmanager, version 0.26.0 (branch: HEAD, revision: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)
  build user:       root@df8d7debeef4
  build date:       20230824-11:11:58
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo
```

* Prometheus version:
```
prometheus, version 2.47.1 (branch: HEAD, revision: c4d1a8beff37cc004f1dc4ab9d2e73193f51aaeb)
  build user:       root@4829330363be
  build date:       20231004-10:31:16
  go version:       go1.21.1
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

* Alertmanager configuration file:
```yaml
global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
receivers:
- name: "null"
- discord_configs:
  - send_resolved: true
    webhook_url: https://discord.com/api/webhooks/.../...
  name: discord
route:
  group_by:
  - alertname
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: discord
  repeat_interval: 12h
  routes:
  - matchers:
    - alertname =~ "InfoInhibitor|Watchdog"
    receiver: "null"
  - matchers:
    - severity =~ "critical|error|warning|info"
    receiver: discord
templates:
- /etc/alertmanager/config/*.tmpl
```

* Prometheus configuration file:
Not relevant

* Logs:
```
ts=2023-10-30T16:27:09.440Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="discord/discord[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: {\"embeds\": [\"0\"]}"
```

**Comment by dnnnvx** [comment]
According to [this](https://stackoverflow.com/questions/53935198/in-my-discord-webhook-i-am-getting-the-error-embeds-0) that Discord error message pops up on a various type of format errors, the most frequent one is an empty embed field. I am now trying to do a bit of reverse engineering and modifying a the template to see if that's the case

**Comment by dnnnvx** [comment]
After some changes in the template, I was able to make it works, so I can confirm it's due to some empty fields in the embeds
```yaml
title: >-
  [{{ .Status | toUpper }}
  {{ if eq .Status "firing" }}: {{ .Alerts.Firing | len }}{{ end }}]
  {{ with (index .GroupLabels.SortedPairs.Values 0) }}
  {{ . }}
  {{ end }}
message: |-
  {{ if and .Alerts.Firing (gt (len .Alerts.Firing) 0) }}
  {{- range .Alerts.Firing }}
  {{- if gt (len .Annotations) 0 }}
  {{ range .Annotations.SortedPairs }}
  - {{ .Name }}: {{ .Value }}
  {{- end }}
  {{- else }}
  (No Annotations)
  {{- end }}
  {{- end }}
  {{- end }}
```
Obviously this is a slim version (I don't need all of the infos) but my suggestion was to check for the fields in the code and not in the template and maybe add a default string `-` for missing values

**Comment by Vinaum8** [comment]
> After some changes in the template, I was able to make it works, so I can confirm it's due to some empty fields in the embeds
> 
> ```yaml
> title: >-
>   [{{ .Status | toUpper }}
>   {{ if eq .Status "firing" }}: {{ .Alerts.Firing | len }}{{ end }}]
>   {{ with (index .GroupLabels.SortedPairs.Values 0) }}
>   {{ . }}
>   {{ end }}
> message: |-
>   {{ if and .Alerts.Firing (gt (len .Alerts.Firing) 0) }}
>   {{- range .Alerts.Firing }}
>   {{- if gt (len .Annotations) 0 }}
>   {{ range .Annotations.SortedPairs }}
>   - {{ .Name }}: {{ .Value }}
>   {{- end }}
>   {{- else }}
>   (No Annotations)
>   {{- end }}
>   {{- end }}
>   {{- end }}
> ```
> 
> Obviously this is a slim version (I don't need all of the infos) but my suggestion was to check for the fields in the code and not in the template and maybe add a default string `-` for missing values

@dnnnvx Where should I put the settings to use with discord?

**Comment by dnnnvx** [comment]
> @dnnnvx Where should I put the settings to use with discord?

(Note that I'm using the kube-prom-stack chart) in the alertmanager values you need to add a discord receiver (I ended up using the slack title/text templates):
```yaml
alertmanager:
  ...
  receivers:
    ...
    - name: discord
      discord_configs:
        - webhook_url: "https://discord.com/api/webhooks/..."
          send_resolved: true
          title: '{{ template "slack.title" . }}'
          message: '{{ template "slack.text" . }}'
```
