### ISSUE TITLE
MSTeams integration severity not recognized

### ISSUE THREAD

**Issue by rgarcia89** [prometheus/alertmanager#3606]
**What did you do?**
With the former Prom2Teams integration I was using, Microsoft Teams was showing a orange bar for `severity = warning` and a red bar for `severity = critical`. This is not working with the Alertmanager MSTeams integration.

**What did you expect to see?**
Severity warning in prom2teams 
![image](https://github.com/prometheus-operator/prometheus-operator/assets/4134730/38e0f349-c0e7-4702-a8d2-222a4748f078)

**What did you see instead? Under which circumstances?**
Severity warning in Alertmanager MSTeams integration
![image](https://github.com/prometheus-operator/prometheus-operator/assets/4134730/9c86109e-0d51-4d17-a39e-3f2e1218258f)

**Environment**
kube-prometheus

* Alertmanager version: v0.26.0
* Prometheus version: v2.47.2

* Alertmanager configuration file:
```
...
receivers:
    - name: "ap-teams"
      msteamsConfigs:
        - title: ""
          text: ""
          webhookUrl:
            name: msteams-config
            key: url
          sendResolved: true
...
```
