### ISSUE TITLE
Two receivers

### ISSUE THREAD

**Issue by kavyakul** [prometheus/alertmanager#362]
Is it possible to send same group of alerts to two different receivers in alert manager?

**Comment by brian-brazil** [comment]
You can use two routes, with `continue` enabled on the first one.

**Comment by kavyakul** [comment]
Thanks, it works for me in child routes. 
But can we have more that 1 default receivers?

**Comment by fabxc** [comment]
Each receiver can actually be a list of multiple receivers of different
integrations. So you can configure receiver X to always send on 2 Slack
channels and 3 email addresses for exmaple. That sounds like what you are
looking for.

**Comment by kavyakul** [comment]
Ah, ok. Thanks thats what I was looking for.

**Comment by pydolan** [comment]
@fabxc -- can you provide an example of routing alerts to two receivers (e.g. slack + email)? I've tried a few different things without any success. Thanks!

**Comment by juliusv** [comment]
@pydolan There's one in the example config: https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml#L101-L105

**Comment by pydolan** [comment]
Ah, thanks @juliusv

**Comment by xiaoping378** [comment]
i want to send one alert to two users, the below configuration will report api error,  how  do I?
Thanks.
```
receivers:
- name: 'team-X-mails'
  email_configs:
  - to: 'team-X1+alerts@example.org'
  - to: 'team-X2+alerts@example.org'
```

**Comment by sgissi** [comment]
You should be able to use "To" with multiple emails in the same line:

`to: 'team-X1+alerts@example.org, team-X2+alerts@example.org'`

Can you give it a try?

**Comment by xiaoping378** [comment]
@sgissi, don't work.

**Comment by acotorelea** [comment]
Hello, can you send using alertmanager to both slack and opsgenie? I have the following configuration : 
route:
   receiver: 'slack'

receivers:
      - name: 'slack'
        slack_configs:
          - send_resolved: true
            username: 'test'
            channel: '#sre_mon'
            api_url: <hidden>
      - name: 'opsgenie'
        opsgenie_configs:
          - send_resolved: true
            api_key: <hidden>
            teams: 'sre_team'

Thank you!

**Comment by brian-brazil** [comment]
You can create a receiver that goes to more than one place.

The prometheus-users mailing list is the best place for support questions.

**Comment by gaya3chandran1** [comment]
Is it possible to send alert A1 to group X and alert A2 to group Y? Can you please provide sample config. As of now I have all alerts reaching one group

**Comment by mxinden** [comment]
@gaya3chandran1 Please raise support questions in the Prometheus-users mailing list.

**Comment by hmacias** [comment]
@sgissi: your syntax for multiple recipients of a notification worked for me too. Thanks!

**Comment by WilliamLHarms** [comment]
Where is the archive for the prometheus users mailing list archive messages?  I have the same question, with webhook url's.  I need my default reciever to hit two differnt ones.. One for a kafka --> elk siphon and one for a generic ms teams room. 

I like the ability to troll these tickets for intel.. Reason being, they show up on web searches.

**Comment by simonpasquier** [comment]
@WilliamLHarms https://groups.google.com/forum/#!forum/prometheus-users it is listed in the [Community](https://prometheus.io/community/) page.

**Comment by RTG8055** [comment]
you can use something like this..
```
route:
 receiver: slack_pagerduty

receivers:
  - name: slack_pagerduty
    slack_configs:
      - api_url: THE_WEBHOOK_URL
        channel: '#general'
    pagerduty_configs:
      - service_key: AN_INTEGRATION_KEY
```

credits: https://www.robustperception.io/sending-alert-notifications-to-multiple-destinations

**Comment by js-timbirkett** [comment]
I know this is an old thread but for anyone who visits it... 

The trouble with the "receiver with multiple integrations approach" is that you ~can~ will end up with A LOT of ^C^V yaml all over your configs. I take the approach of one receiver == one integration and sort everything out at the route level. Example:

```yaml
route:
  routes:
    - match:
        team: ateam
      receiver: slack-custom
      routes: # Send prd critical/page to slack && pagerduty
      - receiver: slack-custom
        match_re:
          environment: prd
          severity: critical|page
        continue: true # Continue evaluation of sibling routes
      - receiver: pagerduty-ateam
        match_re:
          environment: prd
          severity: critical|page
        continue: false
  
     
    - match_re:
        severity: warning|critical|notify|page
      receiver: slack-custom
      routes: # Send prd critical/page to slack && pagerduty
      - receiver: slack-custom
        match_re:
          environment: prd
          severity: critical|page
        continue: true # Continue evaluation of sibling routes
      - receiver: pagerduty-shared
        match_re:
          environment: prd
          severity: critical|page
        continue: false
          
receivers:
  - name: slack-custom
    slack_configs: 
       - # a lot of customised slack stuff...
         channel: '{{ template "slack.channel" . }}' # Comes from .CommonAnnotations.channel
  - name: pagerduty-shared
    pagerduty_configs:
      - service_key: a servicekey
  - name: pagerduty-ateam
    pagerduty_configs:
      - service_key: a servicekey
```

Produces routes like:
<img width="1093" alt="Screenshot 2021-11-02 at 2 36 19 PM" src="https://user-images.githubusercontent.com/57101177/139868802-14502e0c-2023-4e6d-b2d4-cdaf401b8dd5.png">
<img width="1113" alt="Screenshot 2021-11-02 at 2 36 57 PM" src="https://user-images.githubusercontent.com/57101177/139868835-709bad13-e997-4990-802d-fa5261d284a5.png">
<img width="1120" alt="Screenshot 2021-11-02 at 2 40 15 PM" src="https://user-images.githubusercontent.com/57101177/139869191-883d00e2-f4d7-404d-981e-d61272431f4d.png">
<img width="1103" alt="Screenshot 2021-11-02 at 2 39 51 PM" src="https://user-images.githubusercontent.com/57101177/139869217-eafea1c7-4f9e-4eaa-90f2-14f45c0cb55b.png">
