### ISSUE TITLE
MSTeams integration sending multiple alerts in the same message even if status is different

### ISSUE THREAD

**Issue by rgarcia89** [prometheus/alertmanager#3633]
**What did you do?**
Using the freshly integrated MSTeams integration I can see that multiple alerts with different status are being send in the same message. This makes things very difficult to read and is somehow confusing if next to alerts firing resolving ones are listed as well.

**What did you expect to see?**
Alert status specific message

**What did you see instead? Under which circumstances?**
Alert status unspecific message
![Screenshot from 2023-12-08 13-22-19](https://github.com/prometheus/alertmanager/assets/4134730/9e8207b1-c1f6-4ea9-8aad-222158c11559)

**Environment**

* Alertmanager version: v0.26.0
* Prometheus version: v0.70.0

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: "null"
  continue: false
  routes:
  - receiver: monitoring/alertmanager-ap/null
    group_by:
    - cluster
    continue: true
    routes:
    - receiver: monitoring/alertmanager-ap/healthcheck
      matchers:
      - alertname="Watchdog"
      continue: false
      group_wait: 0s
      group_interval: 10s
      repeat_interval: 1m
    - receiver: monitoring/alertmanager-ap/ap-teams
      matchers:
      - severity="warning"
      continue: false
      repeat_interval: 6h
    - receiver: monitoring/alertmanager-ap/ap-pager
      matchers:
      - severity="critical"
      continue: false
      repeat_interval: 30m
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 6h
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"warning|info"
  equal:
  - namespace
  - alertname
  - cluster
receivers:
- name: "null"
- name: monitoring/alertmanager-ap/null
- name: monitoring/alertmanager-ap/healthcheck
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    url: <secret>
    url_file: ""
    max_alerts: 0
- name: monitoring/alertmanager-ap/ap-teams
  msteams_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    webhook_url: <secret>
    title: '{{ template "msteams.default.title" . }}'
    text: '{{ template "msteams.default.text" . }}'
- name: monitoring/alertmanager-ap/ap-pager
  pagerduty_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    service_key: <secret>
    url: https://events.eu.pagerduty.com/generic/2010-04-15/create_event.json
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    source: '{{ template "pagerduty.default.client" . }}'
  msteams_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    webhook_url: <secret>
    title: '{{ template "msteams.default.title" . }}'
    text: '{{ template "msteams.default.text" . }}'
templates: []
```

**Comment by simonpasquier** [comment]
This is consistent with the default format of many other integrations which lists firing/resolved alerts within the group.

The default `text`  template is defined here:

https://github.com/prometheus/alertmanager/blob/dc1466487a537ea7cfce366b69429ac79a04a221/template/default.tmpl#L151-L160

You're of course free to provide your own template.

**Comment by rgarcia89** [comment]
@simonpasquier Alright not sure if in other integrations it is presented more clearly. In MS Teams case, this leads to confusing behavior, if you ask me.

Am I able to provide an own template using the prometheus-operator?

**Comment by kbudde** [comment]
@rgarcia89 alertmanager allows loading templates from file system. 
I never tested it, but you can load additional configmaps into alertmanager using: `alertmanager.spec.configMaps`.
Inside `alertmanager.spec.alertmanagerConfiguration` you should be able to load the templates. 
Better to ask in the prometheus-operator community as I never tested it :) 

Simpler is to add the template inline with your receivers configuration

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: example
spec:
  route:
    groupBy:
    - cluster
    #...
    receiver: Msteams
  receivers:
  - name: Msteams
    msteamsConfigs:
    - webhookUrl: 
        name: #...
      sendResolved: true
      #... 
      text: |2-
        {{ if gt (len .Alerts.Firing) 0 }} 
        # Alerts Firing: 
        {{ template "__text_alert_list_markdown" .Alerts.Firing }} 
        {{ end }} 
      title: "can also be customized with templates"
```

In general the templates are quite powerful and can be adapted to your way of working. Some people (like me) prefer to only send summary and descriptions of open alerts.

**Comment by rgarcia89** [comment]
@kbudde thanks for your response. I haven't tried to load a template using the `alertmanager.spec.alertmanagerConfiguration` but I will definitely give it a try.

Could you maybe share your template which only sends the summary and description of open alerts?
This could help me with forming something that suits my needs. I was quite happy with the template [prom2teams](https://github.com/idealista/prom2teams/blob/develop/prom2teams/resources/templates/teams.j2) is using.

**Comment by kbudde** [comment]
Sure, 
this should work:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: example
spec:
  route:
    groupBy:
    - cluster
    #...
    receiver: Msteams
  receivers:
  - name: Msteams
    msteamsConfigs:
    - webhookUrl: 
        name: #...
      sendResolved: true
      #... 
      text: |2-
         {{ range .Alerts -}}
         *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
         {{ if  .Annotations.description }}
         
         *Description:* {{ .Annotations.description }}
         {{ end }}
         
         ---
         {{ end }}
```
