### ISSUE TITLE
Is there possibility to add more than 1 email to the receiver group?

### ISSUE THREAD

**Issue by anioool** [prometheus/alertmanager#364]
Hi,

I need to add more than 1 email address to the receiver group. Could you tell me if there is possibility to that?

I tried to add multiple 'to' entries in config.yaml but notification is not sent when event is fired. When I put only one email address then it works.

**Comment by fabxc** [comment]
The `email_configs` field accepts a list of email configurations. For example:

```
receivers:
- name: 'x'
  email_configs:
  - to: 'a@example.org'
  - to: 'b@example.org'
```

Is that what you tried. It's generally good to share the configurations you tried along with version information and logs to help us debug your problem.
