### ISSUE TITLE
Add if statement to alertmanager.yml

### ISSUE THREAD

**Issue by mateeyow** [prometheus/alertmanager#366]
Hi, I was wondering if it's possible to add an if statement to an alertmanager.yml. I'm thinking of something like this:

```yml
receivers:
- name: blackbox
  slack_configs:
  - send_resolved: true
    channel: prometheus
    text: "{{if .Status eq 'firing'}} {{ .CommonLabels.instance }} is down! \nPlease contact the team right away! {{else}} {{ .CommonLabels.instance }} is back up again! You can now relax! {{end}}"
```

But it seems that alertmanager does not recognize 'firing' word.
