### ISSUE TITLE
Request: Add topic_id as an optional parameter to telegram_config

### ISSUE THREAD

**Issue by instantdreams** [prometheus/alertmanager#3672]
**What did you do?**
Configured Alertmanager to use Telegram notifications, and set the chat_id to be a group.

**What did you expect to see?**
The ability to set a topic_id to target a particular topic.

**What did you see instead? Under which circumstances?**
Messages go to first topic, usually General.

**Environment**

* System information:
Linux 6.1.0-17-amd64 x86_64

* Alertmanager version:
alertmanager, version 0.26.0 (branch: HEAD, revision: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)
  build user:       root@df8d7debeef4
  build date:       20230824-11:11:58
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo

* Prometheus version:
prometheus, version 2.49.1 (branch: HEAD, revision: 43e14844a33b65e2a396e3944272af8b3a494071)
  build user:       root@6d5f4c649d25
  build date:       20240115-16:58:43
  go version:       go1.21.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels

* Alertmanager configuration file:
```
global:
  resolve_timeout: 10m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 5m
  receiver: 'id-telegram'

receivers:
- name: 'id-telegram'
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: $BOT_TOKEN
    chat_id: $CHAT_ID
    send_resolved: true
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['[host-ip]:[port}']

rule_files:
  - 'alert.yml'

scrape_configs:
  - [various-configurations]
```

* Logs:
n/a

* Notes:
My logging stack is working well, but I would very much like to be able to target a particular topic in Telgram.
