### ISSUE TITLE
Problem with Alertmanager configuration

### ISSUE THREAD

**Issue by daniel-wtfoxtrot** [prometheus/alertmanager#3700]
**What did you do?**

Hi,
I'm using Grafana in my AWS EKS Cluster via the `[kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)` Helm Chart. I want to use the Prometheus Alertmanager for my Alerting. My configuration looks right to me.

<img width="1254" alt="Screenshot 2024-02-01 at 12 08 28" src="https://github.com/prometheus/alertmanager/assets/111510693/d2999fb9-7e59-4c03-82f7-8235aaeec96a">

What I'm trying to achieve is that only Alerts with `critical` severity from namespaces that don't include `foo-` in their name get send to Slack. When I fire two test alerts from a `foo-` namespace (one with severity critical). I see this:

<img width="1233" alt="Screenshot 2024-02-01 at 10 27 11" src="https://github.com/prometheus/alertmanager/assets/111510693/a2c90319-5e02-413c-bacf-0c376d92ef84">

This looks right as well. However the critical alert still gets send to Slack and I'm really confused about it. I tried a lot of stuff e.g. inverting the configuration, so that default gets send to null. Unfortunately nothing seems to help.

**What did you expect to see?**

None of the alerts should get send to Slack

**What did you see instead? Under which circumstances?**

The critical alert gets still send to Slack

**Environment**

AWS EKS Cluster

* Alertmanager version:

Branch: HEAD
BuildDate: 20230824-11:11:58
GoVersion: go1.20.7
Revision: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d
Version: 0.26.0

* Prometheus version:

Branch: HEAD
BuildDate: 20231116-04:35:21
GoVersion: go1.21.4
Revision: 6d80b30990bc297d95b5c844e118c4011fad8054
Version: 2.48.0

* Alertmanager configuration file:
```
global:
  resolve_timeout: 1m
inhibit_rules:
- equal:
  - alertname
  - cluster
  - service
  source_matchers:
  - severity="critical"
  target_matchers:
  - severity="warning"
receivers:
- name: "null"
- name: slack-notifications
  slack_configs:
  - actions:
    - text: 'Runbook :green_book:'
      type: button
      url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
    - text: 'Query :mag:'
      type: button
      url: '{{ (index .Alerts 0).GeneratorURL }}'
    - text: 'Dashboard :chart_with_upwards_trend:'
      type: button
      url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
    - text: 'Silence :no_bell:'
      type: button
      url: '{{ template "__alert_silence_link" . }}'
    channel: '#alerts'
    color: '{{ template "slack.color" . }}'
    send_resolved: true
    slack_api_url: [REDACTED]
    text: '{{ template "slack.text" . }}'
    title: '{{ template "slack.title" . }}'
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: slack-notifications
  repeat_interval: 12h
  routes:
  - continue: false
    matchers:
    - severity!="critical"
    receiver: "null"
  - continue: false
    matchers:
    - namespace=~"foo-"
    receiver: "null"
templates:
- /etc/alertmanager/config/*.tmpl
```
