### ISSUE TITLE
alertmanager.config.global.http_config.no_proxy is invalid

### ISSUE THREAD

**Issue by lkeijser** [prometheus/alertmanager#3708]
**What did you do?**
Added this piece of config to values.yaml:
```
alertmanager:
    config:
      global:
        http_config:
          proxy_url: 'http://webproxy.my.corp:8080'
          no_proxy: 'prometheus-msteams:2000'
        resolve_timeout: 6m
```

**What did you expect to see?**
The configuration should be applied to alertmanager.yml inside the pod

**What did you see instead? Under which circumstances?**
The configuration does not get applied. The operator logs this error message instead:
`level=error ts=2024-02-05T08:50:16.702986872Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring/prometheus-stack-rotterdam-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 3: field no_proxy not found in type alertmanager.httpClientConfig"`

**Environment**
Using kube-prometheus-stack on kubernetes 1.26.5

* System information:
`alertmanager:  Linux 5.4.0-91-generic x86_64`

* Alertmanager version:
```
alertmanager, version 0.26.0 (branch: HEAD, revision: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)
  build user:       root@df8d7debeef4
  build date:       20230824-11:11:58
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo
```

* Prometheus version:
```
prometheus, version 2.49.1 (branch: HEAD, revision: 43e14844a33b65e2a396e3944272af8b3a494071)
  build user:       root@6d5f4c649d25
  build date:       20240115-16:58:43
  go version:       go1.21.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

* Alertmanager configuration file:
see above

* Prometheus configuration file:
N/A

* Logs:
see above

**Comment by pchang388** [comment]
I am also seeing this same issue, having other problems ([#4358](https://github.com/prometheus-community/helm-charts/issues/4358)) it seems with setting up a simple http proxy config for alertmanager

spec:
```yaml
    receivers:
    - name: 'null'
    - name: ms-teams
      msteams_configs:
        - webhook_url: REDACT
          title: '[Kopje Dev] {{ template "msteams.default.title" . }}'
          http_config:
            proxy_url: REDACT
            no_proxy: ".internal,.svc.cluster.local,10.100.200.1"
            tls_config:
              insecure_skip_verify: true
```
