### ISSUE TITLE
Templates at route level

### ISSUE THREAD

**Issue by JesusFrontelo** [prometheus/alertmanager#3730]
Hi!

I'm trying to define a lot of matchers and their corresponding receivers, but I've run into a bit of a problem. 

If I want to set up a matcher, based on label severity with the value info (for example), for a receiver, and then I want to set up a matcher based on the same label, but with a different value, and I need the email to be sent with a different template for that particular value, I should also create the receiver again with a different name. 

Would it be possible to define templates at the routes level? something like:

```
  - receiver: Team
    matchers:
    - severity =~ "critical|severe"
    html: '{{ template "email.html" . }}'
    continue: true
  - receiver: Team
    matchers:
    - severity = "info"
    html: '{{ template "email_info.html" . }}'
    continue: true
```

Regards.
