### ISSUE TITLE
Why is it not supported to continue to search for a matching receiver and continue sending after the previous receiver fails?

### ISSUE THREAD

**Issue by yuguangye** [prometheus/alertmanager#3743]
I have a scenario where I hope that after the alertmanager fails to push the webhook, even if continue: false, it will continue to look for other receivers and continue to try to send. In this scenario, why is not supported? I think this is more reliable

for example：
```
receivers:
  - name: "receiver-aa"
    webhook_configs:
        - url: 'https://alarm.com/alarms'
          send_resolved: true
  - name: "receiver-bb"
      slack_configs:
        - channel: "#alarms-bb"
          actions: *action_buttons
          http_config: *http_config
          
routes:          
  - match:
       dc: "aaa"
     receiver: "receiver-aa"
     continue: false
  - match:
       dc: "aaa"
     receiver: "receiver-bb"
```
