### ISSUE TITLE
Failing to send email alerts - docs and error messages not helping much

### ISSUE THREAD

**Issue by estechnical** [prometheus/alertmanager#377]
Hi,

I have set up as follows:
```
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp-xxxxx:465'
  smtp_from: 'Alertmanager <xxxx@xxxxx.com>'
  smtp_auth_username: 'xx@xxxxxx.com'
  smtp_auth_password: 'xxxx'
  require_tls: true
route:
  group_by: ['severity','alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: mail
receivers:
- name: 'mail'
  email_configs:
  - to: 'xxxxx@gmail.com'
```

I have tried many permutations of the config without any obvious success. The most I have got to happen is regular messages printed to stdout:
```
level=warning msg="Notify attempt 1 failed: EOF" source="notify.go:193" 
```

Firstly, the docs don't say very much about configuring email alerts. 

2nd, the error message is not helping me at all.

Any suggestions? Many thanks!

**Comment by Chentongxuedefanhua** [comment]
how to fix it?

**Comment by aecolley** [comment]
The smtp_from is incorrect. It should be just the email address proper (no "Alertmanager <" or ">"). It's used as the Reverse-Path field (defined in section 4.1.2 of RFC-2821).

**Comment by brian-brazil** [comment]
Presuming that's the issue, I think this is something that we should have work.

**Comment by jiangytcn** [comment]
hi @aecolley, i had the same issue with you. but even the smtp_from is correct, actually i configure it with the same value with smtp_auth_username.  do you have any insights ?
here's my environment 

→ ./alertmanager --version
alertmanager, version 0.3.0 (branch: master, revision: 66142a9)
  build user:       jiangytcn@XXX
  build date:       20160804-03:57:59
  go version:       go1.6.2

**Comment by estechnical** [comment]
I have now got this working, I think at various stages I changed things as per other setups/docs/hints I found googling etc.
```
smtp_from: 'xxxx@xxxx.com'
```
worked for me in the end, so I agree with others.

Here is a revised config example:

```
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp-xxxxx:465'
  smtp_from: 'xxxx@xxxxx.com'
  smtp_auth_username: 'xx@xxxxxx.com'
  smtp_auth_password: 'xxxx'
  require_tls: true
route:
  group_by: ['severity','alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: mail
receivers:
- name: 'mail'
  email_configs:
  - to: 'xxxxx@gmail.com'
```
