### ISSUE TITLE
Improving the docs for email config?

### ISSUE THREAD

**Issue by estechnical** [prometheus/alertmanager#384]
I thought since I was still having only limited success with alertmanager sending emails, I should check whether I'm doing it right, and at the same time try and get something up here for others to copy from until the docs are the definitive source of info...

Reading from various articles about the SMTP AUTH world, including https://www.fastmail.com/help/technical/ssltlsstarttls.html, I concluded that the likely combinations are:

Example config for TLS email server:

```
global:
  smtp_smarthost: 'xxxx.com:578'
  smtp_from: 'yyyy@xxxx.com'
  smtp_auth_identity: 'yyyy@xxxx.com'
  smtp_auth_secret: 'nnnnnnnn'
```

Example config for SSL email server:

```
global:
  smtp_smarthost: 'xxxx.com:465'
  smtp_from: 'yyyy@xxxx.com'
  smtp_auth_username: 'yyyy@xxxx.com'
  smtp_auth_password: 'nnnnnnnnnn'
```

Example config for plain SMTP email server:

```
global:
  smtp_smarthost: 'xxxx.com:25'
  smtp_from: 'yyyy@xxxx.com'
```

Example config for SMTP with auth:

```
global:
  smtp_smarthost: 'xxxx.com:25'
  smtp_from: 'yyyy@xxxx.com'
  smtp_auth_username: 'yyyy@xxxx.com'
  smtp_auth_password: 'nnnnnnnnnn'
```

Then a simple email `receiver` config:

```
receivers:
- name: 'mail'
 email_configs:
 - to: 'xxx@gmail.com'
   send_resolved: true
   require_tls: false
 - to: 'yyy@gmail.com'
   send_resolved: true
   require_tls: false
```

Please correct me if anything is wrong, I'll edit the config snippets - I'm not sure if I've missed any options.

Where do `smtp_auth_identity` and `smtp_auth_secret` fit into the above configs? Are there more permutations than those I have listed?

I have received errors like `WARN[0600] Notify attempt 1 failed: EOF                  source=notify.go:193` when it tries to send the email. I think this sort of error, once we know the reason for it should be caught and a useful error message printed...

I'm happy to try and fix docs and code, but I'm not an expert in email or go!

Thanks in advance to anyone who can help!

**Comment by estechnical** [comment]
I updated the example configs a bit, I have now successfully sent emails from alertmanager using the SMTP with auth config above. I have had issues with TLS/SSL emails as the error reporting is almost nonexistent.

**Comment by RajatNair** [comment]
@estechnical - are you sure 
```
global:
  smtp_require_tls: false
```
works?

In latest prom/alertmanager image from Docker Hub, this setting did not work. Instead adding this setting as part of email config worked -
```
email_configs:
    - to: 'me@email.com'
      require_tls: false
```

**Comment by beorn7** [comment]
Indeed, there is no global TLS option. See #433

**Comment by estechnical** [comment]
I have updated the config snippets in my post according to these suggestions. Thanks :)

**Comment by michaelyangwj** [comment]
Indeed,a more detail doc is necessary.

**Comment by allenbang** [comment]
> DEBU[0122] Notify attempt 2 failed: EOF                  source=notify.go:546
> ERRO[0122] Error on notify: EOF
I think it make users feel confused. It's better to have more certain error.

**Comment by civik** [comment]
@estechnical you're my f'n hero with the 'require_tls: false'.  Wasted a day because that flag seems to not be documented ANYWHERE.

**Comment by estechnical** [comment]
I notice the "help wanted" tag... how would I help? :)

**Comment by mxinden** [comment]
@estechnical could you extend the existing `email_config` documentation in the [Promtheus documentation](https://prometheus.io/docs/alerting/configuration/#email_config)? You can find the repository [here](https://github.com/prometheus/docs/blob/master/content/docs/alerting/configuration.md).

**Comment by bjoernhaeuser** [comment]
I started to work on this: prometheus/docs#917

**Comment by vietthang207** [comment]
Hello all. I have a question related to this config but the docs is not clear enough. How can I send to multiple email, I've tried some format of the but they didn't work:
1. 
to: a@gmail.com,b@gmail.com
2.
to: a@gmail.com
to: a@gmail.com

Thanks in advance.

**Comment by mxinden** [comment]
@vietthang207 you should just be able to separate them by comma:

```yaml
receivers:
- name: 'email'
  email_configs:
  - to: test1@test.de, test2@test.de
```

For better debugging of the email provider make sure to start Alertmanager with the `--log.level=debug` flag. As a test server you can use `sudo python -m smtpd -n -c DebuggingServer 192.168.2.118:25` in case you have python installed.

In general, please open up usage questions on the prometheus-users@googlegroups.com mailing list.
