### ISSUE TITLE
bad response status 404 Not Found

### ISSUE THREAD

**Issue by dynamicsamurai816** [prometheus/alertmanager#3875]
I have a docker compose setup

```
prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./services/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://${HOST_SERVER}/prometheus'
      
  alertmanager:
    image: prom/alertmanager:v0.21.0
    restart: unless-stopped
    volumes:
      - ./services/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--web.external-url=http://${HOST_SERVER}/alertmanager'
    ports:
      - 9093:9093
```
      
in my prometheus.yml

```
rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
```

In my prometheus, I am testing an alert, to see if Alertmanager can catch it

```
rules:
      - alert: TestAlert
        expr: vector(1)
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: This is a test alert
```

I see the alert firing off in Prometheus. But when I check the docker logs, I keep seeing this 

`ts=2024-06-12T13:01:07.752Z caller=notifier.go:549 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"`

And I truly don't understand the issue here. If I go into the prometheus docker container, and I try to reach the alertmanager container, it says it can reach it

```
/prometheus $ wget http://alertmanager:9093
Connecting to alertmanager:9093 (172.26.0.2:9093)
wget: can't open 'index.html': File exists
```

but why can it not send the alert to alertmanager? I've tried this some time ago and I was able to see the alerts
