### ISSUE TITLE
Docker image prom/alertmanager:v0.27.0 fails to parse webhook_url_file from msteams_config

### ISSUE THREAD

**Issue by martipoe** [prometheus/alertmanager#3894]
**What did you do?**

I tried to use the latest Docker Image [prom/alertmanager:v0.27.0](https://hub.docker.com/layers/prom/alertmanager/v0.27.0/images/sha256-c592a7ed3804780f20bb52614823cac2fef6a356a40beda50bee9573201dd135?context=explore ) with a **webhook_url_file** in https://prometheus.io/docs/alerting/latest/configuration/#msteams_config, because the feature should be supported for 0.27.0 according to the [Changelog](https://github.com/prometheus/alertmanager/blob/main/CHANGELOG.md#0270--2024-02-28).

**What did you expect to see?**

Prometheus should be able to read the URL from **webhook_url_file**.

**What did you see instead? Under which circumstances?**

The docker container displays the error and keeps restarting:
`ts=2024-06-23T20:09:11.319Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/alertmanager.yml err="no msteams webhook URL provided"`

This issue does not occur with [prom/alertmanager:main](https://hub.docker.com/layers/prom/alertmanager/main/images/sha256-525bd26118298318f50bbff1fa3af837da53167a88a8d4f01cc1a07555f1b857?context=explore), then the **webhook_url_file** is read successfully.

**Environment**

* Alertmanager version:

```
alertmanager, version 0.27.0 (branch: HEAD, revision: 0aa3c2aad14cff039931923ab16b26b7481783b5)
  build user:       root@22cd11f671e9
  build date:       20240228-11:51:20
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             netgo
```

* Alertmanager configuration file:
```
...
receivers:
  # https://prometheus.io/docs/alerting/latest/configuration/#msteams_config
  - name: 'MicrosoftTeamsTEST'
    msteams_configs:
      - webhook_url_file: "/etc/alertmanager/secrets/webhook_test"
        send_resolved: true
...
```
