### ISSUE TITLE
AlertManager doesn't send some of alerts to Pagerduty

### ISSUE THREAD

**Issue by De4dGho5t** [prometheus/alertmanager#3902]
I got those erros on some of alerts in alertmanger

`
ts=2024-06-26T14:45:32.988Z caller=dispatch.go:353 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="pagerduty-notifications/pagerduty[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: Event object is invalid: 'payload.severity' is invalid (must be one of the following: 'critical', 'warning', 'error' or 'info')"
`
Because log doesn't say which alert are problematic, for compering I will show screenshot from pagerduty and alertmanager UI

![Screenshot from 2024-06-26 16-55-09](https://github.com/prometheus/alertmanager/assets/17433841/a4bf3575-20e4-4caa-91f5-0ce401b82038)

![Screenshot from 2024-06-26 16-57-32](https://github.com/prometheus/alertmanager/assets/17433841/7d376c9a-df24-4288-bee8-67c734a23237)

Like you see `CPUThrottlingHigh` and `KubePersistentVolumeFillingUp` didn't show up in PD

Those are all alerts from alertmanager api: [alerts.json](https://github.com/user-attachments/files/15991116/alerts.json)
Log is saying that severity is invalid, but all alerts have correct values of severity.

Currently I'm using kube-prometheus-stack in version: 60.2.0, so alert manger version is: `
quay.io/prometheus/alertmanager:v0.27.0`

Alertmanger logs with debug enabled: 
[alertmanager.log](https://github.com/user-attachments/files/15991176/alertmanager.log)

My alertmanager config:

```
global:
  resolve_timeout: 1m
route:
  receiver: pagerduty-notifications
  group_by:
  - alertname
  routes:
  - receiver: "null"
    matchers:
    - alertname =~ "InfoInhibitor|Watchdog"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
inhibit_rules:
- target_matchers:
  - severity =~ warning|info
  source_matchers:
  - severity = critical
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - severity = warning
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - alertname = InfoInhibitor
  equal:
  - namespace
  - alertname
receivers:
- name: "null"
- name: pagerduty-notifications
  pagerduty_configs:
  - send_resolved: true
    routing_key: key
    severity: '{{ range .Alerts }}{{ .Labels.severity | toLower }}{{ end }}'
templates:
- /etc/alertmanager/config/*.tmpl
```
