### ISSUE TITLE
Feature request: slack_configs.send_resolved a templatable field

### ISSUE THREAD

**Issue by dwilliams782** [prometheus/alertmanager#4033]
**What did you do?**

I'm trying to set up a receiver that can take a dynamic value for `send_resolved`, such as:

```
    ## Route alerts based on slack_channel label
      - name: global_slack_channel_label
        slack_configs:
          - api_url: <some-url>
            channel: '{{ printf \"#%s\" (index ((index .Alerts 0).Labels) \"slack_channel\") }}'
            send_resolved: {{ (index ((index .Alerts 0).Labels)) "send_resolved") | quote | default true | replace "\"" ""  }}
```

With this, we get a `line 894: cannot unmarshal !!map into bool` as Alertmanager requires this field to be boolean instead of a tmpl_string. There are various approaches to how this could be done so I'm not worried about this particular template working or not, but the `send_resolved` field does not allow templating as-is.

**What did you expect to see?**

I would like to be able to render true/false boolean based on a label in an alert. This would reduce the number of receivers required.

**Comment by grobinson-grafana** [comment]
I think, at least for me, it is hard to understand what the use case is for this feature. Making notification decisions based on individual alerts also doesn't fit well in the Alertmanager design, which is based around grouping related alerts together into a congruent set.

**Comment by grobinson-grafana** [comment]
I think, at least for me, it is hard to understand what the use case is for this feature. Making notification decisions based on individual alerts also doesn't fit well in the Alertmanager design, which is based around grouping related alerts together. It would also be very easy for someone to write an invalid template and accidentally break all their notifications without realizing it.

**Comment by dwilliams782** [comment]
We have a centralised alertmanager with a configuration containing routes and receivers for a dozen or more teams, with hundreds of different alerts flowing to different channels. 

Some alerts teams will want send_resolved notifications, other alerts won't. The only way to do this currently is to have two routes and two receivers, one with a `send_resolved: false` matcher on it, which will route to the receiver with send_resolved set to be false. 

It would massively simplify (half!) our receivers configuration if we could inherit send_resolved (and other route level attributes like group_by) from the alert labels.

**Comment by grobinson-grafana** [comment]
Isn't this just "moving" the messiness from Alertmanager to Prometheus? Instead of having a receiver per instead, now all alert rules must have a custom label `send_resolved`?

**Comment by dwilliams782** [comment]
It would be optional with `send_resolved: true` default, with alerts optionally able to turn off resolved notifications, yes. 

That complexity per alert makes way more sense to me than it does at a receiver level; a lot of alerts just generate noise with resolved notifications, but some are genuinely useful.

**Comment by dwilliams782** [comment]
Practical example of how we use dynamic configuration. Taking some generic kubernetes alert:

```
        - alert: CPUThrottlingHigh
          annotations:
            description: "{{ $value | humanizePercentage }} throttling of CPU in namespace {{ $labels.namespace }} for container {{ $labels.container }} in pod {{ $labels.pod }}."
            summary: Processes experience elevated CPU throttling.
            runbook: <link to our runbook>
          expr: |
            sum by (container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total[5m]))
            /
            sum by (container, pod, namespace) (increase(container_cpu_cfs_periods_total[5m])) > (25 / 100)
          for: 15m
          labels:
            severity: info
            group_by: pod
```

We want this `CPUThrottlingHigh` alert to be routed to the correct slack channel based on the `team` label in the pod, but this particular alert we want to be grouped by pod, so we get individual alerts per pod instead of grouping them and risk missing notifications. We set a `group_by: pod` label on the alert, and then we then have to have a route per team like:

```
- receiver: slack_devops
   group_by: [alertname, pod]
   match_re:
     team: devops|platform-infrastructure|cloud-infrastructure
     group_by: pod
```

Being able to set the `group_by` attribute from the alert labels would reduce the amount of routes we require, and it's the same idea with making send_resolved templatable too. It makes perfect sense to me for each alert to be able to specify what it should be grouped by, repeat interval, group_wait, send_resolved and all those other route/receiver level attributes.
