### ISSUE TITLE
Bug rocketchat channel not templated

### ISSUE THREAD

**Issue by rekup** [prometheus/alertmanager#4219]
Alertmanager version:

```
alertmanager, version 0.28.0 (branch: HEAD, revision: 4ce04fb010bd626fca35928dcfe82f6f2da52ced)
  build user:       root@40be7f318ba7
  build date:       20250115-14:22:34
  go version:       go1.23.4
  platform:         linux/amd64
  tags:             netgo
```

Configuration:

```yaml
receivers:
- name: dummy
- name: rocketchat
  rocketchat_configs:
    - api_url: https://chat.example.org
      channel: '{{ .CommonLabels.rocketchat_channel }}'
      token: redacted
      token_id: redacted
      text: |
        {{- if (index .Alerts 0).Annotations.summary }}
        {{- "\n" -}}
        *Summary:* {{ (index .Alerts 0).Annotations.summary }}
        {{- end }}

        {{ range .Alerts }}
    
            {{- if .Annotations.description }}
            {{- "\n" -}}
            {{ .Annotations.description }}
            {{- "\n" -}}
            {{- end }}
            {{- if .Annotations.message }}
            {{- "\n" -}}
            {{ .Annotations.message }}
            {{- "\n" -}}
            {{- end }}
    
        {{- end }}

      actions:
      - type: button
        text: 'Runbook'
        url: '{{ (index .Alerts 0).Labels.runbook_url }}'
      - type: button
        text: 'Query'
        url: '{{ (index .Alerts 0).GeneratorURL }}'
      - type: button
        text: 'Dashboard'
        url: '{{ (index .Alerts 0).Annotations.dashboard }}'

route:
  group_by:
  - alertname
  group_interval: 5s
  group_wait: 30s
  receiver: dummy
  repeat_interval: 24h
  routes:
  - matchers:
    - rocketchat_channel =~ ".+"
    receiver: rocketchat
```

According to the [documentation](https://github.com/prometheus/alertmanager/pull/3600/files#diff-17ed18489a956f326ec0fe4040850c5bc9261d4631fb42da4c52891d74a59180R1301), the Rocket.Chat channel name can be a template:

> `[ channel: <tmpl_string> | default = global.rocketchat_api_url ]`

But if I understand the [current implementation](https://github.com/prometheus/alertmanager/pull/3600/files#diff-f2e823977ce50fd8cfe6e7a325c792bba258e92cd6281e2c2e7044359feb82f7R206) correctly, the channel is not passed to `tmplText()`.

Using the configuration above results in the following error:

```
Jan 23 11:30:18 prometheus01.example.org alertmanager[537352]: time=2025-01-23T10:30:18.509Z level=ERROR source=dispatch.go:360 msg="Notify for alerts failed" component=dispatcher num_alerts=1 err="test/rocketchat[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"{{ .CommonLabels.rocketchat_channel }}\": unexpected status code 400: {\"success\":false,\"error\":\"[invalid-channel]\",\"errorType\":\"invalid-channel\"}"
```

I'm not sure what the intended behavior is, but I think templating the channel could be useful.
