### ISSUE TITLE
Support for Jira Service Management in alertmanager

### ISSUE THREAD

**Issue by meesk** [prometheus/alertmanager#4244]
Atlassian recently announced the option to move to JSM (Jira Service Management) from opsgenie. The authentication (for instance) seems to differ from opsgenie. Is it possible this will also be supported by alertmanager in the future? Or is this already a known issue?

More info [https://support.atlassian.com/jira-service-management-cloud/docs/start-shifting-from-opsgenie-to-jira-service-management/](https://support.atlassian.com/jira-service-management-cloud/docs/start-shifting-from-opsgenie-to-jira-service-management/)

**Comment by grobinson-grafana** [comment]
Is that the same as this, or something else? https://prometheus.io/docs/alerting/latest/configuration/#jira_config

**Comment by meesk** [comment]
@grobinson-grafana I believe it is a seperate component. Isnt the jira_config more focused on creating tickets etc? Jira Service Management is purely a replacement for opsgenie, which has all its features opsgenie has.

JSM is pretty new and we are also not migrated yet fully, so I'm not so sure about the technical differences between the two.

The reason I asked this in the first place is because the Heartbeats from opsgenie, seem to be no longer available, but only in JSM, from the UI atleast. We currently have it configured in JSM but use the 'old' opsgenie API to reference it still.

**Comment by meesk** [comment]
@grobinson-grafana the docs for it are here aswell -> https://developer.atlassian.com/cloud/jira/service-desk-ops/rest/v2/api-group-alerts/#api-v1-alerts-get. OpsGenie is now officially in read-only mode.

**Comment by ndlanier** [comment]
I use the opsgenie integration to point to JSM the api is the same, just a different entry point

**Comment by 0xSeb** [comment]
Same issue here, what endpoint do you use @ndlanier  ?

**Comment by ndlanier** [comment]
> Same issue here, what endpoint do you use [@ndlanier](https://github.com/ndlanier) ?

https://api.atlassian.com/jsm/ops/integration/

**Comment by skoenig** [comment]
I can confirm what @ndlanier said. This is a valid config for Alertmanager to send alerts to JSM:
```
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: base-receiver
receivers:
  - name: base-receiver
    opsgenie_configs:
      - api_key: <API_KEY>
        api_url: https://api.atlassian.com/jsm/ops/integration/
        message: '{{ printf "%.130s" .CommonLabels.alertname }}'
```
