### ISSUE TITLE
Query about visibility of alerts in replicas in Alertmanager cluster mode

### ISSUE THREAD

**Issue by shivgana** [prometheus/alertmanager#4249]
**Alertmanager Version**: 0.27.0

**Details:**
Override yaml file
```yaml
replicaCount: 3
extraArgs:
  data.retention: 130m
  log.level: debug
config:
  global:
    resolve_timeout: 24h
  receivers:
  - name: webhook
    webhost_configs:
    - url: http://test-streamer:500/
  route:
    group_by: 
    - alertname
    group_wait: 30s
    group interval: 10s
    repeat interval: 10m
    receiver: webhook
```
When we deploy Alertmanager with 3 replica, alertmanager will deployed with alertmanager cli cluster options.
Pods are up and running.

Now I've sent alert to alertmanager to first replica pod.

**Query:**
- Will Alert Manager of first pod will send alerts to peers. Or it will monitor and if same is received on peers to continue to send alert status to webhook.
