### ISSUE TITLE
No messages sent to the telegram

### ISSUE THREAD

**Issue by VuzzyM** [prometheus/alertmanager#4254]
Hi.

Before I had no problems, now I started to have, I don't know why, it doesn't send messages to telegram, I tried many methods and in the configuration.

**Version:** Docker prom/alertmanager:latest
sha256:d5155cfac40a6d9250ffc97c19db2c5e190c7bc57c6b67125c94903358f8c7d8
version=0.28.0

**docker-compose.yml:**
```
alertmanager:
    container_name: alert_manager
    image: prom/alertmanager:latest
    restart: unless-stopped
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - monitoring
```

**config.yml:**
```
route:
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname', 'cluster', 'service']
  receiver: telegram

templates:
  - "/etc/alertmanager/templates/*.tmpl"

receivers:
  - name: telegram
    telegram_configs:
      - api_url: https://api.telegram.org
        parse_mode: "HTML"
        message: '{{ template "telegram.default" .}}'
        chat_id: -00000000                                 # your chat id
        bot_token: 0000000:0000000000   # your telegram bot token
```

**Logs:**
```
{"log":"time=2025-02-16T17:26:09.729Z level=INFO source=main.go:191 msg=\"Starting Alertmanager\" version=\"(version=0.28.0, branch=HEAD, revision=4ce04fb010bd626fca35928dcfe82f6f2da52ced)\"\n","stream":"stderr","time":"2025-02-16T17:26:09.729909045Z"}
{"log":"time=2025-02-16T17:26:09.729Z level=INFO source=main.go:192 msg=\"Build context\" build_context=\"(go=go1.23.4, platform=linux/amd64, user=root, date=20250115-14:22:34, tags=netgo)\"\n","stream":"stderr","time":"2025-02-16T17:26:09.729950503Z"}
{"log":"time=2025-02-16T17:26:09.730Z level=INFO source=cluster.go:185 msg=\"setting advertise address explicitly\" component=cluster addr=172.18.0.3 port=9094\n","stream":"stderr","time":"2025-02-16T17:26:09.730287047Z"}
{"log":"time=2025-02-16T17:26:09.730Z level=INFO source=cluster.go:674 msg=\"Waiting for gossip to settle...\" component=cluster interval=2s\n","stream":"stderr","time":"2025-02-16T17:26:09.730799821Z"}
{"log":"time=2025-02-16T17:26:09.749Z level=INFO source=coordinator.go:112 msg=\"Loading configuration file\" component=configuration file=/etc/alertmanager/config.yml\n","stream":"stderr","time":"2025-02-16T17:26:09.749128888Z"}
{"log":"time=2025-02-16T17:26:09.749Z level=INFO source=coordinator.go:125 msg=\"Completed loading of configuration file\" component=configuration file=/etc/alertmanager/config.yml\n","stream":"stderr","time":"2025-02-16T17:26:09.749195118Z"}
{"log":"time=2025-02-16T17:26:09.750Z level=INFO source=tls_config.go:347 msg=\"Listening on\" address=[::]:9093\n","stream":"stderr","time":"2025-02-16T17:26:09.750567495Z"}
{"log":"time=2025-02-16T17:26:09.750Z level=INFO source=tls_config.go:350 msg=\"TLS is disabled.\" http2=false address=[::]:9093\n","stream":"stderr","time":"2025-02-16T17:26:09.750579311Z"}
{"log":"time=2025-02-16T17:26:11.731Z level=INFO source=cluster.go:699 msg=\"gossip not settled\" component=cluster polls=0 before=0 now=1 elapsed=2.000208983s\n","stream":"stderr","time":"2025-02-16T17:26:11.731346105Z"}
{"log":"time=2025-02-16T17:26:19.733Z level=INFO source=cluster.go:691 msg=\"gossip settled; proceeding\" component=cluster elapsed=10.002845277s\n","stream":"stderr","time":"2025-02-16T17:26:19.73394317Z"}
{"log":"time=2025-02-16T17:26:42.127Z level=INFO source=main.go:584 msg=\"Received SIGTERM, exiting gracefully...\"\n","stream":"stderr","time":"2025-02-16T17:26:42.127120522Z"}
{"log":"time=2025-02-16T17:26:42.569Z level=INFO source=main.go:191 msg=\"Starting Alertmanager\" version=\"(version=0.28.0, branch=HEAD, revision=4ce04fb010bd626fca35928dcfe82f6f2da52ced)\"\n","stream":"stderr","time":"2025-02-16T17:26:42.569979907Z"}
{"log":"time=2025-02-16T17:26:42.569Z level=INFO source=main.go:192 msg=\"Build context\" build_context=\"(go=go1.23.4, platform=linux/amd64, user=root, date=20250115-14:22:34, tags=netgo)\"\n","stream":"stderr","time":"2025-02-16T17:26:42.569998057Z"}
{"log":"time=2025-02-16T17:26:42.570Z level=INFO source=cluster.go:185 msg=\"setting advertise address explicitly\" component=cluster addr=172.18.0.2 port=9094\n","stream":"stderr","time":"2025-02-16T17:26:42.570239924Z"}
{"log":"time=2025-02-16T17:26:42.570Z level=INFO source=cluster.go:674 msg=\"Waiting for gossip to settle...\" component=cluster interval=2s\n","stream":"stderr","time":"2025-02-16T17:26:42.570707908Z"}
{"log":"time=2025-02-16T17:26:42.595Z level=INFO source=coordinator.go:112 msg=\"Loading configuration file\" component=configuration file=/etc/alertmanager/config.yml\n","stream":"stderr","time":"2025-02-16T17:26:42.595231445Z"}
{"log":"time=2025-02-16T17:26:42.595Z level=INFO source=coordinator.go:125 msg=\"Completed loading of configuration file\" component=configuration file=/etc/alertmanager/config.yml\n","stream":"stderr","time":"2025-02-16T17:26:42.595445098Z"}
{"log":"time=2025-02-16T17:26:42.598Z level=INFO source=tls_config.go:347 msg=\"Listening on\" address=[::]:9093\n","stream":"stderr","time":"2025-02-16T17:26:42.598322819Z"}
{"log":"time=2025-02-16T17:26:42.598Z level=INFO source=tls_config.go:350 msg=\"TLS is disabled.\" http2=false address=[::]:9093\n","stream":"stderr","time":"2025-02-16T17:26:42.598343346Z"}
{"log":"time=2025-02-16T17:26:44.571Z level=INFO source=cluster.go:699 msg=\"gossip not settled\" component=cluster polls=0 before=0 now=1 elapsed=2.000629253s\n","stream":"stderr","time":"2025-02-16T17:26:44.571667993Z"}
{"log":"time=2025-02-16T17:26:52.574Z level=INFO source=cluster.go:691 msg=\"gossip settled; proceeding\" component=cluster elapsed=10.003324685s\n","stream":"stderr","time":"2025-02-16T17:26:52.574327531Z"}
{"log":"time=2025-02-16T17:30:30.860Z level=ERROR source=dispatch.go:360 msg=\"Notify for alerts failed\" component=dispatcher num_alerts=1 err=\"telegram/telegram[0]: notify retry canceled after 2 attempts: context deadline exceeded\"\n","stream":"stderr","time":"2025-02-16T17:30:30.860409229Z"}
{"log":"time=2025-02-16T17:32:41.932Z level=ERROR source=dispatch.go:360 msg=\"Notify for alerts failed\" component=dispatcher num_alerts=1 err=\"telegram/telegram[0]: notify retry canceled after 2 attempts: context deadline exceeded\"\n","stream":"stderr","time":"2025-02-16T17:32:41.93307112Z"}
{"log":"time=2025-02-16T17:34:53.004Z level=ERROR source=dispatch.go:360 msg=\"Notify for alerts failed\" component=dispatcher num_alerts=1 err=\"telegram/telegram[0]: notify retry canceled after 2 attempts: context deadline exceeded\"\n","stream":"stderr","time":"2025-02-16T17:34:53.005014736Z"}
```

**Problem is here:**
```
{"log":"time=2025-02-16T17:30:30.860Z level=ERROR source=dispatch.go:360 msg=\"Notify for alerts failed\" component=dispatcher num_alerts=1 err=\"telegram/telegram[0]: notify retry canceled after 2 attempts: context deadline exceeded\"\n","stream":"stderr","time":"2025-02-16T17:30:30.860409229Z"}
{"log":"time=2025-02-16T17:32:41.932Z level=ERROR source=dispatch.go:360 msg=\"Notify for alerts failed\" component=dispatcher num_alerts=1 err=\"telegram/telegram[0]: notify retry canceled after 2 attempts: context deadline exceeded\"\n","stream":"stderr","time":"2025-02-16T17:32:41.93307112Z"}
{"log":"time=2025-02-16T17:34:53.004Z level=ERROR source=dispatch.go:360 msg=\"Notify for alerts failed\" component=dispatcher num_alerts=1 err=\"telegram/telegram[0]: notify retry canceled after 2 attempts: context deadline exceeded\"\n","stream":"stderr","time":"2025-02-16T17:34:53.005014736Z"}
```

**The method I use to test alertmanager:**
`curl -w '\n' -i --header 'Content-Type: application/json' --data '[{"labels":{"alertname":"test"},"endsAt":"2025-02-16T17:33:10.574"}]' http://localhost:9093/api/v2/alerts`

If you have any questions please let me know, thanks.
