### ISSUE TITLE
Blackhole receiver

### ISSUE THREAD

**Issue by aecolley** [prometheus/alertmanager#428]
Create a receiver which drops all alerts. Currently this requires a workaround involving email or webhook receivers and a dummy server.

Rationale: alertmanager should fully support the page/ticket/log model for alert severity. Alerts of "log" severity should be displayed on a dashboard but otherwise generate no notifications. Unless there's a plan to exclude them from being sent by prometheus to alertmanager, they must be dropped .

**Comment by brian-brazil** [comment]
https://github.com/prometheus/prometheus/issues/1744

It is not desirable for performance reasons to have non-notifying alerts in the alertmanager.

**Comment by aecolley** [comment]
I agree. It's better not to send them at all. How?

**Comment by beorn7** [comment]
I don't know how to not send an alert at all, but it is perfectly possible to set up a blackhole receiver.
At SoundCloud, we use info level alerts where the (still to be improved) Alertmanager UI serves as an "alerts dashboard" (as suggested by my SRECon talk).

Just configure a receiver with a `name` only:

```
receivers:
- name: something-info
  # Deliberately left empty to not deliver anywhere.
- name: some-other-receiver
  email_configs:
  # ...
```

**Comment by beorn7** [comment]
I'll close this as blackhole receivers are in fact possible.
The case where you don't want to send an alert notification to AM in the first place is a Prometheus side issue covered in prometheus/prometheus#1744 .

**Comment by TheTincho** [comment]
I was trying to do exactly this today, and I could not find how. Wouldn't it be good to add this in the documentation?

**Comment by roidelapluie** [comment]
Maybe. Note: You can also drop this at prometheus level (not send certain alerts at all):

```
alerting:
  alert_relabel_configs:
  - source_labels: [time_window]
    regex: never                                                                                                                          
    action: drop                                                                                                                          
```

**Comment by metost** [comment]
> Maybe. Note: You can also drop this at prometheus level (not send certain alerts at all):
> 
> ```
> alerting:
>   alert_relabel_configs:
>   - source_labels: [time_window]
>     regex: never                                                                                                                          
>     action: drop                                                                                                                          
> ```

@roidelapluie This is pretty interesting, can you elaborate a bit more, for example if I want to drop specific alarm before it goes to alertmanager. Let's say If I want to do this for "alertname": watchdog?
Thanks in advance!

**Comment by slomo** [comment]
I tried to use a black hole receiver as described here.  But it seems that alerts are still delivered via the default receiver. So maybe introducing an explicit black hole receiver would still be better?

This is the configuration I tried.

```yaml
---
receivers:
- name: webhook
  webhook_configs:
  - send_resolved: false
    url: http://localhost:12345

route:
  receiver: webhook
  routes:
    # black hole alert
    - match:
        label: value

```
Running alert manager:

```shellSession
> alertmanager-0.20.0.linux-amd64/alertmanager --cluster.listen-address=  --log.level=debug
level=info ts=2020-02-20T08:55:42.912Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
level=info ts=2020-02-20T08:55:42.912Z caller=main.go:232 build_context="(go=go1.13.5, user=root@00c3106655f8, date=20191211-14:13:14)"
level=debug ts=2020-02-20T08:55:42.946Z caller=main.go:370 externalURL=http://de3lxd-108955:9093
level=info ts=2020-02-20T08:55:42.946Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=alertmanager.yml
level=info ts=2020-02-20T08:55:42.946Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=alertmanager.yml
level=debug ts=2020-02-20T08:55:42.949Z caller=main.go:480 routePrefix=/
level=info ts=2020-02-20T08:55:42.950Z caller=main.go:497 msg=Listening address=:9093
level=debug ts=2020-02-20T08:55:47.336Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=test[ae9a25c][active]
level=debug ts=2020-02-20T08:56:17.336Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}/{label=\"value\"}:{}" msg=flushing alerts=[test[ae9a25c][active]]

```

Sending alert:

```shell
echo '[{"labels":{"alertname": "test", "label":"value"}}]' | curl -H'Content-Type: application/json' --data-binary @- 'localhost:9093/api/v2/alerts'
```

Receiving alert:

```shellSession
> nc -l 12345
POST / HTTP/1.1
Host: localhost:12345
User-Agent: Alertmanager/0.20.0
Content-Length: 452
Content-Type: application/json

{"receiver":"webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"test","label":"value"},"annotations":{},"startsAt":"2020-02-20T09:55:47.336078297+01:00","endsAt":"0001-01-01T00:00:00Z","generatorURL":"","fingerprint":"ae9a25c7575c1709"}],"groupLabels":{},"commonLabels":{"alertname":"test","label":"value"},"commonAnnotations":{},"externalURL":"hostname","version":"4","groupKey":"{}/{label=\"value\"}:{}"}
```
If I understand it correctly the alarm should have been black holed, but it is still delivered via the default receiver.
