### ISSUE TITLE
Alertmanager 0.28.1: Jira integration fails with "Field 'labels' cannot be set" error even when labels are not configured

### ISSUE THREAD

**Issue by Zarubenko** [prometheus/alertmanager#4309]
**Alertmanager version:**
0.28.1

**Issue:**
When configuring Jira integration in Alertmanager, the request to create an issue fails with the following error:
`time=2025-03-11T10:24:31.527Z level=ERROR source=dispatch.go:360 msg="Notify for alerts failed" component=dispatcher num_alerts=1 err="jira/jira[0]: notify retry canceled due to unrecoverable error after 1 attempts: failed to POST request to \"issue\": unexpected status code 400: {\"errorMessages\":[],\"errors\":{\"labels\":\"Field 'labels' cannot be set. It is not on the appropriate screen, or unknown.\"}}"`

**Expected behavior:**
Alertmanager should respect the configuration and not send the labels field when it is not explicitly defined in jira_configs.

**Steps to reproduce:**
Configure jira_configs in alertmanager.yml:

```
receivers:
  - name: "jira"
    jira_configs:
      - project: "myproject"
        issue_type: "Incident"
        summary: "Test alert"
        description: "This is a test description"
        labels: [] # Empty fields to ensure no labels are sent
        fields: {}  # Empty fields to ensure no labels are sent
```

**What has been tested:**
Manually sending a request via curl with no labels field works fine:

```
curl -X POST "https://jira.fofo.com/rest/api/2/issue/" \
     -H "Authorization: Bearer your_personal_access_token" \
     -H "Content-Type: application/json" \
     -d '{
          "fields": {
            "project": { "key": "myproject" },
            "summary": "Test Alert Summary",
            "description": "Test Alert Description",
            "issuetype": { "name": "Incident" }
          }
        }'
```

- Downgrading Alertmanager to 0.28.0 does not fix the issue.
- Explicitly setting labels: [] in jira_configs does not help.
- Setting fields: {} does not prevent labels from being sent.
- Debug logs do not show the actual request being sent.

**Suggested Fix:**
Ensure that labels is not automatically added when not defined in jira_configs.
Improve debug logging to show the exact JSON payload being sent to Jira.
