### ISSUE TITLE
Label available but not resolved in alert template

### ISSUE THREAD

**Issue by TLINDEN** [prometheus/alertmanager#4396]
I have created this new alert:

```yaml
- alert: PostgresServiceEndpointUnavailable
  annotations:
    description: >-
      Der Postgres-Service-Endpoint {{ $labels.namespace }}/{{ $labels.endpoint }} auf {{ $labels.cluster }}
      ist seit 10 Minuten nicht verfügbar, es können keine neuen Clientverbundungen aufgebaut werden.
      im NS {{ $labels.namespace }}
    summary: ServiceEndpoint {{ $labels.endpoint }} unavailable
  expr: kube_endpoint_address_available{endpoint=~".*external"} == 0
  for: 10m
  labels:
    severity: critical
```

The alert itself works as intended and fires, but the label `$labels.cluster` is not being resolved, but it exists as can be seen here:

![Image](https://github.com/user-attachments/assets/77bf3d75-aa96-42f3-a281-cf25c074dba2)

However, the same label works in other alerts in the same ruleset on the same cluster.

We're using alertmanager v0.27.0.
