### ISSUE TITLE
Webhooks doesn't send 'resolved' requests

### ISSUE THREAD

**Issue by just1fix** [prometheus/alertmanager#510]
Hi!
I'm testing alertmanager webhooks. "firing" requests are sent just fine,  but resolved requests are never sent, no matter how long I wait for it.
I tried to set "send_resolved" to true, but it doesn't help (obviously, as true is a default value anyway)

**Comment by sevenfourk** [comment]
send_resolved: true was not default, at least for me.  which version are you running? and please share your part of a config.

**Comment by just1fix** [comment]
version 0.3.0
config for webhooks looks like:
```
route:
  receiver: myweb

receivers:
  - name: myweb
    webhook_configs:
    - url: 'http://host:port'
      send_resolved: true # tried both setting this option and removing it

```

**Comment by sevenfourk** [comment]
according to their docs it's good. I'm using email_configs, slack_configs, and send_resolved are working as expected.

**Comment by just1fix** [comment]
I just tried version 0.4.2 - still no change. It keeps sending "firing" requests even though the issue is resolved already (and 5 mins have passed after it was resolved).

**Comment by just1fix** [comment]
at some point it stops sending any requests. Could it be that instead of 'resolved' request it sends 'firing', by mistake?

**Comment by fabxc** [comment]
Can you provide more exact steps to reproduce the issue? Ideally with version 0.5.0.
It's hard to make a guess with such little detail.

**Comment by brian-brazil** [comment]
If you have additional detail, please reopen.

**Comment by stuartnelson3** [comment]
can you post your sanitized config?

**Comment by amaury-d** [comment]
Some information have been scrambled for security

```
global:
  # The smarthost and SMTP sender used for mail notifications.
  #smtp_smarthost: 'localhost:25'
  #smtp_from: 'alertmanager@example.org'
  #smtp_auth_username: 'alertmanager'
  #smtp_auth_password: 'password'
  # The auth token for Hipchat.
  #hipchat_auth_token: '1234556789'
  # Alternative host for Hipchat.
  #hipchat_api_url: 'https://hipchat.foobar.org/'

# The directory from which notification templates are read.
templates: 
- '/usr/share/alertmanager/current/template/*.tmpl'

# The root route on which each incoming alert enters.
route:
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ['alertname']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first 
  # notification.
  # Premier temps d'attente pour grouper avant premier envoi, réduit au minimum
  group_wait: 1s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  # Aprés premier envoi, on attend au minimum ce temps pour renvoyer une alerte sur ce groupe
  group_interval: 1m 

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 1m 

  # A default receiver
  receiver: default_receiver 

  routes:
  # Test receiver
  - receiver: test_receiver
    continue: true

  - receiver: site1_prd
    match:
      site: site1
      env: prd
  - receiver: site1_cae
    match:
      site: site1

  - receiver: site2_prd
    match:
      site: site2
      env: prd
  - receiver: site2_cae
    match:
      site: tls


receivers:
# Void receiver
- name: 'default_receiver'

# Test receiver
- name: 'test_receiver'
  webhook_configs:
    - url: http://xxxxxxxx:8080/prometheus
      http_config:
        basic_auth:
          username: 'xxxxxxxx'
          password: 'xxxxxxxx'
  slack_configs:
    - send_resolved: true
      api_url: https://hooks.slack.com/services/xxxxxxxx
      channel: xxxxxxxx
```
