### ISSUE TITLE
Invalid config undetected.

### ISSUE THREAD

**Issue by itatabitovski** [prometheus/alertmanager#519]
Alertmanager is starting fine without any errors about the group_interval in the global section.

```
./alertmanager -version
alertmanager, version 0.4.2 (branch: master, revision: 9a5ab2fa63dd7951f4f202b0846d4f4d8e9615b0)
  build user:       root@2811d2f42616
  build date:       20160902-15:33:13
  go version:       go1.6.3
```

```
global:
  resolve_timeout: 2m
  group_interval: 1m   # this is invalid config

  hipchat_auth_token: 'xxxx'

# The root route on which each incoming alert enters.
route:
  group_by: ['cluster']
  group_interval: 1m   # this is valid config
  receiver: team-hipchat

  routes:
  - match_re:
      severity: hipchat
    receiver: team-hipchat

receivers:
- name: 'team-hipchat'
  hipchat_configs:
  - room_id: 123456
    send_resolved: true
    message_format: html
    notify: true
```
