### ISSUE TITLE
How to inhibit all other alerts if target is down?

### ISSUE THREAD

**Issue by cofyc** [prometheus/alertmanager#535]
Hi,

Our prometheus has many node_exporter targets, and configured many alert rules.

If one node_exporter instance is down (up!=1), many alerts are sent out.

Only "instance is down" is meaningful (because this is actual issue). I want to mute all other alerts.

I try to configure inhibit rules like this:

```
inhibit_rules:
  - target_match:
    source_match:
       alertname: 'instance_down'
    equal: ['job', 'instance']
```

It inhibit all alerts about this non-up instance, but also inbibit "instance_down" itself.

I try to use regex to match other alertnames:

```
inhibit_rules:
  - target_match_re:
       alertname: '(?!node_down)'
    source_match:
       alertname: 'instance_down'
    equal: ['job', 'instance']
```

But, found that golang `regexp` does not support this syntax (https://github.com/google/re2/wiki/Syntax).

Any way to exclude "instance_down", and only mute other alerts? Or suggestions?

**Comment by fabxc** [comment]
Mh, why is it once `instance_down` and once `node_down` in your second block?

Anyway, can you try:

```yaml
inhibit_rules:
  - target_match_re:
       alertname: '[^(instance_down)]'
    source_match:
       alertname: 'instance_down'
    equal: ['job', 'instance']
```

In general, we probably don't want the alert to inhibit itself as in your first example. @brian-brazil
