### ISSUE TITLE
'Must issue a STARTTLS command first' when using gmail alert

### ISSUE THREAD

**Issue by Mr-Right2** [prometheus/alertmanager#540]
I'm currently trying to set up a sample alertmanager to see if I can receive emails at my gmail account
My alertmanager.yml looks like:
```
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'myaccount@gmail.com'
  smtp_auth_username: 'myaccount@gmail.com'
  smtp_auth_password: '<redacted>'
  smtp_auth_identity: 'myaccount@gmail.com'

route:
  receiver: 'team-X-mails'
  group_by: ['alertname']
  #group_wait: 30s
  #group_interval: 5m
  #repeat_interval: 6h

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname']

receivers:
- name: 'team-X-mails'
  email_configs:
  - to: 'myaccount@gmail.com'
```

When an alert is fired I see the following output in the alertmanager logs:
```
alertmanager, version 0.1.1 (branch: HEAD, revision: 0e541bf)
  build user:       @e5c68db50333
  build date:       20160323-14:13:37
  go version:       1.5.3
time="2016-10-26T09:26:30Z" level=info msg="Loading configuration file" file="/alertmanager.yml" source="main.go:125"
time="2016-10-26T09:26:31Z" level=warning msg="Notify attempt 1 failed: sending mail from: 530 5.7.0 Must issue a STARTTLS command first. h133sm8484711wmg.23 - gsmtp" source="notify.go:193"
time="2016-10-26T09:26:31Z" level=warning msg="Notify attempt 2 failed: sending mail from: 530 5.7.0 Must issue a STARTTLS command first. p13sm1981110wmd.20 - gsmtp" source="notify.go:193"
time="2016-10-26T09:26:32Z" level=warning msg="Notify attempt 3 failed: sending mail from: 530 5.7.0 Must issue a STARTTLS command first. 18sm8503406wmr.5 - gsmtp" source="notify.go:193"`

```

I'm running the following version of alertmanager:
```
alertmanager, version 0.1.1 (branch: HEAD, revision: 0e541bf)
  build user:       @e5c68db50333
  build date:       20160323-14:13:37
  go version:       1.5.3
```

As far as I can see I've configured alertmanager correctly (although the [documentation](https://prometheus.io/docs/alerting/configuration/) mentions variables such as 'auth_username' and 'auth_password', which result in startup errors and alertmanager complaining that it does not recognize these fields)
