### ISSUE TITLE
Recover alerts not sent to webhook

### ISSUE THREAD

**Issue by vpetersson** [prometheus/alertmanager#581]
Sorry if I've missed anything obvious, but just getting started with Prom and Alertmanager. In short, I want to integrate Alertmanager with a separate app using webhooks. My config is very simple (using requestb.in for testing):

```
route:
  receiver: webhook
receivers:
- name: "webhook"
  webhook_configs:
  - url: http://requestb.in/foobar
    send_resolved: true
```

When I trigger an alert, this gets pushed just fine. However, the restore/recover is never sent to the webhook. It is however properly reported both in Prom and in Alertmanager.

Did I miss anything obvious?

I'm using Alertmanager 0.5.1 running insider Docker.
