### ISSUE TITLE
Q: Is it possible to set email receiver from alert data?

### ISSUE THREAD

**Issue by elvanja** [prometheus/alertmanager#585]
Background: I'm working on a system that has some user related events like "login failed" or "could not get data from 3rd party". I'm generalising here, bit overall these events are mostly generated by some background processes. Anyway, the recipient of the email notification for a particular event is a single end user and I could supply the user's email along with other event data/payload.

Q: Would it be possible to configure alertmanager ingeneral or specific email template for a given event type not to use the recipient from static yaml configuration, but rather from the event data?

**Comment by brian-brazil** [comment]
Yes, the email recipient field is templatable. Provide the email address as a label.

**Comment by elvanja** [comment]
Excellent, thank you!

**Comment by elvanja** [comment]
Hi @brian-brazil, still have issues with this, help appreciated :-)

So, I've defined a template to structure the recipient's email address.
It just returns a hard-coded email, to simplify this example:
```
{{ define "email.client.generic.notification.recipient" }}
recipient@acme.com
{{ end }}
```

I have a route in `config.yml` which uses email recipients, which are configured as follows:
```
- name: email_clients
  email_configs:
  - send_resolved: true
    to: '{{ template "email.client.generic.notification.recipient" . }}'
```

I'd expect alert manager to execute the defined template and use it's result to determine the recipient's email. However, I get this error:
```
time="2016-12-29T11:20:33Z" level=error msg="Error on notify: Cancelling notify retry due to unrecoverable error: parsing to addresses: mail: missing word in phrase: mail: invalid string" source="notify.go:272"
time="2016-12-29T11:20:33Z" level=error msg="Notify for 3 alerts failed: Cancelling notify retry due to unrecoverable error: parsing to addresses: mail: missing word in phrase: mail: invalid string" source="dispatch.go:246"
```

What am I doing wrong?

**Comment by brian-brazil** [comment]
It may not be liking the new lines in that template.

**Comment by elvanja** [comment]
Ah, excellent, the hard-coded template now works :-)

But, having a bit of an issue with extracting the event data. So, the template would now look like: 
```
{{ define "email.client.generic.notification.recipient" }}{{ .GroupLabels.email }}{{ end }}
```

And, I'm pushing an events (via API for now) like this:
```json
[
  {
    "labels": {
      "client": "true",
      "accountId": "1",
      "email": "account_1@acme.com",
      "type": "UNUSCCESSFUL_LOGIN_AIRBNB"
    }
  }
]
```

And the error is: 
```
time="2016-12-29T12:13:18Z" level=error msg="Error on notify: Cancelling notify retry due to unrecoverable error: parsing to addresses: mail: no address" source="notify.go:272"
time="2016-12-29T12:13:18Z" level=error msg="Notify for 3 alerts failed: Cancelling notify retry due to unrecoverable error: parsing to addresses: mail: no address" source="dispatch.go:246"
```

**Comment by brian-brazil** [comment]
Does your group_by include `email`?

You can do this without the template.

**Comment by elvanja** [comment]
You're right, the group_by was missing.

Before:
```yaml
route:
  group_by: [type, accountId, channelType]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30s
  receiver: email_clients
  routes:
  - match:
      client: true
    receiver: email_clients
    group_by: []
```

After:
```yaml
route:
  group_by: [type, accountId, channelType]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30s
  receiver: email_clients
  routes:
  - match:
      client: true
    receiver: email_clients
    group_by: [email]
```

And now it works as expected. Thanks 👍 

How would this be done without template?
