### ISSUE TITLE
[Feature] Dynamic routes rules using labels

### ISSUE THREAD

**Issue by ZeeShen** [prometheus/alertmanager#608]
Our scene: We have 100+ applications, each one has a related pagerduty service. 
We want to send alerts of a certain application to the related receiver with a name from the `app` labels. Maybe something like:

```yaml
routes:
- receiver: {{ label_values("app") }}
   match:
      # other match rules
```

Now we have to list all applications in both receivers and routes(over 1000+ lines in alertmanager config yaml). Any suggestion? Maybe an alertmanger pagerduty integration?
