### ISSUE TITLE
Alertmanager sends the resolved messages continuously

### ISSUE THREAD

**Issue by tsboj17** [prometheus/alertmanager#611]
This problem is totally same as this closed issue: https://github.com/prometheus/alertmanager/issues/246

I changed the `resolve_timeout` parameter as you suggested but it did not help.

**Comment by bkupidura** [comment]
Hello, please check my comment from https://github.com/prometheus/alertmanager/issues/246#issuecomment-272196116

Moreover i observed that overwritting prometheus_pod and prometheus_ip helps a little (I got multiple resolved notification, but less than previous) :)

```
alerting:
  alert_relabel_configs:
    - source_labels: [prometheus_pod]
      action: replace
      replacement: prometheus
      target_label: prometheus_pod
    - source_labels: [prometheus_ip]
      action: replace
      replacement: prometheus
      target_label: prometheus_ip
```
