### ISSUE TITLE
grouping alerts

### ISSUE THREAD

**Issue by yosefy** [prometheus/alertmanager#623]
problem: can't disable grouping (to make it in opsgenie)
(two alerts are two diff cpus of same instance)
AM config:

```
route:
  receiver: 'dev_null'
################################
  routes:
  - receiver: 'opsgenie'
    group_wait: 0s
    group_interval: 0s
    continue: true

receivers:
 - name: dev_null

 - name: "opsgenie"
   opsgenie_configs:
   - api_key: XXX
     teams: support_team
     tags: '{{ range .Alerts }}{{ .Labels.region }} {{ end }},{{ range .Alerts }}{{ .Labels.Type }} {{ end }}, {{ range .Alerts}}{{ .Labels.severity }} {{ end }}'
     details: { 'instance': '{{ range .Alerts }}{{ .Labels.instance }} {{ end }}' }
```

expected to get all the alerts not grouped

what happens: 
in opsgenie:
message:
[Prom]: [FIRING:2] CpuUtilizationWarning (xxxxx ap-southeast-1 warning)

Description:	
(i-48fa1def) in region reported over 90% CPU utilization in the past 5 minutes. Monitored by job: . Public IP: 
Alerts Firing:
Labels:
- alertname = CpuUtilizationWarning
- cpu = cpu3
- instance = xxx
- region = xxx
- service = 
- severity = warning
- value = 94%
Annotations:
- description = (xxx) in region reported over 90% CPU utilization in the past 5 minutes. Monitored by job: . Public IP: 
Source: http://xxx:9090/graph?g0.expr=floor%28100+-...
Labels:
- alertname = CpuUtilizationWarning
- cpu = cpu0
- instance = xxx
- region = xxx
- service = 
- severity = warning
- value = 90%
Annotations:
- description = (xxx) in region reported over 90% CPU utilization in the past 5 minutes. Monitored by job: . Public IP: 
Source: http://xxx:9090/graph?g0.expr=floor%28100+-...
