### ISSUE TITLE
mail: missing phrase

### ISSUE THREAD

**Issue by k-s-dean** [prometheus/alertmanager#624]
Hello, 
I'm trying to send emails.

However i get the following.

```
Error on notify: Cancelling notify retry due to unrecoverable error: parsing from addresses: mail: missing phrase" source="notify.go:272"

Notify for 1 alerts failed: Cancelling notify retry due to unrecoverable error: parsing from addresses: mail: missing phrase" source="dispatch.go:246

```

I can get Hipchat notifications working no problem. But email is eluding me. 

Help would be appreciated.

my config is as follows:

```
global:
    resolve_timeout: '5m'
    smtp_smarthost: 'smtp.office365.com:587'
    smtp_from: 'Alert Manager - INT'
    smtp_auth_username: 'alert@company.com'
    smtp_auth_password: 'random_num_string'
    smtp_require_tls: true
    hipchat_url: 'https://company.hipchat.com/'
    hipchat_auth_token: 'random_num_string'


route:
    receiver: 'company-email'
    group_by: ['service']
    group_wait: 30s
    group_interval: 5s
    repeat_interval: 20s

receivers:
    - name: 'company-hipchat'
      hipchat_configs:
      - room_id: 'random_numbers'
        auth_token: 'random_num'




receivers:
    - name: 'company-email'
      email_configs:
      - to: 'user.last@company.com'
        from: 'Alert_Manager_int'
        smarthost: 'smtp.office365.com:587'
        auth_username: 'alert@company.com'
        auth_password: 'random_num_string'
        require_tls: true
        html: 'Check Alertmanager'

```
