### ISSUE TITLE
Feature request: Support Slack Attachments in alert templates

### ISSUE THREAD

**Issue by dewey** [prometheus/alertmanager#654]
Hey,

as already discussed in #650 it would be great to support custom Slack Attachments in the [alert templates](https://prometheus.io/blog/2016/03/03/custom-alertmanager-templates/). Right now [it's already used](https://github.com/prometheus/alertmanager/blob/master/notify/impl.go#L500-L508) but only in a hardcoded way and it's not possible to add additional custom attachments.

This would be really helpful to structure alerts in a better way.

Thanks

**Comment by chriswiggins** [comment]
Hate to dig up an old issue but this would be really helpful.

If I was to look into adding this, what would be the recommended approach with providing the receiver the different attachments to create? Where does `n.conf.Fields` come from that creates multiple attachmentFields?

**Comment by jpds** [comment]
@stuartnelson3 If I try the config you've provided with `v0.15.0-rc.2`; I get:

```
caller=main.go:314 msg="Loading configuration file failed" file=/etc/config/alertmanager.yml err="yaml: unmarshal errors:\n  line 6: field attachments not found in type config.plain"
```

**Comment by simonpasquier** [comment]
A [Slack notification](https://prometheus.io/docs/alerting/configuration/#slack_config) contains only one attachment. You can add multiple [fields](https://api.slack.com/docs/message-attachments#fields) though.

```yaml
receivers:
- name: 'team-X-slack'
  slack_configs:
  - channel: "#ops"
    color: #7CD197
    text: "main text"
    fields:
    - title: "title 1"
      value: "can be markup"
    - text: "title 2"
      value: "more"
```

If you need several attachments, you can still configure several Slack notifiers in the same receiver.
