### ISSUE TITLE
Alerts can inhibit themselves

### ISSUE THREAD

**Issue by lmb** [prometheus/alertmanager#666]
I have a bunch of alerts in the form of Prefix_Some_Name. I've set up the following inhibition rule:

```
- source_match_re:
    alertname: Prefix_.+
  target_match:
    alertname: Prefix_Failsafe_Alert
  equal:
    - label1
    - label2
```

As far as I can tell, this alert will inhibit itself, and never be delivered. Depending on how you look at it this is a bug in the alertmanager, or an important gotcha that should be documented.

Happy to contribute a patch either way.

Edit: I should add that I empirically verified this against an older alertmanager. I looked through the current master branch, and AFAICT the behaviour is still the same.

**Comment by juliusv** [comment]
> As far as I can tell, this alert will inhibit itself

Hm yes, that is the behavior I would expect. I guess you expected that alerts generally cannot inhibit themselves?

I think adding a clarfiying sentence to https://github.com/prometheus/docs/blob/master/content/docs/alerting/configuration.md#inhibit_rule would be generally welcome if you think this is something that is confusing.

**Comment by threemachines** [comment]
I also discovered this behavior the hard way. I agree that it's strictly reasonable within the context of how inhibitions are currently structured, but is this behavior considered desirable?

If alerts never inhibited themselves, certain types of alerting noise could be reduced in a way that's currently infeasible. The only use case I can imagine for self-inhibiting alerts is ensuring they never notify anybody, which would surely be better handled by configuring a matching route with no receivers. But maybe I'm just not thinking big enough?

**Comment by juliusv** [comment]
Yeah, I can't come up with a reason why an alert should be able to inhibit itself either. The question is, is it worth introducing an explicit exception for this case? That's ultimately up to the Alertmanager maintainers (@stuartnelson3 @fabxc).

**Comment by brian-brazil** [comment]
I think the general expectation here is that there's some other label you can work off to distinguish these, such as a "dependency" label or similar.

The "Prefix_" being the same on both is also a bit of a smell, that should probably be a label.

**Comment by lmb** [comment]
@brian-brazil that might be correct, but doesn't change the underlying issue.

**Comment by fabxc** [comment]
This should probably a documented caveat. I think it doesn't really happen for typical inhibition usage as there should be some clearly distinguishing labels. Probably an edge case not worth complicating implementation for.

**Comment by mxinden** [comment]
@lmb Would you mind updating the documentation as suggested by @juliusv in his [comment](https://github.com/prometheus/alertmanager/issues/666#issuecomment-288801874)?

**Comment by lmb** [comment]
Yup can do, feel free to assign to me.

**Comment by mxinden** [comment]
@lmb Thanks! Just tag me on the PR. Let us know if you need any help.

**Comment by beorn7** [comment]
The problem here is that the most obvious fix requires negative matches, which the [inhibit rule syntax](https://prometheus.io/docs/alerting/configuration/#<inhibit_rule>) does not support. E.g. you have a `NodeDown` page that should inhibit _all_ other pages that share the same `node` label (because you know the node is down so you don't need to be notified that your HAProxy on that node is down and your MySQL and your Prometheus etc.).

Naive rule syntax that inhibits the original `NodeDown` alert, too:
```
inhibit_rules:
- source_match:
    alertname: NodeDown
    severity: critical
  target_match:
    severity: critical
  equal:
  - node
```

This works:
```
inhibit_rules:
- source_match:
    alertname: NodeDown
    severity: critical
  target_match:
    severity: critical
  target_match_re:
    alertname: '.{0,7}|.{9,}|([^N]|.([^o]|.([^d]|.([^e]|.([^D]|.([^o]|.([^w]|.[^n]))))))).*'
  equal:
  - node
```

Much nicer would be:
```
inhibit_rules:
- source_match:
    alertname: NodeDown
    severity: critical
  target_match:
    severity: critical
  target_not_match:
    alertname: NodeDown
  equal:
  - node
```
