### ISSUE TITLE
Confused between group_interval and repeat_interval

### ISSUE THREAD

**Issue by txdyzdy** [prometheus/alertmanager#676]
### what did I want?
I want to disable the `repeat_interval`.
Whether it is a repeat alert, Alertmanager will send me an alert every `group_interval`.
### what did I do?
I set the `group_interval` and `repeat_interval` to the same time.
Now their values are all 5 minutes.
```
route:
  group_by: []
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
```
### what did I see?
I can get emails for every 10 minutes...

### Another example:
When I set the `repeat_interval` higher than the `group_interval`, the repeat alert sent normally by `repeat_interval`.
```
route:
  group_by: []
  group_wait: 30s
  group_interval: 3m
  repeat_interval: 5m
```
Alertmanager will send me a mail every 5 minutes(sometimes is 6 minutes).

**I am confused about it.**
