### ISSUE TITLE
group_by not applied after continue

### ISSUE THREAD

**Issue by erikgrinaker** [prometheus/alertmanager#685]
In the following example, alerts to receiver `critical` are always grouped by `instance`, not `daemonset` etc. Alerts to `default` are grouped correctly.

```yaml
route:
  group_by: ["instance"]
  receiver: default

  routes:
  - receiver: critical
    match:
      severity: critical
    continue: true

  - group_by: ['daemonset', 'deployment', 'namespace', 'node', 'pod']
    match_re:
      job: ^kubernetes-state-.*

  - receiver: default
```
