### ISSUE TITLE
Alerts not de-duplicated properly

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#697]
This is for alertmanager at revision 1e34f29532a251b728ddf304ebccd9234fcbd81a.

A call to `/api/v1/alerts/groups` results in two almost identical groups. Here the first few lines of each, the rest is completely identical:

```json
  {
    "labels": {
      "alertname": "NodeHasMemoryErrors",
      "service": "node"
    },
    "groupKey": 5344027977801413000,
    "blocks": [
      {
        "routeOpts": {
          "receiver": "prodeng-warn",
          "groupBy": [
            "alertname",
            "zone",
            "service"
          ],
          "groupWait": 300000000000,
          "groupInterval": 43200000000000,
          "repeatInterval": 86400000000000
        },
        "alerts": [
```

```json
  {
    "labels": {
      "alertname": "NodeHasMemoryErrors",
      "service": "node"
    },
    "groupKey": 5344027977801413000,
    "blocks": [
      {
        "routeOpts": {
          "receiver": "prodeng-warn",
          "groupBy": [
            "zone",
            "service",
            "alertname"
          ],
          "groupWait": 300000000000,
          "groupInterval": 43200000000000,
          "repeatInterval": 86400000000000
        },
        "alerts": [
```

The only difference between the two is the order of the strings in the `groupBy` list.

The alertmanager config contains the following `group_by` directives in different routes:

- `group_by: [alertname, zone, service]`
- `group_by: [alertname, cluster, service]`
- `group_by: [job, service]`

I.e. the "correct" order of grouping labels is in the first group, while the second uses a different order for some reason.

@stuartnelson3 perhaps this gives you some hints.

**Comment by brancz** [comment]
@fabxc @mxinden we identified this problem yesterday I believe. This problem should disappear with the `/api/v1/alerts` endpoint @beorn7 (#694).

**Comment by mattbostock** [comment]
#694 doesn't seem to address the issue with the `/api/v1/alerts/groups` endpoint specifically? It seems like this is a bug worth fixing independent of that change.

**Comment by brancz** [comment]
I see, I was a bit hasty with my conclusion. @beorn7 did this occur when doing two calls to that particular endpoint or did you find duplicate alerting groups in the same response? I feel it's more a stable order issue then a deduplication issue, or am I not understanding the problem correctly?

**Comment by beorn7** [comment]
This is all coming from one call to the endpoint.
I assume the AM code somewhere depends on stable order coming back from a map, which is not what a map does. (This is just a high level guess. I had no time to actually look at code.)

**Comment by brancz** [comment]
@beorn7 that was my first guess as well.

**Comment by fabxc** [comment]
I've trouble reasoning how this could happen. It is true that a map causes the grouping labels to not be shown in stable order but by the code this cannot have caused the whole group to duplicate.

When building the response we are deduping groups based on the hash of their `labels` field, which is the typlical `model.LabelSet.Fingerprint`, which ensures stable order. Because of that, I'm not sure how the same group could exist twice. Even less so because we iterate only once over every group.  
So it could only happen if the group was existing twice to begin with – but then deduplication would hit again.

A way to reproduce would be helpful.

**Comment by iksaif** [comment]
We seem to still experience that, we're looking for a way to reproduce it with 0.7.1.

**Comment by iksaif** [comment]
My group key was: `"groupKey": "{}/{perimeter=~\"^(?:observability)$\"}/{alertname=~\"^(?:(Graphite|Grafana).*)$\",severity=~\"^(?:page|interrupts)$\"}:{alertname=\"GraphitePointLoss\", env=\"preprod\", graphite_web=\"primary\"}",`

I'm pretty sure that 47616633800da8e4daffae4e819e5531646bab6f fixed the issue (by @fabxc)

HEAD seems fixed while I can still reproduce the bug with 0.7.1

Configuration:
```
route:
  receiver: default
  group_interval: 5m
  repeat_interval: 12h
  routes:
  - match_re:
      perimeter: "observability"
    group_by: [alertname, dc, env, graphite_web]
    routes:
      - receiver: default
        group_by: [alertname, env, graphite_web]
        match_re:
          alertname: "(Graphite|Grafana).*"
          severity: "page|interrupts"
      - receiver: default
  # </observability>                                                                                                                                                                         
  - receiver: default
```

Multiple matchers with multiple values.
