### ISSUE TITLE
Notification has empty text

### ISSUE THREAD

**Issue by gianrubio** [prometheus/alertmanager#707]
Related to #663 

When one alert trigger multiple alarms, the description is blank.
 
## Alert
<img width="1415" alt="screen shot 2017-04-12 at 17 39 04" src="https://cloud.githubusercontent.com/assets/5694860/24966353/f805612e-1fa6-11e7-8b48-48c9cf5699c8.png">

## Notification 

<img width="380" alt="screen shot 2017-04-12 at 17 42 11" src="https://cloud.githubusercontent.com/assets/5694860/24966504/648769a0-1fa7-11e7-95bf-40fd93017f4a.png">

## Hipchat config on alert manager

```
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'webhook
  routes:	
  - match:
      severity: 'critical'
    receiver: 'hipchat'
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://alertmanagerwh:30500/'
- name: 'hipchat'
  hipchat_configs:
  - room_id: '111'    
    message: 'Description: {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}'
    notify: true
    send_resolved: true
    auth_token: '11111'

```

If i change the message to  ``` message: 'Description: {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}  ```,  I  receive the correct message

<img width="800" alt="screen shot 2017-04-12 at 17 44 04" src="https://cloud.githubusercontent.com/assets/5694860/24966606/b70d79b2-1fa7-11e7-9f70-da370dfe1db1.png">
