### ISSUE TITLE
Email file with garbage

### ISSUE THREAD

**Issue by jstoja** [prometheus/alertmanager#710]
Hello,

I'm currently using the slack configuration that is working perfectly, but I just tried to add the email config and each time I receive an `.htm` file containing garbage (random characters).

```
Here is my configuration:
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'alertmanager@xxx.com'
  smtp_auth_username: 'xxx'
  smtp_auth_password: 'xxx'
  smtp_require_tls: false


receivers:
- name: 'all'
  email_configs:
  - to: 'xxx@xxx.com'
    require_tls: false
```

Do you have an idea about the eventual issue I'm facing?
Thank you
