### ISSUE TITLE
alertmanager can't send emails with ssl enabled

### ISSUE THREAD

**Issue by hiscal2015** [prometheus/alertmanager#766]
I have alertmanager (v0.5.1, running with docker image) with below config:

```
global:
  smtp_from: 'monitor@demo.com'
  smtp_smarthost: 'smtp.demo.com:465'
  smtp_auth_username: 'monitor@demo.com'
  smtp_auth_password: 'XXXX'
  smtp_require_tls: true

receivers:
- name: 'email'
  email_configs:
  - send_resolved: true
    to: 'user@demo.com'

route:
  group_by: ['alertname','instance']
  group_wait: 10s
  group_interval: 5m
  receiver: email
  repeat_interval: 24h
```

If I use non-ssl (port 25) to send emails then everything looks fine, but I still get failed to send emails by enabling SSL, if I use python script to test email config with ssl enabled I can successfully get emails, 
alertmanager logs are totally useless to debug:
```
time="2017-05-03T02:32:54Z" level=error msg="Error on notify: EOF" source="notify.go:272" 
 time="2017-05-03T02:32:54Z" level=error msg="Notify for 1 alerts failed: EOF" source="dispatch.go:246" 
 time="2017-05-03T02:32:59Z" level=error msg="Error on notify: EOF" source="notify.go:272" 
 time="2017-05-03T02:32:59Z" level=error msg="Notify for 1 alerts failed: EOF" source="dispatch.go:246" 
 time="2017-05-03T02:37:54Z" level=error msg="Error on notify: EOF" source="notify.go:272" 
 time="2017-05-03T02:37:54Z" level=error msg="Notify for 1 alerts failed: EOF" source="dispatch.go:246" 
 time="2017-05-03T02:38:04Z" level=error msg="Error on notify: EOF" source="notify.go:272" 
 time="2017-05-03T02:38:04Z" level=error msg="Notify for 1 alerts failed: EOF" source="dispatch.go:246" 
```

Do I have to add additional parameters to get SSL work? Please help, thanks a lot.
