### ISSUE TITLE
Enable to send alerts emails from SparkPost (SMTP)

### ISSUE THREAD

**Issue by saady** [prometheus/alertmanager#845]
I'm trying to send emails via SparkPost..but I can't get it work.
i'm getting this message:

```2017-06-05T17:17:26.165684583Z time="2017-06-05T17:17:26Z" level=error msg="Error on notify: sending mail from: 530 5.7.1 Authorization required. Ref. https://developers.sparkpost.com/api/index#header-smtp-relay-endpoints" source="notify.go:283"```

My alertmanager.yml file looks like:

```
global:
  smtp_from: 'alertmanager@email.com'
  smtp_smarthost: 'smtp.sparkpostmail.com:2525'
  

route:
  group_by: [Alertname]
  receiver: email_prometheus

  routes:
  - match:
      job: vector
    receiver: email_prometheus
  - match:
      job: requestlatency
  - match:
      severity: page
      receiver: email_prometheus
  - match:
      job: down
      receiver: email_prometheus

receivers:
- name: 'email_prometheus'
  email_configs:
    - to: 'saady@email.com'
```

I also passed `SMTP_AUTH_PASSWORD` and `SMTP_AUTH_USERNAME` as env variables.

all the steps provided in the log link are correct, except  `Encryption: STARTTLS`.

I'm not sure how to configure it within alertmanager.
