### ISSUE TITLE
AlertManager Default Repeat_Interval 

### ISSUE THREAD

**Issue by Mrcortez34** [prometheus/alertmanager#860]
So, I have disabled any type of repeat for alertmanager. The thing is that I still get alerts every 4 hours it seems. So is there a default repeat interval for alert manager?
 I have also setup inhibit rules but that doesn't seem to work completely. 

```
route:
      receiver: slack
      group_wait: 30s
      routes:
      - match:
          alertname: NodeLowDiskSpace
          severity: 'critical'
        receiver: slack
        group_wait: 2m
        group_by: ['alertname', 'node', 'kubernetes_io_hostname']
      - match:
          alertname: NodeLowDiskSpace
          severity: 'warning'
        receiver: slack
        group_wait: 2m
        group_by: ['alertname','node', 'kubernetes_io_hostname']
      - match:
          alertname: NodeNotReady
        receiver: 'slack_pagerduty'
        group_by: ['alertname', 'node']

    inhibit_rules:
      # Inhibit warnings for NowLowDiskSpace when critical exists
    - source_match:
        alertname: NodeLowDiskSpace
        severity: 'critical'
      target_match:
        alertname: NodeLowDiskSpace
        severity: 'warning'
      # Apply inhibition if the alertname is the same.
      equal: ['alertname', 'node', 'kubernetes_io_hostname', 'device']
```
