### ISSUE TITLE
Issues with marshaled config on status page

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#862]
* Regular expressions are shown as `{}` instead of the actual regular expression.
* unset fields are shown as `null` or `""` or their default value

Raw config

```yaml
# ...
      routes:
      - match:
          alertname: MothershipHighErrorRate
        match_re: 
          controller: .*MediaController|.*StreamsController
        receiver: playback-crit
# ...
```

Printed config

```yaml
# ...
      routes:
      - receiver: playback-crit
        match:
          alertname: MothershipHighErrorRate
        match_re:
          controller:
            regexp: {}
# ...
```
