### ISSUE TITLE
alertmanger doesn't send mail when alert.

### ISSUE THREAD

**Issue by huyujie** [prometheus/alertmanager#908]
This is my simple.yml in alertmanger:
global:
  smtp_smarthost: 'smtp.***.com:587'
  smtp_from: '***'
  smtp_auth_username: '***'
  smtp_auth_password: ******
  smtp_require_tls: true

route:
  group_by: ['alertname']
  receiver: team-X-mails

receivers:
- name: 'team-X-mails'
  email_configs:
  - to: '****@qq.com'
    send_resolved: true

and the log is:
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="running maintenance" component=nflog source="nflog.go:286"
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="running maintenance" component=silences source="silence.go:232"
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="maintenance done" component=nflog duration=113.161µs source="nflog.go:303"
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="maintenance done" component=silences duration=61.252µs source="silence.go:249"
Jul 16 21:38:13 i-7un8vy31 alertmanager[23045]: [224B blob data]

and the alert web has alarm:

summary: | Instance CPU usage is dangerously high
This device's CPU usage has exceeded the threshold with a value of 99.76666666674039.

**Comment by jessebolson** [comment]
Config looks fine I think (hard to tell without code-block formatting). Mine for reference:

```
global:
  smtp_require_tls: false
  smtp_smarthost: smtpserver.example.com:25
  smtp_from: alertmanager@example.com

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: mail

receivers:
- name: 'mail'
  email_configs:
  - to: me@example.com
```

Is an SMTP request being sent from your Prometheus server to the SMTP server? Use tcpdump if you can. Otherwise, check your SMTP logs - maybe there's something of interest over there. In any case, I doubt the problem is Prometheus if your config is fine.
