### ISSUE TITLE
[Alertmanager] Custom email template sent as emtpy mail

### ISSUE THREAD

**Issue by doctorlector** [prometheus/alertmanager#936]
Hi,

I receive an empty e-mail alert when I'm using custom email template for alerts.

Debug output:
_ERRO[182542] Notify for 1 alerts failed: Cancelling notify retry for "email" due to unrecoverable error: executing email html template: html/template::1:12: no such template "email.html"  source="dispatch.go:261"_

The e-mail template does exist in the template folder which correctly specified in .yml config file.
I have already raised the topic in prometheus google group but this didn't help me at all.
Already spent weeks in figuring out how to make it work.

Link to a discussion - [Cannot apply custom e-mail template](https://groups.google.com/d/msgid/prometheus-users/1f78166b-4d70-4753-8e68-b943ea6f1442%40googlegroups.com?utm_medium=email&utm_source=footer)

Short extract from alertmanager.yml config:

```
templates:
- '/etc/alertmanager/template/.tmpl'

receivers:
- name: 'username'
  email_configs:
  - to: 'username@companyname.com'
    require_tls: false
    html: '{{ template "email.html" . }}'
```

Thanks in advance.
