### ISSUE TITLE
Multiple webhook in one receiver

### ISSUE THREAD

**Issue by prasenforu** [prometheus/alertmanager#943]
Platform kubernetes.
Alertmanager 0.8.0

In my alertmanager configmap file I have receiver as follows
```
- name: 'email-n-webhook-pod'
      email_configs:
      - to: 'example@test.com'
        send_resolved: true
      webhook_configs:
      - url: http://172.30.200.104:9000/hooks/ose-podhook
      webhook_configs:
      - url: http://172.30.200.104:9000/hooks/ose-sn-hook
```

but when I am checking in alertmanager UI status page, I found following configuration

```
- name: email-n-webhook-pod
  email_configs:
  - send_resolved: true
    to: example@test.com
    from: xxxxx@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: xxxxx@gmail.com
    auth_password: <secret>
    headers:
      From: xxxxx@gmail.com
      Subject: '{{ template "email.default.subject" . }}'
      To: example@test.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
  webhook_configs:
  - send_resolved: true
    url: http://172.30.200.104:9000/hooks/ose-sn-hook
```

that mean alertmanager did not loaded first webhook ``` - url: http://172.30.200.104:9000/hooks/ose-podhook```

Looking for such configuration where  I can define multiple webhook in one receiver as per my requirement.

NOTE : Alerrtmanager running perfectly, there is no error in Alerrtmanager container logs.
