### ISSUE TITLE
connection refused error while sending email when smtp_smarthost authentication is provided for the IP

### ISSUE THREAD

**Issue by sushovan23** [prometheus/alertmanager#965]
Hello,
I'm getting following error messages while sending email notifications for alerts:
```
time="2017-08-29T19:20:37Z" level=error msg="Error on notify: dial tcp <ip>25: getsockopt: connection refused" source="notify.go:283"
time="2017-08-29T19:20:37Z" level=error msg="Notify for 6 alerts failed: dial tcp <ip>:25: getsockopt: connection refused" source="dispatch.go:262"
```

Alert Manager config:
```
  smtp_smarthost: "{{ smtp_server }}"
  smtp_from: "{{ noreply_address }}"

  #smtp_auth_username: ""
  #smtp_auth_password: ""
  email_configs:
  - to: "{{ group_email }}"
```

We have smtp_smarthost providing access directly to the IP address so it doesn't require username/password for authentication.
that is the reason we have commented out username/password in config file. 
I have tested connectivity & email send feature from this host using a test script so connectivity wise it's working,

Could you let me know how to go around this issue?
