### ISSUE TITLE
send out alert immediatly and send out resolved alert after all the 5 minutes are good

### ISSUE THREAD

**Issue by zhihuiFan** [prometheus/alertmanager#973]
what I want is 
  1. if I get an alert,  I can send out the alert immediately.  （ALERT xxx IF 1s?)
  2. if the alert is resolved in the following 1 data point, I would not say it is really resolved.  I want to think the alert is really resolved until all the data points in the following 5 minutes are good. In this case, I want to receive a resolved alert. (group_interval ？)
  3. If in the following 5 minutes, it is not resolved, I don't want to receive the alerts again and again. I can wait for 3 hours at least before receive the same alert again.  (shall repeat_interval be used here?)

  what I did is:

  prometheus:
```
  scrape_interval:     15s

  ALERT OSSlowIO
  IF rate(node_disk_write_time_ms{device="vdb"}[30s]) / rate(node_disk_writes_completed{device="vdb"}[30s])>5
  FOR 1s
  ANNOTATIONS {
       summary = "[P2] {{$labels.cluster_name}} {{$labels.hostname }}"
  }
 ``` 
  simple.yml (alertmanager):

```
global:
  resolve_timeout: 5m
route:
  group_by: ["alertname", "instance"]
  group_wait: 15s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'alert'
receivers:
  - name: 'alert'
    webhook_configs:
      - send_resolved: true
        url: 'http://slc4b03c-0543.stratus.slc.xxxx.com:9002/dbaas/api/alert/webhook2'
```

  **then I usually get firing alert in time 1,  and get resolved alert in `time 1 + 1s`.**

 maybe I have several places wrong,  could you guide me for this purpose?
