### ISSUE TITLE
Local webhook cannot reach getting "getsockopt: connection refused"

### ISSUE THREAD

**Issue by ntwobike** [prometheus/alertmanager#989]
I have simple go webserver running on port 4000(locally not in a container) to consume the post request, and my alertmanager running in a container. I get below errors when its trying to trigger the alerts everytime. I checked with a slack channel its working fine only the webhooks doesnt work for me. 

```
Notify for 1 alerts failed: Post http://127.0.0.1:4000/notifier/: dial tcp 127.0.0.1:4000: getsockopt: connection refused" source="dispatch.go:262
Error on notify: Post http://127.0.0.1:4000/notifier/: dial tcp 127.0.0.1:4000: getsockopt: connection refused" source="notify.go:283
```

my alertmanager configs
```
route:
  receiver: "notifier"
receivers:
- name: "notifier"
  webhook_configs:
  - url: 'http://127.0.0.1:4000/notifier/'
```
I can curl the http://127.0.0.1:4000/notifier/ in local. I checked the port usage of 4000
`server  12799 nadeen.nilanka    3u  IPv6 0x94c5f3ea99ae389      0t0  TCP *:terabase (LISTEN)`

I'm on docker for mac.
docker version: 17.06.2-ce, build cec0b72

Could somebody tell me what is the issue here?
